### ISSUE TITLE
Is the "+"/"-" still necessary for restarts?

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#1004]
While fixing a bug that was introduced due to not remembering that we still have the +- handling at the beginning of restart names, the question arose from multiple people if this is even necessary. Making an issue to remind myself to take a look at see if we are even still using these.
The "-" was to say that you were allowed to bootstrap it
The "+" was something for binary restarts to allow for incomplete restarts

**Comment by tclune** [comment]
@bena-nasa Please try to confirm if this feature should be preserved.   I don't mind the ticket closing, but we want a record for whether to deal with this in any refactoring exercise.

**Comment by bena-nasa** [comment]
@tclune The AGCM.rc you get from gcm_setup from v10.19.4 of the GESOgcm fixture doesn't have any +/- in front any of the restart names...
I was able to use a set of binary restarts so apparently if they aren't there the model seems to be happy so seems like whatever functionality was there with them is not needed.

**Comment by tclune** [comment]
OK - brave enough to commit the change (or ask @Gvilla1000-nasa to)?

**Comment by bena-nasa** [comment]
@tclune I can't see that these are used in that they are not being used in the AGCM.rc so if @Gvilla1000-nasa can do this it should be easy. This would be in the esmfstatewrite/readfromfile in MAPL_Generic.F90 where the logic is applied.

**Comment by lizziel** [comment]
@bena-nasa, @tclune : Related to this issue, GCHP was able to use '+' with pnc4 files to assign a default value to internal fields missing in the restart file. Is this still possible after the removal of '+'? If yes, could you point me to where the default value is set in the latest version?

**Comment by mathomp4** [comment]
@lizziel I'll let @bena-nasa or @atrayano answer in more detail, but you could maybe use the ability of `MAPL_AddXXXSpec`:
```fortran
    call MAPL_AddInternalSpec(GC,                                  &
         SHORT_NAME ='NCPL',                                       &
         LONG_NAME  ='particle_number_for_liquid_cloud',           &
         UNITS      ='kg-1',                                       &
         FRIENDLYTO = trim(FRIENDLIES_NCPL),                       &
         DIMS       = MAPL_DimsHorzVert,                           &
         VLOCATION  = MAPL_VLocationCenter,          &
         DEFAULT = 50.0e6 ,   RC=STATUS  )
```
By default, I think MAPL (when it bootstraps missing variables) will bootstrap to zero. But I'd think that if your add spec had a `DEFAULT` it would then bootstrap with that.

I think.

Hopefully an expert can weigh in. 😄

**Comment by bena-nasa** [comment]
@lizziel 
When MAPL allocates the import/internal/export fields, it

**Comment by lizziel** [comment]
Thanks all. So it sounds like there should not be a problem if an internal state field is not in the file. However, I am getting an error at file read that is fixed if I add the missing field in. I'll make a separate issue about it if I can't figure it out quickly.

**Comment by atrayano** [comment]
@mathomp4 You are right, adding 'DEFAULT' only affects what values are assigned initially to the variable in case of bootstrapping, (and not providing DEFAULT is equivalent to DEFAULT = 0.0). If a variable is read from a restart, then 'DEFAULT' is ignored

**Comment by lizziel** [comment]
Following up on this, I traced the issue to not having config file entry `MAPL_ENABLE_BOOTSTRAP`. Adding that to `GCHP.rc` fixed the issue.

**Comment by tclune** [comment]
Excellent.  Closing the ticket. (Hope I've not misunderstood.)
