### ISSUE TITLE
Setting up output server for GCHP simulation on Pleiades

### ISSUE THREAD

**Issue by 1Dandan** [GEOS-ESM/MAPL#1005]
I am setting up output server on Pleiades following https://github.com/GEOS-ESM/MAPL/issues/739. I am trying to run a 1200 total cores for model and 24 cores for output server. What I changed are:
1) Modified the lines about establishing o_server group in ServerManager.F90 of:

    if (rank == 0 .and. nodes_out(i) /=0 )
    else if (rank==0 .and. npes_out(i) /=0 )
    
    to:

    if (rank == 0 .and. nodes_out(1) /=0 )
    else if (rank==0 .and. npes_out(1) /=0 )

2) Modified MAPL_CapOptions.F90. Added the lines:
    cap_options%npes_model = 1200
    cap_options%nodes_output_server = [1]
    cap_options%npes_output_server = [24]
    cap_options%oserver_type = ‘single’

3) Setting up NX and NY value in GCHP.rc manually. 
    NX: 10
    NY: 120

4) in mpiexec call using: 
    mpiexec -np 1224 ./gchp-oserver &> run-1224-oserver.log

But I got the error message showed below:
```
NOTE from PE     0: MPP_IO_SET_STACK_SIZE: stack size set to     131072.
NOTE from PE     0: MPP_DOMAINS_SET_STACK_SIZE: stack size set to 20000000.
 Integer*4 Resource Parameter: NX:10
 Integer*4 Resource Parameter: NY:120
 Integer*4 Resource Parameter: IM:720
 Integer*4 Resource Parameter: JM:4320
 Integer*4 Resource Parameter: RUN_DT:300
 For k_split (remapping)=           1
n_split is set to 15 for resolution-dt=0721x0721x6-  300.000
Using n_zfilter : 000
Using n_sponge : 001
Using non_ortho :       T
 Starting PEs :         1224
 Starting Threads :            1

FATAL from PE     2: mpp_domains_define.inc: At least one pe in pelist is not used by any tile in the mosaic

```

Are there any other settings I need to do? @tclune @mathomp4 Do you have any suggestions?

**Comment by mathomp4** [comment]
I'm going to pull in @weiyuan-jiang as I only know how to do the FLAP side of these things...

**Comment by weiyuan-jiang** [comment]
These two are exclusive
cap_options%nodes_output_server = [1]
cap_options%npes_output_server = [24]

1) If you ask 24 cores per node when snatching the job, you don't need to specify cap_options%npes_output_server = [24]. So please remove this line.
2) 1200 core vs 24 output probably is not optimal ( but it should work). You may need more cores for observer with type of 'multigroup'.

**Comment by tclune** [comment]
If the options are incompatible, can we add logic to detect that at the point where they are used?

**Comment by 1Dandan** [comment]
Thanks @weiyuan-jiang. I have commented out the line in MAPL_CapOptions.F90:
    `cap_options%npes_output_server = [24]`, 
but I still got the same error message of:
    `FATAL from PE    12: mpp_domains_define.inc: At least one pe in pelist is not used by any tile in the mosaic`

**Comment by weiyuan-jiang** [comment]
I cannot find the lines   
if (rank == 0 .and. nodes_out(i) /=0 )
else if (rank==0 .and. npes_out(i) /=0 )

Which branch or tag of MAPL are you using?

**Comment by 1Dandan** [comment]
I am using GCHP v13.0.0. It says MAPL is v2.2.7 according to http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_13.0.0 The original ServerManager.F90 looks like:
![image](https://user-images.githubusercontent.com/75513026/131508480-c287b77a-ca3d-4419-add4-c578427f0592.png)
I modified line 167 and 169 to:
if (rank == 0 .and. nodes_out(1) /=0 )
else if (rank==0 .and. npes_out(1) /=0 )

**Comment by weiyuan-jiang** [comment]
How do you ask for the resource? Can you post your slurm script here?

**Comment by weiyuan-jiang** [comment]
> if the options are incompatible, can we add logic to detect that at the point where they are used?

In flap when we construct the caption, we have those checks.

**Comment by 1Dandan** [comment]
Sure. I am using PBS (Portable Batch System) to request resources. The scripts are:
```
#!/bin/bash
#PBS -l select=51:ncpus=24:mpiprocs=24:model=has
#PBS -l walltime=2:00:00
#PBS -l site=needed=/home4+/nobackupp12+/nobackupp2+/nobackupp13
#PBS -l place=excl
#PBS -q devel
#PBS -N C720
# loading environment
source /u/dzhang8/gchp-intel.env
cd /nobackupp12/dzhang8/GCHP-v13.0.0/rundir-c720-tracers

module list     # print loaded modules
set -e          # if a subsequent command fails, treat it as fatal (don't continue)
set -x          # for remainder of script, echo commands to the job's log file

ulimit -c 0
ulimit -l unlimited
ulimit -u 50000
ulimit -v unlimited
ulimit -s unlimited

export MPI_LAUNCH_TIMEOUT=40
export PATH=$PATH:/u/scicon/tools/bin
export MPI_OMP_NUM_THREADS=1
export MPI_VERBOSE=1
export MPI_DISPLAY_SETTINGS=1
rm -f gcchem_internal_checkpoint* cap_restart run-1224-oserver.log
#./runConfig.sh

several_tries mpiexec -np 1224 ./gchp-oserver &> run-1224-oserver.log
```
The compiler I am using is Intel 19.1.3 and MPI version is MPT 2.23

**Comment by weiyuan-jiang** [comment]
@bena-nasa , Ben, it seems this error is not caused by oserver setup. Have you seen this kind of error?

**Comment by bena-nasa** [comment]
Yes, every time I've seen this error:
"FATAL from PE 12: mpp_domains_define.inc: At least one pe in pelist is not used by any tile in the mosaic"
It means you executed FV3 (and hence the model) on more processors that you specified via the layout (NX and NY) so FMS is complaining that an MPI rank is not being used.  I'm just catching up with this but somehow the resource allocation and splitting the communicators did not split the communicator and start ESMF and the model on the correct number of cores. So that is what needs to be investigated.

Why are we talking about hard coding the parameters for the o-server in the code. Is this being run in some sort of configuration that does not support flap/command line options?

**Comment by weiyuan-jiang** [comment]
I think flap is not used so the capoption has to be hard coded. You are right, we have to investigate how many pe is used by the model.  @1Dandan can you check the size of the comms with " call mpi_comm_size(this%split_comm%get_subcommunicator(), npes, status) "  under "model" and "oserver"?

**Comment by weiyuan-jiang** [comment]
Actually, check "application_size" in ServerManager.F90 is enough.  I would like to know  if it is 1200

**Comment by tclune** [comment]
I think the user @1Dandan is a GCHP user, which is part of the confusion.

**Comment by 1Dandan** [comment]
Sorry I am not familiar with MAPL and it indeed caused some confusion. I did not find the part that setting the value for application_size. Do I need to add it in MAPL_CapOptions.F90?

**Comment by weiyuan-jiang** [comment]
No. I just want you to print out the variable application_size

**Comment by weiyuan-jiang** [comment]
At some point, you need to call subroutine initialize_io_clients_servers which will call above initialization

**Comment by 1Dandan** [comment]
The source code can be found here: https://github.com/geoschem/GCHP/releases/tag/13.0.0. I modified ServerManager.F90 and MAPL_CapOptions.F90. The modified files are: 
[ServerManager.F90.txt](https://github.com/GEOS-ESM/MAPL/files/7085947/ServerManager.F90.txt)
[MAPL_CapOptions.F90.txt](https://github.com/GEOS-ESM/MAPL/files/7085949/MAPL_CapOptions.F90.txt)

**Comment by weiyuan-jiang** [comment]
Is that possible to upgrade your MAPL? I remember that the values in the CapOptions got lost when it is passed to MAPL_Cap in NOAA's Orion system. We have fixed that problem.

**Comment by weiyuan-jiang** [comment]
If it is too much trouble to upgrade MAPL, you can try this first
1) check the cap_options values after  this block  https://github.com/GEOS-ESM/MAPL/blob/29286d8a78b0bdea447465ede7bb4217782538c2/base/MAPL_Cap.F90#L92-L96

2) if the values are NOT correct, then you re-assign the values just like what you have done to MAPL_CapOptions.F90
3) if the values are correct, then it is useless to assign the value after the block. Instead, you need to re-assign the values after this line https://github.com/geoschem/GCHP/blob/99dd957f36aef2e86290bfefc454df8f52cf5794/src/GCHPctm.F90#L29

**Comment by weiyuan-jiang** [comment]
@1Dandan , I will make a new branch based on v2.2.7 and try to fix this problem.

**Comment by 1Dandan** [comment]
Really appreciated @weiyuan-jiang! Just to let you know that the Pleiades is under maintenance for the whole day and I will try your suggestion tomorrow.

**Comment by weiyuan-jiang** [comment]
@1Dandan , before you try anything, please try to change the two line first. Change "class" to "type"
1) https://github.com/GEOS-ESM/MAPL/blob/29286d8a78b0bdea447465ede7bb4217782538c2/base/MAPL_Cap.F90#L33
   type (MAPL_CapOptions), allocatable :: cap_options
2)https://github.com/GEOS-ESM/MAPL/blob/29286d8a78b0bdea447465ede7bb4217782538c2/base/MAPL_Cap.F90#L85
   type ( MAPL_CapOptions), optional, intent(in) :: cap_options

Please remove your build directory and re-build it.  Hopefully, it would work.

**Comment by 1Dandan** [comment]
I have modified line 33 and 35 in MAPL_Cap.F90 replacing `class` by `type`, and removed build directory and recreated one. Initialing build directory with `cmake ..` received no error. But when I was compiling build directory, I received the error saying `cap_options%oserver_type` is not recognized as a field name: 
```
/nobackup/dzhang8/GCHP-v13.0.0/GCHP.13.0.0.oserver.new/src/MAPL/base/MAPL_CapOptions.F90(65): error #6460: This is not a field name that is defined in the encompassing structure.   [OSERVER_TYPE]
      cap_options%oserver_type = 'single'
------------------^
/nobackup/dzhang8/GCHP-v13.0.0/GCHP.13.0.0.oserver.new/src/MAPL/base/MAPL_CapOptions.F90(65): error #6303: The assignment operation or the binary expression operation is invalid for the data types of the two operands.   ['single']
      cap_options%oserver_type = 'single'
---------------------------------^
compilation aborted for /nobackup/dzhang8/GCHP-v13.0.0/GCHP.13.0.0.oserver.new/src/MAPL/base/MAPL_CapOptions.F90 (code 1)
src/MAPL/base/CMakeFiles/MAPL.base.dir/build.make:575: recipe for target 'src/MAPL/base/CMakeFiles/MAPL.base.dir/MAPL_CapOptions.F90.o' failed
```

**Comment by weiyuan-jiang** [comment]
Your version of MAPL is not v2.2.7. Can you double check for me?

**Comment by weiyuan-jiang** [comment]
In v2.2.7, we have not introduced the "oserver_type".  So it must have been updated to newer version

**Comment by tclune** [comment]
One way to see the version is to look at the top of the CMakeLists.txt file in the top directory of MAPL.    That might be a bit easier than interpreting the SHA code used for the git submodule.

**Comment by 1Dandan** [comment]
The CMakeLists.txt did show the MAPL version is 2.2.7.
```
cmake_minimum_required (VERSION 3.13)
cmake_policy (SET CMP0053 NEW)
cmake_policy (SET CMP0054 NEW)

project (
  MAPL
  VERSION 2.2.7
  LANGUAGES Fortran CXX C)  # Note - CXX is required for ESMF

```

**Comment by weiyuan-jiang** [comment]
In v2.2.7, there is no "oserver_type" in the structure but you were able to assign the values before the changes I proposed (i.e., class ->type). So your previous MAPL is not v2.2.7 or at least it had been modified.  The easy way to use v2.2.7 is to remove oserver_type assignment.

**Comment by tclune** [comment]
@1Dandan can you make your source code on pleiades readable by @weiyuan-jiang?   We should not get bogged down in verifying which version of MAPL is being debugged.

**Comment by 1Dandan** [comment]
Sure. I will change the directory permision.

**Comment by weiyuan-jiang** [comment]
@mathomp4 , It seems an environment variable needs to be set before launching the job. What is that?

**Comment by mathomp4** [comment]
@weiyuan-jiang Well, the MPT variables we use are:
```
   setenv MPI_COLL_REPRODUCIBLE
   setenv SLURM_DISTRIBUTION block
   #setenv MPI_DISPLAY_SETTINGS 1
   #setenv MPI_VERBOSE 1
   
   unsetenv MPI_MEMMAP_OFF
   unsetenv MPI_NUM_MEMORY_REGIONS
   setenv MPI_XPMEM_ENABLED yes
   unsetenv SUPPRESS_XPMEM_TRIM_THRESH
   setenv MPI_LAUNCH_TIMEOUT 40
   # For some reason, PMI_RANK is randomly set and interferes
   # with binarytile.x and other executables.
   unsetenv PMI_RANK
```
He can also try setting `FOR_IGNORE_EXCEPTIONS=false` which can help MPT to not suppress tracebacks:
```
   # Often when debugging on MPT, the traceback from Intel Fortran
   # is "absorbed" and only MPT's errors are displayed. To allow the
   # compiler's traceback to be displayed, uncomment this environment
   # variable
   #setenv FOR_IGNORE_EXCEPTIONS false
```

**Comment by 1Dandan** [comment]
Thank you! I will modify my PBS script, but somewhat odd to me because I am using the same PBS script but previous one did print out traceback info while now it didn't.

**Comment by 1Dandan** [comment]
I have run the simulation again with output server turned on. It works well to write the output diagnostics with one node for output server without any error. That's very promising! And then I tried to use 3 nodes for output server, but it failed at writing output files.
The modification I made for MAPL_CapOptions.F90 is to change cap_options%nodes_output_server=[3] as below:
```
   function new_CapOptions(unusable, cap_rc_file, egress_file, ensemble_subdir_prefix, rc) result (cap_options)
      type (MAPL_CapOptions) :: cap_options
      class (KeywordEnforcer), optional, intent(in) :: unusable
      character(*), optional, intent(in) :: cap_rc_file
      character(*), optional, intent(in) :: egress_file
      character(*), optional, intent(in) :: ensemble_subdir_prefix

      integer, optional, intent(out) :: rc

      _UNUSED_DUMMY(unusable)

      cap_options%cap_rc_file = 'CAP.rc'
      cap_options%egress_file = 'EGRESS'
      cap_options%ensemble_subdir_prefix = 'mem'


      cap_options%npes_model =1200
      cap_options%npes_input_server  =[0]
      cap_options%nodes_input_server =[0]
      cap_options%npes_output_server =[0]
      cap_options%nodes_output_server=[3]
      !cap_options%oserver_type = 'single'

```
The error massage for the 3-node output server is:
```
 AGCM Date: 2019/01/01  Time: 01:00:00  Throughput(days/day)[Avg Tot Run]:  126.6  107.0  123.2  TimeRemaining(Est) 000:00:28   46.0% :  44.9% Mem Comm:Used
                                                                      Mem/Swap Used (MB) at MAPL_Cap:TimeLoop=  7.450E+04  0.000E+00
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
gchp-oserver-mult  0000000002881DAE  Unknown               Unknown  Unknown
libpthread-2.22.s  00002AAAAB5A9C00  Unknown               Unknown  Unknown
gchp-oserver-mult  000000000288198C  Unknown               Unknown  Unknown
libpthread-2.22.s  00002AAAAB5A9C00  Unknown               Unknown  Unknown
forrtl: severe (174): SIGSEGV, segmentation fault occurred
```
The pbs script I used is:
```
#!/bin/bash
#PBS -l select=53:ncpus=24:mpiprocs=24:model=has
#PBS -l walltime=2:00:00
#PBS -l site=needed=/home4+/nobackupp12+/nobackupp2+/nobackupp13
#PBS -l place=excl
#PBS -q devel
#PBS -N C720
# loading environment
source /u/dzhang8/gchp-intel.env
cd /nobackupp12/dzhang8/GCHP-v13.0.0/rundir-c720-tracers

module list     # print loaded modules
set -e          # if a subsequent command fails, treat it as fatal (don't continue)
set -x          # for remainder of script, echo commands to the job's log file

ulimit -c 0
ulimit -l unlimited
ulimit -u 50000
ulimit -v unlimited
ulimit -s unlimited

export MPI_LAUNCH_TIMEOUT=40
export PATH=$PATH:/u/scicon/tools/bin
export MPI_VERBOSE=1
export MPI_DISPLAY_SETTINGS=1

export FOR_IGNORE_EXCEPTIONS=false
export MPI_COLL_REPRODUCIBLE
unset MPI_MEMMAP_OFF
unset MPI_NUM_MEMORY_REGIONS
export MPI_XPMEM_ENABLED=yes
unset SUPPRESS_XPMEM_TRIM_THRESH
unset PMI_RANK

rm -f gcchem_internal_checkpoint* cap_restart run-1272-oserver.log
#./runConfig.sh

several_tries mpiexec -np 1272 ./gchp-oserver-multigroup &> run-1272-oserver.log

```

**Comment by weiyuan-jiang** [comment]
@1Dandan The old oserver is not quite portable and it requires a lot of tuning of the system. Please try to build GCHP with the new version of MAPL. I will help you setup a "multigroup" oserver after that.

**Comment by 1Dandan** [comment]
@weiyuan-jiang Sorry I have no idea how I can upgrade MAPL within GCHP. But thanks a lot for the help.

**Comment by weiyuan-jiang** [comment]
You probably can use  "git checkout develop" and "git pull" in you MAPL directory.  Please try if MAPL can be built independently.

**Comment by 1Dandan** [comment]
GCHP source code is built all together, but latest version of GCHP uses MAPL v2.6.3. I have switched to this latest version of GCHP and hopefully I will get my job scheduled.

**Comment by 1Dandan** [comment]
I have got my job scheduled and the GCHP version I am using is v13.2.1 with MAPL version 2.6.3. But I got the error message as follows:
```
/u/scicon/tools/bin/several_tries is running the command mpiexec -np 1272 ./gchp-oserver-multigroup
pe=00448 FAIL at line=00107    ServerManager.F90                        <captain-soldier need at lease two beckend>
pe=00448 FAIL at line=00193    MAPL_Cap.F90                             <status=1>
pe=00448 FAIL at line=00152    MAPL_Cap.F90                             <status=1>
pe=00448 FAIL at line=00129    MAPL_Cap.F90                             <status=1>
pe=00448 FAIL at line=00031    GCHPctm.F90                              <status=1>

```
The job script I used is:
```
#!/bin/bash
#PBS -l select=53:ncpus=24:mpiprocs=24:model=has
#PBS -l walltime=2:00:00
#PBS -l site=needed=/home4+/nobackupp12+/nobackupp2+/nobackupp13
#PBS -l place=excl
#PBS -q devel
#PBS -N C720
# loading environment
source /u/dzhang8/gchp-intel.env
cd /nobackupp12/dzhang8/GCHP-v13.2.1/rundir-c720-tracers

module list     # print loaded modules
set -e          # if a subsequent command fails, treat it as fatal (don't continue)
set -x          # for remainder of script, echo commands to the job's log file

ulimit -c 0
ulimit -l unlimited
ulimit -u 50000
ulimit -v unlimited
ulimit -s unlimited

export MPI_LAUNCH_TIMEOUT=40
export PATH=$PATH:/u/scicon/tools/bin

export FOR_IGNORE_EXCEPTIONS=false
export MPI_COLL_REPRODUCIBLE
unset MPI_MEMMAP_OFF
unset MPI_NUM_MEMORY_REGIONS
export MPI_XPMEM_ENABLED=yes
unset SUPPRESS_XPMEM_TRIM_THRESH
unset PMI_RANK

rm -f gcchem_internal_checkpoint* cap_restart run-1272-oserver.log
#./runConfig.sh

several_tries mpiexec -np 1272 ./gchp-oserver-multigroup &> run-1272-oserver.log

```
I modified MAPL_CapOptions.F90 with additional `cap_option%oserver_type = 'multigroup'`. The parts are:
```
   function new_CapOptions(unusable, cap_rc_file, egress_file, ensemble_subdir_prefix, esmf_logging_mode, rc) result (cap_options)
      type (MAPL_CapOptions) :: cap_options
      class (KeywordEnforcer), optional, intent(in) :: unusable
      character(*), optional, intent(in) :: cap_rc_file
      character(*), optional, intent(in) :: egress_file
      character(*), optional, intent(in) :: ensemble_subdir_prefix
      type(ESMF_LogKind_Flag), optional, intent(in) :: esmf_logging_mode

      integer, optional, intent(out) :: rc

      _UNUSED_DUMMY(unusable)

      cap_options%cap_rc_file = 'CAP.rc'
      cap_options%egress_file = 'EGRESS'
      cap_options%oserver_type= 'single'
      cap_options%ensemble_subdir_prefix = 'mem'

      cap_options%npes_model =1200
      cap_options%npes_input_server  =[0]
      cap_options%nodes_input_server =[0]
      cap_options%npes_output_server =[0]
      cap_options%nodes_output_server=[3]
      cap_options%oserver_type = 'multigroup'

      if (present(cap_rc_file)) cap_options%cap_rc_file = cap_rc_file
      if (present(egress_file)) cap_options%egress_file = egress_file
      if (present(ensemble_subdir_prefix)) cap_options%ensemble_subdir_prefix = ensemble_subdir_prefix
      if (present(esmf_logging_mode)) cap_options%esmf_logging_mode = esmf_logging_mode

      _RETURN(_SUCCESS)

   end function

```
All other parts except ServerManager.F90 and MAPL_CapOptions.F90 I left them default. To avoid confusion, the source code including all my modifications is available at: https://www.dropbox.com/s/jlb0qm0ri8x5wbl/GCHP.13.2.1.tar.gz?dl=0

**Comment by weiyuan-jiang** [comment]
You need to specify npes_backend_pernode. Basically it is the number of writing processes for each node. 
cap_options%oserver_type = 'multigroup'
cap_option%npes_backend_pernode = 5

**Comment by 1Dandan** [comment]
I have made the changes for MAPL_CapOptions.F90 as follows:
```
   function new_CapOptions(unusable, cap_rc_file, egress_file, ensemble_subdir_prefix, esmf_logging_mode, rc) result (cap_options)
      type (MAPL_CapOptions) :: cap_options
      class (KeywordEnforcer), optional, intent(in) :: unusable
      character(*), optional, intent(in) :: cap_rc_file
      character(*), optional, intent(in) :: egress_file
      character(*), optional, intent(in) :: ensemble_subdir_prefix
      type(ESMF_LogKind_Flag), optional, intent(in) :: esmf_logging_mode

      integer, optional, intent(out) :: rc

      _UNUSED_DUMMY(unusable)

      cap_options%cap_rc_file = 'CAP.rc'
      cap_options%egress_file = 'EGRESS'
      cap_options%oserver_type= 'multigroup'
      cap_options%ensemble_subdir_prefix = 'mem'

      cap_options%npes_model =1200
      cap_options%npes_input_server  =[0]
      cap_options%nodes_input_server =[0]
      cap_options%npes_output_server =[0]
      cap_options%nodes_output_server=[3]
      cap_options%npes_backend_pernode = 5

      if (present(cap_rc_file)) cap_options%cap_rc_file = cap_rc_file
      if (present(egress_file)) cap_options%egress_file = egress_file
      if (present(ensemble_subdir_prefix)) cap_options%ensemble_subdir_prefix = ensemble_subdir_prefix
      if (present(esmf_logging_mode)) cap_options%esmf_logging_mode = esmf_logging_mode

      _RETURN(_SUCCESS)

   end function
```
Now the simulation becomes much slower than before and it was interrupted because walltime is used up. The final line of log file says it finished some stages:
```
 Setting history variable pointers to GC and Export States
        GENERIC: INFO: Finished the 'Run' stage of the gridded component 'GCHPchem'
        GENERIC: INFO: Finished the 'Run' stage of the gridded component 'GCHP'
 
```
And the log file for ESMF says error:
`20210922 185117.860 ERROR            PET1015 ESMF_Config.F90:924 ESMF_ConfigFindLabel Not found  - label EXCLUDE_ADVECTION_TRACERS_LIST: not found`

This GCHP simulation is actually a small test simulation which should run very fast. Is there any other setting I can do to optimize it, or is there something wrong with my settings?

**Comment by weiyuan-jiang** [comment]
Have you changed the total number of pe, like mpiexec -np 1272 ?( assuming 24 cores/node)

**Comment by 1Dandan** [comment]
Yes. The script I used is:
```
#!/bin/bash
#PBS -l select=53:ncpus=24:mpiprocs=24:model=has
#PBS -l walltime=2:00:00
#PBS -l site=needed=/home4+/nobackupp12+/nobackupp2+/nobackupp13
#PBS -l place=excl
#PBS -q devel
#PBS -N C720
# loading environment
source /u/dzhang8/gchp-intel.env
cd /nobackupp12/dzhang8/GCHP-v13.2.1/rundir-c720-tracers-new

module list     # print loaded modules
set -e          # if a subsequent command fails, treat it as fatal (don't continue)
set -x          # for remainder of script, echo commands to the job's log file

ulimit -c 0
ulimit -l unlimited
ulimit -u 50000
ulimit -v unlimited
ulimit -s unlimited

export MPI_LAUNCH_TIMEOUT=40
export PATH=$PATH:/u/scicon/tools/bin

export FOR_IGNORE_EXCEPTIONS=false
export MPI_COLL_REPRODUCIBLE
unset MPI_MEMMAP_OFF
unset MPI_NUM_MEMORY_REGIONS
export MPI_XPMEM_ENABLED=yes
unset SUPPRESS_XPMEM_TRIM_THRESH
unset PMI_RANK

rm -f gcchem_internal_checkpoint* cap_restart run-1272-oserver.log
#./runConfig.sh

several_tries mpiexec -np 1272 ./gchp-oserver-multigroup &> run-1272-oserver.log

```
