### ISSUE TITLE
Add bit grooming in MAPL?

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#1063]
The guru of NCO, @czender, came up with a cool variant of bit shaving called "bit grooming" as detailed in [this poster](https://www.essoar.org/doi/pdf/10.1002/essoar.bb4d390d7f9f73ba.963021f17c584ca8.1) with @JeremySilver and [this paper](https://gmd.copernicus.org/articles/9/3199/2016/). (And [another](https://gmd.copernicus.org/articles/10/413/2017/)!)

Whereas bit shaving uses just zero bits, bit grooming alternates between 0's and 1's. This helps with bias of the shaved/groomed data.

Now, MAPL can bit shave (though maybe not exactly like NCO does), so maybe we can look at adding the grooming algorithm as well to our online netCDF writing. Of course, our code is in C and I'm already night-useless with bit-shifting in Fortran (hello `ishft`!) so hacking our C code might be beyond me. So I'll assign others, though maybe this is a good opportunity for me to brush up on C... 😄

**Comment by mathomp4** [comment]
> Look for BitGrooming to arrive in the next version (4.8.2) of the netCDF C and Fortran libraries.

ooh. Huh. Well, maybe that solves things in another way! :)

**Comment by mathomp4** [comment]
And because @czender has updated NCO for a new algorithm:
```
A. Lossy quantization algorithms have been refactored. First, the
   attribute name that store the level of quantization are now
   algorithm-specific, e.g.,
   QuantizeBitGroomNumberOfSignificantDigits. Previsously, NCO 
   stored the NSD attribute number_of_significant_digits. However,
   this was deemed too ambiguous, given the increasing number of
   supported quantization methods. The new attribute names better
   disambiguate which algorithm was used to quantize the variable.
   Second, the default algorithm has been changed from BitGroom with
   BitRound masks from R. Kouznetsov (2021), to what we call Granular
   BitGroom (GBG). GBG combines the best features of BitGroom,
   BitRound, and DigitRound by Delaunay et al. (2019). GBG improves
   compression ratios by ~20% relative to BitGroom for NSD=3 on
   our benchmark 1 GB climate model output dataset.
   ncks -7 -L 1         --ppc default=3 in.nc out.nc # GranularBitGroom
   ncks -7 -L 1 --baa=0 --ppc default=3 in.nc out.nc # BitGroom
   ncks -7 -L 1 --baa=1 --ppc default=3 in.nc out.nc # BitShave
   ncks -7 -L 1 --baa=2 --ppc default=3 in.nc out.nc # BitSet
   ncks -7 -L 1 --baa=3 --ppc default=3 in.nc out.nc # DigitRound
   ncks -7 -L 1 --baa=4 --ppc default=3 in.nc out.nc # GranularBitGroom
   ncks -7 -L 1 --baa=5 --ppc default=3 in.nc out.nc # BitRound
   ncks -7 -L 1 --baa=6 --ppc default=3 in.nc out.nc # HalfShave
   ncks -7 -L 1 --baa=7 --ppc default=3 in.nc out.nc # BruteForce
   Documentation on Bit-Adjustment-Algorithms (BAA) 3-7 will be
   improved in the future. Bit-Groom/Shave/Set are described here:
   http://nco.sf.net/nco.html#ppq
   http://nco.sf.net/nco.html#gbg
```
cf., http://nco.sourceforge.net/nco.html#gbg

I'll use this issue so I can keep track of the references:

* [R. Kouznetsov (2021)](https://gmd.copernicus.org/articles/14/377/2021/)
* [Delaunay et al. (2019)](https://gmd.copernicus.org/articles/12/4099/2019/)

as well as any experiences I have with NCO 5.0.3 and the new options (once I get it into Baselibs).

**Comment by czender** [comment]
@tclune Pros and cons of layer-by-layer scaling is discussed, with respect to bit grooming and packing, in [this paper](http://www.geosci-model-dev.net/10/413/2017). The method you describe can be used in conjunction with packing to improve the compression relative to BitShaving alone. Everyone has different tolerances for how much precision, dynamic range, speed, and portability they are willing to sacrifice during lossy compression. You are in a good position to make an informed judgement about all that because your group has obviously thought about it a lot, and with NCO 5.0.3 you can experiment with new algorithms pretty easily.
