### ISSUE TITLE
How to use HFLUX regrid method?

### ISSUE THREAD

**Issue by LiamBindle** [GEOS-ESM/MAPL#1124]
Hi all,

I'm trying to use the HFLUX regrid method in MAPL 2.6.3 and I'm getting the following error when I use `H` for the "conservative regrid" entry in my import in ExtData.rc:
```
pe=00018 FAIL at line=00147    NewRegridderManager.F90                  <no such property>
```

For reference my input data is C720 and my simulation is C90.

My ExtDara.rc import is the following
```
MFXC;MFYC Pa_m+2_s-1    N H F0;003000 none  0.6666666 MFXC;MFYC   ./MetDir/Y%y4/M%m2/D%d2/GEOS.fp.asm.tavg_1hr_ctm_c0720_v72.%y4%m2%d2_%h2%n2.V01.nc4 2021-10-01T00:30:00P01:00
```

Am I missing something?

**Comment by tclune** [comment]
Apologies - apparently I got distracted when composing my response to this last week and then it fell off my plate.

There may be other cases that work, but in general we want both grids to be evenly divisible by the number of processes.  And I will assume that NX=NY.   We also want the number of cells of the fine grid (IM_fine / NX) on a process to be an exact multiple of the number of cells on the coarse grid (IM/NX).  And finally, we want to have at least 4 grid points per coarse subdomain (required by the advec core).

The tables below are overkill - I was expecting this to be more complicated before I actually started enumerating things, but I'll leave the tables in as they are useful references.

So for for C90,  we can have the following decompositions:

|  NX      |      local cell count   |   # fine grid cells per cell |
| ------ |   --------- |  ------ |
|             |     90/NX   |     (720/NX) / (90/NX) = 8 | 
| 1   |   90 |     8 |
| 2  |   45 |      8 |
| 3  |   30 |       8 |
| ... | ... | 8 |
| 15 |   4 |      8 |


For C180 we have 
 |  NX      |      local cell count   |   # fine grid cells per cell |
| ------ |   --------- |  ------ |
|             |     180/NX   |     (720/NX) / (180/NX) = 4 | 
| 1   |   180 |     4 |
| 2  |   90 |      4 |
| 3  |   60 |       4 |
| 4  |    45 |      4 |
| ... | ... | 4 |
| 45 |   4 |      4 |

For C360 we have 
 |  NX      |      local cell count   |   # fine grid cells per cell |
| ------ |   --------- |  ------ |
| 1   |   360 |     2 |
|             |     360/NX   |     (720/NX) / (360/NX) = 2 | 
| 2  |   180 |      2 |
| 3  |   120 |       2 |
| 4  |    90 |      2 |
| ... | ... | 4 |
| 90 |   4 |      2 |

**Comment by LiamBindle** [comment]
Thanks! I'll give these a try next week. I'll reopen if I run into any issues.
