### ISSUE TITLE
Setting num_readers > 1 breaks the model with intel19

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#116]
Setting the number of readers greater than one causes a model crash. This appears to only occur with intel 19 using
comp/intel/19.0.2.187
mpi/impi/19.0.2.187

The crash appears to be when reading tiled restarts. Intel 18 seems to be fine. Can not reproduce crash there.

**Comment by bena-nasa** [comment]
In MAPL_GenericInitialize, always setting num readers/writers to 1 if the component is tiled seems to fix the problem. 

Also will try a newer version of intel 19 when Matt has the baselibs to see if this is a bug with that particular version before committing the above change.

**Comment by tclune** [comment]
How confident are you that this is a compiler bug vs a latent GEOS bug being exposed by a different compiler?   I.e. can we create a small reproducer?   (Only do this if the latest 19 still shows the issue.)

**Comment by mathomp4** [comment]
I was able to run C48 with Intel 19.0.5/Intel MPI 20.0.0 on SLES 12 with `NUM_READERS: 6` so it might be "fixed"?

**Comment by mathomp4** [comment]
I think I'm closing this. @wmputman at some point has run with more than one reader and Intel 19. If not, we make a new issue.
