### ISSUE TITLE
return without abort

### ISSUE THREAD

**Issue by weiyuan-jiang** [GEOS-ESM/MAPL#1194]
We may add a conditional in the "RETURN_" macro for it to do the right thing when `I_AM_MAIN` is in effect.
https://github.com/GEOS-ESM/MAPL/blob/0d3a347ec87e3b39e1052be403f1fde6898267ed/include/MAPL_ErrLog.h#L89

Without this, the main program will abort even if `rc` is 0 (or success).

**Comment by mathomp4** [comment]
The fix is to not define the `_RETURN` macro when `I_AM_MAIN` then that will signal if someone incorrectly uses the `_RETURN` macro in a program.

Should also fix the old-Arlindo style as well.

**Comment by tclune** [comment]
I think the discussion at https://stackoverflow.com/questions/2831934/how-to-use-if-inside-define-in-the-c-preprocessor will provide a solution.   I'm working on something else at the moment, so have not read carefully.  Will look at it next week.

**Comment by tclune** [comment]
After a bit of playing around I don't think the stackoverflow discussion is applicable for a couple of different reasons.  First, I don't think the Fortran preprocessors will quite do what we want, and 2nd we would have to change the way we deal with defining and undefining `I_AM_MAIN` which is not desirable.

But ... the work reminded me of the "solution".   Namely, after undefining `I_AM_MAIN` one can re-include the macro package.   In theory it is written to reset all the macros.   Needs to be tested though.  Then the only issue is remembering to re-include the macros outside the main program in such files.
