### ISSUE TITLE
Can we add a throughput timer encompassing IOservers?

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#1209]
Recently, I was trying out `WRITE_RESTART_BY_OSERVER` where the restarts are at the end of the run and as expected, the model didn't get any faster. With it off:
```
Walltime Used		: 00:32:45
```
and with it on:
```
Walltime Used		: 00:32:43
```

But I was a bit confused at first because I also saw, off:
```
MAPL: INFO: Model Throughput:       48.114 days per day
```
vs on:
```
MAPL: INFO: Model Throughput:       51.364 days per day
```
Faster and yet not. My thoughts now is that this was the *model* throughput. And what I had done had maybe "pushed" some of the time the `run_model` step was taking outside the `run_model` procedure so therefore the model throughput did increase, but the walltime was fixed.

So I wondered, would it be possible to make an "Overall" throughput timer? I'm not sure we can in a good way. The Model Throughput timer uses `get_model_duration()` to figure out how many model days the model ran, and that info might be "outside" of `run` or `run_ensemble`.

Maybe we just need to move/copy the throughput timer up a bit?

**Comment by bena-nasa** [comment]
Since it is  wall time /model run length that you are proposing, I also fear this is not easy to do in a clean way. As you say we need the model duration, but that's really only known down in CapGridComp level since this depends on:
the segment length
the start date via the cap_restart that we set in the clock 

And neither of these is seen outside of CapGridComp.

**Comment by tclune** [comment]
Not thread safe, but we could have CapGridComp set the duration of a variable in the Cap layer.   (Encapsulated, but still bad.)

Or, the CAP does have access to the config file and could compute the duration.  Need to make sure it is while ESMF is initialized.

**Comment by mathomp4** [comment]
This does sound more like a "do in gcm_run.j" sort of thing. I really wish that was a bash script. I can think of functions to write already :)

**Comment by bena-nasa** [comment]
Cap would need 2 files to compute the duration the cap_restart + the duration defined in the CAP.rc

I agree with Matt, this does seem more like a do in gcm_run.j
