### ISSUE TITLE
MAPL develop requires dev/MAPL-2.0 ESMA_cmake

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#121]
As the title says, currently the `Externals.cfg` for `develop` has:
https://github.com/GEOS-ESM/MAPL/blob/a1b228057d27dc9f2ec014e9843f0640f9f9195c/Externals.cfg#L5

This should really be:
```
branch = dev/MAPL-2.0
```
due to how FLAP is referenced differently in `develop`.

The question is...how should this be handled. Perhaps we should create ESMA_cmake 2.0.0 at the same time as MAPL 2.0.0? The changes in ESMA_cmake are not huge:

https://github.com/GEOS-ESM/ESMA_cmake/compare/master...dev/MAPL-2.0

but they are, in a way, a change since using FLAP is now different.

**Comment by tclune** [comment]
I'd forgotten that MAPL depends on FLAP.   Or rather when I thought about FLAP I was thinking that the dependency was in the applications.  Forgot that those delegate through MAPL.

At any rate, Externals.cfg should _not_ reference branches.   Lower risk here than the general case, but I think the principle still applies.    Is there a reason that dev/MAPL-2.0 for cmake is different than master?       I'll be by to discuss (unfortunately not capturing in the ticket.)

**Comment by pchakraborty** [comment]
I see two cases where branches are specified in Externals.cfg

- repository: ecbuild, branch: feature/FindMKL-portability-improvement
- repository: GSW-Fortran, branch: develop

**Comment by tclune** [comment]
The ecbuild case could/should be fixed.    I was reluctant to assign a semantic version to a side branch that we have created.   But we could just make a  non SMV tag for the purpose of freezing.

The GSW-Fortran was a choice by @aerorahul  for something that is not actually used in the model.    There is no harm in this, but it becomes a distraction in discussions such as this one.   I'll encourage him to limit the branch entry to Develop.cfg and use some sort of tag in Externals.cfg.

**Comment by mathomp4** [comment]
Long ago done. Closing.
