### ISSUE TITLE
Implement reporter in Cap to produce desired format.

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#1213]

**Comment by tclune** [comment]
@bena-nasa  Please post your recommendation here.
- Global
- Per-component

**Comment by bena-nasa** [comment]
For the component 
# cycles/min/max/mean/std dev the useful stats.
If we include inclusive and exclusive, we need a very good explanation of what this is as I still can't keep it straight and I've had it explained multiple times.

What is the global in this case?
Global on comm world?
Global on the ESFM comm?
Please elaborate, sure what we are going for with the global.

**Comment by tclune** [comment]
"inclusive" _includes_ everything
"exclusive" excludes something 

That ought to be enough to lead you back to the full explanation.   I don't want the reporter itself to generate this explanation, but Cap can certainly add a line above for that.

And maybe we want less info for one than the other.  E.g., inclusive probably just needs total/average.     It is at the leaf component where the statistical measures have more meaning.

**Comment by bena-nasa** [comment]
Is this a fair statement: For a given timer, the exclusive time is the time spent in that timer minus the times of all the timers in the stack below it?

**Comment by bena-nasa** [comment]
If the above definition of inclusive vs exclusive is true and the "global" is just the component hierarchy. Then it seems like for the global we would want both inclusive and exclusive min/max/mean/stdev
The per component probably just the inclusive and do
#\cycles min/max/mean/stdev

**Comment by tclune** [comment]
Yes - to question about exclusive.   Or more accurately, - excluding time spent in any other timer.   Just so happens that they are all "below" by design.   

Do you really find min/max/mean useful for that long list?   Not opposed, just seems like you probably want the more detailed stuff at the leaf level.

**Comment by tclune** [comment]
Probably should find a way to split the report for the global so that we repeat the headers every 20 lines or so.  I'll add a ticket.

**Comment by mathomp4** [comment]
@tclune is this still a desired option? Or have you essentially done this now in your changes to the profiler?

**Comment by tclune** [comment]
There are still elements that are not done.  And the revert lost some of the bits that are there.  But this ticket is a bit vague anyway.  Several other relevant tickets that can be used to drive the work.   Closing.
