### ISSUE TITLE
Failure to WRITE_RESTART_BY_OSERVER at C720 L181 mid-run

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#1215]
I recently decided to try out using `WRITE_RESTART_BY_OSERVER` in the *middle* of a run a la ADAS. So I set up a C720 L72 run and said "dump restarts at 03z and not at the end" and did it with `WRITE_RESTART_BY_OSERVER` on and off. I had to add a lot of ionodes, but in the end it looked like it might show a little benefit.

But knowing that @wmputman is thinking of moving to L181, I thought I'd try that and see if it gained any advantage. So first I tried with 9 ionodes:
```
 Character Resource Parameter: IRRAD_INTERNAL_CHECKPOINT_TYPE:default
 Using parallel NetCDF for file: irrad_internal_checkpoint.20150415_0300z.nc4
 Character Resource Parameter: AIAU_IMPORT_CHECKPOINT_TYPE:default
 Using parallel NetCDF for file: aiau_import_checkpoint.20150415_0300z.nc4
forrtl: severe (41): insufficient virtual memory
Image              PC                Routine            Line        Source
GEOSgcm.x          0000000003326C8C  Unknown               Unknown  Unknown
GEOSgcm.x          00000000032BA133  Unknown               Unknown  Unknown
GEOSgcm.x          00000000032BB5B1  Unknown               Unknown  Unknown
GEOSgcm.x          00000000032BC769  Unknown               Unknown  Unknown
libMAPL.pfio.so    00002B8380943A0D  pfio_stringattrib         643  vector_impl.inc
```
Okay. Might need more memory. 12 ionodes:
```
 Character Resource Parameter: IRRAD_INTERNAL_CHECKPOINT_TYPE:default
 Using parallel NetCDF for file: irrad_internal_checkpoint.20150415_0300z.nc4
 Character Resource Parameter: AIAU_IMPORT_CHECKPOINT_TYPE:default
 Using parallel NetCDF for file: aiau_import_checkpoint.20150415_0300z.nc4
 AGCM Date: 2015/04/15  Time: 03:07:30  Throughput(days/day)[Avg Tot Run]:     20.6      5.5     26.7  TimeRemaining(Est) 000:52:05   71.4% :  66.1% Mem Comm:Used
forrtl: severe (41): insufficient virtual memory
```
15 ionodes:
```
 Character Resource Parameter: IRRAD_INTERNAL_CHECKPOINT_TYPE:default
 Using parallel NetCDF for file: irrad_internal_checkpoint.20150415_0300z.nc4
 Character Resource Parameter: AIAU_IMPORT_CHECKPOINT_TYPE:default
 Using parallel NetCDF for file: aiau_import_checkpoint.20150415_0300z.nc4
 AGCM Date: 2015/04/15  Time: 03:07:30  Throughput(days/day)[Avg Tot Run]:     20.6      6.2     26.3  TimeRemaining(Est) 000:51:59   71.4% :  66.0% Mem Comm:Used
 AGCM Date: 2015/04/15  Time: 03:15:00  Throughput(days/day)[Avg Tot Run]:     20.7     25.9     26.2  TimeRemaining(Est) 000:51:24   71.3% :  66.0% Mem Comm:Used
 AGCM Date: 2015/04/15  Time: 03:22:30  Throughput(days/day)[Avg Tot Run]:     20.8     25.8     26.2  TimeRemaining(Est) 000:50:51   71.3% :  66.0% Mem Comm:Used
 AGCM Date: 2015/04/15  Time: 03:30:00  Throughput(days/day)[Avg Tot Run]:     20.8     23.4     23.6  TimeRemaining(Est) 000:50:22   78.1% :  69.0% Mem Comm:Used
forrtl: severe (41): insufficient virtual memory
```

It looks like no matter how many nodes I add, this something is running out of memory. 

I did look at my "normal" run and the restarts aren't enormous (I'm not doing geoschemchem). The biggest is 51G:
```
-rw-r--r-- 1 mathomp4 g0620  34G Dec  2 15:26 irrad_internal_checkpoint.20150415_0300z.nc4
-rw-r--r-- 1 mathomp4 g0620  49G Dec  2 15:22 moist_import_checkpoint.20150415_0300z.nc4
-rw-r--r-- 1 mathomp4 g0620  51G Dec  2 15:24 gocart_internal_checkpoint.20150415_0300z.nc4
```

I did briefly talk with @bena-nasa about this and he has a theory that I'll let him talk about.

**Comment by mathomp4** [comment]
I now have another thought. What about geoschemchem...or higher resolution. From what I can see, we'd *never* be able to do `WRITE_RESTART_BY_OSERVER` at super-high-res since some restart might be > 180 GB, say. Unless there's a way to "spread out" a restart on the oservers?

**Comment by bena-nasa** [comment]
Besides the issue of a single restart simply blowing out the memory on a node, I think the way the workers are selected in the multigroup server case is non-optimal currently. I've stared at this code a lot in the last month and it does not seem to round robin among nodes the workers when assigning them (if it is I can't see it).
Note this is how the old o-server behaved, when the controller process assigned a worker, it would round robin to the next node relative to the last one assigned. In addition it at a simple memory hueristic to at least keep track of the amount of data being currently written on each node since it knew what was coming (obviously this doesn't account for system allocated memory like MPI).
I'm wondering if the issues Matt is see are just each restart in the case he is trying (c720 181L should fit on a node easily) is just that they all get packed onto one node rather than round robining.

This of course doesn't fix the larger issue matt mentioned in the previous comment I see now reason c720 181L should not work.

**Comment by tclune** [comment]
@weiyuan-jiang and myself have a nominal plan on how to do that.  Indeed, an early generation of the new O-server worked with the writers being distributed.  It's just that NetCDF seems to scale poorly in that use.   We would instead lock and have each node write its bit seriall.

Even without geoschemchem, it is not inconceivable that some high res case running on some platform will exceed the memory available.  So allowing this is important - just a matter of priority.

**Comment by bena-nasa** [comment]
@weiyuan-jiang in the mean time it seems like round robining the worker assignment among the nodes should be an easier first step.

**Comment by weiyuan-jiang** [comment]
@bena-nasa Now the oserver just picks an idle processor to write data. I can added a step to search empty node first.

**Comment by weiyuan-jiang** [comment]
@mathomp4 I believe we have another option "WRITE_RESTART_BY_FACE". I have implemented that function which has never been activated.

**Comment by mathomp4** [comment]
> @mathomp4 I believe we have another option "WRITE_RESTART_BY_FACE". I have implemented that function which has never been activated.

Well...I can try and see what happens! Let's be adventurous on this Friday and keep NCCS on their toes. 😄 

Or...can I do both? The code seems to say they are exclusive:

https://github.com/GEOS-ESM/MAPL/blob/ed3b61450cf18600186cbec6260d68edb14c3ace/generic/MAPL_Generic.F90#L1111-L1117

**Comment by weiyuan-jiang** [comment]
Ok, I will check why they are conflicted

**Comment by weiyuan-jiang** [comment]
@mathomp4 Would you please try PR #1217 ? Now the writers would try not to concentrate on a node

**Comment by mathomp4** [comment]
> @mathomp4 Would you please try PR #1217 ? Now the writers would try not to concentrate on a node

@weiyuan-jiang Okay. Let me check it out, build, and test!

**Comment by mathomp4** [comment]
> > @mathomp4 Would you please try PR #1217 ? Now the writers would try not to concentrate on a node
> 
> @weiyuan-jiang Okay. Let me check it out, build, and test!

Failed with 9 ionodes, but that could just be "not enough nodes with history and restart writes", so I'm trying with 15 ionodes next.

**Comment by weiyuan-jiang** [comment]
If 15 nodes work,  then it may mean there are more than 9 but less than 15 writings simultaneously.

**Comment by mathomp4** [comment]
Well, 15 ionodes worked. By default the walltime was 01:18:33 and with `WRITE_RESTART_BY_IOSERVER: YES` the walltime was 01:13:51.

History and Init times were fairly equivalent, so I'm thinking this might be real. 4-5 minutes isn't nothing, but it's not mind-blowing either. 

Of course at NAS it might be a *lot* more important :)

**Comment by weiyuan-jiang** [comment]
It is great that the new algorithm actually works and improves the performance. I am going to do more testings...

**Comment by weiyuan-jiang** [comment]
> 

Write_restart_by_face and by_oserver may have conflicts. If it is "by_face", different application PEs would have different 'global' domain. That is not trivial to change.

**Comment by weiyuan-jiang** [comment]
But I still think it is doable.

**Comment by weiyuan-jiang** [comment]
write_restart_by_face is not working anymore.....
