### ISSUE TITLE
Support 1D output in History 

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#122]
This request is from Harvard, and the intent is to reduce CTM output to just the values "seen" by an orbiting instrument.   History spec could specify a file that has the (lat,lon,time) path of the instrument.

**Comment by tclune** [comment]
A similar request was made by Leslie Ott for output just at station data.

**Comment by mathomp4** [comment]
> A similar request was made by Leslie Ott for output just at station data.
Would that then be...0-D data?

**Comment by tclune** [comment]
Well, yeah.   Except it's still columns, so the dimensionality does depend a bit on the type of variable.

**Comment by bena-nasa** [comment]
This has been completed
