### ISSUE TITLE
What happens to long duration time averages in HISTORY if a simulation is restarted midway from a checkpoint file?

### ISSUE THREAD

**Issue by LiamBindle** [GEOS-ESM/MAPL#1241]
Hi all,

I have a question about HISTORY handling when a simulation crashes.

If I have a 1 month time-average in HISTORY, and 7-day checkpointing, if I restart my simulation midway from a checkpoint file will my monthly time-average output be okay?

Thanks,
Liam

**Comment by mathomp4** [comment]
Assigning @bena-nasa and @atrayano because...well, they'd know.

**Comment by atrayano** [comment]
This should work. During MAPL finilize, we write checkpoint not only for the gridded components, but also for all monthly collections (unless we stop at the month's boundary). The caveat is the MAPL by itself does not rename the checkpoint files (these are named _collectioname__checkpoint) to the expected _collectionname__rst. Your run script has to do this, or you can do it manually

**Comment by LiamBindle** [comment]
Thanks for the reply. I'm moreso refering to a simulation that's crashed though. If my simulation crashes on day 16 of the month, and I simply restart it by setting `cap_restart` and setting the appropriate checkpoint file in `GCHP.rc`, does the checkpoint file for the gridded component include HISTORY diagnostics? (It sounds like no?)

A user in our group tried this and he noticed a `-partial` suffix in his filename. Is that related?

**Comment by atrayano** [comment]
-partial is indication that MAPL did not read a checkpoint file at the beginning of the run (and the start day/time was not at the month's boundary).

MAPL does not save intermediate checkpoints for History, only at the end of the run
