### ISSUE TITLE
Percentage column in MAPL Timers aren't summing, should they?

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#1242]
Something I just noticed with the MAPL timers. For example:
```
 Times for component <HIST>
                                       Min             
                            ==========================  
Name                          %    inclusive exclusive  
                          | ------ --------- --------- |
HIST                      |   0.00      8.31      0.00 |
--SetService              |   0.00      0.00      0.00 |
----generic               |   0.00      0.00      0.00 |
--Initialize              |  24.93      2.02      2.02 |
----generic               |   0.00      0.00      0.00 |
--Run                     |   0.00      6.29      0.00 |
----GenRunMine            |   0.15      6.29      0.01 |
------ParserRun           |   0.46      0.04      0.04 |
------Couplers            |   2.91      0.24      0.24 |
------I/O                 |   0.00      6.00      0.00 |
--------IO Create         |   0.45      0.04      0.04 |
--------IO Write          |   0.00      5.75      0.00 |
----------IO Post         |  71.07      5.75      5.75 |
----------IO Wait         |   0.00      0.00      0.00 |
----------IO Write        |   0.00      0.00      0.00 |
--Finalize                |   0.00      0.00      0.00 |
----generic               |   0.01      0.00      0.00 |
```

I see that the `inclusive` timer at the "top" `HIST` line does sum to the total of the `SetService`, `Initialize`, `Run`, and `Finalize` phases. The `exclusive` doesn't but I'm sort of debating to myself if it should (probably not).

But, I am wondering about the percentage column. Which I had two questions:

1. Should the Big 4 Phases sum? That is should all the percentages in the `Run` phase sum up and be the percentage in the `--Run` line? 
2. Should the whole column sum up? Part of me pedantically wants to see the top line be:
```
HIST                      | 100.00      8.31      0.00 |
```
But then...we know it should be 100, so is that even worth it?

Just something for @tclune to ponder when he returns.

**Comment by tclune** [comment]
I see it the other way around.  The sum of the times of inclusive's do _not_ add up.  This is because the overlap.  OTOH, the top inclusive overlaps everything - hence it is 100%.  The exclusive times _do_ add up to 8.31 modulo a bit of roundoff.
