### ISSUE TITLE
MPICH4: [WARNING] yaksa: 3 leaked handle pool objects

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#1244]
Recently I decided to try out MPICH with GEOS. This was after the issue the GCHP folks saw with someone running GCHP with MPICH3.

So, I grabbed MPICH 4.0b1 and with the help of @hzhou on the [MPICH mailing list](https://lists.mpich.org/pipermail/discuss/2021-December/006307.html) (see also https://github.com/pmodels/mpich/pull/5728), I got a working MPICH! I could run HelloWorld on Discover, so I built Baselibs and no errors were seen.

I then found that MPICH would crash if you (accidentally) set:
```
  ROMIO_FSTYPE_FORCE="gpfs:"
```
and ran GEOS. (I've asked [the MPICH Discuss list](https://lists.mpich.org/pipermail/discuss/2021-December/006312.html) about that.)

Okay. Worked around that and GEOS runs! Huzzah! And is zero-diff to Open MPI! Double huzzah!

But, at the very end of the run (after all the timers print) I see:
```
[WARNING] yaksa: 3 leaked handle pool objects
```

Obviously, I'll make sure to ask on the MPICH list about this, but since the ROMIO issue might presage a "You built MPICH wrong", I'm waiting to hear back on that before asking there.

Still, I thought I should add an issue here since "leaked handle pool objects" at the end of a run sounds like a possible @tclune or @weiyuan-jiang sort of "we might have not cleaned up some MPI" sort of thing...

**Comment by raffenet** [comment]
It might indicate you didn't call `MPI_Type_free` on all user-defined datatypes before `MPI_Finalize`.

**Comment by mathomp4** [comment]
> It might indicate you didn't call `MPI_Type_free` on all user-defined datatypes before `MPI_Finalize`.

@raffenet Is there a way to make yaksa (or whatever) more verbose? Like can it give hints where we might find the un-free'd types? I have an idea though...

**Comment by raffenet** [comment]
I would try adding `--enable-g` to your MPICH configuration. That turns on MPI object handle debugging, and should be able to tell you if there are unfreed objects at finalize time.

**Comment by mathomp4** [comment]
> I would try adding `--enable-g` to your MPICH configuration. That turns on MPI object handle debugging, and should be able to tell you if there are unfreed objects at finalize time.

Ooh. Rebuild time! Okay. I've put it on my to-do list. Now to find out if I need to rebuild all our dependent libraries, or if just our code is enough... :)

**Comment by raffenet** [comment]
> > I would try adding `--enable-g` to your MPICH configuration. That turns on MPI object handle debugging, and should be able to tell you if there are unfreed objects at finalize time.
> 
> Ooh. Rebuild time! Okay. I've put it on my to-do list. Now to find out if I need to rebuild all our dependent libraries, or if just our code is enough... :)

If you are dynamically linked to MPICH, then just rebuilding/installing it should be enough. Good luck!

**Comment by mathomp4** [comment]
Well, I can definitely say that `--enable-g` does something. Parsing through the rather voluminous output and ignoring lines like:
```
...
[19] 56 at [0xc5f12d0], ./include/mpl_shm.h[96]
[19] 24 at [0xc5f1200], ./include/mpl_shm.h[111]
[19] 24 at [0xc5f1130], src/mpid/common/shm/mpidu_shm_alloc.c[632]
[19] 288 at [0xc5f0f60], src/mpid/common/shm/mpidu_shm_alloc.c[630]
...
```

I see:
```console
$ rg still 1day.no_env.debug_mpich.out | sort | uniq
In direct memory block for handle type GROUP, 2 handles are still allocated
In direct memory block for handle type OP, 1 handles are still allocated
In indirect memory block 0 for handle type COMM, 296 handles are still allocated
In indirect memory block 0 for handle type COMM, 331 handles are still allocated
In indirect memory block 0 for handle type COMM, 334 handles are still allocated
In indirect memory block 0 for handle type COMM, 366 handles are still allocated
In indirect memory block 0 for handle type COMM, 437 handles are still allocated
In indirect memory block 0 for handle type COMM, 507 handles are still allocated
In indirect memory block 0 for handle type DATATYPE, 3 handles are still allocated
In indirect memory block 0 for handle type GROUP, 1 handles are still allocated
In indirect memory block 0 for handle type GROUP, 13 handles are still allocated
```

I'll talk more in #1250
