### ISSUE TITLE
Possible unfreed types and op in DistributedMeter

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#1250]
Based on this reply by @raffenet:

> It might indicate you didn't call `MPI_Type_free` on all user-defined datatypes before `MPI_Finalize`.
> 
> _Originally posted by @raffenet in https://github.com/GEOS-ESM/MAPL/issues/1244#issuecomment-997016436_

I started looking around MAPL. And I saw that in:

- `pfio/ServerThread.F90`
- `pfio/MpiMutex.F90`
- `shared/MAPL_LoadBalance.F90`

we have the usual create-type-free trio. But, then I looked at `profiler/DistributedMeter.F90` and I'm not seeing any `MPI_Type_free` in there. 

This code is pretty good @tclune / @weiyuan-jiang level Fortran (yay OO) so it's always hard for me to parse, but I do not see any frees.

I'm wondering if perhaps we need some sort of "finalize" routine in there to free the types made in there? (Or maybe we need three since there are three different make_type routines?)

**Comment by mathomp4** [comment]
We might have more than unfreed types:
```console
$ rg still 1day.no_env.debug_mpich.out | sort | uniq
In direct memory block for handle type GROUP, 2 handles are still allocated
In direct memory block for handle type OP, 1 handles are still allocated
In indirect memory block 0 for handle type COMM, 296 handles are still allocated
In indirect memory block 0 for handle type COMM, 331 handles are still allocated
In indirect memory block 0 for handle type COMM, 334 handles are still allocated
In indirect memory block 0 for handle type COMM, 366 handles are still allocated
In indirect memory block 0 for handle type COMM, 437 handles are still allocated
In indirect memory block 0 for handle type COMM, 507 handles are still allocated
In indirect memory block 0 for handle type DATATYPE, 3 handles are still allocated
In indirect memory block 0 for handle type GROUP, 1 handles are still allocated
In indirect memory block 0 for handle type GROUP, 13 handles are still allocated
```

We might want to do a scan of all the MPI (assuming a lot of these aren't due to Baselibs libraries). There are way too many COMM here and I can't imagine we are making that many. But, we could have a shot at cleaning up the `MPI_Group`, `MPI_Op`, and `MPI_Type` maybe. 

I do see an `MPI_Op_create` in DistributedMeter, and no associated `MPI_Op_free`.

**Comment by weiyuan-jiang** [comment]
Well catch! I will try to find a way to free them

**Comment by mathomp4** [comment]
The comms are hilarious. It has to be one of our sub-libraries, right? We can't be making 507 communicators that we don't free?

**Comment by raffenet** [comment]
> The comms are hilarious. It has to be one of our sub-libraries, right? We can't be making 507 communicators that we don't free?

The comms may not be entirely what they seem. Each comm in MPICH can internally include additional sub-comms not visible to the user, but which would still show up in the handle debugging.

**Comment by mathomp4** [comment]
> > The comms are hilarious. It has to be one of our sub-libraries, right? We can't be making 507 communicators that we don't free?
> 
> The comms may not be entirely what they seem. Each comm in MPICH can internally include additional sub-comms not visible to the user, but which would still show up in the handle debugging.

Ahhh. I guess I still think of MPI stacks as "black boxes" (if it works, I keep my hands off 😄 ). But makes sense it'd make it's own comms underneath. Thanks for the explanation, @raffenet 

Still, I think the Op and Type are things we need to look at. Probably are some missing frees there.

**Comment by weiyuan-jiang** [comment]
@tclune Should we move these variables ( names may be changed) to abstract class so they can be freed?
https://github.com/GEOS-ESM/MAPL/blob/aba26d6deeb7349b55cf34d752162aaec4b573ca/profiler/DistributedMeter.F90#L92-L95

**Comment by tclune** [comment]
Definitely should be moved into a type - not obvious at first glance that it would need to be an abstract type.
