### ISSUE TITLE
Make new History metadata configurable

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#1282]
Due to the changes in MAPL 2.15.1 (see #1271), we now have "hard-coded" into the global metadata of MAPL History output:
```
:Contact = "http://gmao.gsfc.nasa.gov" ;
:Institution = "NASA Global Modeling and Assimilation Office" ;
```
While these are good defaults for the majority of MAPL users, some of our other colleagues at Harvard (@lizziel) and NOAA (@rmontuoro) and even non-GMAO NASA users (@mmanyin) could use MAPL for History output and would probably enjoy not having to do an extra `ncatted` call to change this. 

So, let us allow the ability to change these values inside `HISTORY.rc` (and upcoming `history.yaml`) files a la:
```
INSTITUTION: "Yoyodyne Propulsion Systems"
CONTACT: "Lord John Whorfin"
```

We also have:
```
:Comment = "NetCDF-4" ;
```
Whatever needs to be done for the `Contact` and `Institution` can probably be extended to the `Comment` field as well. Might as well let users make whatever comments they'd like to as well.

**Comment by mathomp4** [comment]
Actually, I'm not sure if spaces are allowed in ESMF_Config objects (@bena-nasa, @atrayano or @tclune might know). Might be nice to have some sort of "translate underscores to spaces" sort of capability with this?

**Comment by atrayano** [comment]
Spaces are allowed in ESMF_Config and normally they are ignored. But in a quoted string they are preserved and kept

**Comment by mathomp4** [comment]
> Spaces are allowed in ESMF_Config and normally they are ignored. But in a quoted string they are preserved and kept

Ahhh. And you are correct, @atrayano! I just just hacked in a config object in a random GC to test and:
```
INSTITUTION: Yoyodyne Propulsion Systems
```
printed out:
```
MATMAT INSTITUTION: Yoyodyne
```
but:
```
INSTITUTION: "Yoyodyne Propulsion Systems"
```
gave me:
```
MATMAT INSTITUTION: Yoyodyne Propulsion Systems
```
I learned some ESMF today! 😄
