### ISSUE TITLE
Bad chunking and bad write in pFIO isn't trapped correctly

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#1285]
When looking at issue #626 with @tclune I decided to run a test. I set this for `geosgcm_prog`:
```
...
  geosgcm_prog.grid_label: PC96x49-DC
  geosgcm_prog.chunksize:   500 200 1 1,
  geosgcm_prog.deflate:   1,
...
```
This is an obviously bad chunksize for a 96x49 file. The issue is that the model does not crash when you do this:
```
...
 AGCM Date: 2000/04/14  Time: 23:30:00  Throughput(days/day)[Avg Tot Run]:   2194.5   2601.6   2664.1  TimeRemaining(Est) 000:00:35   26.9% :  23.2% Mem Comm:Used
 AGCM Date: 2000/04/14  Time: 23:45:00  Throughput(days/day)[Avg Tot Run]:   2234.1   2730.8   2799.8  TimeRemaining(Est) 000:00:34   26.9% :  23.1% Mem Comm:Used

 Writing:    483 Slices to File:  mapl12151-gcm-2022Jan06-1day-c24-Institution.geosgcm_prog.20000415_0000z.nc4
 Writing:    153 Slices to File:  mapl12151-gcm-2022Jan06-1day-c24-Institution.geosgcm_surf.20000414_2230z.nc4
 Writing:      5 Slices to File:  mapl12151-gcm-2022Jan06-1day-c24-Institution.geosgcm_budi.20000415_0000z.nc4
 Writing:     21 Slices to File:  mapl12151-gcm-2022Jan06-1day-c24-Institution.geosgcm_buda.20000414_2230z.nc4
pe=00000 FAIL at line=00701    NetCDF4_FileFormatter.F90                <status=-127>
pe=00000 FAIL at line=00297    NetCDF4_FileFormatter.F90                <status=-127>
pe=00000 FAIL at line=00063    HistoryCollection.F90                    <status=-127>
pe=00000 FAIL at line=00029    NetCDF4_put_var.H                        <status=-33>
pe=00000 FAIL at line=00029    NetCDF4_put_var.H                        <status=-49>
pe=00000 FAIL at line=00029    NetCDF4_put_var.H                        <status=-49>
pe=00000 FAIL at line=00029    NetCDF4_put_var.H                        <status=-49>
pe=00000 FAIL at line=00029    NetCDF4_put_var.H                        <status=-49>
pe=00000 FAIL at line=00029    NetCDF4_put_var.H                        <status=-49>
pe=00000 FAIL at line=00029    NetCDF4_put_var.H                        <status=-49>
pe=00000 FAIL at line=00029    NetCDF4_put_var.H                        <status=-49>
pe=00000 FAIL at line=00029    NetCDF4_put_var.H                        <status=-49>
pe=00000 FAIL at line=00029    NetCDF4_put_var.H                        <status=-49>
pe=00000 FAIL at line=00029    NetCDF4_put_var.H                        <status=-49>
pe=00000 FAIL at line=00029    NetCDF4_put_var.H                        <status=-49>
pe=00000 FAIL at line=00029    NetCDF4_put_var.H                        <status=-49>
pe=00000 FAIL at line=00029    NetCDF4_put_var.H                        <status=-49>

 AGCM Date: 2000/04/15  Time: 00:00:00  Throughput(days/day)[Avg Tot Run]:   1978.5    876.7   2033.7  TimeRemaining(Est) 000:00:38   26.9% :  23.2% Mem Comm:Used
        EXTDATA: INFO: Updating R bracket for BC_BIOMASS
        EXTDATA: INFO:  ... file processed: ExtData/PIESA/sfc/QFED/v2.4r6/Y2000/M04/qfed2.emis_bc.005.20000416.nc4
        EXTDATA: INFO: Updating R bracket for CO_BIOMASS
        EXTDATA: INFO:  ... file processed: ExtData/PIESA/sfc/QFED/v2.4r6/Y2000/M04/qfed2.emis_co.005.20000416.nc4
...
```

You can see that we triggered part of the traceback and we captured the [netCDF error code for bad chunking](https://www.unidata.ucar.edu/software/netcdf/docs/nc-error-codes.html)

But the model kept on going. Indeed, even worse a failed write of History output didn't stop the model. In the end I ended up with 4 geosgcm_prog files that are just...stumps:
```console
$ ncdump -hsc scratch/mapl12151-gcm-2022Jan06-1day-c24-Institution.geosgcm_prog.20000415_0000z.nc4
netcdf mapl12151-gcm-2022Jan06-1day-c24-Institution.geosgcm_prog.20000415_0000z {

// global attributes:
		:_SuperblockVersion = 2 ;
		:_IsNetcdf4 = 0 ;
		:_Format = "netCDF-4" ;
}
$
```

This is rather scary for sure. @tclune suspects we are not trapping RC in a couple places:

1. A failed write with pFIO (put_var) should be trapped.
2. A bad chunking in netCDF should be trapped.

Probably 1 should be fixed first. Then once that's fixed, 2 can be fixed as well.

I'm also CC'ing in @bena-nasa as this is also History-related. @tclune might have more to say on this.

**Comment by mathomp4** [comment]
Note that it's possible that @bena-nasa could actually stop History at initialize *before* we get here by noticing that a chunksize of 500x200 won't work for a 96x49 output file and output a useful message and abort (see #626).

But we should fix these issues first. Then maybe move the abort up to Initialize time rather than Run time?

**Comment by bena-nasa** [comment]
@tclune @mathomp4 
I can trap this on the History side when defining the metadata if we give bad chunking. Let me see if I can do this without having to introduce more methods into the grid factories that isn't klugy. Remember we go to great lengths to hide the fact that the cubed-sphere grid is tiled so I can't just use the regular MAPL_GridGet to determine the grid extents and compare to the chunking values. Stay tuned

**Comment by tclune** [comment]
@bena-nasa Just remember that this is secondary.   The real issue is that existing checks are not properly trapped.   Fixing in the location you are discussing will mask the other problem, so best done separately/after.

**Comment by bena-nasa** [comment]
@tclune, ok sit on this and let weiyuan try to fix the server.

**Comment by weiyuan-jiang** [comment]
@bena-nasa I will fix this. For this particular error, it is not on pFIO side. It is on MAPL.

**Comment by tclune** [comment]
@weiyuan-jiang No - the error is in pfio.   The _error_ is in not trapping errors that are found.    There may be additional errors, but @mathomp4 and I worked through this stack trace and it is clear that RC is being set and then not checked at intervening levels.

**Comment by weiyuan-jiang** [comment]
@mathomp4 Can you test PR #1290 and see if it solves this issue?

**Comment by mathomp4** [comment]
@weiyuan-jiang I'll try it soon, but I think we might need to trap the `put_var` and `get_var` that I saw in `ServerThread.F90` a la:

https://github.com/GEOS-ESM/MAPL/blob/f98fae5c158838b991eeda51ebe3e7d93f4d6fea/pfio/ServerThread.F90#L814

https://github.com/GEOS-ESM/MAPL/blob/f98fae5c158838b991eeda51ebe3e7d93f4d6fea/pfio/ServerThread.F90#L691

**Comment by weiyuan-jiang** [comment]
OK, indeed, I missed some.

**Comment by weiyuan-jiang** [comment]
There is still chance that some errors are still not trapped. We will see if we can reproduce the case reported by @rmontuoro

**Comment by mathomp4** [comment]
As @weiyuan-jiang has an outstanding PR to partially address this, I'll un-stale it for now.

**Comment by mathomp4** [comment]
@mathomp4 Try this out and see if it works now.
