### ISSUE TITLE
rt-GEOSadas-5_29_3_p2 (fpp tag) opens wrong file for SU_H2O2, SU_OH, SU_NO3 in ExtData at certain times

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#1291]
While trying to assist a user I uncovered a truly bizarre behavior. The user was trying to get zero-diff to a DAS run with said tag starting on 2021-12-30T09:00:00z. When comparing logs I found that the first round of ExtData reads reported this in the OPS run:
```
   EXTDATA: Updating L bracket for SU_H2O2
   EXTDATA:  ... file processed: ExtData/PIESA/L72/A2_ACCMIP_gmic_MERRA_oh_h2o2_no3.x144_y91_z72_t14.2022.nc
   EXTDATA: Updating R bracket for SU_H2O2
   EXTDATA:  ... file processed: ExtData/PIESA/L72/A2_ACCMIP_gmic_MERRA_oh_h2o2_no3.x144_y91_z72_t14.2022.nc
   EXTDATA: Updating L bracket for SU_OH
   EXTDATA:  ... file processed: ExtData/PIESA/L72/A2_ACCMIP_gmic_MERRA_oh_h2o2_no3.x144_y91_z72_t14.2022.nc
   EXTDATA: Updating R bracket for SU_OH
   EXTDATA:  ... file processed: ExtData/PIESA/L72/A2_ACCMIP_gmic_MERRA_oh_h2o2_no3.x144_y91_z72_t14.2022.nc
   EXTDATA: Updating L bracket for SU_NO3
   EXTDATA:  ... file processed: ExtData/PIESA/L72/A2_ACCMIP_gmic_MERRA_oh_h2o2_no3.x144_y91_z72_t14.2022.nc
   EXTDATA: Updating R bracket for SU_NO3
   EXTDATA:  ... file processed: ExtData/PIESA/L72/A2_ACCMIP_gmic_MERRA_oh_h2o2_no3.x144_y91_z72_t14.2022.nc
``` 
but the users run with the same tag, same RC files, start date, and initial conditions gives:
```
        EXTDATA: INFO: Updating L bracket for SU_H2O2
        EXTDATA: INFO:  ... file processed: ExtData/PIESA/L72/A2_ACCMIP_gmic_MERRA_oh_h2o2_no3.x144_y91_z72_t14.2021.nc
        EXTDATA: INFO: Updating R bracket for SU_H2O2
        EXTDATA: INFO:  ... file processed: ExtData/PIESA/L72/A2_ACCMIP_gmic_MERRA_oh_h2o2_no3.x144_y91_z72_t14.2021.nc
        EXTDATA: INFO: Updating L bracket for SU_OH
        EXTDATA: INFO:  ... file processed: ExtData/PIESA/L72/A2_ACCMIP_gmic_MERRA_oh_h2o2_no3.x144_y91_z72_t14.2021.nc
        EXTDATA: INFO: Updating R bracket for SU_OH
        EXTDATA: INFO:  ... file processed: ExtData/PIESA/L72/A2_ACCMIP_gmic_MERRA_oh_h2o2_no3.x144_y91_z72_t14.2021.nc
        EXTDATA: INFO: Updating L bracket for SU_NO3
        EXTDATA: INFO:  ... file processed: ExtData/PIESA/L72/A2_ACCMIP_gmic_MERRA_oh_h2o2_no3.x144_y91_z72_t14.2021.nc
        EXTDATA: INFO: Updating R bracket for SU_NO3
        EXTDATA: INFO:  ... file processed: ExtData/PIESA/L72/A2_ACCMIP_gmic_MERRA_oh_h2o2_no3.x144_y91_z72_t14.2021.nc
```
The ExtData lines that govern these imports are:
```
SU_H2O2 NA     N Y %y4-%m2-%d2t12:00:00 none none H2O2 ExtData/MERRA2/L72/gmi_ctm_hindcast.oxidants.x144_y91_z72_t14.%y4.nc4
SU_OH   NA     N Y %y4-%m2-%d2t12:00:00 none none OH   ExtData/MERRA2/L72/gmi_ctm_hindcast.oxidants.x144_y91_z72_t14.%y4.nc4
SU_NO3  NA     N Y %y4-%m2-%d2t12:00:00 none none NO3  ExtData/MERRA2/L72/gmi_ctm_hindcast.oxidants.x144_y91_z72_t14.%y4.nc4
```
The OPS run appears to be opening the wrong file as it should be opening the 2021 file given the start date. I examined all the fpp logs for the end of December here /home/dao_ops/f5293_fpp/run/.../archive/etc/Y2021/M12 and from the 25th on all runs started opening the 2022 file. (As an aside, these files should have been replaced a long time ago as these t14 padded files are unnecessary, and if they had been replaced I think this would have flat out failed for other reasons, it looks like in the latest version of gocart these have been replaced). 

In any case, I built the tag, ran starting on the 2021-12-30T09:00:00z and saw the same thing the user did, the 2021 files were opened as expected. I spent a long time starting at the code and can't explain what I'm seeing with the OPS logs. The only way the wrong file could be opened is if something is going wrong with some manipulations with ESMF Time Intervals. Some standalone testing suggests there is a problem with this in certain cases, but not in a way that could explain the current symptoms. This is getting long so I will append this with additional posts.

**Comment by mathomp4** [comment]
@bena-nasa is this still an issue/bug?

**Comment by mathomp4** [comment]
@bena-nasa Is this still an issue?

**Comment by mathomp4** [comment]
Time to ping @bena-nasa again.

**Comment by mathomp4** [comment]
Hmm. I'm going to keep this open until @bena-nasa can weigh in on it.
