### ISSUE TITLE
Issue with MOM6 on macOS: Logger Message

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#1292]
When trying to test out the C12 MOM6 on Parcel (my MacBook), the model crashed with:
```
 Character Resource Parameter: MOM6_GEOSPLUG:libMOM6_GEOSPlug.so
 FormatString.F90         173
 format_vector() - additional unprocessed arguments.
1
```
Working with @tclune we found this was due to a logger message call:

https://github.com/GEOS-ESM/MAPL/blob/f98fae5c158838b991eeda51ebe3e7d93f4d6fea/generic/MAPL_Generic.F90#L4799-L4800

Namely the single quotes. @tclune will look at pFlogger but for now, I'll make a PR for a workaround.

**Comment by tclune** [comment]
A proper workaround for this limitation would be to put the literal quotes around the arguments instead of the formats.  Look like even Python's logging package suffers a similar issue.
```f90
call lgr%warning(".... %a ... %a", "'"//arg1//"'",  "'"//arg2//"'")
```
