### ISSUE TITLE
Input regridding does not identify file-defined missing values

### ISSUE THREAD

**Issue by lizziel** [GEOS-ESM/MAPL#1294]
I recently investigated a reported crash in GCHP when using an optional emissions inventory. In looking closer at the issue I stumbled upon a bug in MAPL. The emissions file contains a field with missing values defined in the NetCDF file as -1e-31. Rather than treat them as missing, MAPL regridded them as if they were valid. The resulting negative values for some grid cells caused HEMCO to crash.

The proper behavior should be recognition of missing values via the missing values attribute per field in the NetCDF file, and then appropriate handling during regridding.

**Comment by bena-nasa** [comment]
@tclune @lizziel 
I'm working on this. Should be done today.
For now I will tell it to look for _FillValue.
When perusing the CF conventions about fill value:
https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#missing-data
I'm wondering if I should look for more, like check for missing_value as well and make sure it is consistent with _FillValue if it is there? 
Of course his is not helped that the links for the NUG conventions tgat perhaps clarify this a bit more in the CF document are broken if you click on them.

**Comment by lizziel** [comment]
I checked the data we are using that contains missing values and it has both _FillValue and missing_value defined in the file. The values are the same. It seems like a good idea to check that they are the same if both are present.

**Comment by bena-nasa** [comment]
The way I read the document CF references, the missing_value is merely there for a reference and it's use is really open to interpretation or discretion of the library writer:
https://www.unidata.ucar.edu/software/netcdf/documentation/4.7.4-pre/attribute_conventions.html
"This attribute is not treated in any special way by the library or conforming generic applications, but is often useful documentation and may be used by specific applications."
Seems like missing_value useless if _FillValue is present to me. I suppose if they differ for some reason, it should halt execution?

**Comment by bena-nasa** [comment]
After some more back and forth and rereading documentation, I think we are going to keep things as they are, just look for _FillValue. That's really what should be used and only what should be used.

**Comment by tclune** [comment]
I think we should add a check for files that have no fill value.    Should be an error (maybe a warning) if such a file is ingested.
