### ISSUE TITLE
Updating ecbuild version in MAPL

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#1318]
This is a question for:

- @lizziel 
- @rmontuoro 

A potential user of MAPL found that building _without_ Baselibs but building _with_ our ESMA_cmake/ecbuild caused a CMake error. The issue was that the `FindNetCDF.cmake` package in our fork of ecbuild was too old. 

So, as a test, I updated the file with a recent one from JCSDA (who I think doesn't even use that fork anymore), and it seemed to work from him. Testing with GEOS and MAPL shows no effect because we (at present) don't use this file.

What I'd like to ask our Harvard and NOAA colleagues is: Does this matter for you? I want to say that UFS uses their own CMake setup, so my guess is no, but I'm not too sure of Harvard.

I think this is a "safe" upgrade no matter what since our current `FindNetCDF.cmake` is woefully old and the new one is at least modern.

**Comment by lizziel** [comment]
I don't think this would affect us but I'm bouncing this to @LiamBindle to confirm.

**Comment by mathomp4** [comment]
> Thanks for checking, @mathomp4. I don't expect this change to affect our build, since we are using a different version of ecbuild.

@rmontuoro Thanks. Note that I'm hoping to move GEOS to "essentially" ECMWF ecbuild stable soon. The only issue is we have internal changes to ecbuild (for our Aggressive flags) which we need to keep around. I have an issue raised with them about this, but haven't heard anything back. Maybe I need to propose a CMake change...
