### ISSUE TITLE
Where to move MAPL_SimpleBundleMod (and refactor it too, maybe)

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#1323]
For the v2.8.0.2 patch we are creating for the das we replaced the MAPL_CFIORead in MAPL_SimpleBundleMod with it's replacement mapl_read_bundle. However, due to the reorganization that took place after v2.8.0 making this change introduces a circular dependency between GriddedIO and Base since GriddedIO depends on Base. So MAPL_SimpleBundleMod will have to move to get this same patch into develop. @atrayano @tclune have any preferences where I move this too. It doesn't seem like there is a natural home outside of base. I could just move it to GriddedIO? I don't know, can't really think of a better place, but can't stay where it is. 

While on the topic, it makes liberal use of pointers that probably should be allocatables, but as this is mostly used by the DAS nowadays care must be taken.

**Comment by atrayano** [comment]
I am totally fine with moving it to base

**Comment by tclune** [comment]
I think the details matter here.    I need to understand what the individual elements are that cause the circular dependency.    It could be that something in Base should move out/up.

**Comment by bena-nasa** [comment]
No, no, it needs move OUT of base. I need to change the MAPL_CFIORead to mapl_read_bundle in MAPL_SimpleBundleMod. MAPL_SimpleBundleMod is in Base now. mapl_read_bundle is in GriddedIO. Things in GriddedIO depend on Base, hence MAPL_SimpleBundleMod can't stay there, it has to move. We've already released a patch with this change (v2.8.0.2) so it's got to move somewhere

**Comment by tclune** [comment]
I agree at least one thing must give ...

The odd thing is that SimpleBundle by itself does not suggest anything about I/O, but ... clearly one or more of its procedures do I/O (directly or indirectly).     So it seems to me it should either move to GriddedIO _or_ to `generic`.   Neither is perfect, and neither is probably the permanent home.

Another possibility that is probably too much trouble is to refactor SimpleBundle so that it does not do I/O itself but rather something in Gridded I/O can _build_ a SimpleBundle using I/O.  Then SimpleBundle could safely stay in Base.   Happy to discuss in Teams if you want to explore this option.

**Comment by bena-nasa** [comment]
We could try to break it apart, have something in GriddedIO that creates a simple bundle from a file, although we have more important fish to fry quite frankly, I say just move it to GriddedIO and be done with it. It we are going to the trouble of that kind of refactoring we might as well get rid of all the pointers with allocatables while we are at it. But once again, probably not worth the trouble.

MAPL_SimpleBundleMod is usedin the DAS in the GSI but I suspect once JEDI arrives and the GSI goes away, that use of MAPL_SimpleBundle would go away. The MAPL_SimpleBundleRead looks like an extension that must have been added for chemistry as it is only used a few places in GEOSChem and GEOSChemChem repos.

**Comment by tclune** [comment]
@bena-nasa I'm fine with that.

**Comment by atrayano** [comment]
We need to be careful before deciding to get rid off it. This was Arlindo's creation, and he uses it in the tutorial, Chemistry, and quite possibly other pieces he wrote

**Comment by bena-nasa** [comment]
I'm not getting rid of it.

**Comment by tclune** [comment]
Yes - we most likely cannot eliminate it.  Arlindo not only uses it, he wrote it and thinks it a wonderful thing.

But I think it could be greatly improved as a cleaned up OO layer at some point.  Hopefully we could make it so good he'd be willing to adopt it.
