### ISSUE TITLE
Should ALL timers be controlled by one toggle?

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#1332]
To turn on the model timers you do it via a option in a resource file.
To turn on the PFIO timers you do it via the command line.

This seems a bit confusing and incongruent. It seems like all the timers should be controlled by one toggle whether that is via a file or the command line. 

Just throwing this out there. Thoughts?

**Comment by mathomp4** [comment]
Hmm. Part of me says: "if I want profiling, give me all the profiling". But then I can see the want for maybe a subset of everything. Like, if I'm not writing anything, then pFIO profiling isn't needed.

**Comment by tclune** [comment]
The on/off needs to be added for the new timers. (Including mem profiler)

Now a high priority - with mem profiling being "off" by default.

**Comment by mathomp4** [comment]
I think #1385 closed this.
