### ISSUE TITLE
Missing gFTL v2 target for MAPL.profiler prevents MAPL from building

### ISSUE THREAD

**Issue by rmontuoro** [GEOS-ESM/MAPL#1334]
The following `MAPL.profiler` file includes a template from gFTL v2:
https://github.com/GEOS-ESM/MAPL/blob/28a874ee60734690d0bbdc3fb266a64146fe3ce3/profiler/MeterNodeStack.F90#L9

However, the `GFTL::gftl-v2` target is missing in:
https://github.com/GEOS-ESM/MAPL/blob/28a874ee60734690d0bbdc3fb266a64146fe3ce3/profiler/CMakeLists.txt#L52

**Comment by mathomp4** [comment]
Hmm. I thought `GFTL::gftl` brought in both versions...

**Comment by tclune** [comment]
I'm also curious why this is not a problem on our end.

**Comment by tclune** [comment]
Checking - no GFTL::gftl is just an alias for v1.    It will switch to v2 when gFTL 2.0 is released.   Still confused why we don't get the error though.

**Comment by tclune** [comment]
@weiyuan-jiang Can you do a hotfix off of main to add GFTL::gftl-v2 in the esma_add_library call in the profiler directory.

@rmontuoro Please let us know if you need a patch to any older release.

**Comment by weiyuan-jiang** [comment]
I saw oomph has replaced GFTL::gftl with  GFTL::gftl-v2. So I removed GFTL::gftl in profiler. It builds successfully.

**Comment by tclune** [comment]
No - both are needed.  Some containers still use the older v1 (which is what "gftl" brings in).   We don't yet know why our build seems to work either way.

**Comment by weiyuan-jiang** [comment]
> 

Oops, I remove it.  Let me see if I can have a fresh build

**Comment by weiyuan-jiang** [comment]
@tclune Since there is no problem building profiler without v1 dependency, I prefer to removing it now

**Comment by rmontuoro** [comment]
@mathomp4 -- here are the CMake settings we're using to build MAPL standalone:

```
cmake .. \
      -DCMAKE_INSTALL_PREFIX=$prefix \
      -DCMAKE_MODULE_PATH="${ESMA_CMAKE_ROOT};${CMAKEMODULES_ROOT}/Modules;${ECBUILD_ROOT}/share/ecbuild/cmake" \
      -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_WITH_FLAP=OFF \
      -DBUILD_WITH_PFLOGGER=OFF \
      -DESMA_USE_GFE_NAMESPACE=ON \
      -DBUILD_SHARED_MAPL=OFF
```

**Comment by mathomp4** [comment]
@rmontuoro Thanks. Note that you probably don't need the `-DESMA_USE_GFE_NAMESPACE=ON` anymore. I don't think that option does anything in MAPL anymore.

Now to figure out how to get those flags into our CI... (Though we might build as `Debug` for speed's sake.)
