### ISSUE TITLE
Change default format and protect against illegal values in History.rc

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#1376]
A user mistakenly tried to use the settings that were appropriate for the old pre-MAPL2 oserver in History with a post MAPL2 version of MAPL by specifying the "format" of each collection as "CFIOasync". Surprisingly the code did not crash but rather defaulted to binary output. This should be cleaned up. Detect if the user makes an incorrect option, either make CFIO the default and specify binary is needed (the LDAS still uses this for tiled output). More than that, the format options should really be "binary" or "NetCDF" as those are the best descriptions of the two options.

**Comment by mathomp4** [comment]
Oh. Huh. I think this is the same as #1374. Commenting here to keep open

**Comment by mathomp4** [comment]
Probably best strategy is:

1. Add option for `binary` and `nc4` or whatever in `develop` and deprecate it.
2. in MAPL 3 *only* allow `binary and `nc4`

**Comment by mathomp4** [comment]
MAPL2 → Make `CFIOasync` do `CFIO`
MAPL3 → Add `nc4` and `geosbinary` and change default of History to be `nc4`
MAPL4 → No more `CFIO` and `flat`
