### ISSUE TITLE
Integrate pFlogger

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#142]
Ensure that pFlogger is in Baselibs and integrate conventional ASSERT_() and VERIFY_() to go through the pFlogger layer if possible.

The problem is that the "component" is not readily available.    If it cannot be integrated into the old style, then at least explicitly use it in some high-profile component.

**Comment by mathomp4** [comment]
@tclune I suppose this can now be closed?

**Comment by tclune** [comment]
Merged in v2.1
