### ISSUE TITLE
Extend MAPL_GetResource with a config array overload

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#1453]
At the moment `MAPL_GetResource` has three overloads:

https://github.com/GEOS-ESM/MAPL/blob/8edb2d0d72e663cce3a35b34d2f5703e25f86101/generic/MAPL_Generic.F90#L314-L318

They are:

1. scalar from MAPL_MetaComp
2. scalar from ESMF_Config
3. array from MAPL_MetaComp

This should be extended to have "array from ESMF_Config". Should be fairly simple to do.

I suppose `MAPL_GetResource_array` should be renamed as `MAPL_GetResourceFromMAPL_array` and then we can have a `MAPL_GetResourceFromConfig_array` to match.

I'll assign this to @darianboggs as it might be a nice simple MAPL change to get used to editing MAPL. (And myself, @atrayano or @bena-nasa can help out as needed. Heck, this is the sort of MAPL change I think *I* have a shot at making 😄 )

**Comment by mathomp4** [comment]
@darianboggs This could be a good one

**Comment by darianboggs** [comment]
PR #1453 merged

**Comment by darianboggs** [comment]
Close
