### ISSUE TITLE
Update New ExtData to use new yaFyaml on MAPL v3 branch

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#1474]
MAPL 2 will still use the 1.0-beta7 interfaces to be compatible with older baselibs.

**Comment by tclune** [comment]
I think the relevant Baselibs will be 7.0.0  (@mathomp4 please confirm)

**Comment by mathomp4** [comment]
Yes. It'll end up as Baselibs 7.0.0 I think. Relevant draft PR here: https://github.com/GEOS-ESM/ESMA-Baselibs/pull/41

Note that there is a temporary build found here on discover:
```
/discover/swdev/gmao_SIteam/Baselibs/TmpBaselibs/ESMA-Baselibs-6.2.13-with-GFErepo/x86_64-pc-linux-gnu/ifort_2021.3.0-intelmpi_2021.3.0
```
