### ISSUE TITLE
Is this code redundant?

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#1478]
https://github.com/GEOS-ESM/MAPL/blob/09840e76b6655b023c9adb1ab0982c3b51d06827/shared/DSO_Utilities.F90#L34

**Comment by weiyuan-jiang** [comment]
I think the two calls of 'get_file_extension'  are redundant. It eventually returns an empty extension. But why the empty extension is supported ? https://github.com/GEOS-ESM/MAPL/blob/09840e76b6655b023c9adb1ab0982c3b51d06827/shared/DSO_Utilities.F90#L26

**Comment by weiyuan-jiang** [comment]
OK, I see. It is empty when users don't specify extension.

**Comment by tclune** [comment]
Well, we want to allow the user to have no suffix at all (indeed that is preferred for portability), and it is a matter of where to allow that.  We could put that check in various places.  If you think there is one that is more natural, please suggest.

Can you do a PR to remove the redundancy?
