### ISSUE TITLE
Add handling for double precision input fields when reading _FillValue

### ISSUE THREAD

**Issue by lizziel** [GEOS-ESM/MAPL#1489]
Several GCHP input files contain double precision variables with the `_FillValue` attribute. Recent versions of MAPL read the `_FillValue` to handle cases where it differs from `MAPL_UNDEF` but the model crashes unless the input is single precision. The problem is the object function `get_var_attr_real32` does not have handling for double precision. See [here](https://github.com/GEOS-ESM/MAPL/blob/ad9f4685ec2df676c78a93a9c629f8da5a34e4f6/base/FileMetadataUtilities.F90#L69-L71) and [here](https://github.com/GEOS-ESM/MAPL/blob/ad9f4685ec2df676c78a93a9c629f8da5a34e4f6/base/FileMetadataUtilities.F90#L125-L130).

I implemented an update to handle double precision input which is now working. I am getting negative concentrations in my model run but that is a separate issue (one of our scale factor files has `_FillValue=1` and many missing values when it should simply contain 1s for the data).

Here is the fix I implemented, along with an expansion of the error message to include filename. I can make a PR with this or you can implement the equivalent however you'd like.

```
      real(REAL64) :: tmpd(1)
      character(len=ESMF_MAXSTR) :: fname
      ...
      fname = get_file_name(this,_RC)
      type is(real(kind=REAL32))
         tmp = attr_val
         attr_real32 = tmp(1)
      type is(real(kind=REAL64))
         tmpd = attr_val
         attr_real32 = REAL(tmpd(1))
      class default
         _ASSERT(.false.,'unsupport subclass for units (attribute named '//attr_name//' in '//var_name//' in '//fname)
      end select
```

**Comment by tclune** [comment]
@lizziel If this change works for you, then by all means please submit a PR against develop.   Let us know if you need an earlier MAPL patched with a hotfix.     (@weiyuan-jiang I'm letting you manage the ticket as it is mostly a pfio extension.)

**Comment by lizziel** [comment]
Will do. I won't need a patch since I've already put this in our version.
