### ISSUE TITLE
Introduce a replacement for m_set_eta

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#149]
The concept is to have a data structure that loads its data from a file rather than hardcoded values in source code.   This will allow external users to define their own vertical grid.

Older m_set_eta will continue for a while, but we should gradually replace the new.

**Comment by weiyuan-jiang** [comment]
The MAPL_VerticalGrid is added to prepare for replacing set_eta and get pressure levels in the feature/replace_set_eta branch. The next step is to replace the actual call
