### ISSUE TITLE
Inspect underscore-macros for develop merge back to master

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#15]
Soon we'll want to merge `develop` back into `master` as it is the MAPL of the future. But, we have three macros which changed names: `_VERIFY`, `_RETURN`, `_ASSERT`. I think the first two are okay or simple to fix. `_ASSERT` is the hard one.

**Comment by tclune** [comment]
This change is going to result in a very large number of new warnings about unused "Iam" variables.     Maybe when I do the pull request @mathomp4 can think of a simple way to delete all/most declarations of this variable?

**Comment by mathomp4** [comment]
I think we've solved this. Closing. If something comes up, we'll make a new issue.
