### ISSUE TITLE
Possible MAPL Bug with SCM Debug

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#1549]
@sanAkel discovered what I think is a bug in MAPL when you run the SCM with debugging options on. Maybe it's GOCART, but I think it's more of an uncovered case in MAPL.

To wit, when you run the `arm_97jul` case, you get a traceback:
```
forrtl: severe (408): fort: (2): Subscript #1 of the array COORDS has value 2 which is greater than the upper bound of 1

Image              PC                Routine            Line        Source
GEOSgcm.x          000000000F45324F  Unknown               Unknown  Unknown
libMAPL.base.so    00002B2401248782  mapl_base.base_im        3174  Base_Base_implementation.F90
libMAPL.base.so    00002B240124500C  mapl_base_mp_mapl        3103  Base_Base_implementation.F90
GEOSgcm.x          000000000115FE88  su2g_gridcompmod_         865  SU2G_GridCompMod.F90
GEOSgcm.x          000000000115A2CD  su2g_gridcompmod_         710  SU2G_GridCompMod.F90
libesmf.so         00002B23EDDA39E4  _ZN5ESMCI6FTable1     Unknown  Unknown
libesmf.so         00002B23EDDA752F  ESMCI_FTableCallE     Unknown  Unknown
...
```

The call tree from SU2G is [this](https://github.com/GEOS-ESM/GOCART/blob/821ef40859d6155c8594668e6261c97c49a935bc/ESMF/GOCART2G_GridComp/SU2G_GridComp/SU2G_GridCompMod.F90#L865-L869
):
```fortran
       call MAPL_GetHorzIJIndex(self%nVolc, iPointVolc, jPointVolc, &
                                grid = grid,               &
                                lon  = self%vLon/real(MAPL_RADIANS_TO_DEGREES), &
                                lat  = self%vLat/real(MAPL_RADIANS_TO_DEGREES), &
                                rc   = status)
```

which goes to:

https://github.com/GEOS-ESM/MAPL/blob/f6cf291f9744cf3bb770872c82d434a206a119e6/base/Base/Base_Base_implementation.F90#L3103

and then:

https://github.com/GEOS-ESM/MAPL/blob/f6cf291f9744cf3bb770872c82d434a206a119e6/base/Base/Base_Base_implementation.F90#L3170-L3178

My guess is we might need a sort of "short-circuit" for single column in MAPL_GetHorzIJIndex when it goes through the lat-lon code. It's not a "standard" but I think all SCM cases sort of "hardcode" the latlon of their point in the gridname a la:
```
      AGCM.GRIDNAME: XY1x1-C_34N_100W_38N_95W
```
I'm guessing when MAPL makes the 1x1 grid it doesn't care...I can't see any reason why it would. But maybe we could figure out a way to pull it. Either make the SCM gridname a standard and extract from it, or have a bit of "If grid is 1x1, then we require AGCM.LATS and AGCM.LONS or something?"

I defer to @tclune, @bena-nasa and @atrayano the best way to support this.

**Comment by bena-nasa** [comment]
I'll fix this. Maybe the refactoring we did to horzij broke this. This is going through the non cubed-sphere path which well we did not have a use case for other than this since don't' run lat-lon.

**Comment by sanAkel** [comment]
Thanks! @bena-nasa.

@mathomp4 suggested I test other test cases.

Would you *both* like me to try them? If so, if `debug` or `release`?
