### ISSUE TITLE
Update support for ISO 8601 time format

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#1562]
The logic in the file: 
  https://github.com/GEOS-ESM/MAPL/blob/main/gridcomps/ExtData2G/TimeStringConversion.F90
is a good start at implementing this standard, but several updates are needed/desired.

1. The file should be moved to `./base` as many layers will need to use this.
2. The names must be improved for clarity.
3. Possibly the procedures should be decomposed further.
4. Further checking of error codes should be done (e.g., READ statements without IOSTAT checks)
5. We should have a swath of simple unit tests to verify the implementation. (1st or 2nd step moving forward.)

**Comment by darianboggs** [comment]
I have marked this issue as 'long term' so it doesn't close while I am away from the office.

**Comment by mathomp4** [comment]
> I have marked this issue as 'long term' so it doesn't close while I am away from the office.

Thanks! I probably would have done the same if you didn't. I guess the stale bot doesn't realize something is being worked on if people don't keep commenting on the issue!
