### ISSUE TITLE
Make History check for file existence optional

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#1621]
The change that came it at v2.22.0 to check if a file already exists when History decides it is time for a new file (and thus indicating improper cleanup in the driving scripting) needs to be made optional for NOAA as they apparently rerun but do no clean the temporary work space they are running in. This will be a trivial change.

**Comment by tclune** [comment]
Just for the record - usual runs by NOAA do not have any problem.  The situation happens when some other problem occurs and they must _restart_ a segment.  Apparently they do not get a clean directory under such scenarios.
