### ISSUE TITLE
Creating wiki page about how to use PFIO server with history

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#1642]
As the song goes "there's too much confusion" as to how to use the PFIO server in History based on some back and forth with the OPS team. We need a wiki page or something we can point people to, at the very least for our own sakes to not have to reexplain this again.

I've started a page as a placeholder we should expand...

https://github.com/GEOS-ESM/MAPL/wiki/Optimizing-History-with-the-PFIO-server

**Comment by mathomp4** [comment]
I suppose the Python script @weiyuan-jiang helped me create could be a good thing to add to that page too.

**Comment by bena-nasa** [comment]
@mathomp4 
Throw it on there!

**Comment by tclune** [comment]
Save some work for Jules ...
