### ISSUE TITLE
No need to ASSERT here

### ISSUE THREAD

**Issue by weiyuan-jiang** [GEOS-ESM/MAPL#1663]
https://github.com/GEOS-ESM/MAPL/blob/96793d3c6b2b2a9a81e66355a25c4c80a7c9053b/generic/MAPL_Generic.F90#L4896-L4897

Since the name is adjusted later ( a few lines below), we probably should not stop the program here.

**Comment by mathomp4** [comment]
This might be some belt-and-suspenders when I was developing the code and doing testing. Sort of like, if someone *insists* that the library is named `libfoo.qxg` or something crazy, we say "No". 

But as you say, I guess I automated that issue out of the way right below it and never removed the `_ASSERT`...
