### ISSUE TITLE
Check for duplicates in History collection needs to take alias into account

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#1665]
A user reported that the following in a History.rc file:
```
                           'T2M'      , 'SURFACE' ,  'T2MMIN'  ,  'MIN' ,
                           'T2M'      , 'SURFACE' ,  'T2MMAX'  ,  'MAX' ,
```
was causing History to crash with an error like so:

<Caught collection with duplicate short name: T2M and duplicate component>

It turns out the logic I added to prevent duplication in the collection needs to allow for specifying duplicate short_name+gridcomp combos if the alias is different as there are valid reasons to do this.

**Comment by amolod** [comment]
Nice catch! I think the GEOS_IT has this in its history.
