### ISSUE TITLE
Should we protect History mode better?

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#1668]
In talking with @keknowland on Teams, I noticed something interesting in History.

Per our "documentation" we say we have two modes, `instantaneous` and `time-averaged`:

https://github.com/GEOS-ESM/MAPL/blob/a2ba02078f5ecb825f95ab97eee413e54ebeffa8/gridcomps/History/MAPL_HistoryGridComp.F90#L229

But then the code is:

https://github.com/GEOS-ESM/MAPL/blob/a2ba02078f5ecb825f95ab97eee413e54ebeffa8/gridcomps/History/MAPL_HistoryGridComp.F90#L1767-L1777

To my reading, it isn't that we only allow `instantaneous` and `time-averaged`, we allow *anything* and everything is averaged except for `instantaneous`. 

To me, I think we should be more strict and *only* allow `instantaneous` and `time-averaged` per our docs. If you pass in something else, throw a `_FAIL`. 

If nothing else, it will set us up in case we ever want to add a third mode, but someone could type in a misspell like `instantanious`, or even `instant` and be surprised they are getting out time-averaged history!

I'll ping @tclune, @bena-nasa and @atrayano for their thoughts.

**Comment by tclune** [comment]
I agree.  It should be a `SELECT CASE` block with specific entries for the modes we support and a `_FAIL` in the default clause.

**Comment by mathomp4** [comment]
> I agree. It should be a `SELECT CASE` block with specific entries for the modes we support and a `_FAIL` in the default clause.

I think I can do this sort of MAPL change. Let me try it out!

**Comment by atrayano** [comment]
I agree that we should change it. This was sloppy coding, but luckily everybody constructed their HISTORY.rc correctly
