### ISSUE TITLE
Request that ExtData2G support a masked sum, in a Derived Export

### ISSUE THREAD

**Issue by mmanyin** [GEOS-ESM/MAPL#1682]
It would be very helpful if ExtData2G could combine masking and algebraic computation of fields within the specification of Derived Exports. As a use-case, the EDGAR methane (CH4) emissions dataset is split into source-specific files; we would like to combine subsets of these files and then apply geographic masks to the results, without creating new (custom tailored) emissions files.  Currently ExtData2G supports masking, or algebraic expressions in derived exports, but not both together.  If ExtData2G could combine the two operations, something like MASK( field_A + field_B + field_C, <masking parameters> ), it would be very useful for tagged tracer experiments.

**Comment by bena-nasa** [comment]
@mmanyin This will be very easy to do, already started it. Should have the PR in a day or two.

**Comment by mmanyin** [comment]
Thanks @bena-nasa  !!

**Comment by bena-nasa** [comment]
@mmanyin PR made, took a little longer than I thought it would.

**Comment by mmanyin** [comment]
Hey @bena-nasa that's great!  I look forward to testing it.  Should I wait for the next MAPL release?  Or do you want feedback on it ASAP?
