### ISSUE TITLE
MAPL cannot print array resources

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#1685]
This issue is based on an observation/question from Kazumi. She asked if `JOB_SGMT` was printed in the stdout when the model runs. I looked at one of my experiments and, nope didn't see it. So I figured we must be doing `ESMF_ConfigGetAttribute` which doesn't do our MAPL resource print. 

Yet, when I looked at MAPL:

https://github.com/GEOS-ESM/MAPL/blob/f3ddd913badac0c17a53e6cd63e9e6e28966cebc/gridcomps/Cap/MAPL_CapGridComp.F90#L1711

So we do call for it with `MAPL_GetResource`!

After consulting @bena-nasa, the issue seems to be that scalar `MAPL_GetResource` calls call `print_resource` at the end (if `PRINTRC: 1`). But `MAPL_GetResource_array` does not. 

This now leads to questions:

1. Should we have array `MAPL_GetResource` calls print?
2. If so, how?

For question 1, I think, "yes". Sort of follows along how we already print all MAPL_GetResource calls on scalars.

For question 2, the first way I can think of is to write up a `print_resource_array` and try to figure out how to print the array. Maybe @tclune knows of a fancy Fortran `format` specification that would make it easy?

Note 1: In talking with @bena-nasa we probably will never support more than rank-1 arrays through this, so probably going full-overload assumed-rank `class(*), dimension(..) :: vals` wouldn't be needed...though it would be interesting Fortran.

Note 2: I suppose this is a good time to incorporate #1453 as well.

I'm not assigning this yet until we hear back from the people I cc below, but this might be a good @darianboggs thing to do as it is a good bit changes in the guts of MAPL.

cc: @tclune @bena-nasa @atrayano @darianboggs

**Comment by mathomp4** [comment]
Not stale as @darianboggs is working on this. I'll long-term it.

**Comment by darianboggs** [comment]
Closed by PR #1453
