### ISSUE TITLE
Enforced stretched grid attributes in internal checkpoint files are in units of radians

### ISSUE THREAD

**Issue by LiamBindle** [GEOS-ESM/MAPL#1687]
Hi all,

Today I noticed that internal checkpoints use units of radians for the `TARGET_LAT` and `TARGET_LON` attributes which are now enforced. This means you can restart a stretched-grid simulation from a checkpoint file without overwriting the attributes.

E.g., here are the attributes in my initial restart file (correct)
```
                :STRETCH_FACTOR = 7.5f ;
                :TARGET_LAT = 37.5f ;
                :TARGET_LON = 242.2f ;
```
and here are the attributes in internal checkpoint files (causes error)
```
                :STRETCH_FACTOR = 7.5f ;
                :TARGET_LAT = 0.6544985f ;
                :TARGET_LON = 4.227187f ;
```

**Comment by mathomp4** [comment]
I'd like to think this should be pretty simple to fix...

**Comment by mathomp4** [comment]
As @bena-nasa is on leave for a week, I'm adding @atrayano and @tclune to this issue. 

I see way too many `TARGET_LON` and `TARGET_LAT` in MAPL for me to know exactly what needs changing...correctly. :)

**Comment by mathomp4** [comment]
I am going to take a stab at this and say these lines:

https://github.com/GEOS-ESM/MAPL/blob/e8bf53b8c028ab81014aa943e7fa3ee141494a87/base/NCIO.F90#L3465-L3466

probably need to be:

```fortran
 call cf%add_attribute('TARGET_LON',target_lon*180.0/MAPL_PI) 
 call cf%add_attribute('TARGET_LAT',target_lat*180.0/MAPL_PI) 
```

This is in echo of this:

https://github.com/GEOS-ESM/MAPL/blob/e8bf53b8c028ab81014aa943e7fa3ee141494a87/base/MAPL_CubedSphereGridFactory.F90#L1072-L1076

I'm not smart/brave enough to know if this is the right fix (plus I don't really know how to trigger the stretched grid), so, @LiamBindle, could you try it out locally and see if it fixes it for you? If so, that'll make it easy for us to (hot)fix when confirmed.

**Comment by mathomp4** [comment]
@LiamBindle A fix for this is now in `develop` and should be in MAPL 2.28 soon (today I hope).
