### ISSUE TITLE
Improve documentation of external dependencies

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#1688]
For GCHP and to a lesser degree, we should be documenting for each release what dependencies MAPL has on other libraries.     For GCHP this can be a baselibs version.

A pain, I know.  Spack?

**Comment by mathomp4** [comment]
I suppose technically all that info is in the Changelog, just sort of...scattered. 

I tried a first attempt here:

https://github.com/GEOS-ESM/MAPL/releases/tag/v2.26.0

Could probably make it nicer with a table and all. And better wording could be done as well.
