### ISSUE TITLE
Build failure on macOS and Intel with MAPL3

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#1695]
I think some odd behavior with Intel + macOS has changed recently. Code that is pretty dang old has now stopped working. To wit:
```
[ 15%] Linking Fortran shared library ../lib/libMAPL.profiler.dylib
... delete a lot of warnings ...
Undefined symbols for architecture x86_64:
  "_mallinfo", referenced from:
      _mapl_mallocgauge_mp_get_measurement_ in MallocGauge.F90.o
ld: symbol(s) not found for architecture x86_64
```

Thing is `MallocGauge.F90` hasn't changed...ever? So this must be an Intel issue? Or something? 

I'm going to assign @tclune as this is his code. I suppose a simple "if darwin and intel don't do this" is all that's needed, but I'm not exactly sure how to correctly do that here.

**Comment by tclune** [comment]
I thought it was not supposed to do it on OS X at all.

**Comment by tclune** [comment]
No idea why it worked with GNU

**Comment by mathomp4** [comment]
I "got around it" by just commenting out the line:
https://github.com/GEOS-ESM/MAPL/blob/a61a7a7e6593cbb505c7bed3dcdd6af467e2c5e4/profiler/MallocGauge.F90#L62

but there is probably a more elegant way. Maybe have a dummy `mallinfo()` function if darwin and intel?

**Comment by tclune** [comment]
BTW,  I am fairly certain I built my branch of MAPL v3 over the weekend with Intel (2021.6) on OS X.

**Comment by mathomp4** [comment]
Yeah. I should try this again!
