### ISSUE TITLE
Should MAPL ACG have an option for alloc=.true. in the generated MAPL_GetPointer

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#1722]
During a discussion with @vbuchard they were showing me code and wanted to generate a new diagnostic that depends on other exports in GOCART. However, those intermediate exports may not be requested in History and to generate this new one they had to add all the others to the History.rc so that the export field would actually be created. These are 3D fields so outputting them just to generate this is a wasteful.
I said, just add the alloc=.true. to get pointer, but...
Since GOCART uses the ACG and the ACG doesn't have this option the only way to currently get it is to not use the ACG for all variables you want to add the alloc=.true. to. Or extend the ACG to add this. Since we use alloc=.true. all over the place probably will have to add this anyway if the ACG is coming to more grid comps.

**Comment by mathomp4** [comment]
I wonder if @darianboggs can fit this into #1713 ?

**Comment by darianboggs** [comment]
I talked to Ben about this issue this afternoon. After reviewing the existing ACG, it looks possible, and it looks like a good idea. Ben told me to wait before making the changes. I can't remember if I talked to Ben before after this issue was created. Let me know if I should move forward with this or hold off.

**Comment by tclune** [comment]
Yes - probably needed for MAPL2.   I'm hoping to forbid that feature in MAPL3, but pragmatism may win.

If it is easy (I think it is), I'd go ahead and include it in the ACG for now.

**Comment by mathomp4** [comment]
And as Ben probably told you, `alloc=.true.` is used fairly often in the model. It used to be a rash all over moist, but I think Bill tried to fix all that. But probably will be needed...

**Comment by tclune** [comment]
My understanding is that the functionality is needed, but that the expression of it may be handled differently.   For the moment I'm treating it as a small detail.  (I.e., not letting it distract me from the core design)

E.g., how is `alloc=.true.` different than making the field internal and then adding it to the export state?  (Pseudo e2e connection.)
