### ISSUE TITLE
Could the ACG do basic sanity checking of the state specs

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#1738]
A suggestion for the auto code generator. 

I just helped a gocart developer. They have some crash in MAPL generic they didn't understand in the MAPL_GenericInitialize sequence. Turned out the issue was that they added new exports in the statespec file. However, one of the the dims was xyz, but they accidentally said the vloc was n (no vlocation) which made the field createfromspec just say no you don't and die at runtime.

Could this be intercepted at the python acg when the spec file is parsed to construct the include file and return a failure there when cmake is run during the build if there are basic inconsistencies like this rather than waiting all the way until runtime deep in the initialization sequence.

**Comment by darianboggs** [comment]
There is nothing that prevents adding this capability.
Two routes:
1. Put this directly into python. Doesn't seem sustainable.
2. Use YAML or similar language/format to encode the rules. It could be easier for users to add rules.

What would the pseudocode logic look like for this example? Would it be like this?
```
if 'dims' == 'xyz' .and. 'vloc' == 'n':
  error("'xyz' and 'vloc' are incompatible")
```

**Comment by tclune** [comment]
Yes - and there are the conjugate errors:

```
if 'dims' == 'xy' .and.' 'vloc' != 'n': 
   error(....)
```

**Comment by mathomp4** [comment]
I think this was merged in long ago and not close. Closing!
