### ISSUE TITLE
MAPL_GridCompSpecs_ACG.py does not support '(/ /)' brackets (old Fortran)

### ISSUE THREAD

**Issue by darianboggs** [GEOS-ESM/MAPL#1751]
`MAPL_GridCompSpecs_ACG` does not support '(/ /)' brackets in state specs configuration files. This older form of Fortran brackets could still occur for "array-like" spec options. It should parse these brackets as it processes square brackets. It should use square brackets in the include files it produces.

**Comment by tclune** [comment]
I'm torn on this.  Yes, it is a valid Fortran expression, but ... all of the ACG files are new, and have thus been created long after the introduction of the square bracket notation.    Why encourage the use of a suboptimal format?   Rather, this could help us teach the older programmers that there is a better syntax.  (That it is like Python's is a plus.)

**Comment by mathomp4** [comment]
I suppose then the ACG should emit an error "Obsolete Fortran detected. Use '[ ... ]' instead of '(/ ... /)'"?

**Comment by mathomp4** [comment]
I think we will close this. Like Tom said, this is an opportunity to remove some of the old array-constructor syntax in GEOS. Good riddance!
