### ISSUE TITLE
Outputting variables with ungridded dims is apparently broken now in MAPL

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#1811]
@dr0cloud apparently found that outputting fields with unguided dimensions is just broken. I tried output FSWBAND from the solar grid comp which as an ungridded dim and it was coming out as 2D. I will fix.

**Comment by mathomp4** [comment]
Eep. Huh. Do we not have any ungridded-dims variables in the "usual" AGCM history? I mean...someone would have noticed you'd think!

**Comment by bena-nasa** [comment]
This is a wakeup call. I need to extend my primitive ACG "like" thing that allows runtime (not compile time), specification of VarSpecs used by ExtDataDriver.x to allow for more options including VarSpecs with ungridded dims so that this can be tested. Time to move to yaml for that.

**Comment by bena-nasa** [comment]
@mathomp4 I do not think the usual AGCM History has that explicit ungridded dims output, now we do have the "split field" option which indirectly removes that ungridded dim, I would have thought we would have seen right away if that was broken.

**Comment by bena-nasa** [comment]
@mathomp4 this is getting weird, FSWBAND in Solar, that definitely should have more than 1 band right? So the field History gets seems to have a field rank of 2, which makes no sense. It should be 3...

**Comment by mathomp4** [comment]
@bena-nasa I thought so. I know when I created FSWBAND long ago, it was 3d. Now, it was never what the obio people wanted, but it was what Max asked me to create.

**Comment by bena-nasa** [comment]
The field comes into History as a 3D field as it should, by the time my IO layer gets the bundle that has the field, it is a 2D field. I'm running in a collection with a 2D variable and FWSBAND, instantaneous so no time-average, output on the native grid, nothing should be happening to it. So somebody is doing something, creating a new field it should not be, or if it is supposed to it is doing it wrong before giving my IO layer.

**Comment by bena-nasa** [comment]
And I think here is the problem. There is this function
https://github.com/GEOS-ESM/MAPL/blob/v2.30.2/gridcomps/History/MAPL_HistoryGridComp.F90#L3034

it seems to be saying that we will split any field that has an ungridded dimension???

**Comment by atrayano** [comment]
We split only if the collection has splitField = 1

**Comment by atrayano** [comment]
And yes, Arlindo had asked me to split not only 4d, but 3d as well

**Comment by bena-nasa** [comment]
@atrayano that function will return true for any field that is 3D with one ungridded dim, there is something going wrong now even if you don't tell it to split. I'm still digging but it is like this trigger something that has broken the ability to output fields with ungridded dims when you don't want to split. Hang tight

**Comment by bena-nasa** [comment]
@atrayano 
https://github.com/GEOS-ESM/MAPL/blob/v2.30.2/gridcomps/History/MAPL_HistoryGridComp.F90#L2064
Why are we doing any of this if the collection did not say split field?

Like that function returns true for any 3D field with an unguided dim, but why even do that if the user did not ask for the split fields in the first place. I'm still adding prints, but that seems like we should not be there at all...

**Comment by dr0cloud** [comment]
Thanks Ben and team!

**Comment by tclune** [comment]
Could not resist editing the title of this issue.   MAPL supports ungridded dims, but we refuse to support "unguided" dims.

**Comment by atrayano** [comment]
@bena, the issue we found yesterday can easily explain the weird behavior NOAA/UFS team is reporting. For them adding splitField=1 would work (as suggested by @weiyuan-jiang ), but nevertheless, a proper fix will be much better

**Comment by weiyuan-jiang** [comment]
I copied the issue here found by NOAA/UFS even with splitField =1:  
inst_aod.mode:       'instantaneous'
  inst_aod.frequency:  060000,
  inst_aod.duration:   010000,
  inst_aod.ref_time:   000000,
  inst_aod.splitField:      1,
  inst_aod.grid_label: PC720x361-DC
  inst_aodfields:      'CA.bcEXTTAU'   , 'CA.bc'    , 'AOD_BC',
                       'CA.ocEXTTAU'   , 'CA.oc'    , 'AOD_OC',
                       'DUEXTTAU'      , 'DU'       , 'AOD_DU',
                       'NIEXTTAU'      , 'NI'       , 'AOD_NI',
                       'SSEXTTAU'      , 'SS'       , 'AOD_SS',
                       'SUEXTTAU'      , 'SU'       , 'AOD_SU',
                       'TOTEXTTAU'     , 'GOCART2G' , 'AOD'   ,
                       ::

I don't get AOD_BC001 AOD_BC002 AOD_BC003 and AOD_BC004 as variables.  Instead I get AOD_BC, CA.bcEXTTAU002, CA.bcEXTTAU003, CA.bcEXTTAU004

So although this seems to achieve the desired effect of outputing the AOD at each wavelength I think that there is more to is here as the naming comvention isn't being passed through.  So 1) variable output name doesn't propagate 2) the first wavelength isn't reported as 001 instead with no wavelength designation.

**Comment by weiyuan-jiang** [comment]
Let me summarize the issues here.
1) need to use the naming convention ( output names)
2) the first wavelength should have '001'
3) long name  has fixed and incorrect wavelengths.
