### ISSUE TITLE
move the four numbers to MAPL Constants? 

### ISSUE THREAD

**Issue by weiyuan-jiang** [GEOS-ESM/MAPL#1818]
https://github.com/GEOS-ESM/MAPL/blob/8bb4b4ae158e8f26400dadd4a5052d0814220d8e/generic/MAPL_Generic.F90#L4119-L4133

**Comment by mathomp4** [comment]
Those are @dr0cloud things, so I'm mentioning him here...

**Comment by dr0cloud** [comment]
Are these constants being duplicated any where else? Anyone who accesses the Orbit should now do so through the mechanisms of MAPL_SunGetInsolation which uses these constants, not through some other adhoc routine. I did notice the other day that there were orbital parameters in the MAPL Physical Constants. Who is using these?

**Comment by mathomp4** [comment]
As @weiyuan-jiang points out, they are in some catch code it looks like:

https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/667

**Comment by mathomp4** [comment]
@weiyuan-jiang @dr0cloud Is this now taken care of via #1920 ?

**Comment by dr0cloud** [comment]
Hi Matt, PR #1920 replaces PR #1902 and whatever the issue it was based on. P.

Peter Norris, Ph.D.
Senior Research Scientist
Global Modeling and Assimilation Office (GMAO) / NASA Goddard Space Flight Center
Goddard Earth Sciences Technology and Research (GESTAR) II / University of Maryland, Baltimore County (UMBC)
Cell 240-505-1476




From: Matthew Thompson ***@***.***>
Reply-To: GEOS-ESM/MAPL ***@***.***>
Date: Sunday, January 15, 2023 at 3:32 PM
To: GEOS-ESM/MAPL ***@***.***>
Cc: "Norris, Peter M. (GSFC-610.1)[UNIVERSITY OF MARYLAND BALTIMORE CO]" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [GEOS-ESM/MAPL] move the four numbers to MAPL Constants? (Issue #1818)


@weiyuan-jiang<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fweiyuan-jiang&data=05%7C01%7Cpeter.m.norris%40nasa.gov%7Ccf8ccec3c12b46699d4808daf737a3ee%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638094115594834866%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=UMN95hTiCoGQM%2F306Zlqenq4yZkqt4245uuHwnykRhw%3D&reserved=0> @dr0cloud<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdr0cloud&data=05%7C01%7Cpeter.m.norris%40nasa.gov%7Ccf8ccec3c12b46699d4808daf737a3ee%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638094115594834866%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pCLo6nc2b13l6f%2BM2Pes9kBDMEmaweKuiraRFbBksSg%3D&reserved=0> Is this now taken care of via #1920<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGEOS-ESM%2FMAPL%2Fpull%2F1920&data=05%7C01%7Cpeter.m.norris%40nasa.gov%7Ccf8ccec3c12b46699d4808daf737a3ee%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638094115594991079%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DDiRg8QLBfPlu8If1jSalr83ptlkrPujb8BTq7gePf8%3D&reserved=0> ?
