### ISSUE TITLE
History: Detemplate %d in long name

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#1878]
Per @amdasilva, he would like the `%d` seen in the ACG here:

![image](https://user-images.githubusercontent.com/2982494/207668823-45100f7d-9abe-4ac5-b5d5-0cac0b2195a9.png)

to be expanded to the Bin Number when the fields are split on bins:

> Now, when history expands the bin number for the ungridded dimension, it is supposed to expand the %d above with the bin number; right now, I believe the output file shows “%d” which is not right. Another possibility is to omit the “(Bin %d)” from the rc file and have history add (Bin 001), (Bin 002), etc as it flattens out the ungridded dimension.  Atanas knows what I am talking about.

Note to @atrayano, I guess if only one bin just use `Bin 001`??

**Comment by tclune** [comment]
I want to be careful here.  "Bin" has a strong meaning in GOCART but another component might want to use some other parameter for expansion.   So it might be best to have a slightly more complex notation that can be more clearly used in other contexts.

**Comment by tclune** [comment]
Never mind.   The parameter is evaluated for the "split" dimension.

So now my concern is that we want something  that could work in some future case with 2 ungridded dims.
