### ISSUE TITLE
CMake failing on mac

### ISSUE THREAD

**Issue by sanAkel** [GEOS-ESM/MAPL#1880]
My mepo status:
```
env                    | (t) v4.8.0 (DH)
cmake                  | (t) v3.21.0 (DH)
ecbuild                | (t) geos/v1.3.0 (DH)
NCEP_Shared            | (t) v1.2.1 (DH)
GMAO_Shared            | (b) main
MAPL                   | (b) develop
FMS                    | (t) geos/2019.01.02+noaff.8 (DH)
GEOSgcm_GridComp       | (b) develop
FVdycoreCubed_GridComp | (t) v1.12.1 (DH)
fvdycore               | (t) geos/v1.5.0 (DH)
GEOSchem_GridComp      | (t) v1.10.4 (DH)
HEMCO                  | (t) geos/v2.2.3 (DH)
geos-chem              | (t) geos/v13.0.0-rc1 (DH)
GOCART                 | (t) v2.1.2 (DH)
QuickChem              | (t) v1.0.0 (DH)
GEOS_OceanGridComp     | (t) v1.1.1 (DH)
mom                    | (t) geos/5.1.0+1.2.0 (DH)
mom6                   | (t) geos/v2.0.4 (DH)
cice6                  | (t) geos/v0.0.1 (DH)
sis2                   | (t) geos/v0.0.1 (DH)
GEOSradiation_GridComp | (t) v1.2.0 (DH)
RRTMGP                 | (t) geos/v1.5+1.0.0 (DH)
GEOSgcm_App            | (b) develop
UMD_Etc                | (t) v1.1.0 (DH)
CPLFCST_Etc            | (t) v1.0.1 (DH)
```

> cmake .. -DBASEDIR=$HOME/installed/MPI/intel-clang-2021.2.0/openmpi-4.1.1/Baselibs/7.5.1 -DCMAKE_Fortran_COMPILER=ifort -DCMAKE_INSTALL_PREFIX=../install-Debug -DCMAKE_BUILD_TYPE=Debug -DUSE_F2PY=OFF

Is there a problem with `fArgParse` ? Does it relate to: https://github.com/GEOS-ESM/MAPL/commit/da7d37cf260bbe1fb0f3bd0824c3ea5d638313b4

Log file are attached.

[CMakeError.log](https://github.com/GEOS-ESM/MAPL/files/10232454/CMakeError.log)
[CMakeOutput.log](https://github.com/GEOS-ESM/MAPL/files/10232455/CMakeOutput.log)

Problem does not go away with MAPL `v2.33.0`!

**Comment by sanAkel** [comment]
FWIW, same procedure on discover, no problems! 
(I got lucky 🤞  and could login despite NCCS issue: `NCCS Downtime: Discover experiencing GPFS issues`)

**Comment by mathomp4** [comment]
@sanAkel You'll need Baselibs 7.7.0 to compile MAPL 2.32+ with the default options. The `g5_modules` for GEOS was updated at the same time (well, before, actually) so it is good on discover, pfe, etc.

If you don't want to rebuild Baselibs, you can set at CMake time `-DBUILD_WITH_FARGPARSE=NO`. You won't miss out on any functionality as it's more of an "alternate" code path for now.

**Comment by sanAkel** [comment]
> @sanAkel You'll need Baselibs 7.7.0 to compile MAPL 2.32+ with the default options. The `g5_modules` for GEOS was updated at the same time (well, before, actually) so it is good on discover, pfe, etc.
> 
> 
> 
> If you don't want to rebuild Baselibs, you can set at CMake time `-DBUILD_WITH_FARGPARSE=NO`. You won't miss out on any functionality as it's more of an "alternate" code path for now.

Thank you @mathomp4, will try once without building Baselibs and with the arg.

**Comment by sanAkel** [comment]
I could successfully build with:
> `cmake .. -DBASEDIR=$HOME/installed/MPI/intel-clang-2021.2.0/openmpi-4.1.1/Baselibs/7.5.1 -DCMAKE_Fortran_COMPILER=ifort -DCMAKE_INSTALL_PREFIX=../install-Debug -DCMAKE_BUILD_TYPE=Debug -DUSE_F2PY=OFF -DBUILD_WITH_FARGPARSE=NO` 

As @mathomp4, said, **without** having to update to `Baselibs 7.7.0`. @mathomp4 thanks again!
