### ISSUE TITLE
Refactor MAPL_Generic.F90 GetResource

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#1918]
There are a couple of issues with the existing logic for `MAPL_GetResource` in `generic/MAPL_Generic.F90`.

1. The code (or at least most of it) should be pulled into a separate module.   Something in Base, like `MaplResource.F90`
2. The procedures that have  `MetaComp` arguments should be very thin, but remain in MAPL_Generic.   These procedures just call to the new layer mentioned above, but first extracting the bits of the `MetaComp` that are needed.   I think this is just the config and the comp name.  But I did not dwell on it.
3. Unfortunately, the code is "almost" already organized the way described in (2), but ... not quite.   I think things would be improved if additional procedures were introduced that handle such things as searching through labels:

https://github.com/GEOS-ESM/MAPL/blob/14b9789f91f72f022d0cf037256c7f2375b0c80d/generic/MAPL_Generic.F90#L8459-L8476

With these changes we can bring most of this code over to MAPL3 (separate step).   It also will improve our ability to expand for using YAML when ESMF supports it. (Though only slightly.)

Mentioning @atrayano and @bena-nasa in case they have concerns.

**Comment by darianboggs** [comment]
Got it. This dovetails with the work I am finishing on MAPL_GetResource (#1453). To clean it up. I am refactoring already. I may merge the two.

**Comment by mathomp4** [comment]
I think we can close this now
