### ISSUE TITLE
WRITE_RESTART_BY_OSERVER is broken for 4d restarts

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#1923]
I have long been vexed by why GNU + GOCART2G does not regress (see https://github.com/GEOS-ESM/GEOSgcm/issues/380). Well, we might have an answer.

Today, I (finally) realized that GNU + MPT at NAS regresses just fine. Likewise, I've shown GNU + Intel MPI regresses. Only GNU + Open MPI does not. And the *one* major difference in GEOSgcm (and GEOSldas?) is that if you are using Open MPI, we set `WRITE_RESTART_BY_OSERVER: YES`. This was a while back when I noticed that checkpointing with Open MPI was stupid slow if you were using Open MPI, but we got speed back if we set `WRITE_RESTART_BY_OSERVER: YES`. 

Today, I ran some tests and it turns out even Intel + Intel MPI has issues if `WRITE_RESTART_BY_OSERVER: YES` is set. If you run a day with that set to `NO` and `YES` all your restarts will be identical *EXCEPT* `du_internal` and `ss_internal`. And they are unique in that they have 4D variables in them with ungridded dims.

@bena-nasa and myself looked at this and he is pretty sure he sees the issue (4d is not handled correctly for by_oserver). 

I'm marking this high-priority because it is a pretty big bug. Indeed, I'll need to check with @weiyuan-jiang if the LDAS also uses this for their GNU+OpenMPI runs and if they have any 4d variables, there might be issues.

**Comment by bena-nasa** [comment]
I will fix this.

**Comment by tclune** [comment]
Yes - high priority and very glad you found this!

**Comment by mathomp4** [comment]
Adding a list for testing #1925 from @bena-nasa 

- [ ] Intel Release + WRITE_RESTART_BY_OSERVER=OFF
- [ ] Intel Release + WRITE_RESTART_BY_OSERVER=ON
- [ ] Intel Debug + WRITE_RESTART_BY_OSERVER=OFF
- [ ] Intel Debug + WRITE_RESTART_BY_OSERVER=ON
- [ ] GNU Release + WRITE_RESTART_BY_OSERVER=OFF
- [ ] GNU Release + WRITE_RESTART_BY_OSERVER=ON
- [ ] GNU Debug + WRITE_RESTART_BY_OSERVER=OFF
- [ ] GNU Debug + WRITE_RESTART_BY_OSERVER=ON
