### ISSUE TITLE
Question about times in ExtData: cTime, interpTime, fileTime

### ISSUE THREAD

**Issue by lizziel** [GEOS-ESM/MAPL#1939]
I am working on day of week handling in ExtData that is custom in the GCHP MAPL fork. I have a PR on that fork to fix problems with our method but am not 100% sure I understand the different times used in ExtData. I'd like to run my understanding by you to see if the behavior is correct.

This work is related to an old PR (https://github.com/GEOS-ESM/MAPL/pull/171) in which I submitted day of week handling to you, but ultimately decided to hold off on. My new PR, currently on just the GCHP MAPL fork, is here: https://github.com/geoschem/MAPL/pull/26. It incorporates using ESMF to extract day of week, as suggested by @bena-nasa (thanks Ben for keeping around your branch `feature/dow_handling`). I am not sure if day of week file handling should propagate to the upstream given it is file-specific (first index must be Sunday). This is another thing I would like feedback on. Are you interested in adding this to ExtData?

Regarding the update, the data being read is set in `ExtData.rc` as this:
`NEI99_DOW_CO   1 D N F1999-%m2-01T00:00:00 none none CO   ./HcoDir/NEI2005/v2014-09/scaling/NEI99.dow.geos.1x1.nc`

The cyclic 'D' option is new and indicates a day of week data file. The file contains 84 entries, with 7 per month. Times, and their associated day of week, are as follows. 
```
1999-01-01 00:00:00 is Sunday in January
1999-01-02 00:00:00 is Mon
1999-01-03 00:00:00 is Tue
1999-01-04 00:00:00 is Wed
1999-01-05 00:00:00 is Thu
1999-01-06 00:00:00 is Fri
1999-01-07 00:00:00 is Sat
1999-02-01 00:00:00 is Sunday in February
..
1999-12-07 00:00:00 is Saturday in December
```
Confusingly 01Jan1999 is actually a Friday. I think the file year is meant to be arbitrary. The point is the index of the file, with indexes 0 to 6 corresponding to Sunday-Saturday, and the rest proceeding across the rest of the months.

To determine what file time to use I now pass current clock time to subroutine `GetBracketTimeOnSingleFile` and retrieve the day of week for that time from ESMF. The file time (in/out variable `fileTime`) is set accordingly using year 1999, current month, and target day of week. This appears as `Record time` in the logging file when using root_level DEBUG for ExtData.

I am sure this is correct, but am not sure I fully understand the other in/out times, `cTime`, and `interpTime`. The `cTime` variable is printed to the log as `Time Requested`, and the `interpTime` variable is printed as `Effective Time`.

An example of output for a run starting on July 1, 2019 (Monday) is below.

```
0000: CAP.EXTDATA: DEBUG: ExtData Run_(): READ_LOOP: variable 1265 of 1282: CO
0000: CAP.EXTDATA: DEBUG:    ==> file: ./HcoDir/NEI2005/v2014-09/scaling/NEI99.dow.geos.1x1.nc
0000: CAP.EXTDATA: DEBUG:    ==> cyclic: d
0000: CAP.EXTDATA: DEBUG:    ==> isConst:: F
0000: CAP.EXTDATA: DEBUG:    ExtData Run_: DO_UPDATE: Start. doUpdate_ is true.
0000: CAP.EXTDATA: DEBUG:    ExtData Run_: Has_Run: Start. hasRun is false. Update time.
0000: CAP.EXTDATA: DEBUG:    ExtData Run_: HAS_RUN: NotSingle is true. Update left time (bracket L)
0000: CAP.EXTDATA: DEBUG: Updating L bracket for NEI99_DOW_CO
0000: CAP.EXTDATA: DEBUG:             UpdateBracketTime: Scanning fixed file ./HcoDir/NEI2005/v2014-09/scaling/NEI99.dow.geos.1x1.nc for side L
0000: CAP.EXTDATA: DEBUG:  Retrieving formatter for: ./HcoDir/NEI2005/v2014-09/scaling/NEI99.dow.geos.1x1.nc
0000: CAP.EXTDATA: DEBUG:                GetBracketTimeOnSingleFile: Reading data for DOW 1 (entry 44 into bracket L
0000: CAP.EXTDATA: DEBUG:                   ==> File: ./HcoDir/NEI2005/v2014-09/scaling/NEI99.dow.geos.1x1.nc
0000: CAP.EXTDATA: DEBUG:                   ==> Data from: month 07 day of week 02 (01=Sunday)
0000: CAP.EXTDATA: DEBUG:                   ==> Mapped to: 1999-07-01 00:00
0000: CAP.EXTDATA: DEBUG:             UpdateBracketTime: Updated bracket L for ./HcoDir/NEI2005/v2014-09/scaling/NEI99.dow.geos.1x1.nc
0000: CAP.EXTDATA: DEBUG:             ==> (L Time Requested: 1999-07-01 00:00:00
0000: CAP.EXTDATA: DEBUG:             ==> (L Record time   : 1999-07-02 00:00:00
0000: CAP.EXTDATA: DEBUG:             ==> (L Effective time: 1999-07-01 00:00:00
0000: CAP.EXTDATA: INFO:  ... file processed: ./HcoDir/NEI2005/v2014-09/scaling/NEI99.dow.geos.1x1.nc
0000: CAP.EXTDATA: DEBUG:       ExtData Run_: HAS_RUN: NotSingle is true. Update right time (bracket R)
0000: CAP.EXTDATA: DEBUG: Updating R bracket for NEI99_DOW_CO
0000: CAP.EXTDATA: DEBUG:             UpdateBracketTime: Scanning fixed file ./HcoDir/NEI2005/v2014-09/scaling/NEI99.dow.\
geos.1x1.nc for side R0000: CAP.EXTDATA: DEBUG:  Retrieving formatter for: ./HcoDir/NEI2005/v2014-09/scaling/NEI99.dow.geos.1x1.nc
0000: CAP.EXTDATA: DEBUG:                GetBracketTimeOnSingleFile: Reading data for DOW 2 (entry 45 into bracket R
0000: CAP.EXTDATA: DEBUG:                   ==> File: ./HcoDir/NEI2005/v2014-09/scaling/NEI99.dow.geos.1x1.nc
0000: CAP.EXTDATA: DEBUG:                   ==> Data from: month 07 day of week 03 (01=Sunday)
0000: CAP.EXTDATA: DEBUG:                   ==> Mapped to: 1999-07-02 00:00
0000: CAP.EXTDATA: DEBUG:             UpdateBracketTime: Updated bracket R for ./HcoDir/NEI2005/v2014-09/scaling/NEI99.do\
w.geos.1x1.nc
0000: CAP.EXTDATA: DEBUG:             ==> (R Time Requested: 1999-07-01 00:00:00
0000: CAP.EXTDATA: DEBUG:             ==> (R Record time   : 1999-07-03 00:00:00
0000: CAP.EXTDATA: DEBUG:             ==> (R Effective time: 1999-07-02 00:00:00
0000: CAP.EXTDATA: INFO:  ... file processed: ./HcoDir/NEI2005/v2014-09/scaling/NEI99.dow.geos.1x1.nc
0000: CAP.EXTDATA: DEBUG:       ExtData Run_: HAS_RUN: End
0000: CAP.EXTDATA: DEBUG:       ExtData Run_: NOT_SINGLE: Start. Update bracketing times?
0000: CAP.EXTDATA: DEBUG:          ==> updateR: F
0000: CAP.EXTDATA: DEBUG:          ==> updateL: F
0000: CAP.EXTDATA: DEBUG:          ==> swap: F
0000: CAP.EXTDATA: DEBUG:       ExtData Run_: NOT_SINGLE: End
0000: CAP.EXTDATA: DEBUG:    ExtData Run_: DO_UPDATE: End
```

Another example of output, this time for a run starting on July 31, 2019 (Wednesday) is below.

```
0000: CAP.EXTDATA: DEBUG: ExtData Run_(): READ_LOOP: variable 1265 of 1282: CO
0000: CAP.EXTDATA: DEBUG:    ==> file: ./HcoDir/NEI2005/v2014-09/scaling/NEI99.dow.geos.1x1.nc
0000: CAP.EXTDATA: DEBUG:    ==> cyclic: d
0000: CAP.EXTDATA: DEBUG:    ==> isConst:: F
0000: CAP.EXTDATA: DEBUG:    ExtData Run_: DO_UPDATE: Start. doUpdate_ is true.
0000: CAP.EXTDATA: DEBUG:    ExtData Run_: Has_Run: Start. hasRun is false. Update time.
0000: CAP.EXTDATA: DEBUG:    ExtData Run_: HAS_RUN: NotSingle is true. Update left time (bracket L)
0000: CAP.EXTDATA: DEBUG: Updating L bracket for NEI99_DOW_CO
0000: CAP.EXTDATA: DEBUG:             UpdateBracketTime: Scanning fixed file ./HcoDir/NEI2005/v2014-09/scaling/NEI99.dow.\
geos.1x1.nc for side L
0000: CAP.EXTDATA: DEBUG:  Retrieving formatter for: ./HcoDir/NEI2005/v2014-09/scaling/NEI99.dow.geos.1x1.nc
0000: CAP.EXTDATA: DEBUG:                GetBracketTimeOnSingleFile: Reading data for DOW 3 (entry 46 into bracket L
0000: CAP.EXTDATA: DEBUG:                   ==> File: ./HcoDir/NEI2005/v2014-09/scaling/NEI99.dow.geos.1x1.nc
0000: CAP.EXTDATA: DEBUG:                   ==> Data from: month 07 day of week 04 (01=Sunday)
0000: CAP.EXTDATA: DEBUG:                   ==> Mapped to: 1999-07-01 00:00
0000: CAP.EXTDATA: DEBUG:             UpdateBracketTime: Updated bracket L for ./HcoDir/NEI2005/v2014-09/scaling/NEI99.do\
w.geos.1x1.nc
0000: CAP.EXTDATA: DEBUG:             ==> (L Time Requested: 1999-07-01 00:00:00
0000: CAP.EXTDATA: DEBUG:             ==> (L Record time   : 1999-07-04 00:00:00
0000: CAP.EXTDATA: DEBUG:             ==> (L Effective time: 1999-07-01 00:00:00
0000: CAP.EXTDATA: INFO:  ... file processed: ./HcoDir/NEI2005/v2014-09/scaling/NEI99.dow.geos.1x1.nc
0000: CAP.EXTDATA: DEBUG:       ExtData Run_: HAS_RUN: NotSingle is true. Update right time (bracket R)
0000: CAP.EXTDATA: DEBUG: Updating R bracket for NEI99_DOW_CO
0000: CAP.EXTDATA: DEBUG:             UpdateBracketTime: Scanning fixed file ./HcoDir/NEI2005/v2014-09/scaling/NEI99.dow.geos.1x1.nc for side R
0000: CAP.EXTDATA: DEBUG:  Retrieving formatter for: ./HcoDir/NEI2005/v2014-09/scaling/NEI99.dow.geos.1x1.nc
0000: CAP.EXTDATA: DEBUG:                GetBracketTimeOnSingleFile: Reading data for DOW 4 (entry 47 into bracket R
0000: CAP.EXTDATA: DEBUG:                   ==> File: ./HcoDir/NEI2005/v2014-09/scaling/NEI99.dow.geos.1x1.nc
0000: CAP.EXTDATA: DEBUG:                   ==> Data from: month 07 day of week 05 (01=Sunday)
0000: CAP.EXTDATA: DEBUG:                   ==> Mapped to: 1999-07-02 00:00
0000: CAP.EXTDATA: DEBUG:             UpdateBracketTime: Updated bracket R for ./HcoDir/NEI2005/v2014-09/scaling/NEI99.dow.geos.1x1.nc
0000: CAP.EXTDATA: DEBUG:             ==> (R Time Requested: 1999-07-01 00:00:00
0000: CAP.EXTDATA: DEBUG:             ==> (R Record time   : 1999-07-05 00:00:00
0000: CAP.EXTDATA: DEBUG:             ==> (R Effective time: 1999-07-02 00:00:00
0000: CAP.EXTDATA: INFO:  ... file processed: ./HcoDir/NEI2005/v2014-09/scaling/NEI99.dow.geos.1x1.nc
0000: CAP.EXTDATA: DEBUG:       ExtData Run_: HAS_RUN: End
0000: CAP.EXTDATA: DEBUG:       ExtData Run_: NOT_SINGLE: Start. Update bracketing times?
0000: CAP.EXTDATA: DEBUG:          ==> updateR: F
0000: CAP.EXTDATA: DEBUG:          ==> updateL: F
0000: CAP.EXTDATA: DEBUG:          ==> swap: F
0000: CAP.EXTDATA: DEBUG:       ExtData Run_: NOT_SINGLE: End
0000: CAP.EXTDATA: DEBUG:    ExtData Run_: DO_UPDATE: End
```

My question is does the log output for `interpTime`, `fileTime`, and `cTime` make sense based on what I am trying to do? I'm happy to make this question more specific if that is helpful.

**Comment by bena-nasa** [comment]
Hi LizzieI assume this references the old ExtData that uses the ESMF Config based rc files? .

I'm totally cool with this coming into **ExtData2G** which use the yaml files as a new feature if it can be done in a way that is clean code wise. I guess the first thing is define the desired feature in very precise terms so we are in agreement as to what needs to be implemented. 

ExtData1G is now legacy and no new developments will be made there. That code is essentially impossible to cleanly add new new feature to anyway, the whole reason I basically rewrote ExtData from scratch is we could add new features like this. The way files and all that logic is there in the old code is just impossible to follow and extend. I basically rewrote most of it from scratch including the part you  reference that does the file selection.

**Comment by lizziel** [comment]
Hi Ben, I am happy to implement this in ExtData2G to submit, bypassing the old ExtData altogether. I will have to rewrite our old code in ExtData2G anyway in preparation for MAPL3.

In the meantime I need to make the old code work in our fork. I am having trouble following it so it is good to hear I am not alone there. In much older versions of GCHP I know `cTime` coming into `getBracketSingleTimeOnFile` was the current clock time. At some point something changed in MAPL such that `cTime` is now file time in GCHP, and that appears to be messing up the (non-ESMF) dow calculation. I changed things to use clock time to get dow from ESMF, and use that to set `fileTime`. My main question is whether that output variable `fileTime` is what actually ends up being used, with `interpTime` only used if interpolation is on. For this particular dataset interpolation is off.

If this is all too much ancient history then no worries. I completely understand about not supporting old versions.

**Comment by bena-nasa** [comment]
My memory is that fileTime is the time used to detemplate to the file template to obtain the file to be read.
InterpTIme is the time which is used for the time interpolation which generally will be the same as the filename, unless we are talking something like a climatology. In that case you may need to apply the time for the actual year etc of the data to get the file which is not where your applications in time, but the interptime is the time used for the interpolation. I'm pretty sure the interpolation time is shifted to the climatological time.

I.E. say your application clock is at 2005-07-01 21z, and you have a single year climatology that is for the year say 1995, I'm pretty sure the the interpolation time is gets set to to 1995-07-01 21z and that the file time is probably literally the time of the bracket. Like maybe your single year climatology had 12 times  the file at mid month, so the file time would be something like 1995-07-15 0z or 1995-06-15 0z depending on which side bracketing information we are after

**Comment by lizziel** [comment]
Thanks @bena-nasa. I think this answers my questions for now so I'll close it out. I hope to get to ExtData2G very soon.
