### ISSUE TITLE
Bug found with climatological dataset in ExtData2G

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#1991]
User @dbarahon  found had a dataset consisting of monthly data (one file per month timestamped at 0z on the last day of the month for 2005) and was reporting a crash when using in ExtData2g and using the "climatology" feature for sampling outside the dataset.

I ran this this dataset through my ExtDataDriver.x

The odd thing.
If I start the driver say in 2004 everything is fine, I can run for 4 yeas and it samples at the correct times.

If I start the driver in December of 2005 like @dbarahon was doing, it crashes on 1/30/2006 presumably when it should find the next file.

I will debug.

**Comment by bena-nasa** [comment]
@dbarahon I submitted a PR to fix this. Thank you for finding it. I clearly was not robustly testing this particular feature or hammering hard enough in my testing during development.
Thanks again

**Comment by dbarahon** [comment]
Great, thanks. Do you know how I can get the fix into my tag?

Donifan



From: Ben Auer ***@***.***>
Reply-To: GEOS-ESM/MAPL ***@***.***>
Date: Friday, March 3, 2023 at 11:29 AM
To: GEOS-ESM/MAPL ***@***.***>
Cc: "Barahona, Donifan (GSFC-6101)" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [GEOS-ESM/MAPL] Bug found with climatological dataset in ExtData2G (Issue #1991)


@dbarahon<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdbarahon&data=05%7C01%7Cdonifan.o.barahona%40nasa.gov%7Cbb03f151e70b4b2ef68508db1c047f54%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638134577864436205%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=I%2FjaVAQzlcQvEEDdsFuMoQnLsjx99OvXdcqW%2FMcEPos%3D&reserved=0> I submitted a PR to fix this. Thank you for finding it. I clearly was not robustly testing this particular feature or hammering hard enough in my testing during development.
Thanks again

**Comment by mathomp4** [comment]
> Great, thanks. Do you know how I can get the fix into my tag? 

If you have a branch on the GEOSgcm fixture, you can change the version of MAPL in `components.yaml` to be MAPL 2.35.2...or ping Scott to update his branch if you are using that.
