### ISSUE TITLE
CMake error when using MAPL/2.35.2 module

### ISSUE THREAD

**Issue by natalie-perlin** [GEOS-ESM/MAPL#2016]
MAPL/2.35.2 builds OK with intel/2022.1.2 +impi, and with minimal options -
```
 -DCMAKE_BUILD_TYPE=Release \
  -DBUILD_WITH_FLAP=OFF \
  -DBUILD_WITH_PFLOGGER=OFF \
  -DESMA_USE_GFE_NAMESPACE=ON \
  -DBUILD_SHARED_MAPL=OFF \
  -DBUILD_WITH_FARGPARSE=NO \
  -DUSE_EXTDATA2G=OFF \
  ...
```

The mapl/2.35.2 module is used to build [ufs-weather-model ](https://github.com/ufs-community/ufs-weather-model) with a submodule[ GEOS-ESM/GOCART](https://github.com/GEOS-ESM/GOCART). Getting the following errors during the build:
```
CMake Error at GOCART/CMakeLists.txt:64 (find_package):
  By not providing "FindMAPL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "MAPL", but
  CMake did not find one.

  Could not find a package configuration file provided by "MAPL" with any of
  the following names:

    MAPLConfig.cmake
    mapl-config.cmake

  Add the installation prefix of "MAPL" to CMAKE_PREFIX_PATH or set
  "MAPL_DIR" to a directory containing one of the above files.  If "MAPL"
  provides a separate development package or SDK, be sure it has been
  installed.
```
Does MAPL provide some kind of FindMAPL.cmake, or could it be generated?
The following modules are used to build mapl/2.35.2:
```
Currently Loaded Modules:
  1) gcc/10.2.0       5) hpc-intel/2022.1.2   9) cmakemodules/v1.2.0  13) yafyaml/v0.5.1
  2) git/2.28.0       6) impi/2022.1.2       10) cmake/3.22.1         14) hdf5/1.14.0
  3) hpc/1.2.0        7) hpc-impi/2022.1.2   11) ecbuild/ecmwf-3.6.1  15) netcdf/4.9.1
  4) intel/2022.1.2   8) esma_cmake/v3.24.0  12) gftl-shared/v1.5.0   16) esmf/8.4.1
```

Any comments on what needs to be done or changed in these installations to solve the issue?

**Comment by natalie-perlin** [comment]
Closing the issue, not able to reproduce the error reported. All builds were resolved.

**Comment by mathomp4** [comment]
Huh. Well, glad you ... didn't figure it out? 😄

**Comment by natalie-perlin** [comment]
Reconfigured and reinstalled things, tested myself building the same code, and did not get such an error :) 
Wishing every time  I reach out for help, the issue is resolved that fast!
