### ISSUE TITLE
Create string utilities module

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#202]
In particular create an add_suffix() procedure to append formatted integer to string.

**Comment by mathomp4** [comment]
See GEOS-ESM/GEOSgcm_GridComp#174 for why

**Comment by tclune** [comment]
Creating a stream-of-conscious list of existing/desired features that could go here:

* case conversion (lower, upper, capitalize)  (maybe just ESMF)
* directories and paths
* add_suffix(), add_prefix()  (with integer argument and optional field width)

**Comment by weiyuan-jiang** [comment]
Is this issued addressed by String.F90? @tclune

**Comment by tclune** [comment]
Addressed, but it is not complete.     Indeed this issue formally can probably never be closed.

But we can close it for now.
