### ISSUE TITLE
Grids created for all GRID_LABELS regardless of usage in collections

### ISSUE THREAD

**Issue by lizziel** [GEOS-ESM/MAPL#2025]
This issue was uncovered during investigation of https://github.com/geoschem/GCHP/issues/303. Ideally only declared `GRID_LABELS` used in enabled collections would have grids created for them. Right now all declared labels have grids created. Code for this is [here](https://github.com/GEOS-ESM/MAPL/blob/c271aceafcd2936516e8ca4f1d5831a78512ba84/gridcomps/History/MAPL_HistoryGridComp.F90#L619).

**Comment by lizziel** [comment]
Yes, the GCHP HISTORY.rc file includes examples for three grid types. This is so users can adapt existing grids rather than look them up in the documentation (and potentially make errors creating from scratch).

**Comment by bena-nasa** [comment]
Right now, if you put a grid definition in the grid label list, it tries to create grid. There is no extra logic to check if the grid is needed by a collection. The easiest solution is to keep the grid definitions, but remove from the GRID_LABELS list. I read the issue, you can keep all the example grid definitions in the file you want, but then anything in the list is created, there is not smarter logic right now, and certainly trying to create c24 grid on 3500 cores won't fly. For the lat-lon grid we do allow very coarse grids to be created on lots of processors, but I do not believe we have made this generalization to every factory, it was really a one-off for our FP system.

**Comment by lizziel** [comment]
I added a fix to GCHP that comments out the example labels in GRID_LABELS. Thanks for the feedback.
