### ISSUE TITLE
Allow accumulation to be not reset by writing to file in History

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#2039]
A suer @sdrabenh was asking if History could perform accumulation, I.E. do the accumulation for the time average but not divide the count. The motivation for this is that the stretched hazardous weather experiments effort needs accumulated precipitation (basically precipitation from 0-1z, 0-2z, etc...  for each day) as one of the products we must submit. I looked at it and indeed that in addition to min/max, a straight accumulation was allowed by the coupler.

However, there was a one problem. The coupler essentially has two alarms and receiver two frequencies. The history collection has two keywords "frequency" which controls how often the collection writes, and one I was unaware of "acc_interval" which defaults to the frequency and does not appear to be used, but does exist.

Both frequencies are passed to the coupler, and two alarms are made. One is a "time to couple" alarm which controls basically when the coupler puts the result in the output. The 2nd is "time to clear" which clears the accumulators and counts. Currently both alarms are set to the frequency of "frequency", passed to the coupler, even though it gets a 2nd frequency which is the acc_interval from history.

Essentially for all practical purposes the way we run history, the "time to couple" and "time to clear" run on the same alarm. So when you write, you clear, and if you wanted something like hourly accumulated precipitation and that reset once a day, you are out of luck.

The 2nd thing I discover is that History has this notion of a reference time for the collection which defaults to 0z, so the "frequency" of writing is relative to this ref time, but this ref time is never passed to the coupler, so if you do time average, unless you set the ref_time to the start time you intend to run, the time-averaging behavior is not right. I will make a separate issue for that.

However, the coupler looks like it was designed to do this, but almost but not quite there. I made some minor tweaks and I think I've fixed it so @sdrabenh could do what he wanted. 
The changes that have to take place are:
1. the "time to zero" alarm in the coupler should be set to the acc_interval passed from history
2. some sort of reference time for this alarm needs to be passed. Since you can't pass this I highjacked the offset of the varspec which is not passed via history. I added an acc_ref_tinme, then I compute an offset so that the time-to-zero alarm can be set to ring at the time the user wants which may not be the start time which the time to couple alarm is hardwired to.
3. I removed 2 bits of logic the coupler, one was that when the couple is called it stops accumulation for that item even if you don't zero, but @atrayano could not think of a use case for that. 2nd for the time to zero alarm I removed the restriction that is has to start at or later than the model start time.

**Comment by mathomp4** [comment]
@bena-nasa Can we close this issue? or is there more work to be done?

**Comment by mathomp4** [comment]
I'm still not sure if this is fixed or not. Will contact @bena-nasa
