### ISSUE TITLE
Add mepo support to MAPL

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#205]
MAPL should be able to use `mepo` like all fixtures.

**Comment by mathomp4** [comment]
Pinging @lizziel and @LiamBindle. This is sort of a notice to you guys. GEOS is hoping to transition from using `checkout_externals` as our "external dependency tool" to an in-house tool developed by @pchakraborty (formerly of GMAO) called `mepo`.

I'm going to try and add the support in such a way that using `mepo` is an option to be specified at CMake time rather than the default. However, eventually we will be moving solely to `mepo`.

**Comment by lizziel** [comment]
Thanks @mathomp4. We are not using `checkout_externals` in GCHP and do not plan on using `mepo` after you switch over. Much appreciated if you make it non-default sooner rather than later!

**Comment by mathomp4** [comment]
@lizziel Huh. I did not know that. Do you use git submodules instead?

**Comment by lizziel** [comment]
Yes, we use git submodules. Two are nested (FV and gFTL) but so far it has been working out fine, though only two of us are developing/using it so far.

**Comment by mathomp4** [comment]
Well that makes it easy for us! I'll consult @tclune and we might just go `mepo` by default with `checkout_externals` as backup.

**Comment by lizziel** [comment]
If `mepo` is going to be default, how should we turn it off? Like `manage_externals`, we are not planning to use `mepo`.

**Comment by LiamBindle** [comment]
Thanks for the heads up! This shouldn't pose any problems on our end, but we will need a way to prevent `mepo` from running. Is there a CMake variable we could set to enable/disable `mepo`?

**Comment by LiamBindle** [comment]
I just looked at #206 and see the `USE_MEPO` variable. If I undertand correct, I can set `USE_MEPO=OFF` to prevent mepo from running? That should work good for us!

**Comment by mathomp4** [comment]
@LiamBindle Actually, it's less than that. All that code was doing was allowing someone to run MAPL.git as a standalone. Thus, if you ran `cmake .. ...` on the repo and you didn't have an `@cmake` directory, then you'd run `mepo` or `checkout_externals` to go grab it. 

However, since it seems like GCHP doesn't use this functionality (since you never used `checkout_externals` before), this is essentially a no-op for you.

**Comment by LiamBindle** [comment]
@mathomp4 Great, that sounds like it shouldn't pose any problems for us then.
