### ISSUE TITLE
Carbon fields appended with .ca and AOD fields have 001

### ISSUE THREAD

**Issue by acollow** [GEOS-ESM/MAPL#2058]
The latest x run, x0048, is running with MAPL v2.35.2 but Ben's fix for this went in with v2.34.0. For example, brown carbon is getting written to the netcdf file as CA.brEXTTAU001 despite this line in HISTORY: 'CA.brEXTTAU'    , 'CA.br'     , 'BREXTTAU'    ,.

**Comment by mathomp4** [comment]
Hmm. Let me mention @atrayano and @bena-nasa. This does look incorrect. 

I mean, I think it should be putting out `BREXTTAU001` and not `CA.brEXTTAU001` (I think the `001` will always happen since this has ungridded dims).

**Comment by acollow** [comment]
It is actually the x48 experiment, configured by Ricardo and being run by Mohar. The path is /discover/nobackup/projects/gmao/dadev/dao_it/Summer_Runs/x0048/run.

**Comment by atrayano** [comment]
Thanks. I did not see "splitField = 1" for this collection. I believe we still need it (@bena-nasa could you please confirm). But this alone cannot explain the behavior...

**Comment by rtodling** [comment]
The issue here is a grads problem not an actual source code issue.

**Comment by rtodling** [comment]
I think point that Allie was making w/ this PR is that we need a fix to remove the "ca." from the carbon species names ... and anything else that would have a period in the name.

Whereas in practice we can do tricks of the sort I say, the fact is that there is still a problem that needs to be fixed in the source code.

**Comment by tclune** [comment]
Ah - allies!    I don't want "." in component names for (almost?) completely unrelated reasons.

**Comment by mathomp4** [comment]
Reopening as I'm not sure this is fixed yet...

**Comment by mathomp4** [comment]
Yes. This is still an issue.

@bena-nasa @atrayano can you look at this?

**Comment by mathomp4** [comment]
I'll also ping @tclune in case I forget about this again.

**Comment by tclune** [comment]
Going to be hard to get attention of GOCART developers on this, esp. over the summer.    Can force the issue with MAPL 3 when that rolls out in 2040.

**Comment by mathomp4** [comment]
> Going to be hard to get attention of GOCART developers on this, esp. over the summer. Can force the issue with MAPL 3 when that rolls out in 2040.

I think it must be a MAPL issue as it seems like HISTORY is not respecting the alias passed in.

**Comment by acollow** [comment]
Sorry, I'm late to the game here...Just adding my two cents that I don't think this is a GOCART issue, but rather MAPL. The aliases were getting ignored in HISTORY.

Allie
________________________________
From: Tom Clune ***@***.***>
Sent: Monday, July 3, 2023 11:03 AM
To: GEOS-ESM/MAPL ***@***.***>
Cc: Collow, Allie (GSFC-610.1)[UNIVERSITY OF MARYLAND BALTIMORE CO] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [GEOS-ESM/MAPL] Carbon fields appended with .ca and AOD fields have 001 (Issue #2058)

CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.




Ah - I misunderstood Ricardo's comment. If it is MAPL, we should have addressed this a while back. Now a priority.

**Comment by acollow** [comment]
Following up on this since it showed up in another run I am looking at. In case it helps, the build has v2.35.3 for MAPL and v2.1.2 for GOCART. The issue was not in runs that used v10.22.0 of the GCM.

**Comment by tclune** [comment]
Not reflected in this thread,  but @atrayano is actively looking into this now.

**Comment by mathomp4** [comment]
@acollow There is a new MAPL 2.39.5 now with this fix. If you need it backported to a previous MAPL, please let us know and we can work on that.

**Comment by acollow** [comment]
Thanks Matt! I will need to check with others, but there is a possibility we will need this for x48 should it get promoted and/or R21C.
________________________________
From: Matthew Thompson ***@***.***>
Sent: Monday, July 10, 2023 11:12 AM
To: GEOS-ESM/MAPL ***@***.***>
Cc: Collow, Allie (GSFC-610.1)[UNIVERSITY OF MARYLAND BALTIMORE CO] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [GEOS-ESM/MAPL] Carbon fields appended with .ca and AOD fields have 001 (Issue #2058)

CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.




@acollow<https://github.com/acollow> There is a new MAPL 2.39.5 now with this fix. If you need it backported to a previous MAPL, please let us know and we can work on that.

**Comment by mathomp4** [comment]
@acollow Okay. Just let us know the MAPL version that will be used in R21C and x48 and I can work with @atrayano to make a patch for that as well.
