### ISSUE TITLE
Complaint to subroutine MAPL_GetGlobalHorzIJIndex

### ISSUE THREAD

**Issue by metdyn** [GEOS-ESM/MAPL#2069]
@weiyuan-jiang:

I have a complaint on 
 module subroutine MAPL_GetGlobalHorzIJIndex
https://github.com/GEOS-ESM/MAPL/blob/main/base/Base/Base_Base_implementation.F90#L3173-L3253

The error is from my recent code addition:

    MAPL_HistoryGridComp.F90
     subroutine Run
        call list(n)%td_mask%get_mask(time_span,grid_in,_RC)  !  td_mask is an type obj. from TimeDependentMask defined below.

      MAPL_HistoryTdMask.F90
        module MAPL_TimeDependentMaskMod
            type :: TimeDependentMask
             contains
                 procedure :: get_mask

                 subroutine get_mask(this, time_span, grid, rc)
                    call  MAPL_GetGlobalHorzIJIndex(nx,II,JJ,lon=obs_lons,lat=obs_lats,grid=Grid,_RC)   !! code hangs
                   !! call MAPL_GetHorzIJIndex(nx,II,JJ,lon=obs_lons,lat=obs_lats,grid=grid,_RC)             !! not code hang
      
If I use  MAPL_GetHorzIJIndex,  there is no error.
If I use  MAPL_GetGlobalHorzIJIndex,  after a few  model time steps and subsequent history calls,  the code hangs forever. 

I suspect:
   -   elemental subroutine calculate(x, y, z, i, j)  is fancy and I see arrays not deallocated.  
  
I did the following tests:

    1. allocate(x(npts), y(npts), z(npts))
        deallocate (lons, lats, xyz, max_abs, x, y, z)
        it did not solve my specific problem. 

    2. inside my subroutine get_mask 
       if I make a do loop call
          do k=1, 2
              call  MAPL_GetGlobalHorzIJIndex(nx,II,JJ,lon=obs_lons,lat=obs_lats,grid=Grid,_RC)
          enddo 
       The code does not hang.  There is no problem.   This surprised me.  I donot know how to explain.

Additional information:   my input nx = 54810  e.g. 

It appears that MAPL_GetHorzIJIndex does not have element subroutines. So I think deallocate and element subroutines are the issues here. 

Will you please take a look?

Thanks!

**Comment by weiyuan-jiang** [comment]
What is "k" 's role in original call ?

**Comment by metdyn** [comment]
The "k" does not belong to the original code. 

With and without "k"-loop, the history run fails after a few collection cycles. 

With the k-loop, I thought the code failure can occur at the first cycle, but I find no failure at the first cycle, meaning the k-loop can not reveal the problem earlier. 

I will give a try by  do k=1, 1000 ; to see if there is a problem.

**Comment by metdyn** [comment]
The first history collection step does not crush at the step:
  do  k=1, 10**6
    call MAPL_GetGlobalHorzIJIndex
If it is not the memory leakage,  does the algorithm has a problem?

**Comment by bena-nasa** [comment]
@metdyn in Fortran there's no need to explicitly deallocate purely local allocatable variables in procedures, anything with allocate is automatically deallocated when leaving scope

**Comment by metdyn** [comment]
> @metdyn in Fortran there's no need to explicitly deallocate purely local allocatable variables in procedures, anything with allocate is automatically deallocated when leaving scope

@bena-nasa  Thank you; that really helps me!   I will check more into it.

**Comment by tclune** [comment]
Yeah - the danger with random points is that they may miss the corner cases.  (Possibly literal "corners" in this case!)

**Comment by metdyn** [comment]
@weiyuan-jiang:

Debug shows the following for   mpirun -np 6   bin/ExtDataDriver.x  when using
`call  MAPL_GetGlobalHorzIJIndex(nx,II,JJ,lon=obs_lons,lat=obs_lats,grid=Grid,_RC)`
``` 
when ( myid == 0 ) 
 code hangs at 
    subroutine MAPL_GetGlobalHorzIJInde
       good_grid = grid_is_ok(grid)
            call MAPL_GridGetCorners(Grid,corner_lons,corner_lats)
                  module subroutine MAPL_GridGetCorners
else
  code run through 
```

This happens at the first instance call. (My previous description is erroneous, because I failed to see that only 5 thread passes through the call MAPL_GetGlobalHorzIJIndex, the tile=1 fails at the first call.)  It is not related to the interpolation method, but only the check grid step. 

When I commented out   `good_grid = grid_is_ok(grid)`,   the mpirun completes (I have not check numerical results). 
I think something happened inbetween `call MAPL_GridGetInterior(grid,I1,I2,J1,J2)` and `call MAPL_GridGetCorners(Grid,corner_lons,corner_lats)` in  function grid_is_ok(grid) result(OK) has a problem.  I cannot be sure. 

My guess is either the CS grid_in I am using from ExtDataDriver.x has problematic setup, or the grid_is_ok subroutine and the calls therein has a bug. Please let me know if you can reproduce this result. I believe you will see the same error. Thanks.

I used:
AGCM1.rc
NX: 1
NY: 6

Root.GRID_TYPE: Cubed-Sphere
Root.GRIDNAME: PE180x1080-CF
Root.LM: 5
Root.IM_WORLD: 12
Root.NF: 6

**Comment by weiyuan-jiang** [comment]
Can you comment out the two line and try again ? https://github.com/GEOS-ESM/MAPL/blob/7905086a9207e0b131d78c5d279c49d1c43460a9/base/Base/Base_Base_implementation.F90#L3207-L3208

I guess  inside the MAPL_GetCorners, there are collective calls. I need to pull the call out of the condition

**Comment by metdyn** [comment]
Thanks. I will do it!

**Comment by metdyn** [comment]
@weiyuan-jiang, yes, the code runs through.  Thanks!
