### ISSUE TITLE
HISTORY.rc duration ignored in gchp/v1.0.0; frequency used instead

### ISSUE THREAD

**Issue by lizziel** [GEOS-ESM/MAPL#21]
A beta tester for GCHP 12.5.0 reported that HISTORY.rc duration is not working as expected. GCHP 12.5.0 uses a modified version of gchp/v1.0.0, but with no modifications to HISTORY. I reproduced the behavior and can confirm that files are written periodically based on frequency rather than duration in HISTORY.rc. Collection frequency still works as expected. However, this means we can only output data for one time per file.

I am investigating the source code directly, but wonder if you already know if this is either a bug or simply a change in usage of HISTORY.rc in the new version.

**Comment by bena-nasa** [comment]
Can you give an example of the History.rc you are trying to use and what you want History to do? Has there been a change in the behavior? History will always write at the frequency, not the duration. In principle the duration controls when new file is created. This may never have been super robust as both our ADAS and GCM default histories never write more than one time per file.

**Comment by lizziel** [comment]
I have two test run configurations:

1) frequency = 1 hour; duration = 1 hour
2) frequency = 1 hour; duration = 3 hour

In both cases the collection file is written every hour with hourly data. I checked the run stdout as well as the rcx files written with information on the collection. Duration appears to be set correctly, as this is in the rcx file:

  SpeciesConc.frequency:  010000
  SpeciesConc.duration:   030000

It appears that this is not actually a new problem. The bug report was for a GCHP version using a 2019 version of MAPL, but I just tested with an older version and it also has the same behavior.

**Comment by bena-nasa** [comment]
What exactly is the problem or behavior you are seeing that you are seeing that is not what we expect? If frequency is 1 hour, it will always write every hour. Are you saying you are not seeing a new file every 3 hours with a 3 hour duration?

**Comment by lizziel** [comment]
My understanding is that if frequency is 1 hour and duration is 3 hours then a file should be created every 3 hours and contain hourly data. Instead I am seeing that a new file is created every hour.

**Comment by bena-nasa** [comment]
I just tried this with both our stock and development branches.
I'm starting at 21z
I have a collection like this:
  geosgcm_prog.template:  '%y4%m2%d2_%h2%n2z.nc4',
  geosgcm_prog.archive:   '%c/Y%y4',
  geosgcm_prog.format:    'CFIO',
  geosgcm_prog.frequency:  010000,
  geosgcm_prog.duration:  030000,
  geosgcm_prog.fields:    'PHIS'     , 'AGCM'         ,

I'm seeing a new file created at 0z, 3z, etc... and they have 3 times. Can you post the full collection

**Comment by lizziel** [comment]
My collection is defined as:
```
  SpeciesConc.template:   '%y4%m2%d2_%h2%n2z.nc4',
  SpeciesConc.format:     'CFIO',
  SpeciesConc.frequency:  010000
  SpeciesConc.duration:   030000
  SpeciesConc.mode:       'time-averaged'
  SpeciesConc.fields:     'SpeciesConc_Rn222                   ', 'GIGCchem',
                          'SpeciesConc_Pb210                   ', 'GIGCchem',
                          'SpeciesConc_Pb210Strat              ', 'GIGCchem',
                          'SpeciesConc_Be7                     ', 'GIGCchem',
                          'SpeciesConc_Be7Strat                ', 'GIGCchem',
                          'SpeciesConc_Be10                    ', 'GIGCchem',
                          'SpeciesConc_Be10Strat               ', 'GIGCchem',
                          'SpeciesConc_PassiveTracer           ', 'GIGCchem',
                          'SpeciesConc_SF6Tracer               ', 'GIGCchem',
                          'SpeciesConc_CH3ITracer              ', 'GIGCchem',
                          'SpeciesConc_COAnthroEmis25dayTracer ', 'GIGCchem',
                          'SpeciesConc_COAnthroEmis50dayTracer ', 'GIGCchem',
                          'SpeciesConc_COUniformEmis25dayTracer', 'GIGCchem',
::
```
My output of a 3-hr run is as follows:
```
GCHP.SpeciesConc.20160101_0030z.nc4
GCHP.SpeciesConc.20160101_0130z.nc4
GCHP.SpeciesConc.20160101_0230z.nc4
```
Taking a look at the differences between my MAPL_HistoryGridComp.F90 and the one in the develop I see there are several changes related to the o-server (see attached diff). I wonder if the updates fixed the issue?
[HistoryGridComp_gchp_vs_develop.txt](https://github.com/GEOS-ESM/MAPL/files/3502633/HistoryGridComp_gchp_vs_develop.txt)

**Comment by bena-nasa** [comment]
I'm very confused. None of those difference would matter for this. I can't reproduce what you are seeing, both the development and the CVS version are behaving. With a history collection set as you are showing above I get this:

scratch/testduration.geosgcm_prog.20000414_2130z.nc4
scratch/testduration.geosgcm_prog.20000415_0030z.nc4
scratch/testduration.geosgcm_prog.20000415_0330z.nc4
scratch/testduration.geosgcm_prog.20000415_0630z.nc4
scratch/testduration.geosgcm_prog.20000415_0930z.nc4
scratch/testduration.geosgcm_prog.20000415_1230z.nc4
scratch/testduration.geosgcm_prog.20000415_1530z.nc4

**Comment by lizziel** [comment]
Okay, I'll see if it I can find it in my version by tracking down the step where the file is created. There must be a conditional that is returning the wrong value, and if I can find that maybe I can work backwards to see what's wrong. It's definitely puzzling!

**Comment by atrayano** [comment]
Lizzie, could you please share your HISTORY.rc with us. This might be related to the starting time (21z vs 0z) and/or ref_time

**Comment by lizziel** [comment]
Here is my HISTORY.rc. I start the run at 0z. I tried starting at 21z but it still gives three different output files.
[HISTORY.rc.txt](https://github.com/GEOS-ESM/MAPL/files/3506570/HISTORY.rc.txt)

**Comment by mathomp4** [comment]
@lizziel Can you tell us when your run starts as well? Are your restarts at 00z? 21z?

**Comment by lizziel** [comment]
My restart file is at 00z. Here are my CAP.rc and GCHP.rc files as well.
[GCHP.rc.txt](https://github.com/GEOS-ESM/MAPL/files/3506804/GCHP.rc.txt)
[CAP.rc.txt](https://github.com/GEOS-ESM/MAPL/files/3506833/CAP.rc.txt)

For my 21z test I changed the start time in CAP.rc but did not change my restart file.

**Comment by bena-nasa** [comment]
Hmm, I still could not reproduce running 3 hour segments as your CAP.rc indicates (although you will never get a file with 3 times in it if you run this way). It still put 2 times in a file. For example, starting a 0z, it created the file at 1z, wrote 1z and 2z to the file, then created a new file at 3z. Of course the model will stop then so the next segment you could get a 4z file, then 6z file etc ...
As an aside, I would advise not using the BEG_DATE and END_DATE in the CAP.rc to control how long the model runs. I would set the BEG_DATE to something far in the past and just rely on the cap_restart file to control the start time and then it will run for the segment length in the CAP.rc Also the END_DATE is only needed in a multi-segment job

**Comment by lizziel** [comment]
Thanks @bena-nasa for looking more into this. This is a comparatively minor issue so it is on the back-burner at the moment for me to look at, and I am hoping updating versions again soon will simply make it go away as has been the case for other mysterious MAPL behavior.

Regarding your usage suggestions, good to know. The design was intended to make GCHP usage as similar as possible GEOS-Chem Classic usage, to ease the transition for users. Are there known problems with using BEG_DATE and END_DATE as start/end for single runs? By default cap_restart is deleted prior to single runs to avoid issues. As for multi-run, I implemented a multi-run option in the GCHP run directory which does a lot of things automatically so as to allow monthly average diagnostics. The auto setup includes settins BEG_DATE and END_DATE as endpoints of the full multi-run span and rigorously checking cap_restart to look for problems between runs, cancelling all jobs if there is one. Do you see any issues with this? So far it's been working well and makes things fairly easy for users.

**Comment by lizziel** [comment]
I revisited this GCHP issue using a newer version of MAPL develop (https://github.com/GEOS-ESM/MAPL/commit/9453677868678e81da779bf3b0b083f61848a77e). As hoped, the the problem goes away in the newer version.
