### ISSUE TITLE
How to retrieve simulation start time

### ISSUE THREAD

**Issue by lizziel** [GEOS-ESM/MAPL#2112]
I would like to retrieve the simulation start time for the case of `cap_restart` present at the start of the run. I notice `ESMF_ClockGet` returns `BEG_DATE` in `CAP.rc` rather than simulation start date. however, the start time in `cap_restart` should be available since it is stored in `cap%cap_restart_time`. Is there an easy way to access this from any gridded component in any timestep without reading `CAP.rc` again? 

For reference I am trying to extract the start time [here](https://github.com/GEOS-ESM/geos-chem/blob/75f1b9ca737b4442a6970118288644a3ea8bddf3/Interfaces/GCHP/Chem_GridCompMod.F90#L3896-L3901). I want to use to compute an accurate elapsed time.

This issue is somewhat related to https://github.com/GEOS-ESM/MAPL/issues/506.

**Comment by tclune** [comment]
Hmm.   I don't really like the idea of accessing the Cap or the CAP.rc file from other components; encapsulation and all that.

Better would be to attach this to the clock and then get it from there.    

@bena-nasa  My knowledge of clocks and alarms is only large enough to be dangerous.  Does a solution suggest itself to you?

**Comment by lizziel** [comment]
Thanks for the quick reply. In the meantime I have a work-around of setting a local saved ESMF_Clock variable equal to current time in the first timestep. Perhaps this is the best way to go?

**Comment by bena-nasa** [comment]
@lizziel When Cap creates the clock, it creates the clock start/end based on the BEG_DATE and END_DATE in the CAP.rc

It then looks if there is a cap_restart and set the current time of the clock to the date in the cap_restart.

Unfortunately there's nothing special about this time nor do we to my knowledge do anything in the lock to store the fact this was the real model start time, the the clock start time.

If you want to access, the actual start time in any gridded component, at any time, you would have to query cap_restart or we need to add a decoration to the clock to record this.
