### ISSUE TITLE
Can ESMF route handles be applied to fields with trailing undistributed dimensions?

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#2145]
@tclune thought that perhaps ESMF had removed the restriction that to reuse an ESMF route handle on a field that has undistributed dimensions, when the route handle had been created via fields that had no undistributed dimensions,  so that making temporary fields with the ungridded dimensions as the leading dimensions may not be necessary which would have implications for MAPL3 and the regridder redesign to work on fields rather than fortran arrays.

Now that I am looking at MAPL3, I remembered we wanted investigate this question, so I did a quick experiment and changed the MAPL_EsmfRegridder to not do this transposition for the fields created when regridding 3D fields with a route handle that was defined based on 2 fields with no ungridded dimensions. Unfortunately it did not work and failed spectacularly when applying the route handle.

The ESMF logging had these sorts of errors that appear to indicate an issue with the dynamic masking that we must use:

```
20230519 092451.937 ERROR            PET0 ESMCI_DELayout.C:6832 ESMCI::XXE::exec() Internal error: Inconsistency  - Dynamic masking is not defined for interleaved distributed and undistributed dims
20230519 092451.937 ERROR            PET0 ESMCI_Array.C:12304 ESMCI::Array::sparseMatMul() Internal error: Inconsistency  - Internal subroutine call returned Error
20230519 092451.937 ERROR            PET0 ESMCI_Array_F.C:1257 c_esmc_arraysmm() Internal error: Inconsistency  - Internal subroutine call returned Error
20230519 092451.937 ERROR            PET0 ESMF_Array.F90:940 ESMF_ArraySMM() Internal error: Inconsistency  - Internal subroutine call returned Error
20230519 092451.937 ERROR            PET0 ESMF_FieldRegrid.F90:263 ESMF_FieldRegrid Internal error: Inconsistency  - Internal subroutine call returned Error
```
Just making a note here to inquire about this an an ESMF telecon as the documentation implied we might not have to do this anymore. Indeed the document seems to imply a route handle can be reused regardless of where the ungridded dimensions are (leading or tailing), but it almost seems like once you choose to use dynamic masking this goes out the window. And using the dynamic masking is non-optional for our requirements.

**Comment by tclune** [comment]
@bena-nasa please point me at your example.     This is surprising, so I'd like to double check that there is not some other issue hitting us.

**Comment by bena-nasa** [comment]
@tclune  I simply checked out MAPL, changed the 3D real32 procedure (here is where I did it locally on Discover):
/gpfsm/dswdev/bmauer/models/mapl_remove_3D_hack/MAPL/base/MAPL_EsmfRegridder.F90

so that the temporary 3D fields that get created (since the regridder needs fields not arrays of course) use a gridToFieldMap = [1,2], rather than [2,3] and then just assign the input array to the field pointer rather than doing a reshape. Here is the git diff
```
           _ASSERT(kin == size(q_in,3),'inconsistent array shape')
       end if
       src_field = ESMF_FieldCreate(spec%grid_in, typekind=ESMF_TYPEKIND_R4, &
-                  gridToFieldMap=[2,3],ungriddedLBound=[1],ungriddedUBound=[kin],&
+                  gridToFieldMap=[1,2],ungriddedLBound=[1],ungriddedUBound=[kin],&
                   rc=status)
       _VERIFY(status)
       if (HasDE) then
          call ESMF_FieldGet(src_field,localDE=0,farrayPtr=p_src,rc=status)
          _VERIFY(status)
-         p_src = reshape(q_in,shape(p_src), order=[2,3,1])
+         p_src = q_in
+         !p_src = reshape(q_in,shape(p_src), order=[2,3,1])
       end if


@@ -320,7 +321,7 @@ contains
           _ASSERT(km == size(q_out,3),'inconsistent array shape')
       end if
       dst_field = ESMF_FieldCreate(spec%grid_out, typekind=ESMF_TYPEKIND_R4, &
-                  gridToFieldMap=[2,3],ungriddedLBound=[1],ungriddedUBound=[kout],&
+                  gridToFieldMap=[1,2],ungriddedLBound=[1],ungriddedUBound=[kout],&
                   rc=status)
       _VERIFY(status)
       if (HasDE) then
@@ -332,7 +333,8 @@ contains
       call this%do_regrid(src_field, dst_field, rc=status)
       _VERIFY(status)

-      if (HasDE) q_out = reshape(p_dst, shape(q_out), order=[3,1,2])
+      !if (HasDE) q_out = reshape(p_dst, shape(q_out), order=[3,1,2])
+      if (HasDE) q_out = p_dst
```

I then just tried to regrid an input file with Regrid_Util.x and it spit out the above, seems to me like this doesn't play nicely with dynamic masking.

**Comment by bena-nasa** [comment]
@tclune 
Ah, direct from their documentation:
"Dynamic masking is also available for source and destination fields that contain leading undistributed dimensions. When ESMF applies the regridding weights, it interprets the product space of leading undistributed dimensions of a Field or Array as the elements of a vector. In this approach the interpolation becomes a vector operation. When applying the concept of dynamic masking to such a vector operation, without making further assumptions, it must be assumed that different vector elements may be affected differently by the dynamic mask. ESMF therefore unrolls the vector dimension when constructing the information passed to the dynamicMaskRoutine. As a consequence of this, masking routines do not generally have to consider vectorization explicitly."
