### ISSUE TITLE
pflogger always used

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [GEOS-ESM/MAPL#2152]
Since 2.38.0, geom/CMakeLists.txt and pfio/CMakeLists.txt contain `find_package (PFLOGGER REQUIRED)` which are not conditional based on BUILD_WITH_PFLOGGER. This for example causes spack-stack builds with pflogger disabled (`mapl ~pflogger`) to fail.

**Comment by mathomp4** [comment]
@tclune This does bring up a few things:

1. We really should still support non-pFlogger builds of MAPL...
2. ...but I think that should not be the default when MAPL reaches Spack

But I should also maybe figure out how to get the CI to not have pflogger. I'll need to discuss with @tclune next week.
