### ISSUE TITLE
Extend O-server - replace collection method

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#2182]
Notifying @metdyn and @bena-nasa 

The new swath sampler has a time-varying grid that changes the collection metadata at various timesteps.   History needs to be able to inform the server of the changes in the metadata.    

I see 2 approaches:
1. Introduce a method to delete an existing collection.   History can then just "re-add" the collection.
2. Add a method which simply overwrites an existing collection.   This might look the same under the hood.

**Comment by weiyuan-jiang** [comment]
I have not tested the PR #2186 @bena-nasa . I don't know how and when are you going to use it.  But if it is not working, please let me know. Basically, a method "replace_metadata" is added. It is quite similar to modify_metadata situation. ( The argument is different though)

**Comment by bena-nasa** [comment]
@weiyuan-jiang 
Thank you, I will put it on the plate today to test this PR and will let you know if I hit an issue.
