### ISSUE TITLE
Are the 'PE' and 'PC' correct?

### ISSUE THREAD

**Issue by weiyuan-jiang** [GEOS-ESM/MAPL#2183]
@bena-nasa @tclune 

https://github.com/GEOS-ESM/MAPL/blob/dea3ee7a8481a75a50d25a2dc9f9459d3117d661/base/MAPL_LatLonGridFactory.F90#L500-L508

**Comment by tclune** [comment]
I believe so.  Do you have a specific concern?   If nothing else so many runs have used this implementation that it almost _defines_ what we mean by these terms.    I agree that PC is a strange beast.     Not only are the polar cells degenerate in that 2 corners are the same point (the pole), but the "center" is also at the pole.   For PE,  you still have the 2 corners being degenerate, but at least the "center" is somewhere near the geometric middle of the region.

**Comment by weiyuan-jiang** [comment]
Hmm, it is center, not edge. I thought is not compatible with  GEOSldas. But in GEOSldas, it is about edge. 
So, this is not an issue.
