### ISSUE TITLE
Missing XCdim and YCdim variables in monthly tripolar collection

### ISSUE THREAD

**Issue by zhaobin74** [GEOS-ESM/MAPL#2231]
As of MAPL 2.39.1, the postprocessing of climatologies failed on monthly tripolar collections, e.g. ```geosgcm_ocn2dT```. The errors  showed the following
```
ncvarid: ncid 65536: NetCDF: Variable not found
 GFIO_GetBegDateTime: ncvid failed
NCAGT: : NetCDF: Attribute not found
ncvarid: ncid 65536: NetCDF: Variable not found
ncvarid: ncid 65536: NetCDF: Variable not found
NCAGT: : NetCDF: Attribute not found GFIO_GetBegDateTime: ncvid failed
```
A bit investigation indicates the errors are from the **GFIO** layer used by **time_ave.x** when it tried to form climatologies from monthly files.  At some point, two new dimensions (```XCdim``` and ```YCdim```)were added but they don't have corresponding variables defined in the nc4 file. As a result, GFIO quits prematurely and creation of climatology fails. 

A potential fix may be to add variables  ```XCdim``` and ```YCdim``` with fake data, just like ```Xdim``` and ```Ydim``` to make **GFIO** happy.

**Comment by bena-nasa** [comment]
@zhaobin74 
Technically time_ave.x nor, GFIO are not part of MAPL and are not maintained by the SI team. As Matt said, we have a new utility time_ave_util.x that IS part of MAPL that I intended to replace_time_ave.x. Matt said you tried it but that also failed. Happy to look at that once I have more details.
