### ISSUE TITLE
Help with ExtData Template

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#2250]
Received an email about ExtData from Mariusz Pagowski (@mpagowski) of NOAA

> I work at NOAA with a model called UFS-Aerosols which is derived from NASA's GOCART2G. I am trying to make the model read (emission) files at hourly intervals
> coded in ExtData.rc . I followed a template used for 24h interval and changed it from
> 
> ```
> # -------------|-------|-------|--------|----------------------|--------|--------|-------------|----------|
> #  Import      |           |          | Regrid  |        Refresh            | OffSet | Scale  | Variable On |   File   |
> #  Name       | Units | Clim  | Method |     Time Template    | Factor | Factor |     File          | Template |
> # -------------|-------|-------|--------|----------------------|--------|--------|-------------|----------|
> 
> ...
> 
> BC_ANTEBC1 NA  N Y %y4-%m2-%d2t12:00:00 none none BC       ExtData/nexus/CEDS/v2019/%y4/CEDS.2019.emis.%y4%m2%d2.nc
> ```
> to
> ```
> BC_ANTEBC1 NA  N Y %y4-%m2-%d2t%h2:00:00 none none BC       ExtData/nexus/CEDS/v2019/%y4/CEDS.2019.emis.%y4%m2%d2%h2.nc
> ```
> plus other attempts with _%h2%n2 etc. but failed to solve the problem as the code crashes and I cannot decipher the correct format.
> 
>
> 
> First, will the code read consecutive emission files every 24 hours for forecasts longer than a day when configured as in the original formulation above?
> Or read only initially for the first hour and keep emissions constant forever. Then, is it possible to make the code read emissions at hourly intervals during a forecast
> and how to format it properly?
> 
> I asked at NOAA but did not find a solution.

**Comment by mathomp4** [comment]
@mpagowski Was this ever fixed/solved for you?

**Comment by mpagowski** [comment]
Yes, I understand how it works
