### ISSUE TITLE
GEOSgcm MAPL3 failure (2023-Jul-28)

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#2264]
I have been trying to trace these two issues
#2263 
and
#2262 
and have come to the conclusion they are really the same symptom.
The issue is in the MAPL_TerminateImportAllBut which was now being call in the surface component. The issue is this loop:
https://github.com/GEOS-ESM/MAPL/blob/release/MAPL-v3/generic/MAPL_Generic.F90#L5114
With gcc we get the crash references in issue #2262, with intel we get the crash referenced in #2263, but that is only because rather than failing the line referenced, the size(...) returns 0, and just skips the loop for all 4 children, so all their imports make their way to ExtData.

The fundamental problem is that the size( ) should not be zero, in fact for child 1 which is ocean, on develop I see that it is 47!

So clearly the child metacomp is screwed up. It is almost like the SetService has never happened as that size( ) returns 0 for all 4 children of surface.

**Comment by bena-nasa** [comment]
@atrayano has confirmed the MAPL release/MAPL-v3 branch now executes the SetServices in a different order so at this point the SetServices of the children not run so, this code in TerminateAllBut will simply not work on this branch.

**Comment by tclune** [comment]
Ugh.  That is unfortunate.

@mathomp4 Maybe we stop testing the MAPL3 branch for now.  After all for many months my development has been on features that are not yet used.   I jumped the gut with my early work.

**Comment by mathomp4** [comment]
Closed by #2270
