### ISSUE TITLE
Update pfio FileMetadata to gftl2

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#2310]
There are several useful features in gFTL2 that I would have wanted to use when manipulating FileMetadata in the new GeomFactory.   In particular:  `ftn_begin()` and `ftn_end()` which are safer than the older begin/end.

Unfortunately this upgrade will have fingers in many parts of MAPL, but hopefully does not extend beyond that.

This can be done in incremental steps.   
1. Convert StringVariableMap
2. Use gFTL2 StringIntegerMap
3. use gFTL2 StringVector

If you run into any `Ptr` containers - see me.  These are not well supported in gFTL2.

**Comment by mathomp4** [comment]
Closed by #2315 I believe.
