### ISSUE TITLE
Bug in pfio (nonstandard Fortran)

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#2319]
In the code snippet below, we have use cases (e.g. ExtData1G_case12) which send down a zero-sized array.   `c_loc()` is not permitted on zero sized arrays, and NAG flags this.

One possibility is that the array should not be zero sized, in which case @bena-nasa should track down why that happens, and a runtime check should be added to trap it in the code below.     The other possibility is that this is intentional, in which case @weiyuan-jiang should devise an extension to support this.

https://github.com/GEOS-ESM/MAPL/blob/d3085a106ebdb62c9b13ccd6b2c642e34059765a/pfio/ArrayReference.F90#L48-L59

**Comment by bena-nasa** [comment]
@tclune case12 is exactly the one that intentionally exercises the case when the grid cannot be decomposed so yes, some processes have no data or 0 sized arrays

**Comment by weiyuan-jiang** [comment]
Will this branch fix the issue ? @tclune 
https://github.com/GEOS-ESM/MAPL/tree/feature/wjiang/bypass_cloc

**Comment by bena-nasa** [comment]
@weiyuan-jiang 
All the extdata tests are here:
https://github.com/GEOS-ESM/MAPL/tree/main/Tests/ExtData_Testing_Framework/test_cases
To run any one of them you copy the files from the test case somewhere and run ExtDatDriver.x using the appropriate number of processors.
So to run test 12 you could copy the contents of case12 to a directory
In CAP1.rc and CAP2.rc add "USE_EXTDATA2G: .true. "
Then mpirun -np 216 path_to_install/bin/ExtDataDriver.x
