### ISSUE TITLE
extrapolation may be needed

### ISSUE THREAD

**Issue by weiyuan-jiang** [GEOS-ESM/MAPL#233]
https://github.com/GEOS-ESM/MAPL/blob/c3bc53fe7c4cad5ef20ac1630ce12da0df5279b4/MAPL_Base/MAPL_LatLonToLatLonRegridder.F90#L572-L573

There is no guarantee that the "out" will fall between "in". So we may need to consider the extrapolation instead of interpolation
@tclune @bena-nasa

**Comment by tclune** [comment]
@weiyuan-jiang 

This regridder is not being used any more.  We now delegate all regridding through ESMF.

@bena-nasa Should we possibly start deleting the unused MAPL modules?

**Comment by weiyuan-jiang** [comment]
But the ModelE  branch is using these codes

**Comment by weiyuan-jiang** [comment]
Can we replace the old MAPL with the new one ? It seems we need to replace a lot of components to make it work. @bena-nasa

**Comment by mathomp4** [comment]
@bena-nasa @weiyuan-jiang Can this be closed? Perhaps this issue is "complete"?

**Comment by mathomp4** [comment]
Closing for now. If ModelE work resumes, open new issue.
