### ISSUE TITLE
History SCU17 Woes

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#2347]
@mathomp4 reported that on the new SCU17 system, the model was hanging in certain configuration, in particular if the dedicated o-server is on and you are using intel compiler/intel mph.
@mathomp4 has run with gnu and says it does not hang with gnu, although then we have other problems...

I have reproduced this, here is where things get weird.
Indeed my c180 run with the o-server hangs in History. If I turn off the dedicated o-server it runs through there. If I turn it on hangs. If I just turn off History it runs to ExtData and hangs in ExtData.

And to make it weirder. I noticed if I don't regrid the collection, it gets past the History started. Using that clue I confirmed that hang seems to be when creating the regridding handle, only when the dedicated o-server is on. This makes no sense as these have nothing to do with each other.

That is the situation as of the time I post this. I will investigate more but my first instinct is this is an MPI issue, but a weird one...

**Comment by bena-nasa** [comment]
@mathomp4 reported that Intel compiler + openmpi does not hang, so strongly suggests we have an Intel MPI issue here.

**Comment by bena-nasa** [comment]
Yep, just hangs on the ESMF_FieldRegridStore, when the dedicated o-server is running, even though they should have nothing to do with each other...
Any flags you can think of @mathomp4 that we might twiddle? Unfortunately just commenting out any or all of the flags we have set in gcm_run.j right now, seem to help. Indeed a few of them seem to be necessary for the model to even start...

**Comment by mathomp4** [comment]
@bena-nasa Not really. @theurich, do you have any ideas on what types of MPI calls might be involved underneath in `ESMF_FieldRegridStore` calls? We'd like to try adjusting Intel MPI to see if we can figure it out, but we'd need to know what types of calls/algorithms to target (aka, `MPI_AllgatherV`, etc.)

**Comment by theurich** [comment]
@mathomp4 The `ESMF_FieldRegridStore()` call does weight generation (by @oehmke) and smmstore (by myself). For the smmstore part, there are a few (~3 or so) `Allgather()` calls, and then many `Isend()` and `Irecv()` calls. Bob can comment on the weight generation part. 
As for the _hanging_ of the `ESMF_FieldRegridStore()` call, have you verified that all of the PETs (i.e. MPI ranks) are actually making it into to where the `ESMF_FieldRegridStore()` call is made? Maybe place a `Barrier()` right ahead of the call and see if you can get past it. If not, then there might be PETs stuck some place before.

**Comment by oehmke** [comment]
@mathomp4 <https://github.com/mathomp4> For the weight generation, the exact calls would depend on the grid, regrid method, and options. However, in general, there are probably some MPI_Allreduce(), MPI_Reduce_scatter(), MPI_Allgather*(),  and/or MPI_Scan(), to set things up and then MPI_Send(), and MPI_Irecv() to move data around.

**Comment by bena-nasa** [comment]
That prompted me to put a barrier to synchronize all my prints (I was printing the line so see how far I got), turns out it is the ESMF_FieldSMMStore where we are hanging, it gets past the RegridStore, I assuming FieldSMMStore more of the same MPI calls that RegridStore uses? I did confirm that every process gets to the SMMStore call, but does not get past it.
The “good” news is the only reason we are even calling this is to get the transpose route handle, which for normal runs of GEOS is not needed. I can skip that see how far I can get…


From: oehmke ***@***.***>
Reply-To: GEOS-ESM/MAPL ***@***.***>
Date: Wednesday, September 13, 2023 at 1:14 PM
To: GEOS-ESM/MAPL ***@***.***>
Cc: "Auer, Benjamin M. (GSFC-610.1)[SCIENCE SYSTEMS AND APPLICATIONS INC]" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [GEOS-ESM/MAPL] History SCU17 Woes (Issue #2347)

CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.


@mathomp4 <https://github.com/mathomp4> For the weight generation, the exact calls would depend on the grid, regrid method, and options. However, in general, there are probably some MPI_Allreduce(), MPI_Reduce_scatter(), MPI_Allgather*(), and/or MPI_Scan(), to set things up and then MPI_Send(), and MPI_Irecv() to move data around.

**Comment by bena-nasa** [comment]
Turns out I was wrong, even with the o-server off, the model is still hanging on a RegridStore call, just seems to be happening now in ExtData. I'm going to try to see if I can reproduce this outside the model...

**Comment by bena-nasa** [comment]
Bingo, I can reproduce this with Regrid_Util.x, hanging in the route handle generation

**Comment by oehmke** [comment]
A reproducer would be great. Do you know what regrid method the RegridStore call is using?  Thanks.

**Comment by bena-nasa** [comment]
Now I don't where the heck it's hanging... just so confused, it might be in our own code :( might take a while to get to the bottom of this where I can design a reproducer, not sure what to reproduce...

**Comment by tclune** [comment]
Can we reproduce on a coarse configuration and run in the debugger?    This is one of those situations where even _I_ find value in debuggers.

**Comment by bena-nasa** [comment]
This is driving me crazy. Adding prints seems to have fixed the hang. I'm going to need to have someone else (realistically Matt) try the same thing and confirm what I'm seeing. It seems as adding prints in the code to find out where I was hanging seemed to fix the hang.

**Comment by mathomp4** [comment]
Not sure this is solved. Maybe @bena-nasa can comment
