### ISSUE TITLE
Tripolar Grid Factory Missing Changes from CVS

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#243]
Yuri was testing the latest release of the GCM that includes MAPL v2.0.0

It was crashing in when trying to create a tripolar grid. It turns out we had made changes for the tripolar grid to register the tripolar grid factory and changes to read in the coordinates that were on the yuri_JD_merge branch of CVS that had not made it into git.

**Comment by mathomp4** [comment]
Fixed by #244
