### ISSUE TITLE
In HISTORY, allow arithmetic involving a bundle field

### ISSUE THREAD

**Issue by mmanyin** [GEOS-ESM/MAPL#2440]
HISTORY supports the output of bundle fields, it also supports arithmetic on fields, but it does not allow these two in combination,  i.e.  it does not allow arithmetic involving bundle fields.  Could this feature be added?  An example "use case" would be the units conversion of Increment bundle fields.  Thanks for considering this.

**Comment by mathomp4** [comment]
I'll assign @bena-nasa and @atrayano as they have the best shot at seeing if this is doable.

**Comment by mathomp4** [comment]
@bena-nasa Has this been enabled/fixed?

**Comment by mmanyin** [comment]
@tclune This is the PR that I mentioned.  It has particular value for doing units conversion, in the context of a monthly output collection.

**Comment by mmanyin** [comment]
I'm hoping that @bena-nasa still has this on his radar : - )

**Comment by mathomp4** [comment]
I will label as long-term

**Comment by bena-nasa** [comment]
@mmanyin Might have some time finally to explore and see if it is feasible

**Comment by mmanyin** [comment]
@bena-nasa  great --  thanks!

**Comment by bena-nasa** [comment]
@mmanyin 
I finally had a chance to look at bundle arithmetic. I thought it was going to be hopeless or at least require a lot code reorganization, but I think I did without having change a huge amount of code, shocked at how little I had to change really... Hopefully this is still useful.
I need to test more and make sure I haven't broken and remove the ridiculous amount of comments I had to put in the code to figure out how the heck this all worked...

**Comment by mathomp4** [comment]
> and remove the ridiculous amount of comments I had to put in the code to figure out how the heck this all worked...

Quoth @tclune "pFlogger DEBUG time!" 😄

**Comment by mmanyin** [comment]
@bena-nasa 
That is great news! Very useful (still)!  Thanks for all the work on this.

**Comment by bena-nasa** [comment]
@mmanyin 
I got it working. I will make a PR.

What is NOT working still is combining the splitting and arithmetic. I'm just not sure if this is feasible. I would really understand how the splitting works to see if the issue I'm seeing can be resolved.

**Comment by mmanyin** [comment]
@bena-nasa 
Thank you.  Our email exchange from Jan 29/30 identified the splitting + arithmetic problem as a separate issue. But I never opened an "issue" on GitHub, in part because I didn't want to divert focus from the work that you just did.
