### ISSUE TITLE
Modifications to use the new field split capability of ESMF

### ISSUE THREAD

**Issue by aoloso** [GEOS-ESM/MAPL#2454]
Made changes to allocate fields to use farray instead of farrayPtr. This allows explicit specification of indexflag required by the new MAPL field split functionality. This functionality allows a clean way to create a new field from an exiting field where the new field is a 'slice' of the existing field with the slicing index being that of the trailing ungiridded dim of the existing field.

**Comment by mathomp4** [comment]
@aoloso This is done, right?
