### ISSUE TITLE
Fix failing FieldBLAS_AXPY_R8 test

### ISSUE THREAD

**Issue by darianboggs** [GEOS-ESM/MAPL#2549]
Since updating the tests in field_utils/tests to use npes in the @Test decorator, test_FieldAXPY_R8 fails on 3 out of 4 PE's. test_FieldAXPY_R4 does not fail. test_FieldAXPY_R8 is a literal copy of test_FieldAXPY_R4 with all references to ESMF_KIND_R4 replaced with ESMF_KIND_R8. The functions being tested are identical except for ESMF_KIND_R4 / ESMF_KIND_R8.

Why is the ESMF_KIND_R8 failing?

**Comment by darianboggs** [comment]
Linked to new branch

**Comment by tclune** [comment]
Or alternatively, one can let ESMF do the allocation and avoid passing in an external array entirely.  (Still need to specify typekind somewhere though, of course.)

**Comment by darianboggs** [comment]
Fixed.

**Comment by darianboggs** [comment]
Pushing up fix, shortly

**Comment by darianboggs** [comment]
Closed by #2584
