### ISSUE TITLE
[Feature Request] History equivalent of ExtData DEBUG_LEVEL

### ISSUE THREAD

**Issue by lizziel** [GEOS-ESM/MAPL#255]
The ExtData component has a handy run-time flag set in ExtData.rc to turn on prints useful for debugging. It would be great if the History component had one as well. This could, for example, be used to find out what field is tripping up HISTORY.rc read, such as a duplicate name. I am happy to help with this since it is a feature that would greatly benefit the GEOS-Chem community.

**Comment by tclune** [comment]
The answer is better than that.   The _reason_ I've been working on YAML is that is an important part of the pFlogger capability I've been mentioning for years.    Within the next week, I hope to start activating pFlogger (see #142) within MAPL infrastructure on the develop branch.    We'll be able to have several knobs for managing DEBUG and ERROR messages.    Functionality is nearly identical to Pythons Logging package, but with a few extensions to support MPI issues.

I'm going to close this ticket, but watch the commits to MAPL in the near future.

**Comment by lizziel** [comment]
I know this issue is closed, but just checking in on if there is now functionality to gracefully exit with a duplicate export message if there are duplicate exports listed in a HISTORY config file collection. This keeps tripping up GCHP users, and most recently a GEOS user I'm helping today.

**Comment by tclune** [comment]
I thought we directly fixed that particular issue.  My memory is that @bena-nasa and I submitted a PR for this.   But my memory is bad.
