### ISSUE TITLE
pfio collective_stage_data fails when client root process passes no data AND using multi group server

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#2557]
The collective_stage_data call of the PFIO server has for many years now had the ability to still function if some process do not have data, in that case you just make a local memory reference or array reference with a size 0 array on those processes that do not have any data to stage.
This is used when the grid is too coarse in History and some processes do not have a de. It's also used in the restart writing to write the tile data where it is all gathered to root.

In both those cases the root process does have data to write.

I've been trying to finish another PR I am working to have one file per write. That is all working but I was also trying to get it working with o-server. If I have say 6 writers, then when it is time to write, you make the collective_stage_data call for all 6 files for example. With each request only 1/6th of the processes have a non-zero sized array reference passed. If I use the simple server, (i.e. where there s no separate o-server) it seems to work and I get 6 files with the right data

However, once I turn on the multi group server I've been struggling and have concluded that **if the ROOT process of the application does not have a non-zero size array something goes wrong** in this case. That's the only logical conclusion I can come to after struggling for over day with this. When I've been prototyping this I can write the file  for writer 1 which has the root process. But if I try to write any other file for the other writers it fails here:
https://github.com/GEOS-ESM/MAPL/blob/main/pfio/MultiGroupServer.F90#L397

Next I attempted to create a reproducer from one of the pfio tests that exercises the multi group server to reproduce this issue. I think I have (kind of).
That can be found here on discover

~bmauer/for_users/for_weiyuan/collective_stage_debugger.F90
Basically I took the pfio test executable and stripped it down.

Here is an example of how to run with 6 client process,  a multgroup server with 3 writers, 3 front end cores (for total of 6 cores for the server, and 12 total). I also added a new -o option:
mpirun -np 12 ./bin/collective_stage_debugger.x -nc 6 -nso 6 -ngo 1 -v T -s multigroup -nw 3 -o 1

In the code the server is told to create a file with xdim=12 and ydim=12 so the file has 144 points total, then which ever process you specify with the new -o options (so value must be <= nc -1) writes to the file, otherwise collective stage is passed an empty array reference.
The process that does pass non-empty data to collective state has it's values (a 12x12 array) set to the rank of that process 
So if you set -o 1 the file should be filled with 1's
if you set -o 0, it should be filled with 0's
if you set -o 2, it should be filled with 2's
In other words the file should filled with the rank of the process you said to write on.

But I'm seeing that unless I set -o 0 the file is filled with garbage.

The strange thing is I'm not seeing the same error (that select case with the "yet to implement" fail), in fact I see no error, but the unless the non-empty array is on rank 0, it's clearly not work as it should in that file is not being correctly written, the value of the variable is garbage like it was never written to at all.

Either way I am forced to conclude that when collective_state_data is used with the multi group server, if the root process of the application code (therefore client) does not pass data, something goes wrong.

**Comment by tclune** [comment]
That root requires non-zero data is an interesting theory.   I cannot immediately think of any underlying design aspect of the server that would require such - it is pretty agnostic about such things as "root" on the client side.  Hopefully @weiyuan-jiang has a good idea on how to dig into that.

**Comment by bena-nasa** [comment]
at least I was able to reproduce something outside of our checkpoint code (that's where I hit this first) via the reproducer I posted. It does seem to be something  with root having/not having data, I spend a long time and I just can't see that I've made any other mistakes in the checkpoint code where I hit his, it really does seem to be exactly as I've described :(

**Comment by weiyuan-jiang** [comment]
I am working on it now...

**Comment by bena-nasa** [comment]
This PR https://github.com/GEOS-ESM/MAPL/pull/2559 seems to have fixed. Thanks @weiyuan-jiang 
I will close issue.
