### ISSUE TITLE
Use ESMF::ESMF CMake target

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [GEOS-ESM/MAPL#2569]
ESMF's FindESMF.cmake [now has a CMake target called `ESMF::ESMF`](https://github.com/esmf-org/esmf/commit/da8f4108c65605a4762b2383f025be3ba5fd6543) which has the benefit of avoiding ambiguity between library name and target name when invoking `target_link_libraries()`. If MAPL can move to using this target name, then when UFS Weather Model/GOCART imports MAPL, we can avoid the spurious `-lESMF` flag we've been seeing because of a mismatch in the case of the target name.

I'm happy to help however I can with making this happen, but I don't know MAPL or its build system very well.

**Comment by AlexanderRichert-NOAA** [comment]
@mathomp4 as discussed

**Comment by mathomp4** [comment]
@AlexanderRichert-NOAA I'm working on it now. There will be a series of steps needed, but hopefully can get a release of MAPL 2.44 out soon (tomorrow?). We have a hotfix first needing to go in, so that wins.
