### ISSUE TITLE
Change in bit shave behavior?

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#2655]
The modeling team is seeing some odd behavior in some diagnostics that appears to be due to a change in bitshave behavior.   I'm not recalling any changes there except a couple(?) years back when we identified that the MAPL implementation was not layout reproducible.   But even then we don't expect significantly different results from that change.  (I think)

@wmputman , @narnold1 , and @sdrabenh Should be updated if there is an update.  (And they should update this ticket with additional details - esp. MAPL versions ...)

**Comment by atrayano** [comment]
If I remember correctly, there was a change in the bit-shaving to produce more proper roundoff behavior. Hard to believe that this would have measurable impact. Could anybody provide more details (and pictures that illustrate the odd behavior)

**Comment by narnold1** [comment]
This is surface pressure, PS, output with (black) and without (red) bit shaving and deflation, based on collection int_inst_1hr_glo_C90x90x6_slv in the R21C HISTORY.rc (https://github.com/GEOS-ESM/GEOSgcm_App/blob/c0ecf07a1b8a30e985f0e3837b0eb7124834690e/HISTORY_R21C.rc.tmpl). This was run with the GEOSadas "R21C" branch.  MAPL branch is also "R21C."<p>  <img width="563" alt="image" src="https://github.com/GEOS-ESM/MAPL/assets/53791641/018ceec5-aac2-4a50-ab16-f11cad1bdd53">

**Comment by mathomp4** [comment]
The last `nbits` change I can see is #1947 which was a fix for #1941. Per @bena-nasa:

> This is obviously non-zero diff for History diagnostic output when using the nbits option in History unless your application is only being run on a single MPI processes but also obviously has no effect on the module checkpoints and MODEL non-zero diff.

This change came in with MAPL 2.35.

As far as I know it still uses the negative-bias version (bits set to zero). A while back I *added* support for netCDF quantize support but that does not key off of `nbits`. It has more complex quantization support including a less-biased "bit shaving" as well as other algorithms.

**Comment by bena-nasa** [comment]
What are people saying is wrong? I'm confused.
I fixed bug in version 2.35 because the bit shaving was being done in a non-layout reproducible way. But I don't understand what the issue is. A bit-shaved vs non-bit shaved output are different. If you make a plot where you compare these 2, they are not the same, you are throwing away data

**Comment by atrayano** [comment]
If we use the typical value nbits=12, that would translate into a difference of at most 14 Pascals for sea level pressure (bit-shaved vs not-shaved). This is in agreement with Nathan's plot

**Comment by mathomp4** [comment]
> If we use the typical value nbits=12, that would translate into a difference of at most 14 Pascals for sea level pressure (bit-shaved vs not-shaved). This is in agreement with Nathan's plot

R21C is using `nbits: 10` it looks like. I tried running this with current GEOS at C360 and I'm only seeing at most 4 Pa difference, but I only ran for a day and probably using different physics, etc.

**Comment by narnold1** [comment]
I think the issue is not a change or problem in the bit-shaving itself, but simply that the bit-shaving is too aggressive in the R21C HISTORY to close the various budgets.  A 4 Pa difference is still too coarse for some budget calculations.  We'll just have to reduce or remove the shaving for some collections.

**Comment by atrayano** [comment]
I agree with Nathan. The bit-shaving is a technique to minimize the file size, but it might impact negatively any post-run budget calculations. Mt suggestion would be to run without bit-shaving
