### ISSUE TITLE
MAPL Issue with netCDF in pFIO (OTRS Issue 0110840)

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#268]
Saulo has encountered an issue with his runs that seems odd to me. If you look at, say:
```
/gpfsm/dnb31/srfreita/geos5/exac1_72L_C360/J3xGIT_x0039_v12a_10dy5dy_forecasts/gcm_forecast_Exact_x0039.o20180105-20180105
```
You'll see output like:
```
 AGCM Date: 2018/01/04  Time: 23:37:30  Throughput(days/day)[Avg Tot Run]:   78.1   92.3   92.5  TimeRemaining(Est) 001:32:27   26.3% Memory Committed
 AGCM Date: 2018/01/04  Time: 23:45:00  Throughput(days/day)[Avg Tot Run]:   79.1  107.4  107.7  TimeRemaining(Est) 001:31:13   26.3% Memory Committed
 AGCM Date: 2018/01/04  Time: 23:52:30  Throughput(days/day)[Avg Tot Run]:   80.4  126.7  127.1  TimeRemaining(Est) 001:29:38   26.3% Memory Committed

 Writing:    122 Slices to File:  G5GMAO.geosgcm_fcst.20180105_0000z.nc4
 Writing:     55 Slices to File:  G5GMAO.geosgcm_surf.20180104_1200z.nc4
 Writing:      4 Slices to File:  G5GMAO.geosgcm_dicy.20180104_2330z.nc4
 Writing:     55 Slices to File:  G5GMAO.geosgcm_surf.20180104_1200z.nc4
 Writing:    690 Slices to File:  G5GMAO.geosgcm_tend.20180104_1200z.nc4
 Writing:    246 Slices to File:  G5GMAO.tavg3d_aer_p.20180104_1200z.nc4
pe=00116 FAIL at line=00138    NetCDF4_FileFormatter.F90                <status=13>
pe=00116 FAIL at line=00062    HistoryCollection.F90                    <status=13>
pe=00116 FAIL at line=00029    NetCDF4_put_var.H                        <status=-33>
pe=00116 FAIL at line=00224    NetCDF4_FileFormatter.F90                <status=-101>
pe=00116 FAIL at line=00029    NetCDF4_put_var.H                        <status=-33>
pe=00116 FAIL at line=00029    NetCDF4_put_var.H                        <status=-33>
pe=00116 FAIL at line=00029    NetCDF4_put_var.H                        <status=-33>
pe=00116 FAIL at line=00029    NetCDF4_put_var.H                        <status=-33>
```
And then after that, every time step you get errors:
```
 AGCM Date: 2018/01/05  Time: 00:22:30  Throughput(days/day)[Avg Tot Run]:   76.7  126.9  127.5  TimeRemaining(Est) 001:33:35   26.6% Memory Committed
pe=00116 FAIL at line=00241    NetCDF4_FileFormatter.F90                <status=-33>
pe=00116 FAIL at line=00106    HistoryCollection.F90                    <status=-33>
 AGCM Date: 2018/01/05  Time: 00:30:00  Throughput(days/day)[Avg Tot Run]:   77.6  114.2  114.6  TimeRemaining(Est) 001:32:23   28.8% Memory Committed
pe=00116 FAIL at line=00241    NetCDF4_FileFormatter.F90                <status=-33>
pe=00116 FAIL at line=00106    HistoryCollection.F90                    <status=-33>
 AGCM Date: 2018/01/05  Time: 00:37:30  Throughput(days/day)[Avg Tot Run]:   78.6  126.0  126.6  TimeRemaining(Est) 001:31:04   26.6% Memory Committed
pe=00116 FAIL at line=00241    NetCDF4_FileFormatter.F90                <status=-33>
pe=00116 FAIL at line=00106    HistoryCollection.F90                    <status=-33>
```
But as far as I can see...everything works? I see output here:
```
/gpfsm/dnb31/srfreita/geos5/exac1_72L_C360/J3xGIT_x0039_v12a_10dy5dy_forecasts/Exact_x0039_20180105_00z
```
that doesn't seem like garbage?

The fact we get history spitting out every step makes me think it might have something to do with time-averaging? I'm a bit baffled.

**Comment by mathomp4** [comment]
Further info. Saulo says he's running against the latest (v10.12.1) which is essentially what I run at night, but those tests have no output like this:
```
/gpfsm/dnb02/mathomp4/SystemTests/runs/AGCM/c48_O1_GOCART/BASELINE/run/1day/slurm-38019669.out
```
So my first guess is setup related.

**Comment by tclune** [comment]
Compounding the mystery,  the code -33 is:
```
#define NC_EBADID       (-33)   // Not a netcdf id
```
But this is happening on an _open_ statement that _creates_ the id:
```f90
      status = nf90_create(file, NF90_NOCLOBBER + NF90_HDF5, this%ncid)
```

This suggests memory corruption.

And this should be crashing the O-server as the errors propagate up the call stack which implies a missing ```_VERIFY()``` somewhere.

**Comment by tclune** [comment]
Please let me know if this can be reproduced.

**Comment by mathomp4** [comment]
> And this should be crashing the O-server as the errors propagate up the call stack which implies a missing `_VERIFY()` somewhere.

Yet, weirdly, Saulo says everything actually does complete. All the history output is good, everything. Seems like if the oserver had trouble, the netCDF output would be garbage.

**Comment by mathomp4** [comment]
> But this is happening on an _open_ statement that _creates_ the id:
> 
> ```fortran
>       status = nf90_create(file, NF90_NOCLOBBER + NF90_HDF5, this%ncid)
> ```

FYI, `NF90_HDF5` is deprecated by netCDF. We should use `NF90_NETCDF4`. That isn't causing this, though, as I looked at the netcdf source code and `NF90_HDF5` hasn't been removed yet, just deprecated with a comment. I'll put in an issue (and PR when I can test).

**Comment by bena-nasa** [comment]
His history seems fine when I use it in a c48. I will have to try to reproduce the full run.

**Comment by mathomp4** [comment]
> His history seems fine when I use it in a c48. I will have to try to reproduce the full run.

Dang it. My hope was some weird history entry.
