### ISSUE TITLE
MAPL_ConnectAll in MAPL3g needs fixing

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#2721]
When attempting to use MAPL_ConnectAll in the CapGridComp, it failed with this message:
```
<Private state with  OUTER_META_PRIVATE_STATE <MAPL::OuterMetaComponent::private> not found for this gridcomp.>
```
The fix in CapGridComp was to do this:
```
      outer_meta => get_outer_meta_from_inner_gc(gridcomp,_RC)
      call outer_meta%connect_all(cap%root_name, cap%history_name, _RC)
```
Does MAPL_ConnectAll need to be changed to use `get_outer_meta_from_inner_gc` inside, rather than `get_outer_meta`

**Comment by tclune** [comment]
@bena-nasa This issue might be fixed by #2730.

Please test after that merges.
