### ISSUE TITLE
Set sensible defaults for vertical_geom_spec in MAPL3g

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#2729]
One of the issues we found when trying to exercise cap and History3G.

It seems when making a variable spec the vertical_geom_spec had no default. This meant that apparently two variables that didn't even have a vertical dimension were being flagged as unable to connect when testing the can_connect capability since the checking routine was claiming they had different vertical_geom_specs.

**Comment by tclune** [comment]
I see two possibilities.   Make a default presumably (NONE ==> Surface) *or* require specification of vertical.

To me, "surface" does not seem default-ish, so I lean towards forcing a field to specify (with MIRROR eventually being an option).
