### ISSUE TITLE
History 3G: Parse expressions, add to import state

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#2757]

**Comment by bena-nasa** [comment]
Now that we can import simple fields, another step is to support expressions. By this I mean if the value for `expr:` for an item in the `var_list` is not a single field we need to parse the expression, determine what are the actual fields in the expression, and add those to the import state of the HistoryCollectionGridComp we are in. The current parser does have a routine to take an expression and return the variables in the expression in a gFTL string vector I believe.

Note that there are a few issues with this.
1. How do you know that you don't have just a single field. My strategy in the old History was to determine if string had something that could not be in a name, basically any of these characters `+-/*()`. Klugey but I can't really think of a better way...
2. Since we will be denote fields with `expr: component_name.field_name` we need to check if the current expression parser has issues with field names with a "." in them and because it also looks for constants in the expression i.e. `1.0, 0.9, .8` etc..., just need to check
3. Probably should rename MAPL_NewArthParser.F90 to something better, could use some unit testing etc in the long term...

**Comment by tclune** [comment]
We may have to compromise on syntax if "." becomes problematic.  ":" should be safe.   "/" is ideal, but we know that would be a problem for the expressions.
