### ISSUE TITLE
Simple fix for identifying bad HISTORY lines

### ISSUE THREAD

**Issue by mmanyin** [GEOS-ESM/MAPL#276]
If HISTORY.rc has a bad field name  (e.g. typo, or the field doesn't exist), the model aborts and just refers you to a VERIFY  line in  MAPL_StateGet  within  MAPL_HistoryGridCompMod. This can be time-consuming to figure out what's going wrong.  Please check for SUCCESS in MAPL_StateGet, and print a warning that includes the **field name**,  before calling VERIFY. That will make it obvious to the user what the problem field is. Thanks!

**Comment by tclune** [comment]
Agreed.   I'll take this one on.

**Comment by lizziel** [comment]
Thanks @tclune. This update would be fantastic for GCHP users as well. Please include a check for if the name is accidentally listed twice.
