### ISSUE TITLE
run_children (an overload of MAPL_RunChild) needs to be recursive

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#2761]
This procedure seems to need to be declared as recursive once you have 3 level hierarchy where multiple components call MAPL_RunChildren

**Comment by tclune** [comment]
Weird.  Several of our test_scenarios should have at least that much depth.   And gfortran usually catches this early ...   Looking into it.

**Comment by tclune** [comment]
Ah.  It is recursive inside of OuterMetaComponent, but not in the top-level `MAPL_Generic` interface.
