### ISSUE TITLE
Update MAPL_NewArthParserMod to use v2 StringVector

### ISSUE THREAD

**Issue by darianboggs** [GEOS-ESM/MAPL#2770]
The `parser_variables_in_expression` function in `base/MAPL_NewArthParser.F90` uses gFTL v1 of StringVector for the `parser_variables_in_expression`. This makes it incompatible with some new code that uses gFTL v2 StringVector with calls to `parser_variables_in_expression`. `MAPL_NewArthParserMod` should be updated to use gFTL v2 StringVector, and existing code dependent on it should be updated to gFTL v2 StringVector.

**Comment by tclune** [comment]
Fixed in #2784
