### ISSUE TITLE
Porting LocStream Factory into MAPL3

### ISSUE THREAD

**Issue by metdyn** [GEOS-ESM/MAPL#2781]
Porting Locstream factory into MAPL3 is a necessary step to migrate sampler codes to mapl3.

**Comment by tclune** [comment]
Just in case the change points are not obvious:

1. GeomManager and associated factories live in `./geom_mgr`.   Follow the pattern there for LatLon, though I expect your use case is even simpler in some respects.
2. I want unit tests in there too, but we don't want unit tests to read files if we can avoid it.   Consider a variant constructor for LocStream that accepts a list of lons and lats.  That will be easier to test.
3. We will want an extension to the regrid scenario in `./generic3g/tests/scenarios/regrid` that include a LocStream use case.  Should be trivial - just makes sure the logic is exercised in the broader sense.
