### ISSUE TITLE
excessive print statements to stdout from MAPL OpenMP_Support.F90

### ISSUE THREAD

**Issue by junwang-noaa** [GEOS-ESM/MAPL#2853]
When we run with GOCART in UFS weather model, we noticed excessive print statements in the model run output file:

41:  OpenMP_Support.F90         536 splitting component: <GOCART2G>
 57:  OpenMP_Support.F90         536 splitting component: <GOCART2G>
 43:  OpenMP_Support.F90         536 splitting component: <GOCART2G>
 49:  OpenMP_Support.F90         536 splitting component: <GOCART2G>
 47:  OpenMP_Support.F90         536 splitting component: <GOCART2G>
 59:  OpenMP_Support.F90         536 splitting component: <GOCART2G>
 53:  OpenMP_Support.F90         536 splitting component: <GOCART2G>
 51:  OpenMP_Support.F90         536 splitting component: <GOCART2G>

This becomes a problem when we run high resolution tests with large number of tasks. Further check shows that the prints are from MAPL OpenMP_Support.F90:

https://github.com/GEOS-ESM/MAPL/blob/df6786ca32f75b4848743301f5a31e6a6288622e/generic/OpenMP_Support.F90#L540-L541

This line seems a debug prints, could this line be commented out or only run in debug mode? Thanks

**Comment by junwang-noaa** [comment]
@tclune @weiyuan-jiang FYI.

**Comment by tclune** [comment]
@weiyuan-jiang Please either delete or convert these to use pflogger.

**Comment by weiyuan-jiang** [comment]
@junwang-noaa which tag are you using now ? I can patch your tag and also remove the extra print for the future release.

**Comment by junwang-noaa** [comment]
We are using MAPL 2.40.3.

**Comment by mathomp4** [comment]
So that'd be a new MAPL v2.40.5 as we already have v2.40.4. I can work with @weiyuan-jiang to get that released.

(Note: [v2.40.4](https://github.com/GEOS-ESM/MAPL/releases/tag/v2.40.4) was a minor update for `find_package(MAPL)`.)

**Comment by weiyuan-jiang** [comment]
The version is so close  that we probably don't need an extra patch. Just move ahead with new tag. [Here] (https://github.com/GEOS-ESM/MAPL/pull/2854)

**Comment by mathomp4** [comment]
@junwang-noaa Thanks to @weiyuan-jiang we now have a [MAPL v2.40.5](https://github.com/GEOS-ESM/MAPL/releases/tag/v2.40.5). The only real change is the removal of these prints:

https://github.com/GEOS-ESM/MAPL/compare/v2.40.4...v2.40.5

**Comment by junwang-noaa** [comment]
Thank you all!

**Comment by junwang-noaa** [comment]
@mathomp4 Another question, may I ask if you have a major release version with this change? There is request in UFS to install MAPL 2.43.0, which I believe does not contain this fix in this issue. Thanks

**Comment by mathomp4** [comment]
@junwang-noaa MAPL v2.46.2 has the fix, but if you can't move to that, we could issue MAPL v2.43.3 with the fix.

**Comment by mathomp4** [comment]
@junwang-noaa Sounds good. If you can't move to it (needs MAPL 8.6.1 which is in spack-stack v1.7), then we can backport for you.
