### ISSUE TITLE
Add support for "mirror" of ungridded dims in MAPL3

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#2900]
The default should be *no* ungridded dims, but we want an option to specify that the ungridded dims of a FieldSpec should come from whatever field to which it is ultimately connected.

In this case, only imports should be allowed to specify mirror.   But for now we will allow exports.    Other mirror things make sense for ExtData, but not this one.

@bena-nasa @darianboggs

**Comment by bena-nasa** [comment]
Fixed by PR #2907
