### ISSUE TITLE
Add VM_PARENT flag to GridCompCreate in MAPL3 

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#2948]
Currently MAPL3 is using the default value for the `contextFlag` argument.   Concerns about memory footprint suggest that we instead explicitly use `ESMF_CONTEXT_PARENT_VM` unless petList is present.

```
contextFlag = ESMF_CONTEXT_PARENT_VM
if (present(petList) contextFlag = ESMF_CONTEXT_OWN_VM
call ESMF_GridCompCreate(..., contextFlag)
```

**Comment by darianboggs** [comment]
Got it.
