### ISSUE TITLE
Fix MAPL_HConfigMatch

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#2996]
This procedure needs to use YAML tags to produce correct results.   

Currently there are 2 disable tests in Test_HConfigMatch.pf that are disabled.  (See `@disable`)  These should be activated and the procedure should be fixed.

**Comment by mathomp4** [comment]
Hmm. Would this require us to move to ESMF 8.7? I want to say the HConfig match stuff was put into a branch that was never on 8.6... I'll ask at CUPID today.
