### ISSUE TITLE
How to specify export bundle fields in HISTORY.rc

### ISSUE THREAD

**Issue by lizziel** [GEOS-ESM/MAPL#30]
I have a general MAPL history question. I have code below that creates an ‘MSA’ field in the ‘AEROSOLS’ bundle within the ‘AERO’ export.

In SetServices:
```
call MAPL_AddExportSpec(GC,                    &
       SHORT_NAME = 'AERO',                        &
       LONG_NAME  = 'aerosol_mass_mixing_ratios',  &
       UNITS      = 'kg kg-1',                     &
       DIMS       = MAPL_DimsHorzVert,             &
       VLOCATION  = MAPL_VLocationCenter,          &
       DATATYPE   = MAPL_StateItem, __RC__)
```

In Initialize:
```
call ESMF_StateGet(expChem, 'AERO', aero, __RC__)
aero_state_aerosols = ESMF_FieldBundleCreate(name='AEROSOLS', __RC__)
call MAPL_StateAdd(aero, aero_state_aerosols, __RC__)
call ESMF_StateGet(INTERNAL,’GOCART::MSA_ForBundle', FIELD, __RC__ )
fld = MAPL_FieldCreate(FIELD, name=’MSA’, __RC__)
call MAPL_FieldBundleAdd(aero_state_aerosols, fld, __RC__)
```

My question is how do I output the ‘MSA’ field via History? Is there syntax for specifying export/bundle/field? I realize perhaps outputting the internal state here is a better option, but I would like to know how to get at the AERO export contents directly.

**Comment by lizziel** [comment]
@bena-nasa Following our discussion last week I tried adding each of these to HISTORY.rc, specifying gridcomp 'GOCART': 
'AEROSOLS%MSA'
'AERO%AEROSOLS%MSA'
'AERO%MSA'
'MSA'
'AERO'

All of these combinations failed with MAPL_StateGet errors in History. Do you know for certain that export bundle fields can be output via MAPL History?

**Comment by bena-nasa** [comment]
> call MAPL_AddExportSpec(GC,                    &
>        SHORT_NAME = 'AERO',                        &
>        LONG_NAME  = 'aerosol_mass_mixing_ratios',  &
>        UNITS      = 'kg kg-1',                     &
>        DIMS       = MAPL_DimsHorzVert,             &
>        VLOCATION  = MAPL_VLocationCenter,          &
>        DATATYPE   = MAPL_StateItem, __RC__)

**Comment by bena-nasa** [comment]
Lizzie,
First, we never add states to state like that in the addexport, importspec
In SetServices you create the bundle in the export state:
```
call MAPL_AddExportSpec(GC,                    &
       SHORT_NAME = 'AERO',                        &
       LONG_NAME  = 'aerosol_mass_mixing_ratios',  &
       UNITS      = 'kg kg-1',                     &
       DIMS       = MAPL_DimsHorzVert,             &
       VLOCATION  = MAPL_VLocationCenter,          &
       DATATYPE   = MAPL_BundleItem, __RC__)
```

**Comment by lizziel** [comment]
@bena-nasa My example code is cut and pasted from GOCART in a fairly recent version of GEOSgcm. I did not edit it beyond omitting non-relevant lines of code. It seems to work okay for exporting the aerosol bundle from GOCART to Radiation since it has been in place for a while.  I believe Elliot Sherman is working to rewrite GOCART to clean up the code. Perhaps this is an area that could be made more standard?

I am going to close this issue since it is no longer a problem for me. I am getting the array values I want to History via other means.
