### ISSUE TITLE
Vertical flipping in ExtData fails for edge-aligned 3-D arrays

### ISSUE THREAD

**Issue by sdeastham** [GEOS-ESM/MAPL#301]
When reading in data, ExtData gives grid-centered data indexing of 1:LM, but gives grid-edge data indexing of 0:LM. The ExtData vertical flipping subroutine however assumes a 1:LM indexing. This results in memory corruption if a grid-centered array needs to be flipped.

**Comment by mathomp4** [comment]
Fixed by #302
