### ISSUE TITLE
Odd time print format from Cap

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#3034]
Per @briardew, he was wondering about these prints from Cap:

```
CAP: INFO: Read CAP restart properly, Current Date =   2019/08/08
CAP: INFO:                            Current Time =   03/00/00 
```

Namely: Why is the time represented by slashes. My only guess is that it was that way long ago in MAPL and, well, we just never changed it.

The code would be simple to change:

https://github.com/GEOS-ESM/MAPL/blob/c7926cd3ce4c0bf66fd01f54b0c50ce2ec9900fa/gridcomps/Cap/MAPL_CapGridComp.F90#L1852-L1853

The question is: Should we? I appeal to @atrayano and @bena-nasa to know if they know of anyone or any scripts that depend on this format?

I'll even mention at @rtodling in case he knows of an ADAS script that depends on this output for any reason.

And, why not, I'll mention @tclune because everyone else has been. 😄

**Comment by atrayano** [comment]
I ready do not think anybody cares... Cannot imagine that we parse the time from this output. My vote is to change it.

**Comment by briardew** [comment]
If we want to go real crazy, we could also change the date to be 2019-08-08
to be more ISOy. Agree with Atanas that likely no one cares except me.

**Comment by mathomp4** [comment]
Just for @tclune benefit, I did communicate to @briardew that MAPL3 will be using ISO time format.

I suppose if we wanted, we could conver this logging output to ISO...
