### ISSUE TITLE
Fill in wiki on raw io benchmark utility

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#3050]
I've made page as requested by NCCS staff on how to use the low-level IO benchmarking tools we have in MAPL

I've filled my bits about the `checkpoint_simulator.x` and `restart_simulator.x` and will add stuff about how to profile where possible with `ExtDataDriver.x` at a later date.

@tclune made his own benchmark
https://github.com/GEOS-ESM/MAPL/tree/main/benchmarks/io/raw_bw

There is a section for him to fill about how to use his tool at his leisure:

https://github.com/GEOS-ESM/MAPL/wiki/MAPL-IO-Benchmarks#raw-io-benchmark

**Comment by mathomp4** [comment]
Note to @bena-nasa and @tclune, I hope to have MAPL 2.48.0 out soon (see #3049). So the wikis can point to that release instead of `develop`...hopefully by tomorrow?

**Comment by tclune** [comment]
I've put a bit into my section, but probably won't add much more without external pressure.
