### ISSUE TITLE
Check VerticalDimSpec based on name

### ISSUE THREAD

**Issue by darianboggs** [GEOS-ESM/MAPL#3054]
A `VerticalDimSpec` value is stored as a string in the `ESMF_Info` object in a `ESMF_Field` object. To check the `VerticalDimSpec` value of an `ESMF_Field` requires a string match to a string literal. The string literal can be stored in a parameter so that multiple string literals are created for the same `VerticalDimSpec`, but then matching requires knowing the parameter name. There is no guarantee that the parameter name or string literal match the name of the relevant `VerticalDimSpec`. This seems fragile.

Two options:
1. Store the string literals in parameters in the module that defines type(VerticalDimSpec). The parameters would be used to create the `ESMF_Info` for the VerticalDimSpec objects, and the parameters used for the creation would be public for the sake of comparison. This still requires that the parameter names be known, but it does protect against changes in the string in the `ESMF_Info` object.
2. Define type-bound logical function with a string argument that the verifies that the string corresponds to the `VerticalDimSpec`.
```
type :: VerticalDimSpec
   character(len=:), allocatable :: name_
...
contains
   module procedure :: matches => matches_spec
...
contains

   logical function matches_spec(this, string)
      class(VerticalDimSpec), intent(in) :: this
      character(len=*), intent(in) :: string
      
      matches_spec = (this%name_ == string)
      
   end function matches_spec
```

**Comment by tclune** [comment]
How would option (2) work?  At the point one is examining the info object the dim spec object would generally not be available.  And if it was available, there is no reason to use the info object.

**Comment by tclune** [comment]
I also don't understand this sentence:

>The string literal can be stored in a parameter so that multiple string literals are created for the same VerticalDimSpec, but then matching requires knowing the parameter name.
