### ISSUE TITLE
Move VerticalDimSpec

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#3106]
Routines in ./field_utils need access but VerticalDimSpec lives in generic3g.    Module should be moved - probably to field_utils.  Or maybe into ./vertical which should then be moved out of generic3g.

Currently important strings are instead duplicated across modules.

Another solution could be to move the named constants into ./shared.

**Comment by mathomp4** [comment]
@tclune How about this one? From what I see, `VerticalDimSpec` is now in `generic3g/specs`.

**Comment by tclune** [comment]
Well, we really want to move it out of generic3g altogether, but ... it gets complicated to tease the dependencies apart in this case. 

Closing - will arise again organically when we clean for release.
