### ISSUE TITLE
Grid detection heuristics in MAPL_LatLonGridFactory need improvement, allow periodic grid when does not span full latitude

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#3175]
I will add more as I figure out more, but @mfmehari and @zhaobin74 reported they had files that were being regridded and results in "missing" points at the dateline. The files are evenly spaced in longitude and clearly are `GC` in our convention. The latitude is less clear, but when regridded to cube beyond some resolution it would indeed have the dateline full of missing values when I reproduced this.

I put a bunch of prints in. It decides it is a `GC` in longitude and `XY` in latitude. Now because of this the heuristic set the grid to non-periodic, so now if a destination point falls "outside" the grid which is that last half delta, it will not be mapped to any source cells.

I need to look at this, we clearly need allow for periodic grids, even if they do not span the full latitude.

**Comment by bena-nasa** [comment]
![SLP_in_out_c90](https://github.com/user-attachments/assets/497fbcde-3a91-42f3-b23c-14a9d89430c2)

**Comment by tclune** [comment]
I agree with analysis, but am astounded that we are only now encountering this.

**Comment by bena-nasa** [comment]
I am too

**Comment by bena-nasa** [comment]
@zhaobin74 pointed out that these files have a `lat_bnds` and `lon_bnds` variable, so the grid factory needs to additionally detect these to determine PC/PE/DC/DE etc... if available. If not we fall back on the usual heuristics
