### ISSUE TITLE
How do you actually use this Fortran interface to udunits

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#3198]
@darianboggs @tclune 
I am trying to use UDUNITS in MAPL2 (develop branch), the Fortran interface you made. Basically, I get the units of something and I want to ask, can this be converted to a pressure in some units, i.e. can whatever this unit is be converted to say pascals for example. At first tried in real code, but it says it can't convert the same thing that the UDUNITS test said it can...
So then I made this simple code that asks if it can one convert kilometers to meters just like one of the tests I saw:

```
program test_udunits
use udunits2f, UDUNITS_are_convertible => are_convertible, &
    initialize_udunits => initialize, finalize_udunits => finalize
implicit none
integer :: status

character(len=:), allocatable :: src_units, dst_units

call initialize_udunits(rc=status)
print*,status
src_units = "KM"
dst_units = "M"
print*,UDUNITS_are_convertible(src_units, dst_units, rc=status)
print*,status
call finalize_udunits()

end program
```

Here is the output, says it can't convert which makes no sense since this is one of the tests in the UDUNITS directory...
```
           0
 F
           0
```

What am I doing wrong? Looking at the tests and use in MAPL3 seems like this is the sequence one calls...

Any documentation about the interface and how to use? Clearly I'm missing something basic. I figured out something in that I probably need to set `UDUNITS2_XML_PATH` in my environment from looking at the CMake file in the UDUNITS test directory. I tried setting an environment variable that is both the full path to the `udunits2.xml`  file in baselibs as well as just the directory. I'm doing this on bucy. I've even tried adding the `path=...` argument to `initialize_udunits` and point it to the xml file.

All of those give this output which is not working:
```
         102
 F
           1
```
So I'm not sure what I'm missing

**Comment by bena-nasa** [comment]
and I'm stupid. Helps if you set the right path....

**Comment by tclune** [comment]
I think there is an environment variable that controls where the database for udunits is stored.   A very annoying artifact.

If you look in the cmake logic for the tests you are referencing it will probably jump out at you.
