### ISSUE TITLE
nf90_get_att returning character variables with c null terminator

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#3201]
While trying to use a NetCDF4 file provided by a user I was hitting an error that we ultimately traced to the fact that `nf90_get_att` was returning a character string with a C null terminator at the end. We are not sure if it is this file but we do need to protect against this. I will make a PR.

**Comment by weiyuan-jiang** [comment]
I think we should use   "pfio_get_att_string"  instead of  "nf90_get_att" . But I found many string version of   nf90_get_att .
