### ISSUE TITLE
Refactor Variable class to that you can retrieve specify attribute types

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#3210]
I doing some work and it was helpful to have specific procedures in the `Variable` class in PFIO to retrieve attributes of specific types. Note there was a helper procedure in `FileMetaDataUtilities.F90` that given a `FileMetaDataUtilities` class, a variable name, and an attribute name you could retrieve an attribute of a specific type but no way, given a `Variable` to retrieve. 

It makes sense to do a simple refactor and move some of this into the `Variable` class so that this class can have the functionality to get attributes of specific types and the existing interfaces  to `FileMetadataUtilities` can remain unchanged.

I'm just making an issue for the PR I'm going to do as I've already done the refactor.

Will make more sense when one sees the PR.

**Comment by weiyuan-jiang** [comment]
I am a little bit confused. I think the original get_attribute can just did what you added
