### ISSUE TITLE
(minor) bug in UDSystem.F90

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#3253]
I got the following error with a new use case:
```
Runtime Error: /Users/tclune/swdev/GEOS-ESM/MAPL3/udunits2f/UDSystem.F90, line 420: Reference to OPTIONAL argument RC which is not PRESENT
```
This should not happen.  If the RC is not present then the procedure should not touch it.

The underlying issue is that this file uses custom macros rather than the usual `_RC`.   It needs to be modified to protect references to the rc argument with `if (present(rc))`

If udunits is on develop already - it should be fixed there.

**Comment by darianboggs** [comment]
OK. I think I can get rid of the custom macros, and then, use the macros in `./include` instead.

**Comment by darianboggs** [comment]
PR merged
