### ISSUE TITLE
Subroutine MAPL_FieldBundleAddField in MAPL_Base.F90

### ISSUE THREAD

**Issue by JulesKouatchou** [GEOS-ESM/MAPL#34]
The subroutine MAPL_FieldBundleAddField has multiflag (logical input variable) as an optional argument. Inside the routine, we have the call:

          call ESMF_FieldBundleAdd(Bundle, fields, multiflag=multiflag, RC=status)

without checking first if multiflag is present. I assume that the compiler will set it to .FALSE. which is the default value for ESMF_FieldBundleAdd. I could be better to do the following:

    logical                                 :: multiflag_

    multiflag_ = .FALSE.
    if (PRESENT(multiflag)) THEN
       multiflag_ = multiflag
    ENDIF
    call ESMF_FieldBundleAdd(Bundle, fields, multiflag=multiflag_, RC=status)

**Comment by tclune** [comment]
No.   In Fortran if a "non-present" optional argument is used as an actual argument in a subsequent invocation, then it is also non-present in the 2nd procedure.   Thus there is no need to check these at each level - so long as the argument remains optional the whole way down the calling sequence.
