### ISSUE TITLE
MPI_Finalize issue with GEOSgcm on Haswell/SLES12

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#346]
So, this is fun. @sdrabenh has found another MPI_Finalize issue with GEOS. If you run at c48 on the Haswell/SLES12 system:
```
pe=00082 FAIL at line=00712    MAPL_Cap.F90                             <status=806970127>
pe=00082 FAIL at line=00183    MAPL_Cap.F90                             <status=806970127>
pe=00082 FAIL at line=00032    GEOSgcm.F90                              <status=806970127>
Abort(109856960) on node 82 (rank 82 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 109856960) - process 82
```
I can confirm this at 0-days. Now, not much is printing here because our "workaround" for the issue with MPT actually hides the errors. If you undo our workaround:
```
Abort(806970127) on node 18 (rank 18 in comm 0): Fatal error in PMPI_Finalize: Other MPI error, error stack:
PMPI_Finalize(367)...............: MPI_Finalize failed
PMPI_Finalize(278)...............:
MPID_Finalize(1069)..............:
MPIDI_OFI_mpi_finalize_hook(1626): OFI domain close failed (ofi_init.c:1626:MPIDI_OFI_mpi_finalize_hook:Device or resource busy)
>> Error << /usr/local/intel/2020/compilers_and_libraries_2020.0.166/linux/mpi/intel64/bin/mpirun  -np 96 ./GEOSgcm.x : status = 15; at /gpfsm/dswdev/mathomp4/Models/GEOSgcm-SLES12-stock/GEOSgcm/install-Release-Haswell/bin/esma_mpirun line 376.
```
So nuts.

**Comment by mathomp4** [comment]
I got bored and even tried adding:
```fortran
         call ESMF_Finalize(endflag=ESMF_END_KEEPMPI, rc=ierror)
         _VERIFY(ierror)
```
before the `MPI_Finalize()` call, but no help. Dangit.

**Comment by atrayano** [comment]
Matt,

I am not surprised. The mail reason we do not call ESMF_Finalize (we should, but please see below), is that deep inside ESMF_Finalize there a call to ESMF_VMFinalize. And in there, among other things, there is cleanup section which destroys ESMF objects. And because of the pointer sharing this causes tons of issues for us

**Comment by mathomp4** [comment]
@atrayano I know, but it was a hope. Did do anything.

**Comment by mathomp4** [comment]
Another (possible) data point. Searching the web makes me think this sort of error is because there are still MPI_Request outstanding when we MPI_Finalize.

So, I thought, "maybe restart writing uses them?" and turned off the final checkpointing, but I still get this error on Finalize.

**Comment by mathomp4** [comment]
Also, note, you can get this with C48 on 1 node of Haswell and running 1x6 and for 0days. So you don't need much to show this. Just all of GEOS

**Comment by mathomp4** [comment]
Okay. Another issue incoming for @weiyuan-jiang

**Comment by mathomp4** [comment]
Sadly, the nice fix from @weiyuan-jiang for #347 doesn't help this issue. Dangit.

**Comment by tclune** [comment]
Do the unit tests still fail with his "fix"?

**Comment by tclune** [comment]
Sorry - I see that answered in the PR discussion.

**Comment by mathomp4** [comment]
We fixed this I'm pretty sure.
