### ISSUE TITLE
MPI_Finalize issue with pFIO Tests: DirectoryService

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#347]
In trying to debug #346, I decided to run `make tests` on a Haswell/SLES12 node and saw:
```
The following tests FAILED:
	  1 - pFIO_tests (Failed)
	  2 - pFIO_tests_mpi (Failed)
	  3 - pFIO_tests_simple (Failed)
	  4 - pFIO_tests_hybrid (Failed)
Errors while running CTest
```
So, let's look at `pFIO_tests`:
```
(1145)(master) $ mpirun -np 8 src/Shared/@MAPL/GMAO_pFIO/tests/pFIO_tests
srun: cluster configuration lacks support for cpu binding
................................................................... WARNING: no serverthread
.............
.
Time:         0.049 seconds

 OK
 (81 tests)
Abort(806970127) on node 7 (rank 7 in comm 0): Fatal error in PMPI_Finalize: Other MPI error, error stack:
PMPI_Finalize(367)...............: MPI_Finalize failed
PMPI_Finalize(278)...............:
MPID_Finalize(1069)..............:
MPIDI_OFI_mpi_finalize_hook(1626): OFI domain close failed (ofi_init.c:1626:MPIDI_OFI_mpi_finalize_hook:Device or resource busy)
```
So, it "succeeds" at every test, but it fails at the end. But this isn't all of GEOS, just pFIO.

**Comment by mathomp4** [comment]
Per @tclune I ran:
```
mpirun -np 8 src/Shared/@MAPL/GMAO_pFIO/tests/pFIO_tests -f Unlimited
mpirun -np 8 src/Shared/@MAPL/GMAO_pFIO/tests/pFIO_tests -f Local
...
```
through all the tests. And exactly *one* triggers it, `DirectoryServiceMod`:
```
(1177)(master) $ mpirun -np 8 src/Shared/@MAPL/GMAO_pFIO/tests/pFIO_tests -f DirectoryServiceMod
srun: cluster configuration lacks support for cpu binding
.......
Time:         0.019 seconds

 OK
 (7 tests)
Abort(806970127) on node 5 (rank 5 in comm 0): Fatal error in PMPI_Finalize: Other MPI error, error stack:
PMPI_Finalize(367)...............: MPI_Finalize failed
PMPI_Finalize(278)...............:
MPID_Finalize(1069)..............:
MPIDI_OFI_mpi_finalize_hook(1626): OFI domain close failed (ofi_init.c:1626:MPIDI_OFI_mpi_finalize_hook:Device or resource busy)
```

**Comment by weiyuan-jiang** [comment]
I have a fix for DirectoryServiceMod on the branch feature/wjiang/io_restructure. Instead of full pull request, I will pick the relative files to update MAPL.

**Comment by mathomp4** [comment]
Made a typo above. It's `DirectoryService` is the name of the test of course

**Comment by mathomp4** [comment]
Another thing I can say, I removed everything from `tests/Test_DirectoryService.pf` except for `test_publish` and even that seems to trigger this issue:
```
(1230)(master) $ mpirun -np 8 src/Shared/@MAPL/GMAO_pFIO/tests/pFIO_tests -f DirectoryService
srun: cluster configuration lacks support for cpu binding
.
Time:         0.022 seconds

 OK
 (1 test)
Abort(806970127) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Finalize: Other MPI error, error stack:
PMPI_Finalize(367)...............: MPI_Finalize failed
PMPI_Finalize(278)...............:
MPID_Finalize(1069)..............:
MPIDI_OFI_mpi_finalize_hook(1626): OFI domain close failed (ofi_init.c:1626:MPIDI_OFI_mpi_finalize_hook:Device or resource busy)
```

**Comment by tclune** [comment]
Memory starting to come back.   There really needs to be  a FINAL method for the DirectoryService type.   FINAL had issues the last time I played with it (years ago).

The tests are incomplete in this sense and may not actually be as relevant as I hoped.  But either way, fix the tests first and then see about the implementation.

**Comment by mathomp4** [comment]
Hmm. Well perhaps the lessons learned with this could help with the full model?

And I'm guessing there's no way to run MAPL and bypass pFIO at this point? It's sort of fully-baked in, right?

**Comment by weiyuan-jiang** [comment]
Why I can't run the tests just with MAPL component? "make tests" just hang there on sles12 ( don't know what hapened to sles 11) . I am checking out the full gcm model to try again

**Comment by mathomp4** [comment]
> Why I can't run the tests just with MAPL component? "make tests" just hang there on sles12 ( don't know what hapened to sles 11) . I am checking out the full gcm model to try again

@weiyuan-jiang You should be able to. Let me try...

**Comment by mathomp4** [comment]
Yeah, I just did:
```
git clone  git@github.com:GEOS-ESM/MAPL.git
cd MAPL
mepo init && mepo clone
```
to get the repo. Then after sourcing the g5_modules:
```
cmake .. -DBASEDIR=$BASEDIR/Linux -DCMAKE_BUILD_TYPE=Release
make -j pFIO_tests
(1255)(master) $ mpirun -np 8 GMAO_pFIO/tests/pFIO_tests -f DirectoryService
srun: cluster configuration lacks support for cpu binding
.......
Time:         0.018 seconds

 OK
 (7 tests)
Abort(806970127) on node 5 (rank 5 in comm 0): Fatal error in PMPI_Finalize: Other MPI error, error stack:
PMPI_Finalize(367)...............: MPI_Finalize failed
PMPI_Finalize(278)...............:
MPID_Finalize(1069)..............:
MPIDI_OFI_mpi_finalize_hook(1626): OFI domain close failed (ofi_init.c:1626:MPIDI_OFI_mpi_finalize_hook:Device or resource busy)
Abort(806970127) on node 7 (rank 7 in comm 0): Fatal error in PMPI_Finalize: Other MPI error, error stack:
PMPI_Finalize(367)...............: MPI_Finalize failed
PMPI_Finalize(278)...............:
MPID_Finalize(1069)..............:
MPIDI_OFI_mpi_finalize_hook(1626): OFI domain close failed (ofi_init.c:1626:MPIDI_OFI_mpi_finalize_hook:Device or resource busy)
```

**Comment by weiyuan-jiang** [comment]
I could run "make tests" before and run all the tests. But now even I follow your steps, I could not launch the tests. Would you please try hotfix/wjiang/free_directory_win  for me ? I am not sure if this will fix the issue.

**Comment by weiyuan-jiang** [comment]
wait! I may introduce a bug.

**Comment by weiyuan-jiang** [comment]
I think I fixed this issue. I have suspected that the Directory service has something to do with the MPI_Finalize failure. But after I fixed it, the error is still there. It turns out I forgot to clean up the Mutex inside Directory Service. Thanks @mathomp4 for pointing out the simple tests

**Comment by weiyuan-jiang** [comment]
@bena-nasa @atrayano  , In the subroutine MAPL_LocStreamMod.F90, there is a call MPI_WIN_Create.   I am not sure if it is ever called. If it is, then we need to add a call MPI_free_mem. Please refer DirectoryService.F90 or MpiMutex.F90 at GMAO_pFIO

**Comment by weiyuan-jiang** [comment]
I saw the default is TWO_SIDED_COMM, so that is not THE problem so far

**Comment by mathomp4** [comment]
I'm pretty sure we fixed this. Closing.
