### ISSUE TITLE
Error handling in MAPL_Profiler

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#360]
The current MAPL profiler has no error checking currently.
For example BaseProfiler.F90:
```
   subroutine start_name(this, name)
      class(BaseProfiler), target, intent(inout) :: this
      character(*), intent(in) :: name

      class(AbstractMeter), pointer :: t
      class(AbstractMeterNode), pointer :: node
      class(AbstractMeter), allocatable :: m

      if (this%stack%empty()) then
         block
           use MPI
           integer :: rank, ierror
           call MPI_Comm_rank(MPI_COMM_WORLD, rank, ierror)
           if (rank == 0) then
             print*,'start name should not be empty: ', __FILE__,__LINE__,name
           end if
         end block
         return
      else
```
This is a spot where it is return because of error that needs to be trapped. I'm sure there are others but this is the one I spotted so far.

**Comment by tclune** [comment]
OK - this is the trigger to move the MAPL exception handling files into a new subdirectory.   @weiyuan-jiang  is calling it "shared".  The other possible name is "utils" and "utilities".

Once that is done, then MAPL profiler (and pFIO) can be updated to use the usual mechanisms.   I suspect there are numerous small issues that I'd want to get right, so be prepared for multiple iterations on the PR review.

**Comment by mathomp4** [comment]
Closing. Open new issues if missed routines are found.
