### ISSUE TITLE
Need a "state statistics" printer

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#378]
In ESMFL_Mod.F90 there are some older routines:  StateDiff and BundleDiff which operate on 2 states or 2 bundles respectively.

What is needed now is something which just prints statistics for a single state.  It could function similarly, though I see opportunities for improving and generalizing on the original approach.

The idea is to loop over fields in the state and print out a one line summary for each field.    For now:  name, max, min, avg, stddev.  (not sure these really make sense for a highly-stratified 3D variable)

When you have something ready for testing, share with @gmao-esherman 

I'm assigning this to @weiyuan-jiang , but am notifying @atrayano and @bena-nasa in case they have additional insights to bear on the issue.     E.g, did I miss the interface that does this arleady.

**Comment by weiyuan-jiang** [comment]
@tclune @gmao-esherman The branch can print out the statistics https://github.com/GEOS-ESM/MAPL/tree/feature/wjiang/%23378_statistcs_print .  Basically, it is a ESMFL_diff call without destination argument. But I prefer the new interface ESMFL_statistics  which only take one argument. Let  me know if it really prints out what you want. Please comment on it  @bena-nasa @atrayano

**Comment by tclune** [comment]
Thanks - I have glanced through the implementation - looks like it should suffice for now.   Arlindo may come back with additional requirements.

**Comment by tclune** [comment]
Oh.  Just realized.   These procedures need to be extended for 4D variables.  :-)

Probably the best thing is to treat the 4th dimension as a loop over additional variables and just modify the var name with "_001", "_002" ...

**Comment by weiyuan-jiang** [comment]
Now it can print 4d var statistics. @atrayano Can you confirm the change ( from == to >=)  here ? https://github.com/GEOS-ESM/MAPL/blob/19aa3765a173a326ca7e8c437763255c4d93d890/MAPL_Base/ESMFL_Mod.F90#L2882 ?

**Comment by weiyuan-jiang** [comment]
@gmao-esherman  Can you give this branch a try? If that is what you need, then I will make a PR.

**Comment by gmao-esherman** [comment]
Sorry for the late reply. I can't get the call to work. I am tying ESMFL_statistics(import, __RC__), and StateStatistics(import, __RC__) and both fail to build. I am on the latest develop branch of MAPL.

**Comment by atrayano** [comment]
I think ESMFL_Statistics needs to made public.

Elliot, could you try this really quick: add a line around 65 in ESMFL_Mod.F90

public MAPL_Statistics

and try again. We should create a fix shortly
