### ISSUE TITLE
Xarray issue with repeated dimension in output var anchor; request to rename dim

### ISSUE THREAD

**Issue by lizziel** [GEOS-ESM/MAPL#38]
Variable 'anchor' in MAPL History cubed sphere output causes problems using python xarray function open_mfdataset. See this xarray issue on github for a complete description of the problem, with examples: [xarray issue 3285](https://github.com/pydata/xarray/issues/3286
). The brief summary is that anchor uses repeated dimension name ncontact. Repeated dimension names is not allowable in xarray and prevents merging files.

Would it be possible for you to update MAPL to use different dimension names, ncontact1 and ncontact2? This would enable merging files with xarray and allow GCHP output to be compatible with GEOS-Chem python package gcpy without modification.

**Comment by lizziel** [comment]
Thanks @atrayano. Any names are fine.

**Comment by tclune** [comment]
@atrayano and @lizziel  Can this issue be closed?   It is very stale.

**Comment by atrayano** [comment]
@tclune , I had all forgotten about this issue. Let me touch base with @bena-nasa , renaming this is piece of cake, but we need to come up with good substitution (Ben came up with the current choice) and then see what the impact of such change would be

**Comment by mathomp4** [comment]
Reexamined on 2021-Apr-12 with @bena-nasa and @tclune

**Comment by lizziel** [comment]
If you could fix this that would be great. To get around the issue we remove the dimension name from xarray datasets prior to merging in GCPy. It is an annoying step that would be nice to get rid of.

**Comment by lizziel** [comment]
Checking in on this issue. Do you still have this as a to do item?

**Comment by mathomp4** [comment]
@lizziel @tclune thinks of this more as an xarray bug than MAPL issue. Did the fix by @yantosca here: 

https://github.com/geoschem/gcpy/commit/5411f3d71292c3a88442eb597813d0cd8f62b44a 

work for you?

**Comment by yantosca** [comment]
@mathomp4: We now use this fix (passing drop_variables to xr.open_mfdataset) in our benchmarking code and it works very well.  I haven't tested with more recent versions of xarray but I suspect that issue is still there.
