### ISSUE TITLE
Keyword enforcer duplicated in two places

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#396]
Making a note of this so I don't forget.

Both MAPL_Shared and GMAO_pFIO have an identical keyword enforcer. 
GMAO_pFIO has a file KeywordEnforcer.F90 with a module pFIO_KeywordEnforcerMod

MAPL_Shared has a file MAPL_KeywordEnforcer.F90 with module MAPL_KeywordEnforcerMod

Other than the names the code is identical.

This should be consolidated under shared. 
If we are following the MAPL conventions document the file should be 
KeywordEnforcer.F90
the module should be MAPL_KeywordEnforcer

**Comment by tclune** [comment]
Yes - this was one of the files that was supposed to be refactored into the new shared subdirectory.

**Comment by mathomp4** [comment]
@tclune says this is trivial. I'll assign to him.

**Comment by mathomp4** [comment]
Reexamined on 2021-Apr-12 with @bena-nasa and @tclune
