### ISSUE TITLE
Delete MAPL_ExceptionHandling.F90

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#401]
We don't have exceptions, we have errors.  (Unfortunately.)   This module serves little purpose as far as I can see.    MAPL_ErrorHandling should be sufficient unto itself.  

Unfortunately the fix is tedious as lots of MAPL modules use the wrong one.

**Comment by weiyuan-jiang** [comment]
Should we remove MAPL_Exception.h ?  Something useful is still in it. @tclune

**Comment by tclune** [comment]
I retract my earlier comment.   I _would_ like to see the two similar .h files merged at some point, but we probably need to retain both names for all the other layers that reference this file.
