### ISSUE TITLE
Provide facility for a solar zenith angle that goes beyond horizon in MAPL_SunGetInsolation()

### ISSUE THREAD

**Issue by dr0cloud** [GEOS-ESM/MAPL#403]
This is work to be done for Dr. Luke Oman to support photolysis calculations.

**Comment by mathomp4** [comment]
@dr0cloud I'm sure you're aware of this, but I think I might have long ago (at the request of Eric Nielsen) put in some "zenith angle starts at 0" protections that were killing...some code. (sqrt of zth? Not sure)

I guess once you start looking at this, it'll be a good time to revisit this.

**Comment by dr0cloud** [comment]
Hi Matt,
At this point I’m just adding a diagnostic that can go negative. Whoever uses it will have to take that into account. It won’t be used directly in the radiation code or land code. Luke Oman wants it for chemistry purposes, but I’m not sure where he will use it.
Peter.

**Comment by lizziel** [comment]
For GCHP we updated sun.H to allow the solar zenith angle to go beyond the horizon. We've done this for the past several years following each merge of the latest MAPL. It would be fantastic if this were an option in MAPL_SunGetInsolation() instead, so that we don't need to either deal with merge conflicts or remember to check that our update didn't get over-written.

This is the behavior we would like to have, probably best achieved with an optional argument:
```
! Do not force SZA to 0 below horizon; allow < -90 in GCHP (ewl)
!!! enforce zero insolation for sun below horizon
!!ZTH = max(ZTH, 0.0)
!!
!!! normalized downward solar flux at TOA
!!SLR = ZTH*AA
SLR = max(ZTH,0.0)*AA
```

**Comment by lizziel** [comment]
@dr0cloud , @tclune : let me know if my requested update above is already in the pipeline or if you would like me to do a PR.

**Comment by dr0cloud** [comment]
@lizziel 
Hi Lizzie,
In response to a request from Luke Oman’s group, pretty much what you require has now been merged into Develop, but with the following changes in how you access the diagnostic:

We do not comment out the lines that you comment out above, but instead make a copy of ZTH into ZTP just BEFORE the ZTH = max(ZTH, 0.0) line. This ZTP is returned if you call MAPL_SunGetInsolation() with the ZTHP= keyword to get the above ZTP value (i.e., a cos(SZA) that can go negative beyond the horizon.) So you would just add ZTHP=PCOSZ at the end of your MAPL_SunGetInsolation() call and use the PCOSZ. This is preferable to altering the ZTH output, which has a particular meaning in other parts of GEOS-5. The PCOSZ so obtained will be exactly equivalent to the modified ZTH you use above for an *instantaneous* call to the MAPL_SunGetInsolation(). But if you use time-averaging by providing the INTV= optional input argument to MAPL_SunGetInsolation(), the PCOSZ will be a simple arithmetic mean of the ZTP over the time interval, which I think is what you probably want, whereas the ZTH will be a solar insolation weighted cos(SZA), so will weight with zero all points below the horizon. Hope this helps. Please let me know if that's not clear. Peter.

**Comment by mathomp4** [comment]
@dr0cloud Was this completed?

**Comment by dr0cloud** [comment]
Yes, completed as per my response to Lizzie just above.

**Comment by mathomp4** [comment]
Closing.
