### ISSUE TITLE
Compiler errors in MAPL_FlapCapOptions.F90 if not using FLAP

### ISSUE THREAD

**Issue by lizziel** [GEOS-ESM/MAPL#451]
The MAPL/base file MAPL_FlapCapOptions.F90 includes a dependency on FLAP regardless of whether USE_FLAP is defined. This causes compiler errors when building MAPL 2.2 within GCHP which does not use FLAP. I got around this issue by surrounding most of the MAPL_FlapCapOptions module in a USE_FLAP ifdef. I am submitting a separate PR with this fix to go with this issue.

**Comment by tclune** [comment]
Thanks.  Our intent was for their to be an option to bypass FLAP.   I've not recently looked into the details, but look forward to your PR.   Please do it as a hotfix - and we'll get it into a patch for 2.2.
