### ISSUE TITLE
ESMF Logging Errors in ExtData with L132

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#480]
Pursuant to https://github.com/GEOS-ESM/GEOSgcm/issues/164, a run with DDT showed that the ESMF Logs are being thrown by ExtData. Putting aside the question @atrayano raised with me ("Why are we running ExtData for a 0-day run?"), the errors are thrown by this section:
https://github.com/GEOS-ESM/MAPL/blob/29286d8a78b0bdea447465ede7bb4217782538c2/base/MAPL_ExtDataGridCompMod.F90#L4324-L4338

My guess is we need to do the usual `isPresent` trick a la:
```fortran
         call ESMF_AttributeGet  (FIELD, NAME="ScavengingFractionPerKm",isPresent=isPresent, RC=STATUS)
         VERIFY_(STATUS)
         if(isPresent) then
            call ESMF_AttributeGet  (FIELD, NAME="ScavengingFractionPerKm",VALUE=FSCAV_(K), RC=STATUS)
            VERIFY_(STATUS)
         else
            FSCAV_(K) = 0.0 ! no scavenging
         end if
```

Though I'm not sure what the `else` case would be here. `_ASSERT`? My reading of MAPL/base/MAPL_CubedSphereGridFactory.F90 seems to think it's always set:
https://github.com/GEOS-ESM/MAPL/blob/29286d8a78b0bdea447465ede7bb4217782538c2/base/MAPL_CubedSphereGridFactory.F90#L63-L66

But ExtData confuses me, so I'll leave this to the experts.

**Comment by mathomp4** [comment]
NOTE: I originally noticed this in GEOSgcm v10.13 which uses MAPL v2.1.5. Thus, the error exists there (and probably in MAPL 2.0). As this really isn't a "fatal" error in anyway, I don't think we'd need to push a backport to the 2.1.x codebase. But I'll leave that up to @GEOS-ESM/mapl-team to discuss. 

NOTE 2: There is a non-zero chance we might want to make a v2.1.6 for the Dan Holdaway JEDI work (unless @bena-nasa can figure out the "why is mom5 non-zero-diff with MAPL 2.2"). If so, we could fold in a fix into that as a nicety.

**Comment by tclune** [comment]
The other stretch factors are only used if ```stretched_cube``` is ```.true.```

If that option is false (default) then the other AttributeGet calls should be skipped entirely.  Otherwise, they are required and an error should be thrown if not present.
