### ISSUE TITLE
MAPL Crashes when asked to write an empty checkpoint: What to do?

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#486]
This is a fun one. In working on the new NCAR GWD code, it was found that we needed to write out the gwd import state (for the first time in a long time) to preserve start-stop regression. @atrayano helped me add that in an elegant way.

I then started looking closer and realized that the *NCEP* GWD code that @wmputman sometimes runs has more bits in the GWD Import State (which would be captured). BUT! it also adds a GWD **Internal** State which only exists in its case.

So, I did an experiment, what if I'm *not* running NCEP GWD, but ask MAPL to write out the gwd_internal_checkpoint. (With New NCAR GWD we are saved in that no matter what, the import restart has a field). It's a checkpoint where no AddInternalSpec was called. Answer: Bit of a crash! See here a traceback from a GCC 10 Debug run (I had that build around).

```
pe=00000 FAIL at line=05227    MAPL_Generic.F90                         <status=57>
pe=00000 FAIL at line=02144    MAPL_Generic.F90                         <status=57>
pe=00000 FAIL at line=01840    MAPL_Generic.F90                         <needs informative message>
pe=00000 FAIL at line=02072    MAPL_Generic.F90                         <needs informative message>
pe=00000 FAIL at line=01840    MAPL_Generic.F90                         <needs informative message>
pe=00000 FAIL at line=02072    MAPL_Generic.F90                         <needs informative message>
pe=00000 FAIL at line=01840    MAPL_Generic.F90                         <needs informative message>
pe=00000 FAIL at line=02072    MAPL_Generic.F90                         <needs informative message>
pe=00000 FAIL at line=01840    MAPL_Generic.F90                         <needs informative message>
pe=00000 FAIL at line=00794    MAPL_CapGridComp.F90                     <status=1>
```

NOTE 1: This is against MAPL 2.1.5 not develop.
NOTE 2: My guess is this might be what would happen if we also, say, asked for a checkpoint of a state where all the fields were RestartSkip. 

I suppose my question is how to best handle this. Should MAPL support writing out 0-length/variable restarts? Maybe...? I mean, it would allow flexibility that if you turn on the NCEP GWD, say, you have a chance at preserving the state. But then in a non-NCEP GWD case, you'd have to deal with "writing" and "reading" a zero-variable restart...which seems weird (and might not be possible with netCDF).

The other thought is MAPL could determine at, say, SetServices time that a 0-length restart/checkpoint is being asked for and stop and inform the user. But then that means knowing, say, if NCAR GWD, then you must add/uncomment lines in AGCM.rc for state preservation (maybe `gcm_setup` should do this?) 

Or maybe MAPL could just mark the restart as empty and then just remove the checkpoint from its list of checkpoints to write? Just plain ignore AGCM.rc?

I suppose if that could be done, then would AGCM.rc need to know about checkpoints or restarts? As MAPL itself could just say "I'm writing/reading all checkpoints/restarts which have non-zero length IMPORT and INTERNAL states" and error out if one is missing as it tries to reconcile the model to the restarts on disk. But this would mean needing a "standard" for how to name restarts and...oy, my head hurts.

I think I'm going to leave this to people smarter than I. Aka the assignees 😄

**Comment by tclune** [comment]
I think the long term answer is that these should be pulled apart into separate gridded components.   And maybe the long term is here now.

A short term silly solution would be just to add a small Field to internal state regardless, so that it is not empty.  It won't significantly impact performance.  But hopefully it is even easier to add logic in MAPL to just skip the file (both reading and writing) when the internal state is empty.

**Comment by atrayano** [comment]
I agree that MAPL should have logic to skip reading and writing of 0-lenght restarts. We already have some protection(s), definitely for reading, but apparently is not enough to catch all cases

**Comment by lizziel** [comment]
I just want to chime in that I support this update. A GCHP user a while back was trying to turn on the checkpoint file for dynamics and getting crazy errors. I took a look and it was because we don't populate the internal state for that grid comp.

**Comment by mathomp4** [comment]
@atrayano Do you know if anything was done in this realm? So many PRs since this was opened...

**Comment by mathomp4** [comment]
Reexamined on 2021-Apr-12 with @bena-nasa and @tclune 

@atrayano has this been addressed?

**Comment by mathomp4** [comment]
Hmm. This should be in 2.8.6 now. Closing.
