### ISSUE TITLE
Where is free for this create ?

### ISSUE THREAD

**Issue by weiyuan-jiang** [GEOS-ESM/MAPL#497]
https://github.com/GEOS-ESM/MAPL/blob/8e1ce3623cc8459143bea3187944d5aea14f2005/base/MAPL_LocStreamMod.F90#L2554-L2556

@bena-nasa @atrayano , for the call MPI_WIN_Create, there should be a corresponding call MPI_free_mem. Please refer DirectoryService.F90 or MpiMutex.F90 at pfio. Otherwise, it may cause MPI_Finalize failure.

**Comment by mathomp4** [comment]
@weiyuan-jiang Was this taken care of during your many sweeps through MAPL to get finalize to work?

**Comment by weiyuan-jiang** [comment]
Yes. It has been taken care of.
