### ISSUE TITLE
NUOPC wrapper encounters an invalid MPI comm

### ISSUE THREAD

**Issue by WilliamJamieson** [GEOS-ESM/MAPL#500]
When running a MAPL GridComp wrapped by NUOPC, the following run time error happens during the initialization phase of NUOPC:
```
Abort(1007237637) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Comm_dup: Invalid communicator, error stack:
PMPI_Comm_dup(171): MPI_Comm_dup(comm=0x0, new_comm=0x7ffffffe3abc) failed
PMPI_Comm_dup(127): Invalid communicator
```
This is likely due to rearrangements that have occurred as part of newer versions of MAPL, likely MAPL 2.2+.

**Comment by mathomp4** [comment]
Closing as it looks like @WilliamJamieson fixed this.
