### ISSUE TITLE
NUOPC running MAPL encounters an error during finalize

### ISSUE THREAD

**Issue by WilliamJamieson** [GEOS-ESM/MAPL#503]
When NUOPC runs MAPL through the NUOPC wrapper, the application experiences the following error during finalize:
```
pe=00000 FAIL at line=00192    BaseProfiler.F90                         <There are still something on the stack when stop timer>
pe=00001 FAIL at line=00192    BaseProfiler.F90                         <There are still something on the stack when stop timer>
```

This likely is due to an issue with profile timers not being started or stopped within the NUOPC wrapper.

**Comment by mathomp4** [comment]
@WilliamJamieson Can this be closed?

**Comment by WilliamJamieson** [comment]
Yes this can be closed.
