### ISSUE TITLE
GCC9 + MOM6 Dies Reading Vegdyn

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#505]
All, in trying to figure out https://github.com/GEOS-ESM/GEOSgcm/issues/177 once I got it working, I decided to run MOM6 with GCC 9. And oddly it crashes in vegdyn during the `vegdyn.data` read:
```
$ rg pe=00000 slurm-38517310.out
645:pe=00000 FAIL at line=01296    MAPL_IO.F90                              <status=5001>
902:pe=00000 FAIL at line=00981    MAPL_IO.F90                              <status=5001>
903:pe=00000 FAIL at line=05678    MAPL_Generic.F90                         <status=5001>
904:pe=00000 FAIL at line=01620    MAPL_Generic.F90                         <status=-1>
```

For some reason this seems familiar to me, though I can't seem to find any notes on it. @atrayano do you remember something similar somewhere? For some reason, the model dying here:

https://github.com/GEOS-ESM/MAPL/blob/2a1834a122ce5be5e0166e4463e70e78cce189fa/MAPL_Base/MAPL_IO.F90#L1293-L1300

reminds me of some issue in the past.

**Comment by mathomp4** [comment]
I believe @yvikhlya "fixed" this in the coupled model by changing/updating/fixing the boundary conditions.

**Comment by yvikhlya** [comment]
This PR should fix this https://github.com/GEOS-ESM/GEOSgcm_App/pull/201. Basically, vegdyne in coupled model is now the same as in AMIP model. This works with intel compiler. I did not test a coupled model with gcc though.
