### ISSUE TITLE
MAPL Regridder crashing in GCHP

### ISSUE THREAD

**Issue by aechristiansen** [GEOS-ESM/MAPL#507]
I am running a GCHPctm simulation at c180 resolution, and have run into a problem with the MAPL regridder which causes my run to crash. The GCHP version I am running is GCHPctm 13.0.0-alpha.5. My SLURM file shows this error:

```
pe=00015 FAIL at line=00964    MAPL_AbstractRegridder.F90               <status=545>
pe=00015 FAIL at line=00793    MAPL_newCFIO.F90                         <status=545>
pe=00015 FAIL at line=04815    MAPL_ExtDataGridCompMod.F90              <status=545>
pe=00015 FAIL at line=01595    MAPL_ExtDataGridCompMod.F90              <status=545>
pe=00015 FAIL at line=01802    MAPL_Generic.F90                         <needs informative message>
pe=00015 FAIL at line=01038    MAPL_CapGridComp.F90                     <status=1>
pe=00015 FAIL at line=01000    MAPL_CapGridComp.F90                     <status=1>
pe=00015 FAIL at line=00722    MAPL_CapGridComp.F90                     <status=1>
pe=00015 FAIL at line=00841    MAPL_CapGridComp.F90                     <status=1>
pe=00015 FAIL at line=00435    MAPL_Cap.F90                             <status=1>
pe=00015 FAIL at line=00309    MAPL_Cap.F90                             <status=1>
pe=00015 FAIL at line=00151    MAPL_Cap.F90                             <status=1>
pe=00015 FAIL at line=00129    MAPL_Cap.F90                             <status=1>
pe=00015 FAIL at line=00029    GCHPctm.F90                              <status=1>
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 15 in communicator MPI_COMM_WORLD
with errorcode 0.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
```

And my log file shows this:

```
ExtData Run_: READ_LOOP: Complete
 ExtData Run_: ---PopulateBundle
 ExtData Run_: ---CreateCFIO
 ExtData Run_: ---prefetch
 create_route_handle        1450
 initialize_subclass        1309
 MAPL_RegridderManager_private::make_regridder_from_grids         269
```

I discussed this issue with the GEOS-Chem support team (https://github.com/geoschem/GCHPctm/issues/32) and they suggested I ask here. What could be the issue?

**Comment by lizziel** [comment]
Fyi, GCHPctm 13.0.0-alpha.5 uses MAPL v2.0.2. GCHPctm development has moved on to using MAPL v2.2.7 but high resolution tests are a few weeks away. If there's a known issue causing an issue running at c180 in v2.0.2 that would lead to this error please let us know. Otherwise the GEOS-Chem Support Team will not be debug this version of MAPL which is used in an older dev version of GCHPctm.

See also: https://github.com/geoschem/GCHPctm/issues/32

**Comment by tclune** [comment]
@bena-nasa will no doubt have a better memory than myself, but the only recent regridder issues that I recall were to do with extreme cases where there are not enough lats/lons for each process to get at least 2 points. (An ESMF requirement.)   Maybe there was some other corner case for _creating_ LatLon grids for Harvard that is different than the GMAO convention, but I would not expect the error reported here for that.

BTW, v2.0.2 of ExtData does not have 4815 lines, so I'm not sure which version of MAPL is actually being used.

If there is any clue as to which file is being used for said regridding, that is likely to shed more light on what might be different about this case.   Certainly we regrid lots and lots of things at C180 without issue.

**Comment by lizziel** [comment]
I should clarify. It is v2.0.2 with some minor modifications for GCHP which would make the line numbers slightly different.

**Comment by bena-nasa** [comment]
I really need to know what file is being handled that triggers this as well as the number of processors you are using for example would be useful. It appears to be in the generation of the regridding weights based on the output provided. If you could re-run and put a print in MAPL_newCFIO.F90 in the routine "request_data_from_file" and print the filename being passed in that would tell us what the file is that might be causing this, as that routine is where the call the computes the regridding weights occurs. My first guess is that there is something unique about the particular file.

**Comment by tclune** [comment]
@bena-nasa We should add a pFlogger `debug()` call for this.   The question comes up often enough that it would be nice to just modify the logging.yaml and get that extra info.

**Comment by lizziel** [comment]
If there's a way to get the identifying name/info whenever there is a crash in a loop that would be wonderful. I can't count how many times I've gone in to add prints to figure out what file or variable is the problem, in ExtData or History. And then that requires rebuild, and then another rebuild when you remove the print. It gets time-consuming, and definitely not clear for our GCHP users not familiar with programming or MAPL.

**Comment by tclune** [comment]
Yes - this is probably the 2nd most important use case that drove me to develop pFlogger.  The other being the ability to route output from different processes to different files and/or annotate the output with which process generated it.

**Comment by bena-nasa** [comment]
Do have a working example in MAPL of adding a pFlogger debug() I can follow for this?

**Comment by tclune** [comment]
The source code is 2 parts.  First we need to retrieve a logger.   Presumably we would call it something like:
```
class(Logger), pointer :: lgr
lgr =>  logging%get_logger('MAPL.ExtData')
```
And then diagnostic messages would be written like:

```
call lgr%debug("Attempting to access file %a", trim(filename))
...
call lgr%debug("Access to file %a succeeded", trim(filename))
```
These will effectively do nothing until there is something in the config to activate them.   Simplest entry would be to add something in the loggers section like:
```
MAPL.ExtData:
    handlers: [console]
    root_level: DEBUG
    level: WARNING
```
This would send those messages (on the root pe) to the console.    Changing to ```root_level: INFO``` would deactivate them.

**Comment by tclune** [comment]
I may have time today to do a PR for this if you would like to avoid the frustration of whatever details did not occur to me in my previous post.    I just did a similar exercise with Elliot yesterday for GOCART.  (Alas his case will have to be removed as it is in the "process library" that is not allowed to have external dependencies.)

**Comment by mathomp4** [comment]
@tclune @bena-nasa @lizziel Is this still an issue with GCHP?

**Comment by tclune** [comment]
I believe that ExtData is now properly instrumented with pflogger and this issue can now be closed.
