### ISSUE TITLE
Change in Attribute class in ESMF 8.1 snapshot breaks MAPL/Model

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#508]
In chasing another bug we tried running the GEOS gcm we tried using the latest ESMF snapshot  (ESMF 8.1 beta 23) for the upcoming 8.1 release. It looks like changes being made to the ESMF_AttributeClass have issues with GEOS. It appears the ESMF_Attribute class is being superseded by the ESMF_Info class, and the legacy ESMF_Attribute class will be a wrapper on top of the ESMF_Info class.
However when running GEOSgcm.x with this snapshot the model immediately crash in MAPL_FieldCopyAttributes as the typekind of what had been added as a 32-bit integer, was coming being returned by the ESMF_AttributeGet call as being a 64-bit integer. The subsequent if block fails as it expects either a 32-bit integer, 32-bit real, 64-bit real, string or logical. If not one of those it fails. Just change the if to expect a 64-bit integer gets you a little further until the next crash.
The documentation says the ESMF_Info class JSON compatible and as such:
"Only 64-bit data types for integers and reals are supported ([3], [2]). 32-bit data is converted to 64-bit data and
vice versa. An error will occur if truncation is triggered during a conversion."
It seams as though this conversion on the get call is not happening. Communication with Gerhard said 8.1 should be backwards compatible with 8.0 so perhaps this is a "hiccup" along the way that may be fixed in a future snapshot but we should be keeping an eye on this going forward.
In the longer term the ESMF documentation suggest transitioning to the ESMF_Info class.

**Comment by bena-nasa** [comment]
Found what seems to be the cause and have sent a reproducer to ESMF. Seems to be that MAPL_StateCreateFromSpec, if the field is a copy of an existing field, then all the attributes we set have already been added to the field, via a call to MAPL_FieldCopyAttributes. In this case the ESMF_AttributeSet fails now, where as before it did not in ESMF 8.0 and before. It seems to be HOW we are doing the copy the cases the problem. For example, I can create a simple program, create a field, and do
integer :: i
i=2
ESMF_AttributeSet(field,name=attname,value=i,rc=status)
i=3
ESMF_AttributeSet(field,name=attname,value=i,rc=status)

etc...
and the return status is always 0.

the point is that it is not the fact that the attribute has already been set that is the issue but rather, how it was set the first time.

**Comment by bena-nasa** [comment]
Ok, ESMF seems to think it is related to the fact that in the copy we add the attribute as an array, but then try to set it again as a scalar.

**Comment by rsdunlapiv** [comment]
Making sure @bekozi has his eyes on this one.

**Comment by mathomp4** [comment]
@bena-nasa @rsdunlapiv Do you know if this has been taken care of in ESMF 8.1.0 development? Or is it something we need to press for ESMF 8.2.0?

**Comment by mathomp4** [comment]
Reexamined on 2021-Apr-12 with @bena-nasa and @tclune 

We are running with 8.1.0, so must work.
