### ISSUE TITLE
negative throughput numbers reported

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#511]
Several users have reported negative values for throughput from MAPL_Cap.

The timers are using `system_clock()` with default integers instead of 64 bit which greatly increases the odds that the clock will "roll over" during a run.      Should be a simple fix.

**Comment by tclune** [comment]
Mentioning @lizziel, who reported this concern.

**Comment by mathomp4** [comment]
@tclune Would moving our `system_clock()` calls to `int64` be sufficient? Or should we move to something like `MPI_Wtime()`?

**Comment by tclune** [comment]
I don't think accuracy is a concern.   Just the rollover at MAX_TICK.    But I'm not opposed to an MP_Wtime() solution either.

**Comment by mathomp4** [comment]
Well, we have a good mix. 

Files using `system_clock`:
```
❯ rg system_clock -l
base/MAPL_Cap.F90
base/cub2latlon_regridder.F90
base/tests/testbin.F90
base/MAPL_Profiler.F90
profiler/FortranTimerGauge.F90
pfio/pfio_io_demo.F90
pfio/pfio_collective_demo.F90
pfio/tests/pfio_ctest_io.F90
```
Files using `MPI_Wtime()`:
```
❯ rg mpi_wtime -l
base/MAPL_Generic.F90
base/Regrid_Util.F90
base/MAPL_IO.F90
base/MAPL_CapGridComp.F90
profiler/MpiTimerGauge.F90
pfio/BaseServer.F90
pfio/tests/pfio_performance.F90
```

Luckily we have no files using both! 😄

**Comment by tclune** [comment]
Yeah - I (probably for no good reason) tend to favor the Fortran intrinsics over use of a library.  But if one knows that MPI is always being linked, it's hard to argue against ```MPI_Wtime()```.     

All of the ones you found that are not tests/demos should be considered for adoption of the new profiler.    (Except of course, _inside_ the profiler itself which intentionally provides multiple interfaces.)

**Comment by mathomp4** [comment]
@tclune @weiyuan-jiang Has the new profiler been spread enough in GEOS to consider this "fixed"? It does look like we still have a good mix:
```console
❯ rg mpi_wtime -l | sort
base/MAPL_Generic.F90
base/MAPL_IO.F90
gridcomps/Cap/MAPL_CapGridComp.F90
pfio/BaseServer.F90
pfio/MultiLayerServer.F90
pfio/tests/pfio_performance.F90
profiler/MpiTimerGauge.F90
❯ rg system_clock -l | sort
base/MAPL_Profiler.F90
base/cub2latlon_regridder.F90
base/tests/testbin.F90
gridcomps/Cap/MAPL_Cap.F90
pfio/pfio_collective_demo.F90
pfio/pfio_io_demo.F90
pfio/tests/pfio_ctest_io.F90
profiler/FortranTimerGauge.F90```

**Comment by mathomp4** [comment]
Reexamined on 2021-Apr-12 with @bena-nasa and @tclune
