### ISSUE TITLE
Wrap ESMF_AttributeGet (or ESMF_Info equivalent)

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#517]
Pursuant to a comment by @tclune:

> We do enough of this sort of thing that I think we should add a wrapper in MAPL_Base that does this combination. Would be a no-brainer except for the the amount of overloading that is involved.

The code he is referring to is:
```fortran
call ESMF_AttributeGet(grid, name='STRETCH_FACTOR', isPresent=isPresent, rc=status)
_VERIFY(status)
if (isPresent) then
   call ESMF_AttributeGet(grid, name='STRETCH_FACTOR', value=temp_real, rc=status)
   _VERIFY(status)
```
Indeed, this does seem a good candidate for a wrapper. 

But, should it be for ESMF_AttributeGet? Or is @bena-nasa thinking of perhaps moving MAPL to using ESMF_Info directly and that should be wrapped? Or both (one for legacy code, one for future)?

**Comment by tclune** [comment]
If there is a new and better way, I'd write the new wrapper layer to use that.   And then we can update legacy "2-calls-plus-conditional" into calls to the new wrapper at our leisure.   (OTOH, if we don't follow up immediately, it will probably defeat the purpose as people cut-and-paste the existing way.)

**Comment by mathomp4** [comment]
Reexamined on 2021-Apr-12 with @bena-nasa and @tclune

**Comment by mathomp4** [comment]
This is definitely a long-term sort of issue. My guess is it could be a good candidate for MAPL3 (though @tclune might say it could go in any time). I'll add that label as well as long-term.
