### ISSUE TITLE
Missing metadata in ocean history collections.

### ISSUE THREAD

**Issue by yvikhlya** [GEOS-ESM/MAPL#527]
Following metadata are missing in ocean history collections after update to MAPL2:
1. Geographical 2d latitudes and longitudes in tripolar collections.
2. Depth levels in 3d collections.

Current post processing scripts depend on these metadata. Since all our history output is on A-grid, A-grid coordinates are sufficient.  Before MAPL2, tripolar collections were conformant with CF conventions, it would be nice if they stay conformant.

**Comment by bena-nasa** [comment]
Ok, I will take a look at this. Please point me to your coupled setup I should use for testing.

**Comment by yvikhlya** [comment]
@bena-nasa You can use set up at 
```
~yvikhlia/aogcm/xxx_mom5, ~yvikhlia/geos5/xxx_mom5
~yvikhlia/aogcm/xxx_mom6, ~yvikhlia/geos5/xxx_mom6
```
for MOM5 and MOM6 respectively, or just generate set up using gcm_setup script and copy initial conditions from above locations. You'll probably want to test MOM5 only, and when everything is ready, I can do test with MOM6.

**Comment by mathomp4** [comment]
@bena-nasa I can tell you how to set up a MOM5 and MOM6 experiment. Heck, I should take the time and make `makeoneday.bash` do it!

**Comment by bena-nasa** [comment]
OK, as part of this I am going to update the tripolar grid creation to get the correct coordinates in for MOM5 and MOM6 respectively from the appropriate files into the ESMF grid. I have the gridspec file for MOM5 that I can use to get the coordinates. @sanAkel has said he is going to make a file for MOM6 I can use to obtain the coordinates that I will code to.

**Comment by yvikhlya** [comment]
@bena-nasa Previously, we had coordinates in ascii files, like:
```
tripolar_360x210.ascii
vgrid50.ascii
```

You can find the same data in grid_spec.nc for MOM5. As for MOM6, we have 
```
/home/yvikhlia/nobackup/coupled/Forcings/MOM6/CF0090x6C_TM0360xTM0210/INPUT/ocean_static.nc
/home/yvikhlia/nobackup/coupled/Forcings/MOM6/CF0090x6C_TM0360xTM0210/INPUT/vgrid.nc
```
cordinate names are geolon, geolat and zt. We can create netcdf file for MOM5 and MOM6 which are named the same and have same coordinate names.

**Comment by bena-nasa** [comment]
@yvikhlya  I see that ascii file which I want to replace in the tripolar factory for the following reason. At some point I modified my regridding utility (Regrid_Util.F90) under MAPL to read what I thought was the grid spec file because it had both center and corner coordinates (at the very least you or Bin gave me a file I used, I didn't just make this up). It was looking for variables named x_T, y_T for the centers, and x_vert_T, y_vert_T for the corners. I used this file because to support both bilinear and and conservative regridding which needed both the centers of each cell as well as the corners so the ascii file is not sufficient. I would like the factory in MAPL to read both so it can support both regridding options.

However, now when I look at the grid_spec.nc file in the setup you pointed me to for MOM5 I see what I have pasted below. Has the gridspec file changed as this is not what I remember or what I had coded a long time ago. That is fine, but which is the correct variable to use for the centers and corner?
Please advise, I need to code to something and I would rather not keep having to reimplement this. Let's agree on a standard and stick to it.
@sanAkel if the MOM5 and MOM6 could be make to look identical (or at least have the same variable and dimension names so I can use the same read routine that would make things easier).

```
netcdf grid_spec {
dimensions:
        gridlon_c = 360 ;
        gridlon_t = 360 ;
        gridlon_vert_c = 361 ;
        gridlon_vert_t = 361 ;
        gridlat_c = 200 ;
        gridlat_t = 200 ;
        gridlat_vert_c = 201 ;
        gridlat_vert_t = 201 ;
        zt = 50 ;
        zw = 50 ;
        i_atmXocn = 79644 ;
        i_atmXlnd = 5177 ;
        i_lndXocn = 79644 ;
        xba = 145 ;
        yba = 91 ;
        xta = 144 ;
        yta = 90 ;
        xbl = 145 ;
        ybl = 91 ;
        xtl = 144 ;
        ytl = 90 ;
        xto = 360 ;
        yto = 200 ;
        XT_OCEAN = 360 ;
        YT_OCEAN = 200 ;
variables:
        float gridlon_c(gridlon_c) ;
                gridlon_c:long_name = "gridlon_c" ;
                gridlon_c:units = "degrees_E" ;
                gridlon_c:modulo = "y" ;
        float gridlon_t(gridlon_t) ;
                gridlon_t:long_name = "gridlon_t" ;
                gridlon_t:units = "degrees_E" ;
        float gridlon_vert_c(gridlon_vert_c) ;
                gridlon_vert_c:long_name = "gridlon_vert_c" ;
                gridlon_vert_c:units = "degrees_E" ;
        float gridlon_vert_t(gridlon_vert_t) ;
                gridlon_vert_t:long_name = "gridlon_vert_t" ;
                gridlon_vert_t:units = "degrees_E" ;
        float gridlat_c(gridlat_c) ;
                gridlat_c:long_name = "gridlat_c" ;
                gridlat_c:units = "degrees_N" ;
        float gridlat_t(gridlat_t) ;
                gridlat_t:long_name = "gridlat_t" ;
                gridlat_t:units = "degrees_N" ;
        float gridlat_vert_c(gridlat_vert_c) ;
                gridlat_vert_c:long_name = "gridlat_vert_c" ;
                gridlat_vert_c:units = "degrees_N" ;
        float gridlat_vert_t(gridlat_vert_t) ;
                gridlat_vert_t:long_name = "gridlat_vert_t" ;
        float zt(zt) ;
                zt:long_name = "zt" ;
                zt:units = "meters" ;
                zt:cartesian_axis = "z" ;
                zt:positive = "down" ;
        float zw(zw) ;
                zw:long_name = "zw" ;
                zw:units = "meters" ;
                zw:cartesian_axis = "z" ;
                zw:positive = "down" ;
        double geolon_t(gridlat_t, gridlon_t) ;
                geolon_t:long_name = "geographic longitude of t-cell centers" ;
                geolon_t:units = "degrees_E" ;
        double geolat_t(gridlat_t, gridlon_t) ;
                geolat_t:long_name = "geographic latitude of t-cell centers" ;
                geolat_t:units = "degrees_N" ;
        double geolon_c(gridlat_c, gridlon_c) ;
                geolon_c:long_name = "geographic longitude of corner cell centers" ;
                geolon_c:units = "degrees_E" ;
        double geolat_c(gridlat_c, gridlon_c) ;
                geolat_c:long_name = "geographic latitude of corner cell centers" ;
                geolat_c:units = "degrees_N" ;
        double geolon_e(gridlat_t, gridlon_c) ;
                geolon_e:long_name = "geographic longitude of east cell centers" ;
                geolon_e:units = "degrees_E" ;
        double geolat_e(gridlat_t, gridlon_c) ;
                geolat_e:long_name = "geographic latitude of east cell centers" ;
                geolat_e:units = "degrees_N" ;
        double geolon_n(gridlat_c, gridlon_t) ;
                geolon_n:long_name = "geographic longitude of north cell centers" ;
                geolon_n:units = "degrees_E" ;
        double geolat_n(gridlat_c, gridlon_t) ;
                geolat_n:long_name = "geographic latitude of north cell centers" ;
                geolat_n:units = "degrees_N" ;
        double geolon_vert_t(gridlat_vert_t, gridlon_vert_t) ;
                geolon_vert_t:long_name = "geographic longitude of t-cell vertices" ;
                geolon_vert_t:units = "degrees_E" ;
        double geolat_vert_t(gridlat_vert_t, gridlon_vert_t) ;
                geolat_vert_t:long_name = "geographic latitude of t-cell vertices" ;
                geolat_vert_t:units = "degrees_N" ;
        double geo_lonc(gridlat_vert_c, gridlon_vert_c) ;
                geo_lonc:long_name = "geographic longitude of corner cell centers (identical to geolon_vert_t)" ;
                geo_lonc:units = "degrees_E" ;
```

**Comment by yvikhlya** [comment]
@bena-nasa Ben, in the file which you are looking at geolon_t and geolat_t are coordinates of cell centers, geolon_c and geolat_c are corners. x_T and y_T are names in another grid_spec.nc, 0.5 degree.

@sanAkel I think it is a bad idea to rely on grid_spec.nc or other files which are provided by GFDL for MAPL output and post processing, because they change names and format all the time. We need to extract this information from whatever GFDL provides, put it to separate file, and stick to same format for all our setups, such that all our utilities work (MAPL history, tile file generator, runoff table generator, plotting etc). I would invite @atrayano to this discussion too.

**Comment by bena-nasa** [comment]
So the grid_spec file has a different format depending on the resolution even within MOM5?  This is not good! 

Yuri is right. We need one format common across MOM5, MOM6 at all resolutions otherwise this will be unworkable to properly support the tripolar grid whether it is MOM5 or MOM6 in MAPL. This is what I would like to see, a simple file like this that should be very easy to generate from a short python code, these are just sample names, I don't care what they are:
```
netcdf MAPL_Tripolar_file {
dimensions:
        n_center_x = 360 ;
        n_center_y = 200 ;
        n_vert_x = 361 ;
        n_vert_y = 201

variables:
        float lon_centers(n_center_x,ncenter_y) ;
                gridlon_c:long_name = "longitude" ;
                gridlon_c:units = "degrees_E" ;
        float lat_centers(n_center_x,ncenter_y) ;
                gridlon_c:long_name = "latitude" ;
                gridlon_c:units = "degrees_N" ;
         float lon_corners(n_corner_x,ncorner_y) ;
                gridlon_c:long_name = "longitude" ;
                gridlon_c:units = "degrees_E" ;
        float lat_corners(n_corner_x,ncorner_y) ;
                gridlon_c:long_name = "latitude" ;
                gridlon_c:units = "degrees_N" ;
```

**Comment by yvikhlya** [comment]
> So the grid_spec file has a different format depending on the resolution even within MOM5? This is not good!

One of our grid_specs comes from MOM4, I don't remember which one. Then they changed it in MOM5p0, then again changed it in MOM5p1.

**Comment by sanAkel** [comment]
With MOM6, as you all (@yvikhlya , @bena-nasa, @atrayano ) know there is no `grid_spec.nc` 

As to which file should we use? 

- Last week I was talking to @bena-nasa and we agreed on working with `ocean_hgrid.nc` which does come from GFDL, and certainly more _raw_ than what @yvikhlya is pointing to 
>/home/yvikhlia/nobackup/coupled/Forcings/MOM6/CF0090x6C_TM0360xTM0210/INPUT/ocean_static.nc
/home/yvikhlia/nobackup/coupled/Forcings/MOM6/CF0090x6C_TM0360xTM0210/INPUT/vgrid.nc

(since first of above is written out by MOM6 as `output`) an important bit that we need to remind ourselves is that MOM6 works with mosaic file. As for the vertical grid file: `vgrid.nc` Since we are not exporting 3D fields with MOM6, we do not need this file or any such thing!

- Another possibility is straight off of ETOPO and `https://github.com/NOAA-GFDL/FRE-NCtools` that @mathomp4 already built for us on discover: module name: `other/FRE-NCtools/2020Mar16` 

@bena-nasa I totally understand the ease of having the netcdf attributes alike, will try my best to make the Tcell coordinate names same.

**Comment by sanAkel** [comment]
@bena-nasa we can cull out whatever we don't need and write 2 nc files with Tcell: corner points for the lats and lons for the MOM5 and MOM6 ocean models. Will that work? There is no reason for us to keep on taking the `grid_spec.nc` and/or ocean_hgrid.nc` (for MOM5 and MOM6 respectively) as if they were set in stone! They are just lats and lons!

**Comment by yvikhlya** [comment]
> This is what I would like to see

I would also suggest to put there other data required by other GEOS utils, like land mask, grid area, etc. We need to put together a full list of what we need to make **everything** working.

**Comment by atrayano** [comment]
I agree that we should have 1 file that has the same info regardless of the version of MOM. When GFDL switched to mosaic, the also have different staggering, and it took me a while to generate a proper tile file for MOM6. My 2 cents, which should have a pre-processing utility to take the grid_spec (or equivalent) and produce a file that we all can agree. And put that convention in MAPL

**Comment by yvikhlya** [comment]
@bena-nasa @atrayano Are field attributes important for any of our utilities?

**Comment by bena-nasa** [comment]
@yuri I was able to get the 2D lats and lons into the tripolar output.   It is a very trivial modification to output the 2D lons and lats output in files on the tripolar grid all the time. It would be more work if you want to control this and turn it off for some reason. Let me know if that is needed. Otherwise it is a 5 line change I have to make.

As for the vertical. Before you were using the ability in History add a levels option to the collection and putting those values in the vertical variable even if you were not actually doing any vertical regridding. Is this correct. Until we can better support vertical grids in MAPL, I can try to do the same thing in the MAPL 2.0+ HistoryGridcomp.

Finally as far as field attributes, utilities that are reading our History files are about the attributes in the History files, I'm sure there are others, they are not coming to mind. Let's not get too hung up on this, I just need something to code to when reading the centers and corners in the tripolar factory.

**Comment by atrayano** [comment]
@yvikhlya If I remember correctly MAPL used to read the coordinates from an text file (ASCII) and there were no metadata attributtes. The metadata attribute name matters in the ocean raster code, but the current version supports only MOM4/5. I had to make changes (not committed yet) to generated a tile file for @sanAkel for MOM6

**Comment by yvikhlya** [comment]
@bena-nasa We never did vertical regridding in ocean collections, but it is nice to have depth levels. Right now there are indexes instead depth (1,2,3...)

@atrayano This is what I mean, if raster or any other tools rely of netcdf attributes, we need to put them in same file, such that we don't need to change all our tools each time GFDL changes grid format.

**Comment by sanAkel** [comment]
Once we learn how to make use of https://github.com/NOAA-GFDL/FRE-NCtools @yvikhlya it will be better for us.

**Comment by yvikhlya** [comment]
@bena-nasa To start with, I made a file following your example above
```
/home/yvikhlia/nobackup/coupled/Forcings/a90x540_o360x200/INPUT/MAPL_Tripolar.nc
```
This is for MOM5 1 degree configuration. I'll make similar files for MOM6 and any other configuration we want to use. 
@atrayano @sanAkel All, let me know if this is appropriate format.

**Comment by bena-nasa** [comment]
@yvikhlya I made a fix to get the 2D lat/lons in the tripolar about and re-enable the ability to have the values from the ascii file with the levels put into the vertical coordinate in the output file. This is now on our develop branch of MAPL.

That file looks fine to me. I'll wait and give others @sanAkel a chance but if I don't see anyone else chime in, in the next day, I will  modifying the tripolar grid factory to read that format.

**Comment by sanAkel** [comment]
> @bena-nasa To start with, I made a file following your example above
> 
> ```
> /home/yvikhlia/nobackup/coupled/Forcings/a90x540_o360x200/INPUT/MAPL_Tripolar.nc
> ```
> 
> This is for MOM5 1 degree configuration. I'll make similar files for MOM6 and any other configuration we want to use. I'll add more metadata if needed.
> @atrayano @sanAkel All, let me know if this is appropriate format.

It is good! Thank you @yvikhlya

**Comment by yvikhlya** [comment]
One change: since MAPL_Tripolar.nc is not really MOM config file, but GEOS config file, I moved it from
```
a90x540_o360x200/INPUT
```
to
```
a90x540_o360x200
```
This is were it will live in all coupled configurations.

**Comment by sanAkel** [comment]
@yvikhlya one quick suggestion, since the file nc file you are making has coordinates (lat, lon: corner/center) from either MOM5 or MOM6, would you please include some metadata like who (user) which utility made this file and on what date

Let's use nc format as much as possible...

**Comment by yvikhlya** [comment]
> @yvikhlya one quick suggestion, since the file nc file you are making has coordinates (lat, lon: corner/center) from either MOM5 or MOM6, would you please include some metadata like who (user) which utility made this file and on what date
> 
> Let's use nc format as much as possible...

I was just going to ask if we need some global attributes. I'll add them.

**Comment by sanAkel** [comment]
> @yvikhlya I made a fix to get the 2D lat/lons in the tripolar about and re-enable the ability to have the values from the ascii file with the levels put into the vertical coordinate in the output file. This is now on our develop branch of MAPL.
> 
> That file looks fine to me. I'll wait and give others @sanAkel a chance but if I don't see anyone else chime in, in the next day, I will modifying the tripolar grid factory to read that format.

@bena-nasa would you please let us know when you have the grid factory modified. One of us can quickly test to make sure it works for us. Thank you!

**Comment by zhaobin74** [comment]
To generate CICE grid files, additional information as below are needed.

- length of northern edge of T-Cell
- length of eastern edge of T-Cell
- length of nsouthern edge of U-Cell
- length of western edge of U-Cell
- area of U-Cell
- area of T-Cell
- rotation angle centered on T-Cell
- rotation angle centered on T-Cell
**for the lengths, please refer MOM5 manual Figure 9.6 and 9.7 to get their names in grid spec.**

**Comment by yvikhlya** [comment]
> To generate CICE grid files, additional information as below are needed.
> 
>     * length of northern edge of T-Cell
> 
>     * length of eastern edge of T-Cell
> 
>     * length of southern edge of U-Cell
> 
>     * length of western edge of U-Cell
> 
>     * area of U-Cell
> 
>     * area of T-Cell
> 
>     * rotation angle centered on T-Cell
> 
>     * rotation angle centered on U-Cell
> 
> 
> **for the lengths, please refer MOM5 manual Figure 9.6 and 9.7 to get their names in grid spec.**

I don't think we have all of these in 1 degree grid. Are these all needed for cice grid generator?

**Comment by zhaobin74** [comment]
> > To generate CICE grid files, additional information as below are needed.
> > ```
> > * length of northern edge of T-Cell
> > 
> > * length of eastern edge of T-Cell
> > 
> > * length of southern edge of U-Cell
> > 
> > * length of western edge of U-Cell
> > 
> > * area of U-Cell
> > 
> > * area of T-Cell
> > 
> > * rotation angle centered on T-Cell
> > 
> > * rotation angle centered on U-Cell
> > ```
> > 
> > 
> > **for the lengths, please refer MOM5 manual Figure 9.6 and 9.7 to get their names in grid spec.**
> 
> I don't think we have all of these in 1 degree grid. Are these all needed for cice grid generator?

If some information is not available for a particular grid, make them undefined so cice grid generator can treat it as a special case. AFAIK, only one grid, 360x200, lacks the above information.

**Comment by yvikhlya** [comment]
@zhaobin74 I already did this. Path to script which creates this file is in global attributes.

**Comment by sanAkel** [comment]
@yvikhlya can this issue be closed?
