### ISSUE TITLE
Bug when handling string attributes in NetCDF-4 files under Jason

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#530]
Reported by @mmanyin:

Luke Oman has found that some netCDF-4 data files  (the FEER biomass burning emissions*)
don't work with Jason  (v10.12.5),   even though they DO work with Icarus.
Apparently if there are NF90_STRING attributes in a file,  the reader aborts.
Do you know if there are any work-arounds, present or planned for GEOS?
We would rather not edit the attributes of all such files.

I'm not sure if this would help, but I ran across nf90_get_att_text  in
https://github.com/Unidata/netcdf-fortran/blob/master/fortran/netcdf_attributes.f90
However that doesn't seem to be the answer  (I tried adding it into NetCDF4_FileFormatter.F90
but the compiler balked.)
-Mike

* example file: /discover/nobackup/projects/gmao/merra2_gmi/work/ExtData/FEER/2004/FEERv1.0-G1.2_so2_20041210.nc4

(@mathomp4 cc'd)

**Comment by tclune** [comment]
@mmanyin Thanks for reporting this.     We often see compilers struggle with handling strings in some of the ways allowed by Fortran 2003, though these days the problems are largely with GFortran.

Certainly Jason is handling some string attributes correctly, so the details may matter.    I've assigned to @bena-nasa, but he should assigne it back to me if this proves to be a problem in the pFIO layer itself.

**Comment by mmanyin** [comment]
Hi, Luke is asking me if the solution to this might be close at hand?   thx

**Comment by tclune** [comment]
@mmanyin  Apologies - I think this fell off of our collective plates.    I'll encourage Ben to at least confirm what he sees with your example file.

**Comment by mathomp4** [comment]
@bena-nasa @tclune Did we fix this?

**Comment by mmanyin** [comment]
As of early this month (Feb) the problem was still there.  If you want an example case, let me know.

**Comment by mathomp4** [comment]
@mmanyin Please do supply a case!

**Comment by mmanyin** [comment]
@mathomp4 Run gcm_setup but do not ask for MERRA2 or MERRA2-DD emissions;  copy restart files and set to run sometime in the late 2000's.  This should run fine.  Repeat the exercise, but this time, in RC/SU_GridComp_ExtData.rc, replace the line for SU_BIOMASS with this line:
SU_BIOMASS NA  N Y %y4-%m2-%d2t12:00:00 none none biomass /discover/nobackup/projects/gmao/merra2_gmi/work/ExtData/FEER/%y4/FEERv1.0-G1.2_so2_%y4%m2%d2.nc4
The run will fail.

**Comment by mathomp4** [comment]
Huh. Yup, that does it:
```
pe=00080 FAIL at line=00903    NetCDF4_FileFormatter.F90                <no such property>
pe=00080 FAIL at line=00787    NetCDF4_FileFormatter.F90                <status=1>
pe=00080 FAIL at line=00092    MAPL_ExtDataCollection.F90               <status=1>
pe=00080 FAIL at line=02181    MAPL_ExtDataGridCompMod.F90              <Variable biomass not found in file /discover/nobackup/projects/gmao/merra2_gmi/work/ExtData/FEER/%y4/FEERv1.0-G1.2_so2_%y4%m2%d2.nc4>
```

And looking at the web, this does not inspire confidence:
https://www.unidata.ucar.edu/mailing_lists/archives/netcdfgroup/2014/msg00103.html
but that was 6 years ago. Maybe things have changed...
Nope:
https://github.com/Unidata/netcdf-fortran/issues/181

So, my only thought right now is to make that code "ignore" `NF90_STRING`? A la:
```fortran
         case (NF90_CHAR)
            allocate(character(len=len) :: str)
            !$omp critical
            status = nf90_get_att(this%ncid, varid, trim(attr_name), str)
            !$omp end critical
            _VERIFY(status)
            call cf%add_attribute(trim(attr_name), str)
            deallocate(str)
         case (NF90_STRING)
            cycle
         case default
            _RETURN(_FAILURE)
         end select
```
I just tried something like that and the model ran. But @bena-nasa and/or @weiyuan-jiang would need to look at it. I'm not sure if these attributes are needed for anything!

**Comment by mmanyin** [comment]
It appears that the FEER files only have  NF90_STRING  attributes as "global attributes", which are not important, right?

**Comment by mathomp4** [comment]
> It appears that the FEER files only have NF90_STRING attributes as "global attributes", which are not important, right?

I defer to @bena-nasa or @tclune on that. My guess is...no? Or at least, we have none we care about that are `NF90_STRING`?

**Comment by tclune** [comment]
Global attributes are important, but those are working.   The problem with string _variables_ (as opposed to attributes) is the potential for being multidimensional.    Fortran and C don't quite treat arrays of strings in the same manner which leads to subtleties at the interface.  (As well as bugs in the Fortran compilers themselves.)

**Comment by mmanyin** [comment]
Assume that the F90 interface for netCDF strings is permanently broken.  Then either this problem must be handled within GEOS, using an approach such as @mathomp4 has outlined (ignoring strings), or the end users must convert each and every dataset containing NF90_STRING attributes into files that do not contain NF90_STRING attributes. I vote for the first option, because it's a quick solution, as opposed to the second option which will impose a recurring cost on all GEOS users.

**Comment by tclune** [comment]
Taking a fresh look at this.    Is the problem simply that I did not realize that NF90_STRING exists when developing NetCDF4_FileFormatter.F90?      Looking at the code, it should probably not even be necessary to `cycle`.  We should be able to add the appropriate logic- at least for scalar strings.      I'll take a stab at this, if someone is willing to test against a "bad" file.

**Comment by tclune** [comment]
OK - sorry.  Should have reread the open issue on NetCDF before responding.     The problem is that the NF90 interfaces for this don't exist at all.  So there is nothing for us to exercise.    I'll look at the C interface and should instead be able to create our own wrapper that works for the scalar case.    Arrays of strings will be flagged as an error. (unsupported functionality).

**Comment by mmanyin** [comment]
@tclune a C wrapper sounds like a good solution! I agree that arrays of strings don't need to be supported.

**Comment by tclune** [comment]
@mmanyin  OK - I've pushed a branch `feature/tclune//#530-nf90-string-support`.     Have not tested it other than MAPL unit tests which do not exercise this layer.    If you have time, please give it a go.

Note, from my quick read, even the C interfaces don't support an array of strings, so for now I'm not even making this an error.

**Comment by mmanyin** [comment]
@tclune  very good!  I am out of the office this week, but will test it as soon as I have a little time.

**Comment by weiyuan-jiang** [comment]
I have tested it with my simple example. I would like to see if it is fixed in your example. @bena-nasa

**Comment by mmanyin** [comment]
The GCM release v10.19.5 (Nov 30, 2021) includes the fix.  Thanks to everyone who helped with this!
