### ISSUE TITLE
Bug detected with Intel debug flag -check all

### ISSUE THREAD

**Issue by lizziel** [GEOS-ESM/MAPL#535]
I am building and running GCHPctm using MAPL 2.2.7 with ifort18 (18.0.5) using debug flag `-check all`. The default in ESMA_cmake was previously check bounds and uninitialized variables only. With the update to check all I encounter an error in `MAPL_CubedSphereGridFactory.F90` at this line:
https://github.com/GEOS-ESM/MAPL/blob/8e1ce3623cc8459143bea3187944d5aea14f2005/base/MAPL_CubedSphereGridFactory.F90#L744-L746

The error message is as follows and occurs during `HISTORY.rc` read:
```
forrtl: severe (408): fort: (2): Subscript #1 of the array IMS has value 3 which is greater than the upper bound of 2

Image              PC                Routine            Line        Source
geos               0000000009B99E50  Unknown               Unknown  Unknown
geos               000000000764CE9E  mapl_cubedsphereg         745  MAPL_CubedSphereGridFactory.F90
geos               0000000006EF51DA  mapl_gridmanager_         151  MAPL_GridManager.F90
geos               0000000006EF682F  mapl_gridmanager_         196  MAPL_GridManager.F90
geos               0000000006EF882B  mapl_gridmanager_         248  MAPL_GridManager.F90
geos               000000000793D8C7  mapl_historygridc         639  MAPL_HistoryGridComp.F90
geos               00000000085BE979  Unknown               Unknown  Unknown
geos               00000000085C254B  Unknown               Unknown  Unknown
geos               00000000087C3125  Unknown               Unknown  Unknown
geos               00000000085BFFDA  Unknown               Unknown  Unknown
geos               0000000008D71311  Unknown               Unknown  Unknown
geos               0000000008BAFA3F  Unknown               Unknown  Unknown
geos               0000000006DE232C  mapl_genericmod_m        1824  MAPL_Generic.F90
geos               00000000085BE979  Unknown               Unknown  Unknown
geos               00000000085C254B  Unknown               Unknown  Unknown
geos               00000000087C3125  Unknown               Unknown  Unknown
geos               00000000085BFFDA  Unknown               Unknown  Unknown
geos               0000000008D71311  Unknown               Unknown  Unknown
geos               0000000008BAFA3F  Unknown               Unknown  Unknown
geos               000000000707DE72  mapl_capgridcompm         612  MAPL_CapGridComp.F90
geos               000000000707A0CB  mapl_capgridcompm         558  MAPL_CapGridComp.F90
```

I can fix the error by replacing the code with this:
```
         ! same decomposition
         ! GCHP: test each array dim separately to avoid error if debug flags on
         !equals = all(a%ims == b%ims) 
         equals = a%ims(1) == b%ims(1)
         if (.not. equals) return
         equals = a%ims(2) == b%ims(2)
         if (.not. equals) return
```

I find this rather cryptic. I do not understand why I needed to make the change but it does work to fix it. I printed out the values in all the equalities and none of them are 3, which seems to be consistent with other peoples' findings for this particular ifort error that I've found online.  Any thoughts on a better solution or why this is happening? Do you see this as well?

**Comment by tclune** [comment]
Stylistically, I prefer to instead first check the shapes.   I.e., before the offending line, insert
```
equals = (size(a%ims) == size(b%ims))
if (.not. equals) return
```

I guess that Intel must have done something "mostly harmless" (D. Adams) with the optimizer on.

**Comment by lizziel** [comment]
That solves the problem as well.

**Comment by lizziel** [comment]
I printed out the sizes and indeed, `size(a%ims)` is 4 and `size(b$ims)` is 2. My model NY is 24 and NX is 2. Is it a coincidence with these settings divide each face into 2x4 regions?

This is occurring during HISTORY.rc read. I do not apply a grid label for any of my collections so the output grid is the same as the internal grid.

**Comment by lizziel** [comment]
Here is some additional information for my c24 run with 48 cores:
```
 Reading HISTORY RC Files:
 -------------------------
grid size differs. size(a%ims) and size(b%ims):            4           2
b%ims :           12          12
a%ims :            6           6           6           6
```

**Comment by tclune** [comment]
I need to discuss this further with @bena-nasa and @atrayano, but I have a suspicion as to what is happening.   But it would not explain why we're not seeing that same failure on our end.

Nominally your NY and NX imply that you are running on 48 processes with 8 processes per face.   This means the only "clean" decompositions of a face are   1x8, 2x4, 4x2, and 8x1.    And several factors encourage more even aspect ratios, so your observations are not a complete coincidence.

Because of the server aspect, I think History has flexibility in choosing a decomposition.   I know that ExtData often is forced to choose a different layout than implied by NX, NY so that coarse lat/lon grids can still be decomposed at high process counts.    So it may just be that we (@mathomp4) always choose NX=4 for 48 process runs and get "lucky" regarding the missing check.

In any event, I'm 100% confident the missing check is required.    Since you already have it implemented and tested, I encourage you to do a PR for this issue.

**Comment by mathomp4** [comment]
Hmm. How does one trigger this? I just tried running GEOS GCM C24 at 2x24, 3x18, and 4x12 with `-check all,noarg_temp_created` and none of them crashed. Well, after an hour. Do you need to have HISTORY write to see it?

**Comment by tclune** [comment]
You need to have History write some field at native resolution.

**Comment by tclune** [comment]
@lizziel Can you upload your History.rc file?    Native output should not be defining another grid.

**Comment by lizziel** [comment]
The HISTORY.rc I am using is [here](https://github.com/geoschem/geos-chem/blob/dev/gchp_13.0.0/run/GCHPctm/HISTORY.rc.templates/HISTORY.rc.benchmark).

**Comment by bena-nasa** [comment]
Lizzie, you don't need to specify the native grid (c24) in the grid labels list.  History can get this from the fields which already have a grid.

**Comment by atrayano** [comment]
@bena-nasa I agree that @lizziel does not need to specify the grid_label for the native grid, but she is not referencing it anywhere

**Comment by tclune** [comment]
Do we have a mechanism to explicitly confirm that the native grid is to be used?      Having it default to native is good, but I think a best practice would be to explicitly confirm this.   I suppose a comment line could be used.

**Comment by bena-nasa** [comment]
If the collection doesn't have a grid label keyword the native grid is used. You mean like a message to the log confirming this?

**Comment by lizziel** [comment]
A bit of background on this file... The HISTORY.rc is meant to educate users who don't know how to fill it out. The labels at the top are examples. In this case the native run (for benchmark simulation ) is c48 by default so the c24 label is available there if users want to output at higher resolution, to save space for example. Then they don't need to go digging in the wiki to figure out how to do it.

**Comment by tclune** [comment]
@bena-nasa   No I meant something like   
```
foo.grid_label: native
```

**Comment by mathomp4** [comment]
@tclune @bena-nasa Was this fixed? Or was this a "wontfix"?

**Comment by tclune** [comment]
It's a "wontfix".
