### ISSUE TITLE
Some files in MAPL define their own error macros

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#538]
Just adding this as a reminder to clean this up as time permits.
I noticed that some files in MAPL are defining their own ASSERT, VERIFY, etc... macros. The grid factories in particular. These should be cleaned up to use the common error handling macros.

**Comment by mathomp4** [comment]
I stared at this and it looks like we might be nearly clean:
```console
❯ rg assert | rg '#define'
base/tests/MockRegridder.F90:#define _ASSERT(A)   if(.not.A) then; if(present(rc)) rc=_FAILURE; PRINT *, Iam, __LINE__; return; endif
base/tests/MockGridFactory.F90:#define _ASSERT(A)   if(.not.A) then; if(present(rc)) rc=_FAILURE; PRINT *, Iam, __LINE__; return; endif
pfio/DownBit.F90:#define _ASSERT(A)   if(.not.(A)) then; if(present(rc)) rc=_FAILURE; PRINT *, Iam, __LINE__; return; endif
Tests/VarspecDescription.F90:#define _ASSERT(A)   if(.not.A) then; if(present(rc)) rc=_FAILURE; PRINT *, Iam, __LINE__; return; endif
shared/MAPL_Range.F90:#define _ASSERT(A)   if(.not.A) then; if(present(rc)) rc=_FAILURE; call MAPL_throw_exception(__FILE__,__LINE__); return; endif
include/MAPL_ErrLogMain.h:#define ASSERT_(A) if(MAPL_ASRT(A,Iam,__LINE__,RC))call MAPL_abort
```
Of these:
```
pfio/DownBit.F90
shared/MAPL_Range.F90
```
seem to be the main ones to consider (for `_ASSERT`). 

As I see files in both `pfio/` and `shared/` using `_ASSERT` I can assume this can be "fixed"? Maybe I'll give it a try and let you and @weiyuan-jiang judge me!

**Comment by tclune** [comment]
Yeah - I did a fair bit on this back in December.    I recommend doing any of the remainder that are "easy" and closing this issue.
