### ISSUE TITLE
Getting grid-box corners out of HISTORY

### ISSUE THREAD

**Issue by LiamBindle** [GEOS-ESM/MAPL#541]
For seamless plotting of data on curvlinear grids with functions like matplotlib's [`pcolormesh(X, Y, C)`](https://matplotlib.org/3.3.1/api/_as_gen/matplotlib.pyplot.pcolormesh.html), the grid-box corner coordinates are needed. Would it be possible to get corner coordinates in diagnostics out of HISTORY? Functions like `pcolormesh()` expect `X` and `Y` to be size `N+1` if the shape of `C` is `(N, N)`, so corners with duplicates (between faces) would be preferred.

Following up on geoschem/GCHPctm#38 and this comment by @tclune 
> I have discussed with @atrayanov and @ben-nasa and they think this will be straightforward. Please open a ticket in MAPL and assign to @ben-nasa.
> 
> Basically we already have a per-grid factory with a method that specifies metadata. That routine would need a few more lines to add metadata for corners. And then the generic layer that sends data to the I/O server needs a few lines to extract the actual values of the coordinates from the ESMF Grid object. The biggest concern is the handling of the duplicate corners, and the MAPL ticket you would open is the best place to discuss that.

**Comment by bena-nasa** [comment]
Liam,
This should be doable. I need to have the cube grid factory add this to the file metadata; define the extra dimensions, new variables etc .. and then add an extension of an existing routine to pull the corners from grid and  them properly communicated and written by the IO layer when the file is actually written. I'll give it a go in the next couple days and see if there are any problems I'm not anticipating.

**Comment by mathomp4** [comment]
Hmm. I wonder if/when this is done if I should ping Robert Schmunk? Perhaps Panoply could use something like this to make it better/easier for his plotting of our data (like the cube)?

**Comment by LiamBindle** [comment]
> So if I define a grid corner variables for the lat and lons that is dimensioned as (xdim+1,xdim+1,nf) where xdim is the number of cells in each direction on the cube is what you would need?

Yes, that's corect. The ordering `(nf, Ydim+1, Xdim+1)` would be prefered, however, since that's the ordering of our fields.

> You only need this for the cube right?

Yes, cubed-sphere grids (with stretcheding support too). The corners aren't needed for plotting regular grids, so I don't think this needs to be added for latlon grids.

Thanks!

**Comment by tclune** [comment]
@LiamBindle We speak Fortran here.  The ordering is `(Xdim+1, Ydm+1, nf)`.    :-)

**Comment by bena-nasa** [comment]
That turned out to be easy. I have a prototype working, any votes for the extra dimension names and the extra variable names. We have Xdim,Ydim, lons, lats. I created a Xdime,Ydime, corner_lons, corner_lats.  I can call them something else. The values seem reasonable.
```
netcdf testedge.geosgcm_prog.20000414_2200z {
dimensions:
        Xdim = 24 ;
        Xdime = 25 ;
        Ydim = 24 ;
        Ydime = 25 ;
        ncontact = 4 ;
        nf = 6 ;
        orientationStrLen = 5 ;
        time = UNLIMITED ; // (1 currently)
variables:
        double Xdim(Xdim) ;
                Xdim:long_name = "Fake Longitude for GrADS Compatibility" ;
                Xdim:units = "degrees_east" ;
        double Ydim(Ydim) ;
                Ydim:long_name = "Fake Latitude for GrADS Compatibility" ;
                Ydim:units = "degrees_north" ;
        int nf(nf) ;
                nf:axis = "e" ;
                nf:grads_dim = "e" ;
                nf:long_name = "cubed-sphere face" ;
        int ncontact(ncontact) ;
                ncontact:long_name = "number of contact points" ;
        char cubed_sphere ;
                cubed_sphere:additional_vars = "contacts,orientation,anchor" ;
                cubed_sphere:file_format_version = "2.90" ;
                cubed_sphere:grid_mapping_name = "gnomonic cubed-sphere" ;
                cubed_sphere:gridspec_file = "gridspec.nc4" ;
        int contacts(nf, ncontact) ;
                contacts:long_name = "adjacent face starting from left side going clockwise" ;
        char orientation(nf, ncontact, orientationStrLen) ;
                orientation:long_name = "orientation of boundary" ;
        int anchor(nf, ncontact, ncontact) ;
                anchor:long_name = "anchor point" ;
        float lons(nf, Ydim, Xdim) ;
                lons:long_name = "longitude" ;
                lons:units = "degrees_east" ;
        float lats(nf, Ydim, Xdim) ;
                lats:long_name = "latitude" ;
                lats:units = "degrees_north" ;
        float corner_lons(nf, Ydime, Xdime) ;
                corner_lons:long_name = "longitude" ;
                corner_lons:units = "degrees_east" ;
        float corner_lats(nf, Ydime, Xdime) ;
                corner_lats:long_name = "latitude" ;
                corner_lats:units = "degrees_north" ;
```

**Comment by LiamBindle** [comment]
My vote would be for `XEdim` and `YEdim`, but I don't feel strongly

**Comment by bena-nasa** [comment]
It will be, it will be on develop. We can always create a new release.

**Comment by tclune** [comment]
I'm missing it.  Where is "E" coming from?   Wouldn't "C" for corner make more sense?

**Comment by bena-nasa** [comment]
E for edge, but C does make more sense.

**Comment by LiamBindle** [comment]
I agree C would be better. I have my own script to do this and I've used the word "edge" so I'm just used to it...I agree that C is better

**Comment by mathomp4** [comment]
Closing as this looks to be done
