### ISSUE TITLE
Reading/Writing ESMF routehandles when regridding exposes strange non-zero diff behavior

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#551]
I'm seeing a very strange thing that I'm recording here for my memory. I was playing with the ESMF ability to write/read the generated route handle for operations like regriddding. I modified the MAPL_EsmfRegridder.F90 to generate a unique file name from the 2 grids that encodes the grid size and the layout the grid was generated on. 

The MAPL_EsmfRegridder.F90 stores a routehandle map, with the key being the RegridderSpec, and the value an ESMF routehandle, the idea being if you have a spec with two grids you avoid regenerating the route handle. I added logic so that if it decides it needs to generate a new routehandle, first check if the route handle file exists, if so read the route handle from the file, if not generate it and write it to the file.

I tested this with Regrid_Util.x and confirmed I could run the program, get an output file and that the routehandle file was generated. I then could rerun, confirm it was now reading the route handle and get identical output. So far, so good. I then tried this running the full GEOSgcm.x with this change and was getting non-zero diff.

Digging into this I noticed a couple things, first the mechanism to prevent redundant generation of routehandles seems to be not working. The subroutine that creates the route handle has an if statement like so:
```
if (route_handles%count(spec) == 0)
```
so if there is a route_handle with the spec as the key, we skip the generation. After this my modified code has another if/else layer to test if the file exists with the route handle. I put a print before this if to get the size of the route handle, and the count for the spec, and print if I am reading or writing the file. If this works as expected I should never see anyone reading as the route handle files don't exist when I run gcm_run.j and each unique route handle should only be generated once. But that is not what I see, instead I see this reported:
```
 bmaa number:                      0                     2
 bmaa writing DC1152xPC0721_0012x0008__CF0024x6C_0004x0004.rh
 bmaa number:                      0                     3
 bmaa writing DC0360xPC0181_0012x0008__CF0024x6C_0004x0004.rh
 bmaa number:                      0                     4
 bmaa writing DC0144xPC0091_0012x0008__CF0024x6C_0004x0004.rh
 bmaa number:                      0                     5
 bmaa writing DC0288xPC0181_0012x0008__CF0024x6C_0004x0004.rh
 bmaa number:                      0                     6
 bmaa writing DC0576xPC0361_0012x0008__CF0024x6C_0004x0004.rh
 bmaa number:                      0                     7
 bmaa reading: DC0144xPC0091_0012x0008__CF0024x6C_0004x0004.rh
 bmaa number:                      0                     8
 bmaa writing DC0540xPC0361_0012x0008__CF0024x6C_0004x0004.rh
 bmaa number:                      0                     9
 bmaa writing GC0144xPC0091_0012x0008__CF0024x6C_0004x0004.rh
 bmaa number:                      0                    10
 bmaa reading: DC0288xPC0181_0012x0008__CF0024x6C_0004x0004.rh
 bmaa number:                      0                    11
 bmaa writing GC0720xPE0360_0012x0008__CF0024x6C_0004x0004.rh
 bmaa number:                      0                    12
 bmaa reading: DC0144xPC0091_0012x0008__CF0024x6C_0004x0004.rh
 bmaa number:                      0                    13
 bmaa writing GE0720xPE0360_0012x0008__CF0024x6C_0004x0004.rh
 bmaa number:                      0                    14
 bmaa writing DC0720xPC0361_0012x0008__CF0024x6C_0004x0004.rh
```
Two mysteries; first it seems that even when the spec has identical grids the count fails and it goes into the if to generate the route handle as the count is always 0. Fine, but then it should be reading the route handle which was just generated which which should be identical so it should be zero-diff which but this is not when running GEOS.

I'm not sure what is going other other than things don't make sense. I will have to dig deeper.

**Comment by tclune** [comment]
I'm not quite sure I fully understand what you are saying is happening.     If the `count()` mechanism is not working this would suggest that we regenerate RouteHandles at every regridding step in GEOS.     This is independent of your intended changes.

I suppose it may still be inexpensive if ESMF is determining that the RH was already computed and their cacheing is protecting a failure in ours?

**Comment by bena-nasa** [comment]
There are two things going on:
1. The count() mechanism is not working it appears
2. When I implement the read/write of the route handle and run GEOSgcm.x it ends up reading the route handle from file it just generated because of the failure in 1 rather than saying; I've already generated this, I don't need to generate a new route handle, whether from file via ESMF_RoutHandleCreate or via the EMSF_FieldRegridStore call. This non-zero diff and I don't understand why yet. 

This seems strange. One possibility there is something subtle I'm missing. I was just recording this yesterday so I would remember the details this morning.

**Comment by bena-nasa** [comment]
Nevermind, it was different regrid methods. I forgot to encode the regrid method in the filename. All is well.
