### ISSUE TITLE
Inconsistency in cubed sphere output in MAPL 1.x

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#573]
Ricardo found an issue when using History with MAPL v1.x, not this is a non-issue in MAPL v2.x since that is no longer using CFIO in History and does not support the "old format" cubed-sphere output

For the purposes of the discussion the "old format" is the cubed output that does not have the face as an explicit dimension, "new format" does have the face as a dimension.

Ricardo found this oddity. 
The MAPL_CFIO layer has this logic put in a long time ago when we first moved the new format that force any regridded output to be in old format.
However, there is an inconsistency.
If you request native cubed output in the old format you get this in the file:
```
dimensions:
        Xdim = 48 ;
        Ydim = 288 ;
        lev = 48 ;
```
but if you regrid to a different cube resolution you get this:
```
dimensions:
        lon = 48 ;
        lat = 288 ;
        lev = 48 ;
```
This is all because normally if you ask for native output there is a logical "isRectilinear" in MAPL_CFIOCreate that is set to true for the cube or tripolar grid. However, if it detects you are changing resolution at all, isRectilinear is false. and the use of the new cubeformat is set to false.

Ultimately this controls whether the call to little cfio forces the use xdim/dym or lon/lat for the horizontal (this is true even for non-cubed output).

That is the first thing
Testing this I discovered what appears to be a bug.
What I described above is what we see when you set VERSION: 1 in the history.rc file.

If you set VERSION: 0 something must go wrong as if ask for regridded cubed-sphere output you get native output.
Luckily the History.rc being used everywhere have VERSION: 1

This kluge to force the gridded files to be the old format may not even be necessary anymore has MAPL_CFIO can read the files in the new format. We could not remember exactly why the old format was necessary at the time for the DAS workflow.

**Comment by mathomp4** [comment]
@bena-nasa Have you fixed this?

**Comment by mathomp4** [comment]
Reexamined on 2021-Apr-12 with @bena-nasa and @tclune 

Labeling wontfix and closing
