### ISSUE TITLE
HISTORY problem with lat,lon coordinates in diagnostics of multi-node simulations

### ISSUE THREAD

**Issue by LiamBindle** [GEOS-ESM/MAPL#579]
Hi everyone,

A GCHPctm user (@joeylamcy) has reported an issue in the output of his multi-node simulations (https://github.com/geoschem/GCHPctm/issues/37). Specifically, the `lat` and `lon` coordinates are erroneous, but the rest of the diagnostic's data is okay. For single node simulations, `lat` and `lon` are okay, but for multinode simulations there are big blocks of `lat` and `lon` that are close to zero.

The user reported the issue in GCHPctm version 13.0.0-alpha.9 which uses MAPL @ fca3b33. He is using ifort 19.0.4, intel MPI, netcdf-c 4.7.1 and netcdf-fortran 4.5.2.

To try and gather more information on the problem, he reran the following simulation on 1 node, 2 nodes, 3 nodes, and 4 nodes. The configuration of this simulation was
- 1 hour simulation, normal GCHPctm configuration
- 6 cores per node, 100 GB memory per node
- The following HISTORY.rc:
  ```
    TestCollectionNative.template:   '%y4%m2%d2_%h2%n2z.nc4',
    TestCollectionNative.format:     'CFIO',
    TestCollectionNative.frequency:  010000
    TestCollectionNative.duration:   010000
    TestCollectionNative.mode:       'time-averaged'
    TestCollectionNative.fields:     'SpeciesConc_O3', 'GCHPchem',
  ::
  ```

No errors or warnings were raised in the simulations log files.

### Results

Note: The narrow blank bands between faces, like in the figure directly below, are because of my plotting routine.

**When the simulation ran on 1 node**
![1_node_native](https://user-images.githubusercontent.com/12772306/96184715-7a397500-0efe-11eb-9352-428d0577fc9a.png)

**When the simulation ran on 2 nodes**
![2_node_native](https://user-images.githubusercontent.com/12772306/96184737-802f5600-0efe-11eb-8ded-d7851bf65cb3.png)

**When the simulation ran on 3 nodes**
![3_node_native](https://user-images.githubusercontent.com/12772306/96184975-d8665800-0efe-11eb-8b89-dd0c999d08d5.png)

**When the simulation ran on 4 nodes**
![4_node_native](https://user-images.githubusercontent.com/12772306/96184754-84f40a00-0efe-11eb-80b3-8387fdba53c9.png)

### Other results

Adding `TestCollectionNative.conservative: 1` for the 4-node simulation produced a different result:

![4_node_native_cons](https://user-images.githubusercontent.com/12772306/96186439-0ea4d700-0f01-11eb-87ea-5fccd2ac6301.png)

Changing the position of `TestCollectionNative.conservative: 1` line in the collection also produced a different result:

![4_node_native_cons_other](https://user-images.githubusercontent.com/12772306/96186636-5af01700-0f01-11eb-9d5c-bfd7a8228248.png)

### The diagnostic's data is okay though

**Interestingly, it is only the `lat` and `lon` coordinates that are problematic.** The diagnostic's data variables (i.e. SpeciesConc_O3) are okay. For example, if I calculate the coordinates offline, and then replot the diagnostic output, the figures look okay.

--- 

Has anyone seen this before? Do you have any thoughts or ideas? Thanks in advance!
-Liam

**Comment by tclune** [comment]
I don't think we've seen this before and since we routinely produce lat-lon output while using multiple nodes, there must be another factor that is triggering this.

**Comment by tclune** [comment]
Several of the intermediate plots suggest that the problem is correlated with the metadata being wrong for entire faces of the cubed sphere.   But subsequent examples are more complicated than that.

**Comment by bena-nasa** [comment]
So the bottom line is, you run on different core counts and based on how many nodes that represents you get different cubed-sphere output, with the only difference being in the lats and lons? Does it look like the lats and lons in the bad cases were written with something, just bad data, or are they true missing values. I will look at the code but I'm having a hard time figuring out how all the other variables could be written correctly.

**Comment by LiamBindle** [comment]
Yeah this is strange. We've been running lots of multinode simulations too, and we've never seen anything like this before.

> So the bottom line is, you run on different core counts and based on how many nodes that represents you get different cubed-sphere output, with the only difference being in the lats and lons?

Yes. On one node `lat` and `lon` look okay, but on multiple nodes they go bad. 

>  Does it look like the lats and lons in the bad cases were written with something, just bad data, or are they true missing values. I will look at the code but I'm having a hard time figuring out how all the other variables could be written correctly.

I just took a closer look. For some reason, it appears `lat` and `lon` have similar values to the data field at the surface (i.e., SpeciesConc_O3 at lev=0). This truely puzzles me.

Below are some images (2d plots) of `lat` and `lon` for face 4 for the 4 node simulation (a face with "problematic" coordinates).

Image of lons:
![image](https://user-images.githubusercontent.com/12772306/96297919-40787500-0fb7-11eb-806a-c29d04443cae.png)

Image of lats:
![image](https://user-images.githubusercontent.com/12772306/96298078-787fb800-0fb7-11eb-8d42-63dcff8d83e7.png)

Image of SpeciesConc_O3:
![image](https://user-images.githubusercontent.com/12772306/96298320-e0360300-0fb7-11eb-8d74-51fc13a90e63.png)


Note that `lats` and `lons` are not equal to each other or SpeciesConc_O3, but they are similar (e.g. within ~5%). The plots above show that `lats` and `lons` are being written with data that's similar to the fields data.

Here is what SpeciesConc_O3 looks like at level 30. This plot confirms that `lons` is similar to the data at the surface.

![image](https://user-images.githubusercontent.com/12772306/96299395-a0701b00-0fb9-11eb-82de-39756f7539d5.png)


And here is what `lons` looks like for a face 4 when the coordinate is written correctly. This plot shows what an image of `lons` should look like.

![image](https://user-images.githubusercontent.com/12772306/96299465-bd0c5300-0fb9-11eb-8316-bb7693d17c36.png)


I'm thoroughly stumped.

**Comment by LiamBindle** [comment]
Not sure if this is helpful, but here is the NetCDF file: 
[GCHP.TestCollectionNative.20160701_0030z.zip](https://github.com/GEOS-ESM/MAPL/files/5393879/GCHP.TestCollectionNative.20160701_0030z.zip)

And here is the same file for the 1-node simulation:
[GCHP.TestCollectionNative.20160701_0030z.zip](https://github.com/GEOS-ESM/MAPL/files/5393882/GCHP.TestCollectionNative.20160701_0030z.zip)

**Comment by LiamBindle** [comment]
I'm going to close this issue. We aren't able to reproduce the issue, and there's a easy work around we recommended to the user. I'll reopen if we get any more reports of this.

Thanks for everyone's time in looking into this!
