### ISSUE TITLE
timestampEnd

### ISSUE THREAD

**Issue by wmputman** [GEOS-ESM/MAPL#602]
I'm getting an error when I try to use (timestampEnd) in my HISTORY.rc for a time-averaged file:
FAIL at line=01091    MAPL_HistoryGridComp.F90 

Does this still work?

**Comment by atrayano** [comment]
@wmputman could you point me to your HISTORY.rc, and your MAPL version. I am suspecting History expects a logical, and we are supplying integer

**Comment by atrayano** [comment]
@tclune I already asked Bill for his HISTORY.rc. The code MAPL should be able to handle timestampEnd, and my theory is that since the variable is logical, this simply could be integer vs logical in the resource file issue

**Comment by lizziel** [comment]
I am interested to see what the HISTORY.rc looks like for this feature and how it is used. This is a MAPL history feature I don't think anyone in the GEOS-Chem community is aware of.

**Comment by mathomp4** [comment]
Commenting here. For some reason, if you did:
```
collection.timestampEnd: .true.
```
it fails. But if you 'quote' the true, it works:
```
collection.timestampEnd: '.true.'
```

I've stared at the code and cannot figure out why it needs to be a string.

**Comment by lizziel** [comment]
I would like to test this in GCHP as well. What is the expected behavior?

**Comment by mathomp4** [comment]
> I would like to test this in GCHP as well. What is the expected behavior?

@lizziel I think all it does is change the timestamp on the file that MAPL writes out. Using `geosgcm_tracer` (which is a 3-hourly time-averaged collection) as an example, without the flag you get:
```
Writing:    186 Slices to File:  stock-gcm-2020Nov10-6hour-c12-nomkl-6020.geosgcm_tracer.20000414_2230z.nc4
Writing:    186 Slices to File:  stock-gcm-2020Nov10-6hour-c12-nomkl-6020.geosgcm_tracer.20000415_0130z.nc4
```
So the time stamp is midway between the collection period. With the flag:
```
Writing:    186 Slices to File:  stock-gcm-2020Nov10-6hour-c12-nomkl-6020.geosgcm_tracer.20000415_0000z.nc4
Writing:    186 Slices to File:  stock-gcm-2020Nov10-6hour-c12-nomkl-6020.geosgcm_tracer.20000415_0300z.nc4
```
the stamp is at the end of the period.

(Though now that I look at it, the tracer collection is...not quite set up in HISTORY.rc as I would do it. Hmm. I guess I should file an issue about that.)

**Comment by mathomp4** [comment]
Reexamined on 2021-Apr-12 with @bena-nasa and @tclune 

@atrayano noted something similar in #802
