### ISSUE TITLE
--npes_output_server argument being ignored

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#628]
I'm trying to run a split model/oserver case on one node due to the difficulty in getting nodes currently on Discover, MAPL develop branch as of today (12/7) I have the model set to use 12 cores (NX: 2 NY: 6) and am running GEOS like this:

mpirun -np 18 GEOSgcm.x --npes_model 12 --npes_output_server 6 --logging_config 'logging.yaml'

It appears to be ignoring both npes arguments are just running the model on 18 cores. Was the intent of the --npes_output_server argument that you could run like this and I am seeing a bug or am I misunderstanding?

**Comment by bena-nasa** [comment]
Something seems to be broken in develop. I tried running on 2 nodes, asked explicitly for 24 cores per node, model on 24 cores, server on a node (24 cores) and it still just tries to run the model on 48 cores.

**Comment by weiyuan-jiang** [comment]
I believed I have run that small jobs before and it seemed OK. I will try again.

**Comment by bena-nasa** [comment]
Matt tried 2.4 and says it works. 2.4 does not have the cap in gridcomps which is now in develop. I'm wondering if that somehow broke flap. From the prints I put in, it seems like any command line options are just being ignored.

**Comment by bena-nasa** [comment]
nevermind, apparently you have to explicitly toggle something in the gcm_run.j script, just setting the server nodes to something in the AGCM.rc is not enough. False alarm.

**Comment by bena-nasa** [comment]
I was too hasty. 24-24 works (24 cores for the model, 24 cores for the server on a separate node). However, 
```
mpirun -np 18 GEOSgcm.x --npes_model 12 --npes_output_server 6 --logging_config 'logging.yaml'
```
seems to cause a hang with develop

**Comment by weiyuan-jiang** [comment]
For above to work, we need to pass in "isolate_nodes=.false." which is not in the flap.  I will fix it

**Comment by tclune** [comment]
There is some special logic for when all the cores fit on one node, which your case maybe does?   I did that to allow using an external server or my laptop - so that I could test locally.   It's probably not been exercised in a couple of years now and that logic could now be broken with the new command line options.

**Comment by tclune** [comment]
Ah - I had not read @weiyuan-jiang 's message.    Yes -that seems related.

**Comment by weiyuan-jiang** [comment]
@bena-nasa can you try the branch https://github.com/GEOS-ESM/MAPL/compare/feature/wjiang/pass_in_isolated_node ?
add " --isolate_nodes .false. " in the command line should work.  I don't know why gcm broke for me.  I believe it is not related to this branch because it passes the init stage

**Comment by bena-nasa** [comment]
closing this. I think the PR from the referenced branch fixed this.
