### ISSUE TITLE
Could HISTORY output include stretching parameters?

### ISSUE THREAD

**Issue by LiamBindle** [GEOS-ESM/MAPL#634]
During the MAPL telecon today, the question of stretched-grid parameters in HISTORY output came up. Is it possible to include the stretched-grid parameters as metadata in HISTORY output?

**Comment by bena-nasa** [comment]
@LiamBindle 
Added by https://github.com/GEOS-ESM/MAPL/pull/638
Not sure why this didn't autoclose

**Comment by mathomp4** [comment]
> @LiamBindle
> Added by #638
> Not sure why this didn't autoclose

Github only autocloses issues when they get to the "default" branch. So it would close next time we merge to `main`.
