### ISSUE TITLE
Can checkpoint files include stretched-grid metadata?

### ISSUE THREAD

**Issue by LiamBindle** [GEOS-ESM/MAPL#636]
Is it possible for checkpoint files to include grid-stretching metadata? That way, if the checkpoint file's stretched-grid parameters were different from the native grid's parameters the error could be caught.

**Comment by mathomp4** [comment]
I'm thinking this might be a long-term project by @bena-nasa or @atrayano so marking long-term.

**Comment by bena-nasa** [comment]
The checkpoint files should include this now as of MAPL v2.8.1, closing the issue.
