### ISSUE TITLE
Time for MAPL_IO refactoring?

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#641]
Multiple feature requests have been made for the restart IO layer in MAPL.
https://github.com/GEOS-ESM/MAPL/issues/639
https://github.com/GEOS-ESM/MAPL/issues/635

Putting this out here for comment about the general state of MAPL restart IO. Those requests referenced above made me think it is time we at least have a discussion about refactoring of MAPL_IO.

MAPL_IO has reached a state that it is in need to of refactoring to make such requests easier to handle and just for future maintainability if we want to leverage redundant capabilities used by ExtData and History. It is also probably one of the longest or longest source file in MAPL.

The problem: it must currently support both netcdf and binary input/output for:
1D/2D/3D/4D R4/R8 variables needed by MAPL components on both regular gridded distributions (2 distributed dimensions), on the tile distribution (1 distributed dimension, arbitrarily distributed, must be reassembled in original order), and not distributed at all (1D variables like AK/BK). The undistributed dimensions represent edges, centers, or multiple arbitrary undistributed dimensions and generally exist in combination with the distributed dimensions (AK/BK is the exception).
Also supports some IO parallelism which does provide some benefit at higher resolutions for regular gridded variables.

Due to MERRA2 and older OPS version still having produced binary restarts, support for the this is regrettably probably a requirement for GEOS for the near future.

At the very least, it has probably reached a point where the code could be refactored into separate binary and netcdf layers so the netcdf can evolve, and the binary can just exist without getting in the way of future developments until it can be retired.

Other considerations.
Conceptually there should be some overlap between History/ExtData/restart IO in terms of the code base. Currently there is pretty much none. For example, it would seem logical that gridded output, whether for History or restarts really is no different and could certainly share a fair amount of code, for example, specification of metadata.

**Comment by mathomp4** [comment]
Reexamined on 2021-Apr-12 with @bena-nasa and @tclune

**Comment by bena-nasa** [comment]
Just adding a comment as a reminder of this. I added a new feature that reminded me that we really should do this. At the very least split apart MAPL_IO into separate binary and NetCDF modules so we can have some hope of cleaning this up the NetCDF handling someday.
