### ISSUE TITLE
Two variables in native cube output are broken

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#642]
This was discovered by @aoloso when testing the compress-and-compare of @wmputman 's DYAMOND2 data. Namely, two variables in the CS native output are garbage. They are defined as variables but never set it looks like, so you get...uninitialized junk in them. Luckily they seem to be variables nothing cares about, but we should fix it.

The big broken variable is `orientation` and the other one I suspect is broken is `cubed_sphere`. To wit:
```console
❯ ncks -L 1 inst_15mn_2d_asm_Mx.20000414_2200z.nc4 compressed.nc4
❯ nccmp -dfsB inst_15mn_2d_asm_Mx.20000414_2200z.nc4 compressed.nc4
DIFFER : VARIABLE : orientation : POSITION : [0,0,0] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [0,0,4] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [0,1,3] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [0,2,2] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [0,3,1] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [1,0,0] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [1,0,4] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [1,1,3] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [1,2,2] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [1,3,1] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [2,0,0] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [2,0,4] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [2,1,3] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [2,2,2] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [2,3,1] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [3,0,0] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [3,0,4] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [3,1,3] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [3,2,2] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [3,3,1] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [4,0,0] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [4,0,4] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [4,1,3] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [4,2,2] : VALUES :  <>
DIFFER : VARIABLE : orientation : POSITION : [5,0,0] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,0,1] : VALUES : = <>
DIFFER : VARIABLE : orientation : POSITION : [5,0,2] : VALUES : 7 <>
DIFFER : VARIABLE : orientation : POSITION : [5,0,3] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,0,4] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,1,0] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,1,1] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,1,2] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,1,3] : VALUES : \ <>
DIFFER : VARIABLE : orientation : POSITION : [5,1,4] : VALUES : P <>
DIFFER : VARIABLE : orientation : POSITION : [5,2,0] : VALUES : 5 <>
DIFFER : VARIABLE : orientation : POSITION : [5,2,1] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,2,2] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,2,3] : VALUES : w <>
DIFFER : VARIABLE : orientation : POSITION : [5,2,4] : VALUES : T <>
DIFFER : VARIABLE : orientation : POSITION : [5,3,0] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,3,1] : VALUES : � <>
DIFFER : VARIABLE : orientation : POSITION : [5,3,2] : VALUES : \ <>
DIFFER : VARIABLE : orientation : POSITION : [5,3,3] : VALUES : 3 <>
DIFFER : VARIABLE : orientation : POSITION : [5,3,4] : VALUES : � <>
```
It looks like `ncks` compresses the garbage into *different* garbage, so that `nccmp` says, well, they are different. (I wonder if this is a bug in libz? Seems like zip should be able to compress anything even junk...)

Speaking with @tclune, he looked at this code:
https://github.com/GEOS-ESM/MAPL/blob/8e933d8adf111af0d4215ecf09c7e0dbe1388ff9/base/MAPL_CubedSphereGridFactory.F90#L908-L936
where it looks like `cvar` that was filled back in old Developer Git days (https://developer.nasa.gov/GMAO/GEOSagcm/blob/4efb0f3c6210c84fc2cf1380be34c37104ad591c/src/GMAO_Shared/MAPL_cfio/ESMF_CFIOSdfMod.F90#L2347-L2390) was commented out and then `orientation` was never filled. He suspects maybe this was a GNU compiler issue maybe? Unknown as this code has been commented forever it looks like here in GitHub.

I'm also concerned about the other `char` variable `cubed_sphere` where it is declared:
https://github.com/GEOS-ESM/MAPL/blob/8e933d8adf111af0d4215ecf09c7e0dbe1388ff9/base/MAPL_CubedSphereGridFactory.F90#L888-L893
but I can't see anything ever actually filling it.

**Comment by mathomp4** [comment]
Note: This might be an opportunity as well for @bena-nasa and myself. Perhaps we should come up with a special `HISTORY.rc.tmpl` we could have my nightly tests run. The reason this was never caught is that my nightly tests use the "standard" @sdrabenh / @lltakacs `HISTORY.AGCM.rc.tmpl` for most tests. They don't have cube-output so I don't have cube output. 

But if @bena-nasa could dream up a crazy HISTORY with varying code paths it could be a good test.

**Comment by mathomp4** [comment]
@bena-nasa Did we ever fix this? I want to say you looked at it...

**Comment by mathomp4** [comment]
@bena-nasa Did your recent work on the cube sphere factories, etc. fix this?

**Comment by mathomp4** [comment]
Okay. This is a fun one. @bena-nasa and I looked at this and we figured out there might be *NO* way for either of these to be written out. Why? Well if you look at `write_const_variables` in `pfio/NetCDF4_FileFormatter.F90`:
https://github.com/GEOS-ESM/MAPL/blob/beba7fc571c9096b9b0897b4966d8ee0d10ba987/pfio/NetCDF4_FileFormatter.F90#L466-L484
A string would fall under `class default` and...fail!

So, as a stopgap, what I (and @bena-nasa) is proposing is multi-fold:
1. Remove the `cubed_sphere` variable. We do not see the need for it.
2. Comment out the `orientation` variable until pFIO supports string variables

**Comment by weiyuan-jiang** [comment]
You are right we cannot write string variable at this moment. Is that important ? can that be in attribute section?

**Comment by mathomp4** [comment]
@weiyuan-jiang At the *moment* it seems to be okay not to do. The issue would arise in the future if there was a "standard" cubed-sphere format where this would become important.

**Comment by tclune** [comment]
If there is a reasonably straightforward fix for this, my preference would be to enable this now.    Even if it has to be disabled for gfortran.
