### ISSUE TITLE
GEOS runs with wrong restarts!

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#643]
This is something mentioned by @sdeastham in #639. Namely, GEOS doesn't die as fast as I'd expect if you have the wrong restarts. To wit, I made a C24 experiment, but used C48 restarts to run with. Now, GEOS at first will die because of the salt tile checker:
```
Error! Found 99389 tiles in openwater. Expect to find 69464 tiles.
Your restarts are probably for a different ocean.
```
But let's say we don't have that check. If we comment that out, the model will run a fair bit. Indeed, I think it only dies in the ***Run*** method of Catch!
```
...
 Real*4 Resource Parameter: SOLAR_CONSTANT:-1.000000
 Character Resource Parameter: SOLAR_CYCLE_FILE_NAME:ExtData/g5gcm/solar/NRLSSI2.v2017.txt
 Logical Resource Parameter: USE_NRLSSI2:T
 Logical Resource Parameter: PERSIST_SOLAR:T
 Integer*4 Resource Parameter: INTERPOLATE_ATMTAU:0
 Real*4 Resource Parameter: LANDICEEMISS:.999990
 Real*4 Resource Parameter: LANDICEALBEDO:.580000
 Real*4 Resource Parameter: LANDICEDEPTH:.070000
 Real*4 Resource Parameter: LANDICECOND:1.200000
 Real*4 Resource Parameter: LANDICETDEEP:230.000000
 Integer*4 Resource Parameter: INCL_LOUIS_EXTRA_DERIVS:1
 Character Resource Parameter: VISDF_FILE:visdf.dat
 Character Resource Parameter: NIRDF_FILE:nirdf.dat
 NOT using buffer I/O for file: visdf.dat
 Previous time forVISDFs is:
           1           4           7           0           0           0
           1           4          15           0           0           0
 NOT using buffer I/O for file: nirdf.dat
 Previous time forNIRDFs is:
           1           4           7           0           0           0
           1           4          15           0           0           0
 CATCH_INTERNAL_RST is NOT consistent with VEGDYN Data
 CATCH_INTERNAL_RST is NOT consistent with VEGDYN Data
 CATCH_INTERNAL_RST is NOT consistent with VEGDYN Data
CATCHRUN2                                     3629
LANDRun2                                      1642
SURFACERUN2_DOTYPE                            8588
SURFACERun2                                   6742
PHYSICS::Run                                  2575
AGCMRun                                       2382
GCMRun                                        1803
```
That actually amazes me.

The question is: is this something that MAPL should be checking? Or should this be something we do a priori to running `GEOSgcm.x`?

**Comment by mathomp4** [comment]
Even more exciting, if I hack `linkbcs` to point to the c48 `vegdyn.data`, the model runs to completion for at least a day! The output is utter garbage, because it's only a 1/4 of the world or something, but it works!

Correct Restarts T:
![T_in_right_restart](https://user-images.githubusercontent.com/2982494/102371764-89838000-3f8c-11eb-9cbf-b3bb852b1b99.png)

Wrong Restarts T:
![T_in_wrong_restart](https://user-images.githubusercontent.com/2982494/102371774-8d170700-3f8c-11eb-8c44-49fa7f17cd38.png)

**Comment by mathomp4** [comment]
Note: Those pictures are of course T at the lowest level (which is why there are undefs)

**Comment by bena-nasa** [comment]
Fixed by https://github.com/GEOS-ESM/MAPL/pull/655
