### ISSUE TITLE
Multigroup server broken when writing more than one collection.

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#652]
I made an initial attempt at benchmarking a GEOS run with the multigroup server in pfio.
I ran a c180 job on 14 skylake nodes. I ran the model on 8x48 (384) processors and devoted the other 4 nodes to the oserver.

The configuration and run command for GEOSgcm.x was as follows:
```
set IOSERVER_OPTIONS = "--npes_model $MODEL_NPES --oserver_type multigroup --nodes_output_server 4 --npes_output_backend 80"

$RUN_CMD 560 $GEOSBIN/GEOSgcm.x $IOSERVER_OPTIONS --logging_config 'logging.yaml'
```

Here are my observations. I tried running this with the standard History.rc used by the AGCM, only writing surf and prog, each writing every hour. The code crashed like so with less than useful traceback the very first time it writes:
```
 AGCM Date: 2019/03/17  Time: 22:00:00  Throughput(days/day)[Avg Tot Run]:  253.1   88.5   97.5  TimeRemaining(Est) 000:05:27   26.2% :  13.7% Mem Comm:Used
 bmaa captain collection_id:            1
 bmaa writer collection_id:            1
 bmaa captain collection_id:            2
 bmaa writer collection_id:            2
Abort(927612303) on node 437 (rank 437 in comm 0): Fatal error in PMPI_Win_fence: Other MPI error, error stack:
PMPI_Win_fence(124)..................: MPI_Win_fence(assert=0, win=0xa0000005) failed
MPID_Win_fence(264)..................:
MPIDIG_mpi_win_fence(479)............:
MPIDI_NM_rma_win_cmpl_hook(341)......:
MPIDI_OFI_win_progress_fence_impl(47):
MPIDI_OFI_handle_cq_error(1042)......: OFI poll failed (ofi_events.c:1042:MPIDI_OFI_handle_cq_error:Invalid argument)
>> Error << /usr/local/intel/2020/compilers_and_libraries_2020.4.304/linux/mpi/intel64/bin/mpirun  -np 560 /gpfsm/dswdev/bmauer/models/github_stock/GEOSgcm/install/bin/GEOSgcm.x --npes_model 384 --oserver_type multigroup --nodes_output_server 4 --npes_output_backend 80 --logging_config logging.yaml: status = 143; at /gpfsm/dswdev/bmauer/models/github_stock/GEOSgcm/install/bin/esma_mpirun line 378.
```
I put prints in the master/worker polling loops in start_back() in MultiGroupServer.F90 so I could see when a worker rank gets a new request.

However, if I only write one collection it seems to work and happily writes files. Not sure what to make of this but clearly this has stopped any benchmarking efforts.

**Comment by weiyuan-jiang** [comment]
I have examples that wrote many collections and they run fine. But I will check it again

**Comment by bena-nasa** [comment]
Unfortunately, this seems to be something related to the model size/number of cores etc ...
I've tried a smaller case. Running c24 on 8 nodes, with 24 cores-per-node to make the math easy. I give 96 cores to the model, the other 96 to the o-server, and give the back 48. That runs fine. I'm able to run a day with the standard History.rc

**Comment by bena-nasa** [comment]
This is seeming to be a skylake thing. I got 22 haswell nodes, 24 cores per node. I use 16 nodes for the model, 6 for the server, with 2 for the backend. That runs fine, I can output multiple collections.
Now I do the same thing but request 22 skylake nodes, 24 cores per node but the run parameters the same. That fails with the original error in the first post in this chain.
 @weiyuan-jiang was also able to run a case, 24 cores per node, 9 for the model, 6 (4/2 split) for the oserver with the standard history on haswell.

So best guess this is an mpi issue exposed because the skylakes are on a different fabric than the haswells. I'll do more testing on skylakes.

**Comment by bena-nasa** [comment]
More datapoints, seems to be a multi node issue + skylake issue
The latest experiment. I requested 4 skylake nodes with 12 cores per node, run the model on 24.
If I mpirun with 36 cores, have 1 node for o-server and 6 cores for the backend it works. 
If I mpirun wtih 48 cores, have 2 nodes for the o-server and 12 cores for the backend it fails, still the same win fence error.

**Comment by bena-nasa** [comment]
Not unexpectedly based on the error being seen, it appears to be failing on the MPI fence call here:
https://github.com/GEOS-ESM/MAPL/blob/develop/pfio/MultiGroupServer.F90#L562

**Comment by bena-nasa** [comment]
Summarizing what I see.
1.) if I set --oserver_type multigroup
2.) if running on skylakes
3.) if running the oserver on multiple nodes --nodes_output_server n, where n > 1
4.) if History attempts to write 2 or more collections during an iteration

The code appears to fail in the 2nd mpi_win_fence call here:
https://github.com/GEOS-ESM/MAPL/blob/develop/pfio/MultiGroupServer.F90#L562
It was not clear to me why this was needed as there is a mpi_win_fence called during the creation of the RDMAreference so nothing happens between that mpi_win_fence call and the one I reference above. Then there is a 3rd mpi_win_fence when deallocate RDMAreference.

**Comment by weiyuan-jiang** [comment]
mpi_win_fence should be fine as long as all the processes participate the call. I am not sure if skylate has special env for this call. I will test it on skylate.

**Comment by weiyuan-jiang** [comment]
I can confirm that if the front and the back split into different nodes, it hangs. Need more investigation

**Comment by weiyuan-jiang** [comment]
UPDATE:   I have tested c24, and it is still working even under @bena-nasa 's constraint.  It becomes very very  slow. I believe it is due to MPI_put.  more investigation.....

**Comment by weiyuan-jiang** [comment]
I am wondering to ask NCCS to add accelerated RDMA option.  https://edc.intel.com/content/www/us/en/design/products-and-solutions/networking-and-io/fabric-products/omni-path/rn-intel-omni-path-software-release-notes-for-v10-10-3-1/accelerated-rdma-information/

In the file, it said the memory may explode.

cat /etc/modprobe.d/00-hfi1.conf
##
## Managed by Puppet
##

#
# Omni-Path hfi1 module parameters
# Please refer to the Intel Omni-Path Fabric Performance Tuning User Guide
# https://www.intel.com/content/dam/support/us/en/documents/network-and-i-o/fabric-products/Intel_OP_Performance_Tuning_UG_H93143_v12_0.pdf
#

# WARNING!! Accelerated RDMA has shown to explode memory usage. Leaving disabled ATM - aknister

options hfi1 max_mtu=8192 krcvqs=5 pcie_caps=0x51 sge_copy_mode=2 rcvhdrcnt=16352

What do you think ? @bena-nasa @tclune

**Comment by bena-nasa** [comment]
I ran again, different build I'm still see a crash. Are you sure you are tested the same configuration?
I requested 4 skylake nodes with 12 cores per node.
I'm running a c24 with NX=2, NY=12 and launch GEOS like so:
```
mpirun  -np 48 /gpfsm/dswdev/bmauer/models/github_control/GEOSgcm/install-debug/bin/GEOSgcm.x --npes_model 24 --oserver_type multigroup --nodes_output_server 2 --npes_output_backend 8 --logging_config logging.yaml
```
and my History.rc
```
COLLECTIONS: 'geosgcm_prog'
             'geosgcm_surf'
::

GRID_LABELS: PC96x49-DC
::

PC96x49-DC.GRID_TYPE: LatLon
PC96x49-DC.IM_WORLD: 96
PC96x49-DC.JM_WORLD: 49
PC96x49-DC.POLE: PC
PC96x49-DC.DATELINE: DC
PC96x49-DC.LM: 72

  geosgcm_prog.template:  '%y4%m2%d2_%h2%n2z.nc4',
  geosgcm_prog.archive:   '%c/Y%y4',
  geosgcm_prog.format:    'CFIO',
  geosgcm_prog.frequency:  010000,
  geosgcm_prog.grid_label: PC96x49-DC
  #geosgcm_prog.vscale:     100.0,
  #geosgcm_prog.vunit:     'hPa',
  #geosgcm_prog.vvars:     'log(PLE)' , 'DYN'          ,
  #geosgcm_prog.levels:     1000 975 950 925 900 875 850 825 800 775 750 725 700 650 600 550 500 450 400 350 300 250 200 150 100 70 50 40 30 20 10 7 5 4 3 2 1 0.7 0.5 0.4 0.3 0.2 0.1 0.07 0.05 0.04 0.03 0.02,
  geosgcm_prog.fields:    'PHIS'     , 'AGCM'         ,
                          ::


  geosgcm_surf.template:  '%y4%m2%d2_%h2%n2z.nc4',
  geosgcm_surf.archive:   '%c/Y%y4',
  geosgcm_surf.format:    'CFIO',
  geosgcm_surf.mode:      'time-averaged',
  geosgcm_surf.frequency:  010000,
  geosgcm_surf.ref_time:   210000,
  geosgcm_surf.grid_label: PC96x49-DC
  geosgcm_surf.fields:    'PHIS'          , 'AGCM'     ,
::
```

**Comment by bena-nasa** [comment]
Another user was able to replicate this on the skylake nodes. They experimented with some MPI settings that shed some light on the problems however, per the user

"I just looked at this again. I tried the tcp OFI provider and it works, of course significantly slower than psm2. On the Haswell nodes, either the verbs or the mlx provider is used, and of course tcp will work too. It looks as if the psm2 functions in libfabric is the issue - perhaps there is a mismatch between the psm2 version and the rest of libfabric. This is something Intel can probably provide some insight on. We might attempt to build libfabric by ourselves and test that with a customized local Intel MPI module."

**Comment by mathomp4** [comment]
@bena-nasa Interesting. I just sent an email to NCCS about (if they have a chance) to update the libpsm2 on the skylakes. Turns out I can't build Open MPI 4.1.0 on them because:
```
checking whether PSM2_LIB_REFCOUNT_CAP is declared... no
configure: WARNING: PSM2 needs to be version 11.2.173 or later. Disabling MTL.
configure: error: PSM2 support requested but not found.  Aborting
```
I guess there must be something in libpsm2 that Open MPI 4.1.x relies on? 

Are these related? Probably not. But seems like libpsm2 is having a moment here. 🤷🏼

**Comment by weiyuan-jiang** [comment]
Now I can reproduce the crash.  All the crashes come down to the error:

MPIDI_OFI_handle_cq_error(1042).........: OFI poll failed (ofi_events.c:1042:MPIDI_OFI_handle_cq_error:Invalid argument)

Considering I can run the program in Hashwell and also in Skylake with verbs ( very very slow though), I suspected the error is due to libfabric as @aoloso suggested. I am not sure if our problem is related to this issue https://github.com/ofiwg/libfabric/issues/4283

**Comment by mathomp4** [comment]
Note: We do now have a new(-er) Intel MPI to test with, though using the Model as a tester might be out until #644 can be diagnosed by @tclune. But if you can reproduce this outside of GEOS somehow...

Note 2: Not sure if Intel MPI 2021.1.1 change anything in this area, though. The [release notes](https://software.intel.com/content/www/us/en/develop/articles/intel-mpi-library-release-notes.html) are...terse.

**Comment by weiyuan-jiang** [comment]
Now we don't use one-sided mpi_put anymore.  The problem disappears. Closed

**Comment by WilliamDowns** [comment]
Hi there, I'm running into a similar issue running GCHP on AWS EC2 (hang at output time if using EFA provider, tcp works fine). Could you elaborate on 

> 
> 
> Now we don't use one-sided mpi_put anymore. The problem disappears.

Is this an update that recently went into MAPL, or a setting somewhere? The version of MAPL in the latest GCHP dates back to November, so I'm trying to figure out the best course of action for further debugging.

**Comment by tclune** [comment]
The story is a bit complicated.    We were attempting to implement a new variant of the O-server to overcome a performance block in certain complex configurations of GEOS.  That new implementation used `MPI_Put()` which had its own performance issues, as well the bug reported in this ticket for some configurations.   Switching to `Isend()` solved the performance issues and the bug reported here vanished along with that.   (I.e., it was never really diagnosed.)

None of this is yet used in any released version of MAPL, so probably not the explanation for your problems.

However ... we have found a regression in Intel MPI starting in version 19.1.1.217 that causes hangs in `MPI_Win_lock()`.   The IO servers skirt around that problem, but pFlogger can easily trigger it.       Since pFlogger has been in MAPL for some time, it is conceivable that the GCHP use case is running into that.   (But am guessing that GCHP is using OpenMPI, and not Intel MPI, on AWS.)   If you think this is possibly related, @mathomp4 can tell you about an env variable that fixes the problem on our fabric.

**Comment by WilliamDowns** [comment]
Thank you very much for the clarification. I've been running into issues running GCHP on multiple nodes with both OpenMPI and Intel MPI on AWS when using EFA, but this hang is specifically when using Intel MPI (currently 2019.8.254). I'd certainly be interested in hearing about any possible fixes using environment variables.

**Comment by weiyuan-jiang** [comment]
Have you updated MAPL?  The problem should be solved. If not, I will have to reopen this issue @WilliamDowns

**Comment by WilliamDowns** [comment]
No I haven't yet, I'll try to do so. Sorry for commenting so much on a closed issue.

**Comment by WilliamDowns** [comment]
FYI I ended up running into a mix of indefinite hangs and quick crashes during output write on seemingly identical runs. Updating my libfabric version from 1.11.1 to 1.11.2 fixed all issues. I didn't end up trying to update MAPL.
