### ISSUE TITLE
Optional renaming of the split field in History

### ISSUE THREAD

**Issue by atrayano** [GEOS-ESM/MAPL#674]
This is a new feature requested by Arlindo, to allow using the alias feature in History to rename split fields, for example, by wavelengths

**Comment by mathomp4** [comment]
@atrayano Did your fix above get into the code?

**Comment by atrayano** [comment]
I did. But this is not integrated into develop yet (see my last comment for #673)

**Comment by mathomp4** [comment]
Reexamined on 2021-Apr-12 with @bena-nasa and @tclune 

@atrayano @gmao-esherman Is this now fixed as far as you can tell?

**Comment by gmao-esherman** [comment]
Yes, this feature is working for me.

**Comment by mathomp4** [comment]
If it works for @gmao-esherman, I think we can close this. Open new issues as new issues emerge.
