### ISSUE TITLE
ExtDataDriver test case for sparse input/output broken in IO server.

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#698]
I had merged develop into my ExtData refactor branch and ran my usual tests with ExtDataDriver.x where I found one was failing. I then checked and found the plain develop branch was also failing. This test exercises the case when the input or output grid is so coarse that is can not be decomposed in such a way that every processor has a DE. This test has worked in the past. It is now failing in the pfio server when History tries to write (this is using the simple server, no server on separate nodes) like so:
```
libMAPL.pfio.so    00002AAAB873AE1C  pfio_abstractdata         455  AbstractDataReference.F90
libMAPL.pfio.so    00002AAAB8474CCD  pfio_simplesocket         124  SimpleSocket.F90
libMAPL.pfio.so    00002AAAB85DF8A6  pfio_clientthread         338  ClientThread.F90
libMAPL.pfio.so    00002AAAB860C9E9  pfio_clientmanage         291  ClientManager.F90
libMAPL.base.so    00002AAAB6BFA89F  mapl_newcfiomod_m         807  MAPL_newCFIO.F90
libMAPL.base.so    00002AAAB6BD5076  mapl_newcfiomod_m         372  MAPL_newCFIO.F90
libMAPL.history.s  00002AAAB52F1EFF  mapl_historygridc        3527  MAPL_HistoryGridComp.F90
```
Now when History writes and make the collective_stage_data call, not every processor has any data to send. In that case I allocate an array of size zero of the appropriate shape and pass that to collective_stage_data on those mpi processes that have no data. This has just worked in the past everytime I remember running this test.

To test copy these files somewhere:
/gpfsm/dnb31/bmauer/ExtData_Test_Framework/test_cases/case12
Then from that location run:
mpirun -np 216 install_location/bin/ExtDataDriver.x

Note I usually just run this on fewer physical cores and oversubscribe as the sizes of the grid is tiny and even oversubscribing doesn't take it long, just seconds.

What seems to be going on is that there is a point where it copies the datareference passed from the application to a new datareference. It creates a fortran pointer for the datareference that was passed by the application. In addition the SimpleSock gets a visitor_handle and copies the pass in data reference to the data_reference in the visitor handle where this is failing. Something must have changed where now something that was not a null pointer is now a null pointer in the visitor handle (maybe something was being allocated size 0 and now is not?) Or we were just lucky this cases working? I don't know.

**Comment by bena-nasa** [comment]
I'm going back in time, trying to see what version of MAPL broke this.

**Comment by tclune** [comment]
My guess would be recent changes by Matt, Weiyuan, and myself to improve NAG portability.  There were subtle issues with treatment of 0-sized arrays that probably caused the problem.   (@weiyuan-jiang if so, then please try to add another unit test that guards against this.)

**Comment by bena-nasa** [comment]
Got it. In the module LocalMemReference.F90 there is a routine "allocate".
In 2.5 it looks like this:
```
   subroutine allocate(this, rc)
      class (LocalMemReference), intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer(kind=INT64) :: n_words
      integer(kind=INT64) :: n
      integer :: status

      n = product(int(this%shape,INT64))
      n_words = n * word_size(this%type_kind)
      allocate(this%i_ptr(n_words), stat=status)
      _VERIFY(status)
      this%base_address = c_loc(this%i_ptr)
      _RETURN(_SUCCESS)
   end subroutine allocate
```

where as in 2.6 it looks like this:
```
   subroutine allocate(this, rc)
      class (LocalMemReference), intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer(kind=INT64) :: n_words
      integer(kind=INT64) :: n
      integer :: status

      n = product(int(this%shape,INT64))
      n_words = n * word_size(this%type_kind)
      allocate(this%i_ptr(n_words), stat=status)
      _VERIFY(status)
      if (n > 0) then
         this%base_address = c_loc(this%i_ptr)
      else
         this%base_address =  C_NULL_PTR
      endif
      _RETURN(_SUCCESS)
   end subroutine allocate
```
Reverting that fixes the test. Does this have implications for NAG?

**Comment by tclune** [comment]
Probably not the best fix, but as a hotfix it lets us move forward.

I think the "right" fix should be upstream where the C_NULL_PTR is consumed.     Something there is apparently distinguishing between a pointer to a 0-sized array and a C_NULL_PTR and should now check first if it is C_NULL_PTR.  @weiyuan-jiang probably knows where this is.  (Possibly in multiple places, unfortunately.) 

If we can find the right fix quickly, it is probably worth doing now.  Otherwise, do the kludge and keep the issue open for the longer term fix.

**Comment by bena-nasa** [comment]
@weiyuan-jiang I can reproduce on 6 cores if I hack History so it doesn't let MAPL pick a distribution for the output grid but just uses 1x6 if that helps to debug.

**Comment by weiyuan-jiang** [comment]
I have noticed this problem. In my new branch, I changed back to the original one https://github.com/GEOS-ESM/MAPL/blob/f5615cfce6a0e4e256418460f9aec5f855520fcf/pfio/LocalMemReference.F90#L365-L373

Tom told me we can use __NAG_COMPILER_BUILD.  It seems working

**Comment by tclune** [comment]
OK - that is an acceptable solution.   I'm still curious how the Intel compiler was not able to use C_NULL_PTR when this%base_address is consumed at the later stage.

**Comment by bena-nasa** [comment]
This seems to have been fixed in develop so closing the issue

**Comment by bena-nasa** [comment]
Closing, fixed
