### ISSUE TITLE
Bug when constructing a lat-lon pole centered grid from a file

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#71]
The Harvard developers found a bug in the MAPL_LatLonGridFactory

The code does this
`         this%lat_corners(1) = this%lat_centers(1) - (this%lat_centers(2)-this%lat_centers(1))/2
         this%lat_corners(2:jm) = (this%lat_centers(1:jm-1) + this%lat_centers(2:jm))/2
         this%lat_corners(jm+1) = this%lat_centers(jm) - (this%lat_centers(jm-1)-this%lat_centers(jm))/2`

However for a pole centered grid notice this will add a 1/2 of a delta to the pole center and put the corners at -90 - dlat/2 and 90 + dlat/2

**Comment by mathomp4** [comment]
This is definitely closed I believe.
