### ISSUE TITLE
pFIO does not support writing strings to netCDF

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#714]
As seen in #642, it looks like pFIO cannot output string variables to netCDF:

https://github.com/GEOS-ESM/MAPL/blob/beba7fc571c9096b9b0897b4966d8ee0d10ba987/pfio/NetCDF4_FileFormatter.F90#L466-L484

Strings seem to fallover into `class default` and will fail.

I suppose the question is: should it?

**Comment by weiyuan-jiang** [comment]
I will revisit the string in pFIO. We had problems before. Maybe the new compilers can help us go through this issue

**Comment by mathomp4** [comment]
I am not sure if this is related to #530. Thoughts, @tclune ?
