### ISSUE TITLE
HEAD of develop crashes with UFS-GOCART

### ISSUE THREAD

**Issue by rmontuoro** [GEOS-ESM/MAPL#737]
The HEAD of `develop` (aecee0c) crashes when running UFS-GOCART with the following stack trace information:

```
  0: pe=00000 FAIL at line=00104    BaseProfiler.F90                         <Timer ioserver is not a fresh self start>
  0: forrtl: severe (174): SIGSEGV, segmentation fault occurred
  0: Image              PC                Routine            Line        Source             
  0: ufs_model          0000000009D62ADA  Unknown               Unknown  Unknown
  0: libpthread-2.17.s  00002B4E21A245D0  Unknown               Unknown  Unknown
  0: libMAPL.profiler.  00002B4E1D599A4D  mapl_advancedmete          93  AdvancedMeter.F90
  0: libMAPL.profiler.  00002B4E1D60EC61  mapl_baseprofiler         145  BaseProfiler.F90
  0: libMAPL.pfio.so    00002B4E1750D1EA  pfio_abstractserv         228  AbstractServer.F90
  0: libMAPL.pfio.so    00002B4E17630C1B  pfio_serverthread        1092  ServerThread.F90
  0: libMAPL.pfio.so    00002B4E1744F6B2  pfio_messagevisit          87  MessageVisitor.F90
  0: libMAPL.pfio.so    00002B4E1744CEBD  pfio_abstractmess         112  AbstractMessage.F90
  0: libMAPL.pfio.so    00002B4E174C5622  pfio_simplesocket         105  SimpleSocket.F90
  0: libMAPL.pfio.so    00002B4E17664F3B  pfio_clientthread         413  ClientThread.F90
  0: libMAPL.pfio.so    00002B4E17690DC6  pfio_clientmanage         353  ClientManager.F90
  0: libMAPL.base.so    00002B4E15FFF3F6  mapl_extdatagridc        1529  MAPL_ExtDataGridCompMod.F90
```

**Comment by tclune** [comment]
@weiyuan-jiang please give this high priority.    Even if it means we have to block off the timers for now.

**Comment by weiyuan-jiang** [comment]
ok. @tclune

**Comment by tclune** [comment]
@weiyuan-jiang I should add - you may need to work with @bena-nasa or @WilliamJamieson to replicate for the UFS environment.   But I'm hoping it can be replicated in GEOS when using the "local" o-server.

**Comment by weiyuan-jiang** [comment]
I saw the problem even without running the program

**Comment by weiyuan-jiang** [comment]
@bena-nasa , would you help me to test this branch to see if I fixed this issue? Thanks a lot.  hotfix/wjiang/profiler_cleanup

**Comment by rmontuoro** [comment]
@weiyuan-jiang - I've tested your branch with UFS-GOCART and it crashed with the same error message. The stack trace is identical to the previously reported one.

**Comment by weiyuan-jiang** [comment]
OK. Thanks. I will keep looking

**Comment by weiyuan-jiang** [comment]
Can you show me the run_cmd in gcm_run.j ?  For example, mine looks like 
$GEOSBIN/esma_mpirun -np  200 ./GEOSgcm.x --npes_model 96 --nodes_output_server 2 --logging_config 'logging.yaml'

**Comment by tclune** [comment]
@weiyuan-jiang   UFS is not using GEOS scripts.       And in particular they are not using command line options and are thus using the "internal" server.

**Comment by weiyuan-jiang** [comment]
@rmontuoro , I have made more changes. Would you please try again? https://github.com/GEOS-ESM/MAPL/tree/hotfix/wjiang/profiler_cleanup  , Hopefully,  this crash would be fixed this time.

**Comment by bena-nasa** [comment]
We have disabled the feature that was causing this latest crash and gotten that to develop of MAPL. I'm pulling now and will do a double check that we get a clean exit and the other issues (the point source placement code and the issue with output variables with a "." in the name in History) still appear to be resolved.

**Comment by rmontuoro** [comment]
The current `develop` branch (deddd75) works with UFS-GOCART. Issue #723 remains open.

**Comment by weiyuan-jiang** [comment]
@rmontuoro .  How do you build your FMS library? is it static ( libfms_r4.a and libfms_r8.a) or dynamic ( libfms_r4.so and libfms_r8.so).  My question is not related to this issue though.

**Comment by mathomp4** [comment]
@weiyuan-jiang @rmontuoro Has this been fixed in the latest MAPL?

**Comment by rmontuoro** [comment]
@mathomp4 - Yes. This issue can be closed.
