### ISSUE TITLE
Cleanup MAPL_GetHorzIJIndex interface

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#738]
During the recent refactoring of the MAPL_GetHorzIJIndex routine the ability to be passed the grid coordinates and work on a single processor was removed, however the arguments to do this still remain. This capability was added so a program (think python and f2py) could use this to do binning on a single proccessor. This should be cleaned up; either the arguments removed, or reimplemented in the code/moved to a new subroutine/module etc ... if this capability is still desired.

**Comment by mathomp4** [comment]
Reexamined on 2021-Apr-12 with @bena-nasa and @tclune

**Comment by bena-nasa** [comment]
This has been done, the interface has been cleaned up to remove the non-existent functionality
