### ISSUE TITLE
Remove test code fragment from MAPL.base library

### ISSUE THREAD

**Issue by rmontuoro** [GEOS-ESM/MAPL#748]
The [tstqsat.F90](https://github.com/GEOS-ESM/MAPL/blob/7029268300e54c32a19fce5516f0fb13d2e47ec1/base/tstqsat.F90) code fragment should be removed from `MAPL.base` and refactored into a unit test, if needed. See [base/CMakeLists.txt](https://github.com/GEOS-ESM/MAPL/blob/c80a8e2ad58a328eaa589066bce67ee5756ff4d1/base/CMakeLists.txt):
```
set (srcs
  ...
  MAPL_ExtDataCollectionManager.F90                 
  MAPL_ExtDataGridCompMod.F90           MAPL_OrbGridCompMod.F90             tstqsat.F90
  MAPL_LocStreamFactoryMod.F90          MAPL_LocstreamRegridder.F90
```
The code is not encapsulated in a Fortran program unit and might be the source of abnormal behavior, such us being executed unexpectedly (!).

**Comment by tclune** [comment]
It is not a code fragment.  It is a fully formed program, though a bit obscure by modern conventions.   The initial PROGRAM statement is not required, and is implied if absent.   The final "END" suffices to end the program.

Changing from BUG to cleanup.  Low priority.

**Comment by rmontuoro** [comment]
@tclune - agreed.
I did notice this legacy program being executed surprisingly on Orion when `MAPL` was used in a basic test program:
```
program test_mapl
  use MAPL
  print *,'hello!',MAPL_PI
end program test_mapl
```
This behavior might be related to compiler issues and it is not fully reproducible.

**Comment by tclune** [comment]
You have piqued my curiosity.   I cannot see how anything in our system can be "executed suprisingly".    Either one must explicitly launch the executable, or you can run the suite of tests.  I'm unaware of this particular program and it violates my usual rules that a successful test should not produce output.

**Comment by rmontuoro** [comment]
I suspect that a glitch in the `Makefile` used the build the test program above on Orion prevented this program from being compiled at all. The resulting executable was then created by just linking the MAPL libraries. The linker did not complain since `main` was provided by `MAPL.base` in `tstqsat.F90`, then executed "unexpectedly" when running the resulting binary.

The behavior is reproducible in this case. I would still recommend removing the legacy program from the `MAPL.base` library.

**Comment by tclune** [comment]
@mathomp4 Do you recall why you added this program into MAPL?     I'm sure we can find a better subdir now if it is still needed.

**Comment by tclune** [comment]
Oh - and I'd not understood that this was _in_ the library.   I thought it was just _in_ the directory.    I'm actually surprised that this does not break the build under OSX.  Usually one cannot have to mains, as the linker will complain.   Retagging this as a bug with my new understanding.
