### ISSUE TITLE
No Equation of Time correction in sun orbit code

### ISSUE THREAD

**Issue by dr0cloud** [GEOS-ESM/MAPL#78]
Need to add the Equation of Time (EOT) correction to MAPL Sun Orbit code. This expresses the fact that apparent solar time, which governs the actual position of the sun, is not exactly the same as mean solar time (almost UTC).

**Comment by dr0cloud** [comment]
Basic EOT machinery is now in place in MAPL. 
Next will call that machinery from MAPL_SunGetInsolation (in solar and other places) with resource selectable EOT logical.

**Comment by mathomp4** [comment]
@dr0cloud I believe we can close this issue right? All your EOT work is now in 2.1?

**Comment by dr0cloud** [comment]
This is fixed by PR #249 which is the new orbital system.
