### ISSUE TITLE
Migration to ESMF_Info

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#782]
As I'm doing some test builds with ESMF 8.1.0, from their release notes:

> The ESMF_Info class was introduced as a replacement for ESMF_Attribute. ESMF_Info is based on a modern C++ JSON implementation to provide efficient key-value pair storage. Most of the legacy ESMF_Attribute API is preserved for backward compatibility.

and from [the documentation](https://earthsystemmodeling.org/docs/release/ESMF_8_1_0/ESMF_refdoc/node6.html#SECTION06020000000000000000):

> The ESMF_Info class is a replacement for the ESMF_Attribute class and is the preferred way of managing metadata attributes in ESMF moving forward. It is recommended that users migrate existing ESMF_Attribute calls to the new ESMF_Info API. The ESMF_Info class provides the backend for ESMF_Attribute since ESMF version 8.1. The ESMF_Attribute docs are located in appendix 55. In practice, users should experience no friction when migrating client code. Please email ESMF support in the case of a migration issue.

I suppose the fact that the docs for ESMF_Attribute are now in an Appendix is a sign to start looking at this.

Though, as @atrayano, @bena-nasa and @tclune know, ESMF_Attribute is nigh-omnipresent in GEOS. So, this might take a while...

**Comment by tclune** [comment]
My limited understanding is that this was more of an internal design change and that the existing interfaces are backward compatible.  No?

**Comment by mathomp4** [comment]
@tclune Yes, they are. And I imagine if we request ESMF to keep it in the code they will, I just wanted to bring up the fact that they seem to be pushing ESMF_Info.

Indeed, I think one of the early reasons we couldn't use ESMF 8.1.0 snapshots was that the migration sort of "broke" ESMF_Attribute (something to do with 32 or 64 bits? Can't remember).

Annoyingly, the ESMF_Info class seems to be *more* verbose than ESMF_Attribute:

> 39.1.1 Setting an Attribute
> With ESMF_Attribute:
> ```fortran
> call ESMF_AttributeSet(array, "aKey", 15, rc=rc)
> ```
> With ESMF_Info:
> ```fortran
> call ESMF_InfoGetFromHost(array, info, rc=rc)
> call ESMF_InfoSet(info, "aKey", 15, rc=rc)
> ```
>

**Comment by tclune** [comment]
We can always write our own wrappers if the 1-2 combo is frequent enough.

**Comment by mathomp4** [comment]
In re #1032, I took a look at the latest ESMF documentation and I see for `ESMF_AttributeGet`

> STATUS: DEPRECATED CLASS!
> The entire ESMF_Attribute class has been deprecated and is scheduled for removal with ESMF 9.0.0. This includes
> all of the class derived types, named constants, and methods. Please use the replacment class ESMF_Info, section
> 39 instead!

I'm going to invoke the name of @rsdunlapiv about the timeline for ESMF 9. Just so we know because we appear to have 368 `ESMF_Attribute` calls in MAPL and another 313 in the `Components` of GEOSgcm.

So, mayhaps this is another thing for MAPL3, @tclune, depending on the timeline?

**Comment by mathomp4** [comment]
Hmm. I wonder if something like this:

> Nesting uses the JSON Pointer 39.2 syntax. All key arguments in ESMF_Info may use this syntax unless noted
> otherwise. When creating a nested object, objects are created if they do not exist. Hence, it is not necessary to create
> the individual nested elements for deep hierarchies
> ```fortran
> call ESMF_InfoSet(info, "/Universe/Galaxy/Star/Planet", "Venus", rc=rc)
> ```

would be useful for MAPL to "organize" our attributes/info.

**Comment by tclune** [comment]
I need to review my notes from discussions with Arlindo about our next gen use of YAML.    We need a clear policy of how each level in our hierarchy searches for an attribute.   We can then re-examine in light of the above.   Generally YAML is a superset of JSON, but I don't know anything about JSON "pointer syntax".

**Comment by mathomp4** [comment]
It looks like a JSON pointer is a string-based access of a dictionary in `/foo/bar/` format:
https://datatracker.ietf.org/doc/html/rfc6901
https://www.baeldung.com/json-pointer

**Comment by rsdunlapiv** [comment]
@mathomp4 regarding ESMF 9 - I think you still have some time here.  However, perhaps you could migrate a couple of ESMF_Attribute calls to ESMF_Info for some preliminary testing?  If that goes well, then a systematic replacement would hopefully not be too painful!
