### ISSUE TITLE
Incorrect attribute 'time_increment' in History monthly collection files

### ISSUE THREAD

**Issue by lizziel** [GEOS-ESM/MAPL#784]
I ran a 1-year GCHP simulation using MAPL 2.6.3 with the `monthly` collection option turned on in `HISTORY.rc`. The time variable has attribute `time_increment` which I would expect to be the duration of the month per file. Instead it is 7440000 for each month. This corresponds to the `duration` setting otherwise ignored when `monthly` is enabled.

For example, the time information for June is this:
```
        float time(time) ;
                time:begin_date = 20180601 ;
                time:begin_time = 0 ;
                time:long_name = "time" ;
                time:time_increment = 7440000 ;
                time:units = "minutes since 2018-06-01 00:00:00" ;
```
 This is a problem since no information other than `time_increment` is present to infer the file is a monthly average. The way it is now someone may think it is the average over 31 days starting on June 1 which is incorrect.

**Comment by atrayano** [comment]
@lizziel I agree that any value that is constant, would be wrong. I will try to fix this. Computing the correct value for each month is almost trivial, but at the moment MAPL assumes that attribute is constant. When I set the monthly alarm, I ignore it completely. it is just used to create the metadata for the output file. But the value 7440000 came from the "duration" attribute which is set in your HISTORY.rc file (not in MAPL). I am thinking that when a collection is specified as "monthly", we should not even set "duration" (again, I need to do a little more work to pass correct metadata, so please wait before you test again).

**Comment by lizziel** [comment]
Thanks @atrayano. Following our discussion last week of another potential bug, I checked the values of monthly output across a full year against output from a series of 12 consecutive runs. The time-averaged values match. This issue is thus isolated to the `time_increment` field only. When you have a fix you can point me to the relevant commit(s) in develop. Thanks!

**Comment by lizziel** [comment]
The latest update fixes is on my end. Thanks @atrayano!
