### ISSUE TITLE
Enable nearest neighbor interpolation in ExtData

### ISSUE THREAD

**Issue by rmontuoro** [GEOS-ESM/MAPL#786]
A configuration option enabling nearest-neighbor interpolation is missing for ExtData.

This interpolation method is required when reading surface properties used, for instance, by dust schemes such as the NOAA/ARL FENGSHA scheme currently being implemented in GOCART.

**Comment by tclune** [comment]
@bena-nasa Please let us know how involved this extension will be.

**Comment by rmontuoro** [comment]
PR #788 enables this feature. I've used the `E` keyword to request nearest-neighbor interpolation in the ExtData resource file, but please feel free to implement a different keyword if needed.

**Comment by rmontuoro** [comment]
Closing after merge.
