### ISSUE TITLE
Feature Request: TimestampStart

### ISSUE THREAD

**Issue by lizziel** [GEOS-ESM/MAPL#790]
MAPL History names time-averaged files with mid-point datetime by default, and has the capability to use end datetime instead (https://github.com/GEOS-ESM/MAPL/issues/602). This feature request is for implementation of using start datetime in time-averaged History filenames. Like `TimestampEnd`, `TimestampStart` would be an optional setting.

This request is for use in GCHP. We are going to recommend usage of the monthly average for collections. Monthly output files are timestamped with start datetime in the filenames. Having a `TimestampStart` option for _all_ time-averaged output, not just monthly, would allow GCHP output files to have consistent format. An added benefit is they would then match the format of GEOS-Chem Classic.

**Comment by atrayano** [comment]
Yes, it is related. I'll fix both

**Comment by atrayano** [comment]
Actually the code is still doing what it supposed to do, but it is plain messy. I'll fix  it anyway, but the issue was a "red" herring

**Comment by lizziel** [comment]
Do you mean TimestampStart was already an option in History?

**Comment by atrayano** [comment]
@lizziel I made a mistake and my comment went to the wrong issue. But at the moment I am working on a branch that should address both issues (#790) the TimeStampStart and (#784) the incorrect time increment for monthly. I'll send you email once it is ready

**Comment by lizziel** [comment]
Thanks @atrayano for implementing this so quickly. I manually added the feature to GCHP (uses MAPL v2.6.3) and it all looks good.
