### ISSUE TITLE
Imported CMake targets need updating due to name changes

### ISSUE THREAD

**Issue by rmontuoro** [GEOS-ESM/MAPL#798]
The most recent releases of external libraries MAPL is dependent upon provide new CMake target names that include a namespace, following CMake recommendations. As a consequence, the affected targets need to be renamed in the MAPL build system (see example below):

```
diff --git a/base/CMakeLists.txt b/base/CMakeLists.txt
index 9f14fba..fdc6721 100644
--- a/base/CMakeLists.txt
+++ b/base/CMakeLists.txt
@@ -58,7 +58,7 @@ endif()
 
 esma_add_library(
   ${this} SRCS ${srcs}
-  DEPENDENCIES MAPL.generic MAPL.shared MAPL.profiler MAPL.pfio MAPL_cfio_r4 pflogger gftl-shared
+  DEPENDENCIES MAPL.generic MAPL.shared MAPL.profiler MAPL.pfio MAPL_cfio_r4 PFLOGGER::pflogger GFTL_SHARED::gftl-shared
                esmf NetCDF::NetCDF_Fortran MPI::MPI_Fortran
   TYPE SHARED)
```

NOAA would benefit from using the latest version of each dependency since it will reduce the total number of external libraries to introduce in the UFS for GOCART. For example, switching to `yaFyaml v0.5.1` will eliminate the need for `pfutil` in production runs.

What is the timeline for this update?

**Comment by tclune** [comment]
The challenge is that the changes are required in multiple repositories all-at-once which makes coordinating the PRs tricky.

What I have been advocating is to temporarily add a switch in esma.cmake that toggles whether the used version of GFE includes namespaces.  We can then wrap each reference with a conditional.   Once those are all in place, we can toggled the default for the option and adopt the newer baselibs.   And then can go back and eliminate the conditionals and the option.

Of course the "safe" approach mentioned above is not fast either, but we could at least then prioritize the update for MAPL.  (And GOCART if it is directly affected.)

I'll discuss again with @mathomp4 in the morning.

**Comment by mathomp4** [comment]
I believe this is now partially taken care of. (The only straggler will be the GEOSadas as it has a longer test cycle than the other fixtures.)

We've moved most fixtures to ESMA_env v3.3.0 (which has GFE Namespace libraries) and ESMA_CMake v3.5.0 (which sets `ESMA_USE_GFE_NAMESPACE` to `ON`).

Next up is to *remove* the doubling in MAPL, et al. I'll make PRs for that soon.
