### ISSUE TITLE
Should we update non-persist NRL Solar read

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#800]
Before we did our current default of `PersistSolar` in using the NRL Solar file (which just persists the last value at the end of the table when you fall off it), I coded in a scheme where, if you fall off the table, you use a similar position in the last complete solar cycle using some "magic numbers" to know when Solar Cycle 23 was:
```fortran
         OUT_OF_TABLE_AND_CYCLE: if ( outOfTable .and. (.not. PersistSolar_) ) then

            ! Create an ESMF_Time at start of Cycle 23
            ! ----------------------------------------
            call ESMF_TimeSet( startCycle23, YY = 1996,  &
                                             MM = 8,     &
                                             DD = 1,     &
                                              H = 12,    &
                                              M = 00,    &
                                              S = 00,    &
                                             RC = STATUS )
            _VERIFY(STATUS)

            ! Create an ESMF_Time at start of Cycle 24
            ! ----------------------------------------
            call ESMF_TimeSet( startCycle24, YY = 2008,  &
                                             MM = 12,    &
                                             DD = 1,     &
                                              H = 12,    &
                                              M = 00,    &
                                              S = 00,    &
                                             RC = STATUS )
            _VERIFY(STATUS)
```
But, [we are now in Solar Cycle 25](https://www.nasa.gov/press-release/solar-cycle-25-is-here-nasa-noaa-scientists-explain-what-that-means/), so therefore we have a complete Solar Cycle 24. The question is: Should I update the non-persist code to use Solar Cycle 24 instead of 23?

So, I ask @dr0cloud and @wmputman to weigh in on this. Not a crucial question at all, but just something I thought of. 

I mean, it's not the default (and no one besides me or @dr0cloud probably know how to use it) so my guess is ***no one*** would care. It's just, well, I wrote this code and learned a lot about `ESMF_Time` from it, so it's sort of my baby. :smile:

**Comment by dr0cloud** [comment]
I agree with this change :).

**Comment by dr0cloud** [comment]
In fact, next modeling mtg I plan to raise the issue with Bill as to whether this should be the default instead of   persist. It bothers me that sunspots are by definition quite spotty and that persisting the last value of the year may be statistically not the best.

**Comment by mathomp4** [comment]
Okay. I have a draft in now. I need to test it. I did try it with my normal restarts but then realized you won't see much difference if your restarts are in the year 2000 🤦🏼
