### ISSUE TITLE
Option 'timestampEnd' incorrectly prevents time-averaging in History

### ISSUE THREAD

**Issue by atrayano** [GEOS-ESM/MAPL#802]
If a time-averaged collection specifies 'timestampEnd' then the variable "average" is not set properly, and as a result, no averaging is performed.

**Comment by mathomp4** [comment]
Related to #790 ?

**Comment by atrayano** [comment]
Actually the code is still doing what it supposed to do, but it is plain messy. I'll fix it anyway, but the issue was a "red" herring
