### ISSUE TITLE
Bring back "cubed_sphere" variable in Cubed output?

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#827]
I was testing the GEOSadas and GEOSgcmPert.x with the new Adas version. It was failing when reading one of the trajectory files which is produced by the GEOSgcm.x on the cubed when the forecast runs. It turns out that little cfio (which is still used for reading by GEOSgcmPert.x) was not identifying the file as a cubed file because in v2.6.5 we removed two variables from the file because of this issue:
https://github.com/GEOS-ESM/MAPL/issues/642
Little cfio was looking for a variable named "cubed_sphere" which was a character and not finding it. I can use a different variable to determine if it is a cubed file, but one thing I did notice is that the cubed sphere variable did have the version encoded as an attribute:
```
        char cubed_sphere ;
                cubed_sphere:additional_vars = "contacts,orientation,anchor" ;
                cubed_sphere:file_format_version = "2.91" ;
                cubed_sphere:grid_mapping_name = "gnomonic cubed-sphere" ;
                cubed_sphere:gridspec_file = "gridspec.nc4" ;
```
So we have lost that. So the question. Should we reintroduce this, should we add the file_format_version as a global attribute etc ...

**Comment by mathomp4** [comment]
@bena-nasa I think we do still have the *attribute* for these things:
```
		:additional_vars = "contacts,orientation,anchor" ;
		:file_format_version = "2.90" ;
		:grid_mapping_name = "gnomonic cubed-sphere" ;
		:gridspec_file = "C24_gridspec.nc4" ;
```
right? But maybe @weiyuan-jiang needs to look at extending pFIO?

**Comment by mathomp4** [comment]
Note: I think I updated the version number in that attribute to be 2.91. It had gotten out-of-sync with the variable version

**Comment by bena-nasa** [comment]
ah, you are right, the version number is still there as a global attribute. I  didn't scroll down far enough. So there is no issue other than I need to update little cfio to understand this version.

**Comment by mathomp4** [comment]
Update for myself, yes I did update the version. Using MAPL `develop`:
```
// global attributes:
		:additional_vars = "contacts,orientation,anchor" ;
		:file_format_version = "2.91" ;
		:grid_mapping_name = "gnomonic cubed-sphere" ;
		:gridspec_file = "C24_gridspec.nc4" ;
		:_NCProperties = "version=2,netcdf=4.7.4,hdf5=1.10.7," ;
		:_SuperblockVersion = 0 ;
		:_IsNetcdf4 = 1 ;
		:_Format = "netCDF-4" ;
```
