### ISSUE TITLE
Profile GNU Debug Build in MAPL

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#829]
Looking at timings seen in #828, we see:

With `medium` resource:

- build-and-test-MAPL: 11m 40s
- build-GEOSgcm: 45m 41s
- make-FV3-experiment: 51s
- run-FV3-standalone:  2m 6s

With `xlarge` resource:

- build-and-test-MAPL: 10m 37s
- build-GEOSgcm: 15m39s
- make-FV3-experiment: 40s
- run-FV3-standalone:  1m 1s

So while GEOSgcm build was 3x faster (on 4x resources), the MAPL build was only about 10% faster. This makes me think we need to profile MAPL and GNU Debug.

My hazy memory makes me think that it is `MAPL_HistoryGridComp.F90` that is the tall pole with GNU Debug, but I'll do some build profiles to make sure.

@bena-nasa @tclune Can you think of ways we could maybe "split up" that file (if it's the culprit)?

**Comment by mathomp4** [comment]
Mea Culpa. It looks like it isn't History anymore? At least not on my Mac:
```console
❯ ~/bin/show-ninja-build-stats .ninja_log | grep '^.*o$' | head
61.082 base/CMakeFiles/MAPL.base.dir/MAPL_Mod.F90.o
43.862 base/CMakeFiles/MAPL.base.dir/MAPL_ExtDataGridCompMod.F90.o
28.97 gridcomps/History/CMakeFiles/MAPL.history.dir/MAPL_HistoryGridComp.F90.o
27.842 base/CMakeFiles/Regrid_Util.x.dir/Regrid_Util.F90.o
24.179 base/CMakeFiles/MAPL.base.dir/MAPL_CFIO.F90.o
21.827 base/CMakeFiles/MAPL.base.dir/MAPL_Generic.F90.o
19.063 base/CMakeFiles/MAPL.base.dir/FieldBundleRead.F90.o
17.114 base/CMakeFiles/MAPL.base.dir/MAPL_newCFIO.F90.o
16.374 gridcomps/History/CMakeFiles/MAPL.history.dir/MAPL_HistoryCollection.F90.o
14.601 base/CMakeFiles/MAPL.base.dir/MAPL_RegridderManager.F90.o
```

**Comment by mathomp4** [comment]
Here is a capture of the trace from `ninja -j4 install`:

<img width="1591" alt="Screen Shot 2021-05-06 at 4 04 41 PM" src="https://user-images.githubusercontent.com/2982494/117358972-cccf8400-ae84-11eb-80f4-dc3d3c59c7f8.png">

**Comment by mathomp4** [comment]
I am really...confused by `MAPL_Mod.F90` being that expensive. `MAPL_Mod.F90` is just a bunch of `use` statements!

Well, I'll try the same thing on discover soon.

**Comment by mathomp4** [comment]
GNU on Discover:
```
62.894 base/CMakeFiles/MAPL.base.dir/MAPL_Mod.F90.o
41.285 base/CMakeFiles/MAPL.base.dir/MAPL_ExtDataGridCompMod.F90.o
27.223 gridcomps/History/CMakeFiles/MAPL.history.dir/MAPL_HistoryGridComp.F90.o
25.642 base/CMakeFiles/Regrid_Util.x.dir/Regrid_Util.F90.o
21.853 base/CMakeFiles/MAPL.base.dir/MAPL_CFIO.F90.o
18.27 base/CMakeFiles/MAPL.base.dir/MAPL_Generic.F90.o
17.818 base/CMakeFiles/MAPL.base.dir/FieldBundleRead.F90.o
15.168 base/CMakeFiles/MAPL.base.dir/MAPL_newCFIO.F90.o
14.469 gridcomps/History/CMakeFiles/MAPL.history.dir/MAPL_HistoryCollection.F90.o
13.123 gridcomps/Cap/CMakeFiles/MAPL.cap.dir/MAPL_CapGridComp.F90.o
```
<img width="1333" alt="Screen Shot 2021-05-06 at 4 25 56 PM" src="https://user-images.githubusercontent.com/2982494/117361223-c1318c80-ae87-11eb-8a6b-66a045a73fc2.png">

Huh. It really is `MAPL_Mod.F90`, [the most boring file in MAPL](https://github.com/GEOS-ESM/MAPL/blob/develop/base/MAPL_Mod.F90).

**Comment by mathomp4** [comment]
Query for @tclune: Could we "break up" `MAPL_Mod.F90`? That is maybe each subdir of MAPL makes a "super module" and then `MAPL_Mod` aggregates those? 

MAPL_Shared makes a MAPL_SharedMod that has a bunch of `use` statements? Maybe spread the cost of that one file around?

Of course, I now realize the `generic/` directory would make `MAPL_genericMod` and `base/` would make `MAPL_baseMod` so...

I guess another thought would be to try and see if it's "linear" in cost. That is, comment out half the `use` statements in `MAPL_Mod.F90` and then see if it now takes 30 seconds instead of 60 to compile.

**Comment by tclune** [comment]
At the very least we should do some experiments along the lines of splitting this file to better understand just what is taxing the compiler.     I can't believe that it is really trying to do any interprocedural optimizations at that level, but ... what else could take so much time?

I fear we'll pay the price no matter how we split it up though, so long as we want to have a single top level module to export (and thereby give internal refactoring freedom)

**Comment by mathomp4** [comment]
I was about to suggest we compile `MAPL_Mod.F90` at `-O0` and then realized this is happening with `Debug` builds. I might ask the GCC folks about this. Maybe they've seen this and have a thought about why it happens.

**Comment by mathomp4** [comment]
Update from the GCC list. Apparently I'm not the only one:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98426
