### ISSUE TITLE
Weird FROCEAN output in z0044 run

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#835]
This is an issue I saw when looking at the `inst1_2d_ocn_Nx` output of Ricardo's `z0044` test run. Namely the `FROCEAN` output had weird blockiness:

![FROCEAN_in_z0044 inst1_2d_ocn_Nx 20201122_0600z](https://user-images.githubusercontent.com/2982494/117821204-57273780-b239-11eb-8c23-49488173e953.png)

These "blocks" were apparent in a difference from `x0044` but I found I could tease them out from the file directly by having Panoply display with a color-bar from 0.999 to 1.000. But they are there. 

@bena-nasa and I had a thought: Is this due to History regridding the cube fields to latlon? So, with Ricardo's help, I duplicated his `z0044` run (technically the above image is from *my* run, showing it's duplicable) and added a cube-sphere collection version `inst1_2d_ocn_Mx`. And the output is...interesting:

![FROCEAN_in_z0044 inst1_2d_ocn_Mx 20201122_0600z](https://user-images.githubusercontent.com/2982494/117821542-b2f1c080-b239-11eb-8d5b-863c6d8e5f08.png)

This is why I'm making a PR here. I am...confused as to how this is happening. I can accept that blocks would be in the cube output if we were doing something wrong...but why didn't regridding to latlon "smear" them? How does regridding keep the blocks...and move them??

(I'm adding a mention of @rsdunlapiv and @oehmke here in case they've ever seen this.)

**Comment by mathomp4** [comment]
Note: This "blockiness" is present in `FRLAND` and maybe in the other `FR`s? I just chose `FROCEAN` as there is more ocean in the world...

**Comment by mathomp4** [comment]
Also note: This is at C360. So these blocks are *much* bigger than the size of a cell. It's more like they are reflecting the processor layout? Maybe? This run was on 768 cores at 16x48. But in the latlon image it seems to be 32 wide and 24 down!

**Comment by atrayano** [comment]
@mathomp4 I have 2 questions: do you know if this run uses shmem (i.e. USE_SHMEM: 1). Also are we using the new land. If yes, we need to take a closer look at the tile file

**Comment by atrayano** [comment]
@mathomp4 what version of MAPL is used in z0044?

**Comment by atrayano** [comment]
@mathomp4 , hash would be very helpful

**Comment by mathomp4** [comment]
Ah. I was wrong. The @bena-nasa ADAS I cloned was before he needed the updates for pert. Thus, my ADAS clone is rocking v2.6.6. But looking at a comparison:

https://github.com/GEOS-ESM/MAPL/compare/v2.6.6...develop

v2.6.6 doesn't seem to have any changes that would affect this. I want to say the cfio updates in `develop` are more of a "things crash" fix rather than a "weird blocks in output" fix.

**Comment by atrayano** [comment]
@mathomp4 I am wondering if the "new land" resolves small(er) islands better and we see many more of them. If you have a tiny island in the grid box, it will be labeled land (correctly), and naturally the ocean fraction in such a box will be less than 1. This is just a thought

**Comment by tclune** [comment]
That was one of my first thoughts as well, but ... I'd still have expected smaller rectangles - possibly correlated; but not large rectangles.

**Comment by mathomp4** [comment]
I can't seem to reproduce this, so I'll close for now. If we ever can reproduce it, we'll pick it back up.
