### ISSUE TITLE
MAPL_SunOrbitCreate is called multiple times

### ISSUE THREAD

**Issue by atrayano** [GEOS-ESM/MAPL#85]
Peter came up with the following formula: 
duration of run/3hours +1

But should be called once!

**Comment by dr0cloud** [comment]
CORRECTION: above formula wrong. Called exactly 9 times no matter what duration of run.
Perhaps once for every gridded component using SunOrbit ??

**Comment by mathomp4** [comment]
@dr0cloud Have your fixes to the GCM and here in MAPL 2.1 fixed this? Or is this still an issue?

**Comment by dr0cloud** [comment]
@mathomp4 This can be closed. Every Gridded component has its own Orbit. That was the way it was coded, and it can stay that way, at least for now.

**Comment by dr0cloud** [comment]
Hi Matt,
#85 can be closed.
Every Gridded component has its own Orbit. That was the way it was coded, and it can stay that way, at least for now.
Peter.

**Comment by dr0cloud** [comment]
This can be closed. Every Gridded component has its own Orbit. That was the way it was coded, and it can stay that way, at least for now.
