### ISSUE TITLE
ESMF_Initialize() and ESMF_Finalize() mismatch

### ISSUE THREAD

**Issue by weiyuan-jiang** [GEOS-ESM/MAPL#854]
ESMF_Initialize() is called under the communicator model_comm, but the ESMF_Finalize() is called under world_comm. When GEOSgcm main branch is run with the command

$RUN_CMD 48 $GEOSBIN/GEOSgcm.x --npes_model 24 --oserver_type multigroup --nodes_output_server 1 --npes_backend_pernode 4 --logging_config 'logging.yaml'

the error messages are printed at the end.

ESMF_LogWrite(): ESMF_Log not open -- cannot ESMF_LogWrite(). Log message =
Finalizing ESMF
...
...
ESMF_Finalize: Error writing into the default log
ESMF_Finalize: Error flushing log file: Operation not yet supported
ESMF_Finalize: Error flushing log file: Operation not yet supported
ESMF_LogWrite(): ESMF_Log not open -- cannot ESMF_LogWrite(). Log message =
Finalizing ESMF
ESMF_LogWrite(): ESMF_Log not open -- cannot ESMF_LogWrite(). Log message =
Internal error: Bad condition - - Invalid GlobalVM
ESMF_Finalize: Error finalizing VM: Internal error: Bad condition
pe=00029 FAIL at line=00425 MAPL_Cap.F90 <status=18>
pe=00029 FAIL at line=00131 MAPL_Cap.F90 <status=18>
pe=00029 FAIL at line=00032 GEOSgcm.F90 <status=18>
ESMF_Finalize: Error flushing log file: Operation not yet supported
ESMF_LogWrite(): ESMF_Log not open -- cannot ESMF_LogWrite(). Log message =
Internal error: Bad condition - - Invalid GlobalVM
ESMF_Finalize: Error finalizing VM: Internal error: Bad condition

**Comment by tclune** [comment]
ok - do you have a fix?   They certainly should both be the same.  Eventually both will become world_comm, but for now they should both be world_comm.

**Comment by weiyuan-jiang** [comment]
I haven't found a fix even I tried many ways yesterday. I would try again

**Comment by weiyuan-jiang** [comment]
initialization does not have the condition this%mpi_already_initialized, why finalize need it?  @tclune @mathomp4 

     if (.not. this%mpi_already_initialized) then
         call MAPL_Finalize(comm=this%comm_world)
         call ESMF_Finalize(rc=status)
          _VERIFY(status)
      end if
