### ISSUE TITLE
Add ability to enable MOAB Mesh in MAPL

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#869]
Eventually, we will want to test the ESMF MOAB Mesh in GEOS. So, add a command-line option to enable it.

**Comment by mathomp4** [comment]
Note: Per ESMF:

> This method is only temporary. It was created to enable testing during the stage in ESMF development while we have
> two internal mesh implementations. At some point it will be removed.
> 

So eventually, this option will need to be removed!

**Comment by mathomp4** [comment]
Interesting. Apparently MOAB is zero-diff to native (at C24 at least)? @rsdunlapiv @oehmke Is this expected? I guess I don't know exactly what MOAB is so...probably?

**Comment by oehmke** [comment]
It’s not unlikely that they would be the same. it’s using the same bilinear code underneath. The only difference would be if the underlying mesh code (MOAB or ESMF) were storing corners around a cell in a different order, so it went through the algorithm slightly differently. (We have it as a task to have a set  order for the corners, but that hasn’t happened yet).

**Comment by rsdunlapiv** [comment]
@oehmke How can @mathomp4 prove that he is actually using MOAB?  My recollection is that there should be a clear message in the ESMF log files when MOAB is enabled.

**Comment by oehmke** [comment]
Yes, there should be a large message (including the phrase "MOAB turned ON”) in the ESMF log files when MOAB is turned on.

**Comment by mathomp4** [comment]
@rsdunlapiv Oh yeah. You definitely do. MOAB off:
```
20210601 161311.139 INFO             PET00 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
20210601 161311.139 INFO             PET00 !!!        MOAB turned OFF            !!!
20210601 161311.139 INFO             PET00 !!! Meshes now created using native   !!!
20210601 161311.139 INFO             PET00 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
MOAB on:
```
20210601 161524.157 INFO             PET00 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
20210601 161524.157 INFO             PET00 !!!        MOAB turned ON             !!!
20210601 161524.157 INFO             PET00 !!! Meshes now created using MOAB     !!!
20210601 161524.157 INFO             PET00 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
And some warnings:
```
20210601 161536.959 WARNING          PET00 A polemethod is being used (perhaps by default) in ESMF_FieldRegridStore() when MOAB internal Mes
h represenation is on. Polemethods aren't currently implemented in MOAB, so this could lead to unexpected unmapped points.
```
I guess at this resolution it doesn't matter?
