### ISSUE TITLE
MAPL 2.7.0 and MAPL 2.7.1 non-zero diff with OPS emissions

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#887]
When MAPL was upticked to 2.7.1 it was found that GEOS went non-zero diff when using the OPS emissions. On investigation I did find very subtle differences (in the order of the 5 or 6th decimal place in the mantissa) in the emissions in ExtData between MAPL 2.7.0 and 2.7.1 when using the OPS emissions. After much work I traced it down to the fact that two different input files used in the OPS emissions the QFED real time emissions and the "HTAP" emission, both on 3600x1800 DE/PE lat-lon grids have ever so slightly different lon/lat values.
In one the lons are
```-179.95, -179.85, -179.75 .... 179.75, 179.85, 179.95```
In the other the lons are
```-179.949996948242, -179.850006103516, -179.75 .... 179.649993896484, 179.75, 179.850006103516, 179.949996948242```

likewise for the lats.
Now when both files are opened by the Lat-Lon grid factory, it determines that both are 3600x1800 PE/DE regular grids based on the currently logic, but uses the lons and lats from the file.

Now the upshot is, whichever file gets opened first wins and the 3600x1800 PE/DE grid has the lats/lons from that file.

Well of course the the logic change I made to ExtData in MAPL 2.7.1 causes the order of which file gets opened first with the result that the 3600x1800 PE/DE grid is now slightly different which means the route handle for the regriding is slightly different, which means slightly different emissions and non-zero diff.

So on the one hand there is no reason that this could not in principle happen again, a user changes the RC file, new things are being provided by ExtData.

So what are the options
1. Do nothing
2. Modify the equals overload in the factory so it would have caught and made two different grids
3. If it detects that the grid one of our "standard" grids PC/PE/DC/DE ignore the values in the file and have the factory compute them.

The GEOSgcm gatekeeper was not in favor of 1 because what would prevent this from popping up again potentially and flagging a non-zero diff we have to track down.

**Comment by atrayano** [comment]
I am not in favor of 1) either. But if we do 2) chances are we still will get non-zero diffs because one way or the other, in the past we were using coordinates from a single grid (whichever the first file happen to be). 3) is a good option, and with some luck it might be zero diff against older tags

**Comment by bena-nasa** [comment]
Either way, this is a non-zero diff once going forward, the question is what can we do to ensure than something like this will not happen again.

**Comment by atrayano** [comment]
Both options: 2 and 3, will guard against similar occurrences. I have mixed feelings choosing between the two. On one hand, 3) is forcing the "right" thing, on the other, the coordinates in the file might have been used to compute some on the data in the file (I am almost sure this is the case for QFED emissions)

**Comment by bena-nasa** [comment]
I vote for 3, the fact is to be detected as a regular standard PE/PC/DE/DC, you must be awfully close to that in the first place.

**Comment by atrayano** [comment]
I too like 3 the most. Let me double check this with Tom early next week, and if he agrees too, I will modify the grid factory

**Comment by tclune** [comment]
Highest priority is of course to enable reproducibility under reordering of entries in ExtData.   Both 2 and 3 achieve that, but 2 does it in a rather brute force manner that is probably not the intention.   I doubt we'd have any real problems with memory footprint with (2),  but it just feels wasteful.

What I want is a nuanced combination of 2 and 3.     There should be a default tolerance that decides whether the file grid is close enough to the lat lon factory grid and we would use the latter if the difference is less than the tolerance.      When the difference is more than 0, but less than the tolerance an informative warning message should be emitted indicating that the grid is being adjusted.

The tolerance above should be able to be set globally for all of ExtData.   And then it should be possible for each entry in the resource file to set a separate tolerance for that particular field.
