### ISSUE TITLE
MAPL fails to build on Ubuntu 18.04 with gfortran 9.3.0

### ISSUE THREAD

**Issue by rmontuoro** [GEOS-ESM/MAPL#892]
When building MAPL with gfortran 9.3.0 on Ubuntu 18.04, the build fails with the following error: 
```
[...]/mapl-v2.7.1/shared/Interp/Interp_implementation.F90:1:25:
1 | submodule (MAPL_InterpMod) Interp_implementation
|                         1
2 |   use, intrinsic :: iso_fortran_env, only: REAL32
 |                                                 2
Error: Symbol ‘real32’ at (1) conflicts with the symbol at (2)
[...]/mapl-v2.7.1/shared/Interp/Interp_implementation.F90:1:25:
1 | submodule (MAPL_InterpMod) Interp_implementation
|                         1
2 |   use, intrinsic :: iso_fortran_env, only: REAL32
3 |   use, intrinsic :: iso_fortran_env, only: REAL64
|                                                 2
Error: Symbol ‘real64’ at (1) conflicts with the symbol at (2)
```

@mathomp4, @tclune - any suggestions?

**Comment by kgerheiser** [comment]
I think it's a bug with GCC 9.3.0. It works with GCC 9.4.0.

**Comment by tclune** [comment]
Ugh.  As things are, we've already jumped through a few hoops to get things to compile with gfortran, nag, and intel.    Hopefully everyone can live with upgrading to 9.4 (or 10.x) as I'm not sure a workaround is possible short of eliminating the use of submodules here.   (Not itself crucial, but we're hoping to address some issues with CMake compilation cascades that we still see on occasion.)

**Comment by tclune** [comment]
Moving the USE statements into specific procedures and/or up into the primary module may help.   The trick is to then retest with all the compilers ...

**Comment by rmontuoro** [comment]
Removing the USE statements below in `shared/Interp/Interp_implementation.F90` works on Hera with Intel 18.0.5.274 and Intel MPI 2018.0.4:
```
diff --git a/shared/Interp/Interp_implementation.F90 b/shared/Interp/Interp_implementation.F90
index 1796e08..6b67369 100644
--- a/shared/Interp/Interp_implementation.F90
+++ b/shared/Interp/Interp_implementation.F90
@@ -1,6 +1,5 @@
 submodule (MAPL_InterpMod) Interp_implementation
-  use, intrinsic :: iso_fortran_env, only: REAL32
-  use, intrinsic :: iso_fortran_env, only: REAL64
+
   implicit none
 
 contains
```
@kgerheiser - could we test this change with hpc-stack and see if it addresses the current build issues?

**Comment by kgerheiser** [comment]
Yes, I will give it a try.

**Comment by kgerheiser** [comment]
That resolves the error

**Comment by rmontuoro** [comment]
Great! Thank you @kgerheiser. I will submit a PR shortly.

**Comment by rmontuoro** [comment]
Submitted PR #893

**Comment by kgerheiser** [comment]
Can confirm removing those lines allows MAPL to build with gfortran 9.3.0
