### ISSUE TITLE
Trouble compiling Base_implementation.F90

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [GEOS-ESM/MAPL#912]
I am having some trouble building mapl v2.7.2.  I am getting an error when attempting to compile base/Base/Base_implementation.F90 (line 518):
There is no matching specific subroutine for this generic subroutine call.   [MAPL_ATTRIBUTESET]

Base_implementation.F90 is a submodule of Base.F90, which contains the MAPL_AttributeSet interface, under which it looks like this particular call should match MAPL_FieldAttSetI4.

I am attempting to compile using the Intel compilers (version 18.0.3 20180410) with the cmake (version 3.17.1) options 
-DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_FLAP=OFF -DBUILD_WITH_PFLOGGER=OFF -DESMA_USE_GFE_NAMESPACE=ON -DBUILD_SHARED_MAPL=OFF

Here is the environment I am using:

```
Currently Loaded Modules:
  1) license_intel/S4   4) intel/18.0.3       7) esma_cmake/v3.4.3    10) gftl-shared/v1.3.0  13) netcdf/4.7.4
  2) git/2.30.0         5) hpc-intel/18.0.3   8) cmakemodules/v1.2.0  11) yafyaml/v0.5.1      14) esmf/8_1_1
  3) hpc/1.1.0          6) hpc-impi/18.0.3    9) ecbuild/ecmwf-3.6.1  12) hdf5/1.10.6
```

**Comment by mathomp4** [comment]
@DavidHuber-NOAA If I had to guess, I'm thinking Intel 18 might be too old. I'm not sure what the submodule support was like with that version. (Pinging @tclune for more insight.) 

I might try to see if I can build MAPL with Intel 18.0.5 (the only Intel 18 compiler we have on discover.) I'll have to build a Baselibs stack for it first...

Do you have a more recent Intel compiler you can use? We currently use Intel 19.1.3 and 2021.2

**Comment by mathomp4** [comment]
@DavidHuber-NOAA An update. I was able to build MAPL 2.7.3 with Intel 18.0.5 on discover. Now, one of the MAPL tests did not pass:
```
      Start 10: MAPL.generic.tests
10/14 Test #10: MAPL.generic.tests ...............***Failed  Error regular expression found in output. Regex=[Encountered 1 or more failures/errors during testing]  1.93 sec
```
but MAPL did build. (I'll have to ask @tclune or @weiyuan-jiang to help me figure out this failure.)

**Comment by tclune** [comment]
@mathomp4 can you provide the verbose output for the failing test suite?

```
mpirun -np 6  <bin-bath>/MAPL.generic.tests
```

**Comment by DavidHuber-NOAA** [comment]
@mathomp4 Officially, Intel started support of submodules in version 16, with full support of the 2008 standard in version 18.  However, it looks like there was a similar issue with an [early version of Intel 19](https://community.intel.com/t5/Intel-Fortran-Compiler/Bug-in-ifort-19-Submodules-cannot-access-entities-from-module/td-p/1130354).

That said, I am able to compile Shmem_implementation.F90, which references Shmem.f90, without complaint from ifort.  On line 676 of Shmem_implementation, there's a similar call to the Shmem module interface MAPL_AllocNodeArray.  Is there a difference here I'm not seeing?

This doesn't seem to have been an issue when building on Hera, which used Intel 18.0.5.  I do have a version of Intel 19, but I will need to build with 18 at least for the time being.  I can look into upgrading to 18.0.5 if that's necessary.

**Comment by tclune** [comment]
I'm also adding in @rmontuoro so that we can be clear just which versions of the compiler need to be supported.   Submodule support is a bit fragile based on our recent experience, and it is quite possible that small changes will help 18.0.3 while breaking some other compiler/version.    As it is, there was a bit of a struggle to find a combination that worked with the latest Intel, latest GNU and latest NAG.    NOAA then provided a fix that works with GNU 9.3.

**Comment by mathomp4** [comment]
> @mathomp4 can you provide the verbose output for the failing test suite?
> 
> ```
> mpirun -np 6  <bin-bath>/MAPL.generic.tests
> ```

```console
$ /usr/local/intel/2020/compilers_and_libraries_2020.0.166/linux/mpi/intel64/bin/mpirun -np 1 /discover/swdev/mathomp4/Models/MAPL-Intel1805/MAPL/build-Debug/generic/tests/MAPL.generic.tests -d
srun: cluster configuration lacks support for cpu binding


 Start: <Test_ConcreteComposite_suite.test_get_parent_orphan>
.   end: <Test_ConcreteComposite_suite.test_get_parent_orphan>


 Start: <Test_ConcreteComposite_suite.test_get_parent>
.   end: <Test_ConcreteComposite_suite.test_get_parent>


 Start: <Test_ConcreteComposite_suite.test_get_component>
. Failure in <Test_ConcreteComposite_suite.test_get_component>
F   end: <Test_ConcreteComposite_suite.test_get_component>


 Start: <Test_ConcreteComposite_suite.test_get_child>
. Failure in <Test_ConcreteComposite_suite.test_get_child>
F   end: <Test_ConcreteComposite_suite.test_get_child>


 Start: <Test_CompositeComponent_suite.test_get_num_children>
.   end: <Test_CompositeComponent_suite.test_get_num_children>

Time:         0.011 seconds

Failure
 in:
Test_ConcreteComposite_suite.test_get_component
  Location:
[Test_ConcreteComposite.pf:57]
incorrect type
Expected: is .false.
     but: was .true.

Failure
 in:
Test_ConcreteComposite_suite.test_get_child
  Location:
[Test_ConcreteComposite.pf:84]
incorrect type
Expected: is .false.
     but: was .true.

 FAILURES!!!
Tests run: 5, Failures: 2, Errors: 0
, Disabled: 0
*** Encountered 1 or more failures/errors during testing. ***
```

**Comment by tclune** [comment]
@mathomp4, and to be clear, this test passes with the later compilers?

**Comment by tclune** [comment]
Looking more closely at this failing test.  This is definitely a compiler bug.   A workaround might be possible.    The failing assert should also be improved - was sloppy in that it is a branch that really can never be reached.

**Comment by mathomp4** [comment]
Yeah. It's fine on Intel 19.1.3. Looking at `develop`:
```
10/16 Test #10: MAPL.generic.tests ...............   Passed    0.60 sec
```
We just never run with Intel 18 anymore.

**Comment by DavidHuber-NOAA** [comment]
We ended up installing the 18.0.5 compilers and building MAPL with that.

**Comment by mathomp4** [comment]
> We ended up installing the 18.0.5 compilers and building MAPL with that.

I suppose next question: Did it work? 😄
