### ISSUE TITLE
Refactor Constants into separate modules

### ISSUE THREAD

**Issue by Gvilla1000-nasa** [GEOS-ESM/MAPL#926]
All constants are contained in a single file making physical/mathematical/internal distinction hard to observe. These need to be refactored into separate modules for easier identification.

**Comment by Gvilla1000-nasa** [comment]
#42 This seems to be a related topic. Should this be addressed in this effort as well?

**Comment by tclune** [comment]
My vote would be that we would address #42 during this process.  But ... new values should be hidden by `#ifdef` or some similar mechanism until we do a  "major" release of MAPL due to the backward compatibility issues.

**Comment by Gvilla1000-nasa** [comment]
Question: I identified the following parameter: `ESMFL_UnitsRadians = 99` from `base/ESMFL_Mod.F90` as a potential parameter that can be moved into the new module. It is used in 4 different modules. Is this variable okay to be moved or because it is already identified as an `ESMFL` it should be left untouched?

**Comment by bena-nasa** [comment]
I think it should be left untouched, this seems to be another software constant rather than a mathematical or physical constant

**Comment by tclune** [comment]
Anyone care to comment on how much of ESMFL could be eliminated at this point?

**Comment by bena-nasa** [comment]
It is hard to say for sure, I'm sure there are some routines that are either duplicates or not used but we would have to careful go through this and check the DAS. However, there are still some of these that are for sure used in the DAS and have no ESMF or other implementation in MAPL.  For example, off the top of my head, there are these bundle2state and state2bundle routines that do what the name suggests for example that I know the DAS uses.

**Comment by Gvilla1000-nasa** [comment]
Ok. I think some software/internal constants could be added into MAPL_Constants. For example, `UNDEFINED_INTEGER`, `GRID_NAME_DEFAULT`, etc. I also identified `MAPL_UseStarrQsat` and other `use*Qsat` parameters that could be moved to the constants module but it seems these are only parameters that were used in a module that is not longer compiled. Should these `MAPL_Use` be removed to prevent confusion or will the `tstqsat.F90` be enabled in the future?

**Comment by tclune** [comment]
If there are modules that are not being compiled, we (collectively) should decide if the module should be eliminated entirely.   (And if it is a test, as the name suggests it should at the very least be relocated to another direcotry.)

For now I think just maintain a list of questionable cases that we can review in a focused meeting.  

Also, constants that are only used within a single module do not need to move.  If they are PUBLIC then it might take some looking to find out if they are used outside MAPL.   I suspect GRID_NAME_DEFAULT is a purely internal constant and is fine where it is, though I've not looked into it yet.

I'll try to schedule a window this week to do an initial review of what you've found.

**Comment by mathomp4** [comment]
Yeah, `tstqsat.F90` could probably go away. I think it was a tester program that Max wrote when developing the MAPL_SatVapor code. It's in Git so we can restore if ever needed again...or just make a new one.

**Comment by mathomp4** [comment]
But `MAPL_SatVapor` and it's constants:
```fortran
    public MAPL_UseStarrQsat
    public MAPL_UseGoffGratchQsat
    public MAPL_UseMurphyKoopQsat
```
Probably should stay around. I know Andrea at one time would have preferred GEOS moving to the MAPL SatVapor code as in many ways it is better than the qsat code in GMAO_Shared.

**Comment by tclune** [comment]
We'll discuss these issues at the Thursday refactoring meeting.  Unfortunately, it is only 45 minutes this week, so we'll need to be efficient.

**Comment by mathomp4** [comment]
Query for @tclune: Would this be a good time as well to get some Doxygen into MAPL? I suppose if we write comments into these new files, they could be in a Doxygen style?

**Comment by tclune** [comment]
If you are willing to work with @Gvilla1000-nasa on this, we could prototype in the constants work and then expand from there?

**Comment by mathomp4** [comment]
Sort of related: https://github.com/GEOS-ESM/GEOSgcm/issues/271

**Comment by mathomp4** [comment]
ooh. I think it autoclosed!
