### ISSUE TITLE
MAPL develop fails with MOM5

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#928]
Recent changes in MAPL `develop` (from #927) seem to have triggered a crash in MOM5 runs. Per my nightly tests:
```
 Character Resource Parameter: FILTER_TYPE:NULL
                                    Memuse(MB) at ORADMAPL_GenericInitialize=  3.039E+02  3.039E+02  2.912E+02  2.961E+02  0.000E+00
                                                             Mem/Swap Used (MB) at ORADMAPL_GenericInitialize=  1.591E+04  0.000E+00
                                                  CommitLimit/Committed_AS (MB) at ORADMAPL_GenericInitialize=  1.801E+05  4.174E+04
 Real*4 Resource Parameter: OCEAN_DT:450.000000
 Character Resource Parameter: CICE4_IMPORT_RESTART_FILE:seaice_import_rst
pe=00008 FAIL at line=05903    MAPL_Generic.F90                         <Factories not equal>
pe=00013 FAIL at line=05903    MAPL_Generic.F90                         <Factories not equal>
pe=00013 FAIL at line=01578    MAPL_Generic.F90                         <status=1>
pe=00023 FAIL at line=05903    MAPL_Generic.F90                         <Factories not equal>
pe=00023 FAIL at line=01578    MAPL_Generic.F90                         <status=1>
```
This seems to be something beyond my ken of MAPL:

https://github.com/GEOS-ESM/MAPL/blob/fceecb6ea900d1e0d7beeb976899ba1552e938d2/base/MAPL_Generic.F90#L5896-L5906

As these lines were changed in #927, I'm obviously assigning to @bena-nasa (But also CC @tclune and @atrayano as they are MAPL gurus too).

**Comment by mathomp4** [comment]
Note: MOM6 seems happy as it ran just fine. 

And the `seaice_import_rst` for MOM5 doesn't look that exciting (to me), but maybe Ben can see an issue right off!

**Comment by tclune** [comment]
@bena-nasa Let me know if you need help isolating this.   Am guessing that since it is only MOM5 it is related to tripolar which did not get changed correctly?

**Comment by bena-nasa** [comment]
I'll take a look. I'm sure it is the equals definition.

**Comment by atrayano** [comment]
@bena-nasa I looked at the MAPL_TripolarGridFactory.F90, and lines 112-113 seem odd. I thing the pairing should be nx with factory%nx, etc

**Comment by bena-nasa** [comment]
well, I see a lot of problems with what I did and the tripolar grid. I'm not sure how to proceed.
1.) We have no metadata in the restart files for the components on the tripolar grid to queue off of to determine that they are tripolar. So I think the make grid from a file is choose the lat-lon factory as the dimensions are lat-lon, so when we compare this to the application grid for one of the ocean components it says they are not equals.
2.) When the tripolar factory picks a decomposition if we were to make this from the file we need to make sure it evenly divides 
3.) The equal's should probably be comparing the actual coordinates which are 2d arrays, not just the grid_file_name

**Comment by mathomp4** [comment]
Is there any way to tell if a latlon grid is tripolar? Some simple math test where you look at the divergence of the lines or something and you notice "Huh, three poles"?

**Comment by bena-nasa** [comment]
Well, if you were to pull the coordinates from the grid you could test if they are evenly spaced in one dimension or identical in the other. I presume the tripolar would not, the problem is in the 2D coordinates are not in the file, not even the filename you would read. 

I really don't see a way around this given the existing restarts other than skipping this test if the component factory is tripolar as there is simply not enough information in the restart files to make the determination that it is tripolar.

**Comment by atrayano** [comment]
@mathomp4 Yes, if you take a look at the actual coordinates, they should nor be equally spaced if it is a tripolar grid. Also, another hint is that tripolar grid typically does not extend much further south than 80 (to be absolutely sure we could check -85. If MAPL creates the grid, we attach an attribute, saying the grid is tripolar. But just looking at the metadata in the file, we obviously do not have that luxury

**Comment by tclune** [comment]
We should at least engineer the "luxury" into future files ...

**Comment by bena-nasa** [comment]
@atrayano this won't work as the restart files simply do not have the information needed to properly create the tripolar grid. I should have seen this. Either the restart file would have to be modified to add some metadata so it can be properly identified or we have no choice but to skip this test for now.

**Comment by atrayano** [comment]
How about this idea - check if the metadata in the file tells us what the grid is (obviously this info is not there at the moment). If it there, use it. Otherwise, do not fail, and use some kludgy "heuristics" (and I need to make sure that this would work for MITgcm grids - they also do not cover Antarctica)
