### ISSUE TITLE
HiRes Replay failure in MPI Wait

### ISSUE THREAD

**Issue by wmputman** [GEOS-ESM/MAPL#94]
A recent attempt to replay at c2880 132L to a 1152x721 analysis file is giving exceptions in the MPI Wait, it looks like this is associated with a 3D scatter call.

 Reading weights for PE2880x17280-CF_c2l_PC1152x721-DC.nc4
 Reading weights for PE2880x17280-CF_c2l_PC1152x721-DC.nc4
forrtl: error (69): process interrupted (SIGINT)
Image              PC                Routine            Line        Source
GEOSgcm.x          00000000051C8F6E  Unknown               Unknown  Unknown
libpthread-2.22.s  00002AAAB5966C10  Unknown               Unknown  Unknown
libmpi.so.12.0     00002AAAB4E38015  Unknown               Unknown  Unknown
libmpi.so.12.0     00002AAAB4BF653B  PMPIDI_CH3I_Progr     Unknown  Unknown
libmpi.so.12.0     00002AAAB4FA49B5  PMPI_Wait             Unknown  Unknown
libmpifort.so.12.  00002AAAB463E9D7  mpi_wait              Unknown  Unknown
GEOSgcm.x          0000000004E0F6F0  mapl_commsmod_mp_         630  MAPL_Comms.F90
GEOSgcm.x          0000000004E10B3E  mapl_commsmod_mp_         851  MAPL_Comms.F90
GEOSgcm.x          0000000002C004EF  cubetolatlonregri         201  CubeToLatLonRegridder.F90
GEOSgcm.x          0000000002C010A6  cubetolatlonregri         263  CubeToLatLonRegridder.F90
GEOSgcm.x          0000000002A41C8B  geos_mkiaugridcom        1346  GEOS_mkiauGridComp.F90
GEOSgcm.x          0000000002A3EEF6  geos_mkiaugridcom        1135  GEOS_mkiauGridComp.F90
libesmf_fullylink  00002AAAB17B6847  _ZN5ESMCI6FTable1     Unknown  Unknown
libesmf_fullylink  00002AAAB17B9CB3  ESMCI_FTableCallE     Unknown  Unknown
libesmf_fullylink  00002AAAB1BCC395  _ZN5ESMCI2VM5ente     Unknown  Unknown
libesmf_fullylink  00002AAAB17B792D  c_esmc_ftablecall     Unknown  Unknown
libesmf_fullylink  00002AAAB1DDA731  esmf_compmod_mp_e     Unknown  Unknown
libesmf_fullylink  00002AAAB1F8FC0F  esmf_gridcompmod_     Unknown  Unknown
GEOSgcm.x          000000000042863F  geos_gcmgridcompm        1349  GEOS_GcmGridComp.F90
libesmf_fullylink  00002AAAB17B6847  _ZN5ESMCI6FTable1     Unknown  Unknown
libesmf_fullylink  00002AAAB17B9CB3  ESMCI_FTableCallE     Unknown  Unknown
libesmf_fullylink  00002AAAB1BCC395  _ZN5ESMCI2VM5ente     Unknown  Unknown
libesmf_fullylink  00002AAAB17B792D  c_esmc_ftablecall     Unknown  Unknown
libesmf_fullylink  00002AAAB1DDA731  esmf_compmod_mp_e     Unknown  Unknown
libesmf_fullylink  00002AAAB1F8FC0F  esmf_gridcompmod_     Unknown  Unknown
GEOSgcm.x          0000000004EDFDE7  mapl_capgridcompm        1051  MAPL_CapGridComp.F90
GEOSgcm.x          0000000004EDF9FE  mapl_capgridcompm         998  MAPL_CapGridComp.F90
GEOSgcm.x          0000000004EDF6B3  mapl_capgridcompm         720  MAPL_CapGridComp.F90

**Comment by tclune** [comment]
Hmm.   Unlikely there is an actual code bug in this area as it is so widely used.   More likely we have tripped some limit in the MPI implementation.   

The good news is that the layer is not used in MAPL 2.0, so we just need to get there.

@wmputman  If we can get MAPL 2.0 tested in the next 1-2 weeks and moved into the main GCM development will that be soon enough?   Or do we need a near-term workaround?      I can't convince myself the timeline is faster either way.

**Comment by aoloso** [comment]
No particular insight but perhaps try combinations of:
setenv I_MPI_WAIT_MODE 0
setenv I_MPI_TMI_PROVIDER psm2
setenv I_MPI_EAGER_THRESHOLD 524288
setenv I_MPI_SPIN_COUNT 1000

**Comment by wmputman** [comment]
There is no need to rush your MAPL-2 timeframe.  Perhaps I can try that for these tests though. Is there a quick sequence of commands that will lead to a merge of:

-- Bill Putman

William M Putman
Global Modeling and Assimilation Office
NASA Goddard Space Flight Center
Cell: 240-778-5697
Desk: 301-286-2599

**Comment by tclune** [comment]
@wmputman We are reviewing older issues in MAPL.    Do you happen to know if MAPL 2 did fix this issue or simply whether this ticket should be closed?
