### ISSUE TITLE
Feature request: configurable lev positive attribute in checkpoint files 

### ISSUE THREAD

**Issue by lizziel** [GEOS-ESM/MAPL#942]
Currently MAPL reads and writes all restart and checkpoint files assuming vertical dimension direction `down`. This is indicated by the `positive` attribute included for the `lev` dimension in the file. For restart read this behavior is true regardless of whether the `positive` attribute is included in the file.

This feature request is to expand the vertical direction capability of checkpoint files, both upon read and write, to increase flexibility of how the data is stored externally. This would be useful to GCHP which uses a vertical direction `up` convention internally in GEOS-Chem state arrays and therefore has users more familiar with `up` than `down` files. 

To be clear, the internal state arrays would remain `positive:down` within MAPL. It would be the responsibility of grid comps, e.g. in `Chem_GridCompMod.F90` in GCHP, to make appropriate internal data flips to fill the internal state.

I envision the update would include adding an optional setting in the main model config file to set the checkpoint lev positive attribute, e.g. in `GCHP.rc` for GCHP which is the equivalent to `AGCM.rc` in GEOS. Ideally this would be done per gridcomp rather than one setting for all. For example, users would be able to write `positive:up` restart files for GCHP but write a `positive:down` checkpoint for FV3 (if they also implement an internal state for that grid comp - currently we don't have one). Exclusion of the setting for a grid comp could be interpreted as `positive:down` so that no changes to GEOS files are necessary to retain current behavior.

The file content would then look something like this in GCHP:

> GCHPchem_INTERNAL_CHECKPOINT_FILE:  gcchem_internal_checkpoint
> GCHPchem_INTERNAL_CHECKPOINT_TYPE:  pnc4
> GCHPchem_INTERNAL_CHECKPOINT_POSITIVE:  up

The config file setting is for the writing of checkpoint files. The behavior for MAPL restart read would be different in that it would base behavior on the metadata in the input file. MAPL would vertically flip the input arrays if `lev:positive` in the file is `up`, and do nothing if it is `down`. If the file does not contain the attribute then it should fail since `positive` should always be there for COARDS-compliance if lev is not pressure (lev can never be pressure for restarts, correct?).

This request is an off-shoot of https://github.com/GEOS-ESM/MAPL/issues/914. I am pinging a couple other GCHP developers so they are in the loop on this request. @sdeastham, @LiamBindle

**Comment by bena-nasa** [comment]
@lizziel I've implemented this feature as requested in the issue and it is in our develop branch so should be in the next MAPL release issued.
