### ISSUE TITLE
Consolidate usage of tolerance

### ISSUE THREAD

**Issue by Gvilla1000-nasa** [GEOS-ESM/MAPL#948]
the usage of tolerance in the code is quite not uniform. Although it is fine if the tolerance values differ, variable names being different can cause maintainability issues down the road. Suggestion would be to make sure usage is uniform.

Current usages of tolerance are `eps`, `tiny`, and `myeps`.

**Comment by tclune** [comment]
`eps` has a very specific meaning for floating point and `tiny` has a very specific meaning for Fortran, so both should be avoided.   `tol` or `tolerance` would be a better name for user code.     Now, if the coder really meant `tiny` as in trying to avoid divide by zero, then we should just use Fortran `tiny()`.  (Of course roundoff ...  sigh)
