### ISSUE TITLE
MAPL_CapOptions in base: why?

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#996]
I'm not the MAPL guru @tclune and the rest @GEOS-ESM/mapl-team are but as I was looking around today, I saw that `MAPL_CapOptions.F90` is in `base` and not in `gridcomps/Cap`. Is there a reason for that I don't know about?

**Comment by tclune** [comment]
These should be in gridcomps/Cap.    Further, the Flap extension is still not quite implemented in the cleanest way.  This can be done without `#ifdef's`
